- docs/pages/architecture/basics.mdx
Fix some typos in architecture/basics documentation page.
> docs: fix typos in architecture/basics

- .dockerignore
- cmd/vcluster/main.go
- cmd/vclusterctl/cmd/create.go
- cmd/vclusterctl/cmd/delete.go
- devspace.yaml
- docs/pages/operator/external-access.mdx
- docs/pages/operator/external-datastore.mdx
- pkg/controllers/resources/nodes/nodeservice/node_service.go
- pkg/server/filters/metrics.go
- Changes the fake kubelet port from 8443 to 10250
- `vcluster delete` now deletes the PVC as well except `--keep-pvc` is specified (#29)
- Fixed an issue where the flag `--release-values` was specified multiple times
> KubeletPort, PVC delete & flag fix

- cmd/vclusterctl/cmd/create.go
- cmd/vclusterctl/cmd/delete.go
- **cli**: now uses the cli version as default vcluster chart version
- **cli**: `vcluster delete` will now print a message if it has successfully deleted the vcluster pvc aswell
> cli version as chart version & log message for pvc delete

- chart/templates/statefulset.yaml
- chart/values.yaml
- cmd/vcluster/main.go
- devspace.yaml
- **chart**: `syncer.livenessProbe` and `syncer.readinessProbe` can now be configured in the helm chart 
- **chart**: statefulset `labels` and `annotations` can now be configured in the helm chart
> build(chart): syncer liveness & readiness probes

- chart/templates/statefulset.yaml
- pkg/controllers/resources/endpoints/syncer.go
- Fixed an issue where vcluster would show errors during startup syncing the kubernetes endpoints
- Tuned readiness and liveliness probes
> fix: improve probes & kubernetes endpoints sync

- pkg/server/server.go
- Fixed an issue where long running requests such as `kubectl exec` could wrongfully timeout
> fix: fix issue where long running requests were timed out

- cmd/vclusterctl/cmd/connect.go
- cmd/vclusterctl/cmd/create.go
- cmd/vclusterctl/cmd/delete.go
- cmd/vclusterctl/cmd/list.go
- cmd/vclusterctl/flags/flags.go
- **cli**: Added `--context` flag for vcluster commands to specify a kubernetes context
> feat: add global --context flag

- pkg/controllers/resources/nodes/nodeservice/node_service.go
- pkg/controllers/resources/pods/translate.go
- pkg/util/translate/translate.go
- **syncer**: Replace `.-` strings with `-` during translation from virtual name to physical name (#51)
- **syncer**: Fixed an issue where the wrong label name was used in downward API fields (#50)
- **syncer**: Added support for pod `spec.affinity.podAffinity` and `spec.affinity.podAntiAffinity` (#52)
> fix: pod affinity, downward API fix & replace dots

- devspace.yaml
- pkg/controllers/resources/endpoints/syncer.go
- Refactored `devspace.yaml` to make development easier
- vcluster will now strip the `control-plane.alpha.kubernetes.io/leader` annotation of endpoints to prevent not mirroring endpoints to endpointslices in the host cluster
> refactor: remove leader election annotation & refactor devspace yaml

- cmd/vclusterctl/flags/flags.go
- docs/pages/architecture/basics.mdx
Two small typos:
one in the description of "silent" flag
one in docs "Basics" page
> Fix two small typos

- cmd/vclusterctl/cmd/connect.go
- cmd/vclusterctl/cmd/create.go
- pkg/server/cert/syncer.go
- New `--expose` flag for `vcluster create` to use a LoadBalancer service to automatically expose the vcluster
- Improve `vcluster connect` to automatically recognize exposed vclusters and skip port forwarding for those
- Updated default k3s versions for `vcluster create`
> feat: add --expose flag & improve connect

- cmd/vcluster/context/context.go
- cmd/vcluster/main.go
- cmd/vclusterctl/cmd/connect.go
- cmd/vclusterctl/cmd/create.go
- pkg/util/kubeconfig/kubeconfig.go
- **cli**: New `--connect` flag for `vcluster create` that directly runs `vcluster connect` (#81)
- **syncer**: New `--out-kube-config-secret-namespace` flag to override the namespace where vcluster will store the generated kube config (#82)
- **syncer**: New `--out-kube-config-server` flag to override the server of the generated kube config (#84)
- **syncer**: Set owner reference to generated kube config secret if it is in the same namespace as owning statefulset (#83)
> add --connect flag, kube config namespace & server flag and add owner reference

- cmd/vcluster/context/context.go
- cmd/vcluster/main.go
- pkg/controllers/resources/endpoints/syncer.go
- pkg/controllers/resources/endpoints/syncer_test.go
- pkg/controllers/resources/nodes/nodeservice/node_service.go
- pkg/controllers/resources/pods/syncer.go
- pkg/controllers/resources/services/syncer.go
- pkg/controllers/resources/services/syncer_test.go
- pkg/leaderelection/leaderelection.go
- pkg/server/cert/syncer.go
- pkg/server/filters/nodename.go
- pkg/server/server.go
- pkg/util/kubeconfig/kubeconfig.go
- **syncer**: New flag `--service-namespace` to specify where the vcluster service is available
- **syncer**: Fixed several issues where using `--target-namespace` would not work correctly
> fix(syncer): fix issues with syncing to another namespace

- chart/templates/service.yaml
- chart/values.yaml
- cmd/vclusterctl/cmd/create.go
Reverts loft-sh/vcluster#89 because using a Kubernetes service with other than port 443 is not possible
> Revert "Add --port flag to specify service port on the create command"

- cmd/vclusterctl/cmd/connect.go
- pkg/controllers/garbagecollect/garbagecollect.go
- pkg/controllers/resources/persistentvolumes/syncer.go
- Fixed an issue where persistent volumes would sometimes not get cleaned up correctly
- **cli**: New `--address` flag for `vcluster connect` to start portforwarding with a specific address locally
> fix: fixed persistent volume cleanup & --address

- pkg/controllers/resources/pods/syncer.go
- **syncer**: Fixed an issue where terminating pods wouldn't get cleaned up correctly if the service account was deleted beforehand (#119)
> fix: fixed an issue where pods wouldn't get deleted correctly

- pkg/controllers/resources/pods/translate/hosts.go
The issue was with the ordering of the /etc/hosts file which changed in #135
Closes #174
> fix: host rewrite results in incorrect result for `hostname -f`

- e2e/framework/helper.go
- e2e/test/syncer/pods/pods.go
- pkg/controllers/resources/pods/translate/translator.go
Fixes #170 
In this PR I fix the order of synced environment variables to allow access to them in the dependent environment variables.
Additionally, I implemented an e2e test to cover this scenario, and a small tweak to e2e tests to improve performance (imagePullPolicy: IfNotPresent).
Kudos to @FabianKramm for pointing out where the problem might be, and which part of the code needs to be fixed :+1:
> fix: service envvar resolution in dependent envvar

- .github/workflows/e2e-tests.yaml
- .github/workflows/release.yaml
- .github/workflows/unit-tests.yaml
I am trying to make the checks look a little less cluttered, and have them triggered only when it makes sense (based on the files that got changed in the PR).
State before:
> ci: reorganize GH workflows and improve triggers

- e2e/e2e_suite_test.go
- e2e/framework/util.go
- e2e/test/syncer/pods/pods.go
- e2e/test/syncer/services/services.go
- pkg/server/filters/nodechanges.go
- pkg/server/filters/service.go
- pkg/util/encoding/decoder.go
- pkg/util/encoding/decoder_test.go
Fixes #176 
I am fixing a Service creation flow in a scenario where the .Kind field is not part of the request body. 
Additionally, an e2e test is added to cover the fixed scenario, and reusable functions in e2e tests are moved to e2e/framework/util.go
> fix: Service creation when .Kind is not sent

- .gitignore
- .vscode/launch.json
- CONTRIBUTING.md
- Dockerfile
- devspace.yaml
- devspace_start.sh
- e2e/framework/framework.go
I added some documentation for running e2e tests and documentation and config for running the vcluster with the debugger.
The `.vscode/` folder is in the `.gitignore`, so I had to force add the `.vscode/launch.json`, I hope that's okay. I would keep it in .gitignore to let everyone easily customize the config locally without the changes showing up in git all the time.
> docs: instructions for running e2e and debugging

- chart/templates/rbac/role.yaml
- chart/templates/statefulset.yaml
- cmd/vcluster/context/context.go
- cmd/vcluster/main.go
- pkg/controllers/resources/nodes/nodeservice/node_service.go
- pkg/controllers/resources/storageclasses/syncer.go
- pkg/util/kubeconfig/kubeconfig.go
- pkg/util/translate/translate.go
- **syncer**: New `--set-owner` flag that will figure out automatically the owning object of the vcluster pod and set that to the vcluster created objects (#181)
- **syncer**: Deprecated the flag `--owning-statefulset`
> feat: new --set-owner flag

- docs/pages/fragments/deploy-vcluster.mdx
The directions currently indicate that vcluster will be installed in
host-namespace-1, but the helm install uses namespace vcluster-1. This
updates the directions to be consistent.
Signed-off-by: hasheddan <georgedanielmangum@gmail.com>
> Use host-namespace-1 for helm install

- pkg/controllers/resources/pods/translate/translator.go
Fixes the issue reported in slack - https://loft-sh.slack.com/archives/C01N273CF4P/p1633101568199400
GlusterFS volumes use an Endpoint that is local to the pod(created in the same namespace as the pod).
The value of the `glusterfs.endpoints` field is now appropriately translated by the syncer:
```
$ k get endpoints -n vcluster
NAME                                ENDPOINTS                                     AGE
glusterfs-cluster-x-test-x-suffix   192.168.122.21:1,192.168.122.22:1             4m51s
```
> fix: glusterfs volume endpointsName translation on sync

- e2e/test/syncer/pods/pods.go
- pkg/controllers/resources/pods/syncer.go
- pkg/controllers/resources/pods/translate/translator.go
- pkg/util/translate/cluster_metadata.go
- pkg/util/translate/metadata.go
The labels of the namespace in vcluster are now added to the pods created in the host cluster.
This is a first step towards implementing features that use namespace label selectors, e.g. NetworkPolicies (#155) or PodAffinity (#52).
```
$ k get ns default --show-labels
NAME      STATUS   AGE   LABELS
default   Active   14h   kubernetes.io/metadata.name=default,test-label=Hello_PR_reviewer
```
> feat: add namespace labels to synced pods

- pkg/controllers/resources/pods/syncer.go
- pkg/controllers/resources/pods/translate/translator.go
- pkg/controllers/resources/pods/translate/translator_test.go
- pkg/util/translate/util.go
Namespace selectors of the inter-pod affinity rules will now be translated into label selectors and should work for the most part.
This addresses #52, except for the edge case as documented in the code, and which we will address later.
> feat: partial support for namespaceSelector in inter-pod affinity

- cmd/vclusterctl/cmd/app/create/types.go
- cmd/vclusterctl/cmd/app/create/values/k0s.go
- cmd/vclusterctl/cmd/app/create/values/k3s.go
- cmd/vclusterctl/cmd/app/create/values/k8s.go
- cmd/vclusterctl/cmd/create.go
- cmd/vclusterctl/cmd/list.go
- pkg/helm/labels.go
- pkg/helm/secrets.go
- pkg/helm/time.go
- Deprecation of `vcluster create` flags `--release-values` and `--k3s-image`. Use `--extra-values` instead
- Changed default value of `vcluster create` flag `--upgrade` from `true` to `false`. vcluster will not try to upgrade an existing vcluster by default anymore
- New flag `--kubernetes-version` for `vcluster create` to override the kubernetes version used for creating the vcluster. This allows you to create vclusters like this:
```
vcluster create my-vcluster -n vcluster --distro k8s --kubernetes-version v1.20
```
> refactor: deprecate k3s-image, release-values & add kubernetes-version

- cmd/vclusterctl/cmd/app/create/values/k3s.go
- cmd/vclusterctl/cmd/create.go
First step to solve #18 
Add logic to detect if cluster does not have support for IPv4 or if vcluster is forced to use IPv6 only with policy engine.
At least combination of dual stack cluster with Kyverno policy like this:
```yaml
apiVersion: kyverno.io/v1
kind: ClusterPolicy
metadata:
name: service-ipv6-only
spec:
validationFailureAction: enforce
background: false
rules:
- name: service-ipv6-only
match:
resources:
kinds:
- Service
namespaces:
- "vcluster-*"
preconditions:
all:
- key: "{{request.operation}}"
operator: In
value:
- CREATE
mutate:
patchStrategicMerge:
spec:
ipFamilyPolicy: SingleStack
ipFamilies:
- IPv6
```
and using `--distro k8s` works.
Pure IPv6 only env where also host cluster is IPv6 only will need more work. K0s needs this PR https://github.com/k0sproject/k0s/pull/1292 …
> Support IPv6 on service CIDR

- .github/workflows/e2e-tests.yaml
- devspace.yaml
We should run e2e tests against all distributions/charts that are provided - k3s, k8s and k0s.
These changes will ensure that e2e tests in GH workflows(on PRs) are triggered for each distribution/chart.
> test(e2e): run e2e in GH workflows for all charts

- charts/k8s/templates/etcd-statefulset-service.yaml
- charts/k8s/templates/etcd-statefulset.yaml
etcd tries to resolve own DNS name, or names of peers,
but on the first resolution call coredns caches(for 30s) failed response,
etcd keeps trying for 30s before exiting, which results in container restart.
This can result in a crash loop, as Coredns keeps caching failed response.
Setting publishNotReadyAddresses: true seems to prevent this.
First DNS resolution still fails and gets cached for 30s,
resulting in one restart of all etcd pods except last one,
but after CoreDNS cache expires it returns a valid response and
etcd cluster becomes ready.
In my local minikube I was reliably reproducing the crash looping behavior of the original implementation.
With this fix, the k8s flavor of vcluster starts reliably after the aforementioned one restart per etcd pod.
This results into vcluster …
> fix: etcd crash looping due to DNS cache

- .github/workflows/e2e-tests.yaml
- charts/k0s/templates/statefulset.yaml
- charts/k0s/values.yaml
- charts/k8s/templates/syncer-deployment.yaml
- charts/k8s/values.yaml
This fixes a problem mentioned in [this comment](https://github.com/loft-sh/vcluster/issues/167#issuecomment-980006013).
Users are now free to define their own extraArgs for syncer, and the ones needed by default won't get overridden.
> fix: move k0s and k8s syncer extraArgs to allow user defined ones

- charts/k8s/templates/syncer-deployment.yaml
- cmd/vcluster/cmd/start.go
- cmd/vcluster/context/context.go
- pkg/controllers/resources/nodes/nodeservice/node_service.go
- pkg/leaderelection/leaderelection.go
- **syncer**: Fixed an issue where vcluster couldn't find the current pod if the flag `--target-namespace` was provided (#214)
- **syncer**: New flag `--leader-elect` that defaults to false to avoid unnecessary leader election
> restrict leader election & fix current pod failure

- docs/pages/fragments/deploy-to-openshift.mdx
- docs/pages/getting-started/deployment.mdx
- docs/pages/operator/restricted-hosts.mdx
- docs/sidebars.js
Docs chapter describing running as non root has been updated and moved to a new page under operators guide.
A chapter about deploying to OpenShift was added there as well.
> docs: add restricted hosts page to operator guide

- cmd/vcluster/cmd/start.go
- cmd/vcluster/context/context.go
- pkg/controllers/register.go
- pkg/controllers/resources/nodes/register.go
- pkg/controllers/resources/nodes/syncer.go
- pkg/controllers/resources/persistentvolumeclaims/syncer.go
- pkg/controllers/resources/persistentvolumes/register.go
- pkg/controllers/resources/pods/syncer.go
- pkg/controllers/resources/pods/translate/translator.go
- pkg/controllers/resources/priorityclasses/register.go
- pkg/controllers/resources/secrets/syncer.go
- pkg/controllers/resources/storageclasses/register.go
- **syncer**: Renamed flag `--fake-kubelets` to `--disable-fake-kubelets` that makes it easier to understand how to disable fake kubelets as they are enabled by default. `--fake-kubelets` still exists and will be migrated automatically
- **syncer**: New flag `--sync` that defines enabled or disabled sync controllers similar to `--controllers` of [kube-controller-manager](https://kubernetes.io/docs/reference/command-line-tools-reference/kube-controller-manager/). Examples: 
- Default sync resources: `--sync=*`
- Disable `ingresses`: `--sync=*,-ingresses`
- Sync real nodes: `--sync=*,nodes`
- Sync real persistent volumes: `--sync=*,persistentvolumes`
- Sync storage classes and persistent volumes: `--sync=*,storageclasses,persistentvolumes`
- Synced by default (`*`): …
> refactor: add --controllers, deprecate start flags

- charts/k0s/templates/statefulset.yaml
- charts/k0s/values.yaml
- charts/k3s/templates/statefulset.yaml
- charts/k3s/values.yaml
- charts/k8s/templates/api-deployment.yaml
- charts/k8s/templates/controller-deployment.yaml
- charts/k8s/templates/etcd-statefulset.yaml
- charts/k8s/templates/pre-install-hook-job.yaml
- charts/k8s/templates/syncer-deployment.yaml
- charts/k8s/values.yaml
- pkg/controllers/resources/pods/translate/hosts.go
- pkg/coredns/coredns.go
- pkg/util/translate/translate.go
- **chart**: New option `defaultImageRegistry` that allows you to specify an image registry that should be prepended to all deployed system pods by vcluster
> feat: new option to define a default image registry

- .github/workflows/e2e-tests.yaml
I made a mistake last time I was trying to enable e2e on charts changes.
This time I am using a correct pattern, as per docs:
https://docs.github.com/en/actions/learn-github-actions/workflow-syntax-for-github-actions#patterns-to-match-file-paths
> fix(ci): changes to charts should trigger e2e tests

- charts/k8s/templates/etcd-statefulset.yaml
I'm not exactly sure why this is the case but looks that #212 did broke on etcd startup totally on my env where I use Calico + BGP without any overlay or NAT.
This was the error:
```
kubectl -n vcluster-test describe pod/test-etcd-0
Normal   Started                 72s                kubelet                  Started container etcd
Warning  Unhealthy               9s (x6 over 59s)   kubelet                  Startup probe failed: Get "http://127.0.0.1:2381/health": dial tcp 127.0.0.1:2381: connect: connection refused
```
and if I only updated startup probe then error was:
```
kubectl -n vcluster-test describe pod/test-etcd-0
Warning  Unhealthy               8s    kubelet                  Liveness probe failed: Get "http://127.0.0.1:2381/health": dial tcp 127.0.0.1:2381: connect: connection …
```
> etcd: use pod IP instead of localhost on startup and liveness probes

- cmd/vcluster/cmd/start.go
- cmd/vcluster/context/context.go
- **syncer**: Default controllers are now enabled by default, there is no need to specify `*` in the `--sync` flag anymore
> refactor: omit * in --sync flag and enable default controllers

- docs/pages/operator/external-access.mdx
run into this error
error validating data: ValidationError(Ingress.spec.rules[0].http.paths[0].backend.service.port): invalid type for io.k8s.api.networking.v1.ServiceBackendPort: got "integer", expected "map";
> fix ingress port

- charts/k8s/templates/etcd-statefulset.yaml
To render the YAML array correctly with the persistent storage option disabled each value of the volumes 
block should be on the same indention level. 
Before fix It renders like:
```yaml
volumes:
- name: certs
secret:
secretName: t-manual-certs
- name: data
emptyDir: {}
```
What produces an issue in helm: 
`Error: YAML parse error on vcluster-k8s/templates/etcd-statefulset.yaml: error converting YAML to JSON: yaml: line 36: did not find expected key`
> Change empty volume indention to match certs volume

- .github/workflows/e2e-tests.yaml
- CONTRIBUTING.md
- charts/k0s/templates/rbac/role.yaml
- charts/k0s/values.yaml
- charts/k3s/templates/rbac/role.yaml
- charts/k3s/values.yaml
- charts/k8s/templates/rbac/role.yaml
- charts/k8s/values.yaml
- cmd/vcluster/context/context.go
- devspace.yaml
- devspace_start.sh
- e2e/e2e_suite_test.go
- e2e/framework/framework.go
- e2e/framework/util.go
- e2e/test/coredns/coredns.go
- e2e/test/syncer/networkpolicies/networkpolicies.go
- e2e/test/syncer/pods/pods.go
- e2e/test/syncer/services/services.go
- hack/kind-config.yaml
- pkg/controllers/register.go
- pkg/controllers/resources/networkpolicies/syncer.go
- pkg/controllers/resources/networkpolicies/syncer_test.go
- pkg/controllers/resources/networkpolicies/translate.go
- pkg/util/translate/util.go
This should enable NetworPolicy synchronization with all necessary rewrites for the pod label selectors and namespace label selectors.
Fixes #155
> feat: add NetworkPolicy support

- cmd/vcluster/cmd/start.go
> fix: typo in the logs of cmd/vcluster/cmd/start.go

- cmd/vclusterctl/cmd/connect.go
- cmd/vclusterctl/cmd/pause.go
- cmd/vclusterctl/cmd/resume.go
- cmd/vclusterctl/cmd/root.go
New commands `vcluster pause` and `vcluster resume` to pause and resume a vcluster. Those commands are useful to free up computing resources used by the vcluster if its not needed. Pausing a vcluster will scale down the vcluster statefulset as well as delete all workloads created in the host cluster by the vcluster. Upon resuming a vcluster, those workloads will be recreated. Objects within the vcluster such as deployments, statefulsets etc. as well as other objects in the host cluster created through the vcluster such as services, persistent volume claims etc are not affected.
> feat: add pause and resume commands

- docs/pages/fragments/deploy-to-openshift.mdx
The documentation misses a colon in the example values.
> Add missing colon in OpenShift values example

- .github/workflows/e2e-tests.yaml
- charts/k3s/templates/statefulset.yaml
- cmd/vcluster/cmd/start.go
- cmd/vclusterctl/cmd/app/create/values/k3s.go
- devspace.yaml
- e2e/README.md
- e2e/framework/framework.go
- **syncer**: Start controllers after api server started
- **chart**: Fixed a problem where k3s would not startup correctly on cgroupsv2 nodes (#264)
- **cli**: Add v1.23 support for k3s
> Fix k3s not starting & add v1.23 support

- cmd/vclusterctl/cmd/create.go
Related to #190 
- cli: notify the user about incompatible workdir file when running `vcluster create`
> cli: notify user about incompatible workdir file

- pkg/controllers/resources/services/syncer_test.go
- pkg/controllers/resources/services/translate.go
- pkg/server/filters/service.go
We are no longer sharing a cache between the server and controllers.
This unfortunately allowed for a race condition after Service creation.
The controller might be missing Service resource in vcluster cache,
which is causing the deletion of the Service in the host cluster
until it is recreated again by the controller based on Service resource
that gets eventually pulled into vcluster cache.
To prevent this race condition we leave the annotation
that prevents Service deletion in the host until the Service resource
in vcluster is in the expected state.
I also updated the unit test to cover this change too.
And the rest of the changes is due to go fmt :) 
- fix: syncer cache race condition after Service creation
> fix: cache race condition after Service creation

- docs/pages/architecture/storage.mdx
- e2e/test/syncer/services/services.go
- pkg/controllers/resources/volumesnapshots/volumesnapshotcontents/syncer.go
- pkg/controllers/resources/volumesnapshots/volumesnapshotcontents/syncer_test.go
- pkg/controllers/resources/volumesnapshots/volumesnapshots/syncer.go
- pkg/controllers/resources/volumesnapshots/volumesnapshots/syncer_test.go
- pkg/controllers/resources/volumesnapshots/volumesnapshots/translate.go
I am adding unit tests for the VolumeSnapshot and VolumeSnapshotContent syncers and small fixes to the implementation.
Plus one small e2e fix for [this problem](https://github.com/loft-sh/vcluster/runs/4712598512?check_suite_focus=true#step:10:91).
Plus docs for volume snapshot feature, which I marked as "tech-preview" (let me know if you prefer some other term, alpha?).
- docs: volume snapshot feature documented on the Storage page
> Volume snapshot unit tests and docs

- pkg/helm/values/k8s.go
I added 1.23 into the version map a while back, but the condition and fallback values were not updated. 
Since 0.5.0 release notes state `cli: Added support for k8s v1.23`, should I cherry-pick this into v0.5 branch?
> fix: update latest supported minor version for k8s flavor

- cmd/vclusterctl/cmd/connect.go
- cmd/vclusterctl/cmd/create.go
- cmd/vclusterctl/flags/flags.go
- pkg/util/portforward/start.go
- **cli**: Allows command execution with vcluster context in command `vcluster connect`. For example:
```
vcluster connect test -n test -- kubectl get ns
vcluster connect test -n test -- bash
```
- **cli**: `vcluster connect` will now use a random port locally to avoid port conflicts if no `--local-port` flag is specified.
- **cli**: Added shortcut `-s` for global flag `--silent`
> feat: allow command execution with vcluster connect

- pkg/controllers/resources/nodes/fake_syncer.go
- pkg/controllers/resources/nodes/syncer.go
Filter out DaemonSet Pods when evaluating if Node is needed, to avoid DaemonSets being left on Nodes where no other Pods run see #252
Thanks for a create project.
Signed-off-by: Willi Carlsen <carlsenwilli@gmail.com>
> Filter out DaemonSet Pods when evaluating if Node is needed

- cmd/vcluster/cmd/start.go
- pkg/controllers/resources/nodes/nodeservice/node_service.go
- pkg/controllers/resources/pods/translate/translator.go
- pkg/controllers/syncer/translator/namespaced_translator.go
- pkg/util/kubeconfig/kubeconfig.go
- pkg/util/translate/translate.go
- **syncer**: Use vcluster service as owner instead of deployment / statefulset, because we can set the `controller: true` in the owner reference for it, which allows node draining (#273)
> refactor: use vcluster service as owner

- cmd/vclusterctl/cmd/connect.go
- pkg/controllers/resources/events/syncer.go
- pkg/controllers/resources/persistentvolumeclaims/syncer.go
- pkg/controllers/resources/persistentvolumeclaims/syncer_test.go
- pkg/controllers/resources/persistentvolumes/fake_syncer.go
- Refactored fake persistent volume & persitent volume claim controller to not use a shared mutex anymore
- `vcluster connect ... -- command` does not show a fatal anymore if the command has failed.
- Events are only updated if they actually have been changed
> refactor: get rid of shared persistent volume mutex

- cmd/vcluster/cmd/start.go
- cmd/vcluster/context/context.go
- go.mod
- pkg/controllers/resources/pods/syncer.go
- pkg/controllers/resources/pods/syncer_test.go
- pkg/controllers/resources/services/syncer_test.go
- pkg/controllers/resources/services/translate.go
- pkg/controllers/syncer/testing/manager.go
- pkg/controllers/syncer/testing/testing.go
- pkg/controllers/syncer/translator/namespaced_translator.go
- pkg/coredns/coredns.go
- pkg/server/filters/service.go
- pkg/util/applier/util.go
- pkg/util/clienthelper/helper.go
- pkg/util/kubeconfig/kubeconfig.go
- pkg/util/translate/translate.go
- vendor/modules.txt
- **syncer**: Removed `poddisruptionbudgets` as default syncer
- **syncer**: Make initial kube config secret creation non-fatal
- **syncer**: If phyiscal and virtual pod have a node assigned and they differ, delete the physical pod 
- **syncer**: Sync service nodePort from host cluster instead of virtual cluster
- **syncer**: Only write coredns manifests to local file if environment variable "DEBUG" is "true"
> fix: several sync fixes

- pkg/controllers/resources/pods/syncer.go
- pkg/controllers/resources/pods/syncer_test.go
- Delete virtual pod instead of physical if nodeNames between virtual and physical pod differ
> refactor: delete virtual pod if node names differ

- cmd/vcluster/cmd/start.go
- cmd/vcluster/context/context.go
- pkg/controllers/resources/pods/syncer.go
- pkg/util/toleration/toleration.go
- pkg/util/toleration/toleration_test.go
Hey 👋! 
My humble and naive attempt at implementing https://github.com/loft-sh/vcluster/issues/330
I couldn't find any Kubernetes function to parse tolerations.  Kubectl doesn't really support toleration, just taint, and there's technically a difference since tolerations have an operator. This does not support the operator as is
The operator will default to `Equal`` which would enforce that both key and value match the taint.
Because of the above I force the user to provide  the following format `key=value:effect` , and will fail at startup if what's provided does not match.
Might be a good idea to adjust the format to be `key=value:effect:operator` and in that case the parsing and error handling need to be a little smarter. (for example the operator can allow the value to not be provided …
> Add support for automatic tolerations

- manifests/coredns/coredns.yaml
This PR removes the tolerations for the coredns deployment. In many environments there are restrictions on who/what can run on the control-plane nodes. While coredns is required for DNS inside of vcluster it is not necessary or required that it runs on the control-plane nodes.
This was discussed somewhat in https://github.com/loft-sh/vcluster/issues/251 but I'm open to feedback if this isn't an approach you'd prefer to take.
> Don't set tolerations for coredns pods

- cmd/vcluster/cmd/start.go
- docs/pages/architecture/scheduling.mdx
- pkg/controllers/resources/nodes/register.go
- pkg/controllers/resources/pods/syncer.go
- pkg/controllers/resources/pods/syncer_test.go
- pkg/controllers/resources/pods/translate/translator.go
- pkg/controllers/syncer/testing/context.go
- setting the `--node-selector` flag does not implicitly enable synchronization of real nodes anymore. Consult [the Nodes documentation page](https://www.vcluster.com/docs/architecture/nodes) to see the recommended way of enabling real node sync.
- feat: the `--node-selector` and `--enforce-node-selector` flags can now be used with fake nodes
- docs: [Architecture - Pod Scheduling page](https://www.vcluster.com/docs/architecture/scheduling) has been improved and covers more use cases, including the new `--enforce-toleration` flag.
> Node selector can be enforced with fake nodes as well. Docs improvements.

- charts/k0s/templates/rbac/role.yaml
- charts/k0s/values.yaml
- charts/k3s/templates/rbac/role.yaml
- charts/k3s/values.yaml
- charts/k8s/templates/rbac/role.yaml
- charts/k8s/values.yaml
- cmd/vcluster/context/context.go
- pkg/controllers/register.go
- pkg/controllers/resources/pods/translate/translator.go
- pkg/controllers/resources/serviceaccounts/syncer.go
- pkg/controllers/resources/serviceaccounts/syncer_test.go
- pkg/controllers/resources/serviceaccounts/translate.go
/kind feature
resolves #370
Added a new service account syncer that makes it possible to sync service accounts from the vcluster to the host cluster with certain annotations and labels. This is useful for features such as [IAM Roles for ServiceAccounts](https://docs.aws.amazon.com/eks/latest/userguide/specify-service-account-role.html) where the service account needs a certain annotation to give AWS permissions to a pod
> feat: add serviceaccount syncer

- charts/eks/templates/rbac/clusterrole.yaml
- charts/k0s/templates/rbac/clusterrole.yaml
- charts/k3s/templates/rbac/clusterrole.yaml
- charts/k8s/templates/rbac/clusterrole.yaml
- cmd/vclusterctl/cmd/create.go
- cmd/vclusterctl/cmd/list.go
- pkg/controllers/resources/persistentvolumeclaims/syncer.go
- pkg/controllers/resources/persistentvolumeclaims/syncer_test.go
- pkg/controllers/resources/persistentvolumeclaims/translate.go
- pkg/controllers/resources/persistentvolumes/translate.go
- pkg/controllers/resources/priorityclasses/syncer.go
- pkg/controllers/resources/storageclasses/syncer.go
- pkg/controllers/resources/storageclasses/syncer_test.go
- pkg/controllers/resources/storageclasses/translate.go
- pkg/controllers/syncer/testing/context.go
- pkg/controllers/syncer/testing/testing.go
vcluster will now sync storage classes from the virtual cluster to the host cluster if sync of storage classes is enabled. This will replace the current behaviour where storage classes where only synced from host to virtual cluster. 
We decided to replace the existing behaviour, because creating storage classes is a valid use case as long as the CSI driver is installed within the host cluster, but certain parameters for the CSI driver should get changed through a storage class. It also makes sense to not sync created storage classes from the host cluster anymore as this is not required to …
> refactor: sync storageclasses from vcluster

- charts/eks/templates/_helpers.tpl
- charts/eks/templates/rbac/clusterrole.yaml
- charts/eks/templates/rbac/clusterrolebinding.yaml
- charts/eks/templates/rbac/role.yaml
- charts/eks/templates/syncer-deployment.yaml
- charts/eks/values.yaml
- charts/k0s/templates/_helpers.tpl
- charts/k0s/templates/rbac/role.yaml
- charts/k3s/templates/_helpers.tpl
- charts/k3s/templates/rbac/role.yaml
- charts/k8s/templates/_helpers.tpl
- charts/k8s/templates/rbac/role.yaml
/kind bugfix
This change brings EKS chart into sync with all other charts by adding changes done in #346 
- fix: EKS chart now accepts `.sync.*` values as documented
I also moved plugin extra rules to a template helper. This has no impact on the functionality of the charts, it just makes the chart definitions more consistent.
I will also send a PR for v0.6 branch once this one is approved.
> fix: add sync.* values and RBAC changes to EKS chart

- pkg/controllers/resources/services/syncer_test.go
- pkg/controllers/resources/services/translate.go
/kind bugfix
Fixed an issue where setting the service `spec.loadBalancerSourceRanges` was not possible from within the vcluster.
> refactor: spec.loadBalancerSourceRanges from vcluster

- pkg/controllers/resources/nodes/fake_syncer.go
- pkg/controllers/resources/nodes/syncer.go
/kind bugfix
/kind feature
resolves #252
Split daemonset filters into two, because virtual and physical pods do not share exactly the same characteristics when it comes to daemonsets, hence filtering methods needs to be different. This enables the virtual cluster to get rid of lonely daemonsets staying on nodes, where previously valid workload had run. So now a cluster can actually scale down.
> Split daemonset filters into two

- .gitignore
- cmd/vcluster/cmd/start.go
- cmd/vcluster/context/context.go
- pkg/controllers/resources/pods/translate/translator.go
- pkg/controllers/resources/secrets/syncer_test.go
- pkg/controllers/syncer/translator/cluster_translator.go
- pkg/controllers/syncer/translator/namespaced_translator.go
- pkg/server/filters/service.go
- pkg/server/server.go
/kind feature
resolves #
This resolves issue https://github.com/loft-sh/vcluster/issues/386 by adding a `--sync-labels` flag to the syncer. This flag will result in the specified labels being copied directly from virtual resources onto physical resources, in addition to the labels with the vclusted-translated key `vcluster.loft.sh/label-...`. 
Adds `--sync-label` flag to sync untranslated labels onto physical resources
- I also added a line to ignore vim swp files …
> Add `--sync-labels` option

- pkg/server/filters/metrics.go
- pkg/server/server.go
/kind bugfix
Data returned by the vcluster kubelet /stats/summary endpoint contain correct PVC reference now.
Fixed an issue where kubelet metrics proxied by vcluster contained PVC reference name and namespace from the host, instead of values used in the virtual cluster. 
Before:
```
$ curl -k --header "Authorization: Bearer $TOKEN" https://10.64.2.140:10250/stats/summary
...
podRef": {
"name": "prometheus-0",
"namespace": "lens-metrics",
...
"volume": [
...
"name": …
```
> fix: vcluster kubelet PVC ref in /stats/summary

- charts/eks/templates/coredns.yaml
- charts/k0s/templates/coredns.yaml
- charts/k0s/templates/networkpolicy.yaml
- charts/k0s/templates/statefulset.yaml
- charts/k0s/values.yaml
- charts/k3s/templates/coredns.yaml
- charts/k3s/templates/networkpolicy.yaml
- charts/k3s/templates/statefulset.yaml
- charts/k3s/values.yaml
- charts/k8s/templates/coredns.yaml
- charts/k8s/templates/networkpolicy.yaml
- charts/k8s/templates/syncer-deployment.yaml
- charts/k8s/values.yaml
- devspace.yaml
- docs/pages/operator/security.mdx
- manifests/coredns/coredns.yaml
- pkg/coredns/coredns.go
- pkg/metrics/helper.go
- pkg/server/filters/metrics.go
- pkg/util/portforward/portforward.go
- Adds network policies to isolated mode
- Make coredns part of the helm chart to allow easier configuration of the coredns deployment
- vcluster now correctly rewrites PVC kubelet metrics
> refactor: add isolated network policies

- charts/k0s/templates/coredns.yaml
- charts/k3s/templates/coredns.yaml
- charts/k8s/templates/coredns.yaml
/kind bugfix
Fixed an issue where vcluster would use a securityContext for coredns that would cause problems for specific systems
> fix: only set securityContext if isolation mode is disabled

- pkg/controllers/resources/nodes/nodeservice/node_service.go
- pkg/controllers/resources/nodes/register.go
- pkg/util/clienthelper/helper.go
Use the vcluster service label selector for creating a fake kubelet service instead of finding out the pod label selector
> refactor: use vcluster service for fake nodes

- charts/eks/templates/coredns.yaml
- charts/k0s/templates/coredns.yaml
- charts/k0s/templates/limitrange.yaml
- charts/k0s/templates/networkpolicy.yaml
- charts/k0s/templates/resourcequota.yaml
- charts/k3s/templates/coredns.yaml
- charts/k3s/templates/limitrange.yaml
- charts/k3s/templates/networkpolicy.yaml
- charts/k3s/templates/resourcequota.yaml
- charts/k8s/templates/coredns.yaml
- charts/k8s/templates/limitrange.yaml
- charts/k8s/templates/networkpolicy.yaml
- charts/k8s/templates/resourcequota.yaml
/kind bugfix
resolves #
The chart has not set the namespace of the configmap coredns.  If the user runs the command `helm template my-vcluster vcluster --repo https://charts.loft.sh --set serviceCIDR=10.96.0.0/12 -n host-namespace-1 | kubectl apply -f -`. kubectl will create the configmap coredns in the default(which is dependent on the context of kubeconfig) namespace. Then the `syncer-deployment` will not start because of a lack of  coredns config in namespace host-namespace-1.
```
Warning …
```
> add namespace to coredns configmap

- pkg/controllers/resources/nodes/translate.go
- pkg/controllers/resources/persistentvolumes/syncer_test.go
- pkg/controllers/resources/persistentvolumes/translate.go
- pkg/controllers/syncer/testing/context.go
- pkg/controllers/syncer/testing/manager.go
- pkg/controllers/syncer/testing/testing.go
/kind bugfix
Fixed an issue where vcluster would not sync the increased persistent volume size back to the virtual cluster
> fix: sync pv size

- charts/k0s/templates/limitrange.yaml
- charts/k0s/templates/networkpolicy.yaml
- charts/k0s/templates/resourcequota.yaml
- charts/k0s/values.yaml
- charts/k3s/templates/limitrange.yaml
- charts/k3s/templates/networkpolicy.yaml
- charts/k3s/templates/resourcequota.yaml
- charts/k3s/values.yaml
- charts/k8s/templates/limitrange.yaml
- charts/k8s/templates/networkpolicy.yaml
- charts/k8s/templates/resourcequota.yaml
- charts/k8s/values.yaml
also fix their usage in the chart templates
fixes #425
/kind bugfix
resolves #425 
fix `isolation.targetNamespace` usage in the chart templates
> introduce isolation.targetNamespace in k0s, k3s, k8s chart values

- .github/workflows/e2e-tests.yaml
- charts/eks/templates/api-deployment.yaml
- charts/k0s/templates/secret.yaml
- charts/k3s/templates/statefulset.yaml
- charts/k8s/templates/api-deployment.yaml
- devspace.yaml
- devspace_start.sh
- pkg/controllers/k8sdefaultendpoint/k8sdefaultendpoint.go
In this change, I disable the controller("EndpointsReconciler") in the kube-controller-manager which is updating the `default/kubernetes` Endpoints resource because it was updating it to an incorrect value.
Also, to ensure the expected outcome, the vclusters k8sdefaultendpoint controller has been updated to mimic the behavior of the original k8s "EndpointsReconciler" controller.
/kind bugfix
resolves #433 
Fixed an issue where `default/kubernetes` Endpoints object was referencing incorrect IPs in k8s …
> fix: disable k8s controller that reconciles default/kubernetes endpoints

- cmd/vcluster/cmd/start.go
- pkg/controllers/resources/persistentvolumes/syncer.go
- pkg/controllers/resources/pods/syncer.go
- pkg/util/kubeconfig/kubeconfig.go
- vcluster will now try to reapply the kube config secret periodically
- Fixed an issue where vcluster would try to bind a virtual pod multiple times to a node
> Reapply kube config secret & fix multiple bind

- pkg/controllers/resources/pods/translate/translator.go
vcluster will now set the annotation `cluster-autoscaler.kubernetes.io/daemonset-pod` on pods that belong to a daemon set inside the virtual cluster
> refactor: add daemon set annotation

- pkg/controllers/resources/endpoints/syncer.go
/kind bugfix
Fixed an issue where vcluster would not migrate managed endpoints to Kubernetes managed endpoints correctly.
> fix: refresh managed endpoints

- pkg/controllers/k8sdefaultendpoint/k8sdefaultendpoint.go
- pkg/controllers/resources/services/syncer_test.go
- pkg/server/filters/service.go
/kind bugfix
Fixes following conformance tests:
```
[sig-network] DNS [It] should provide DNS for ExternalName services
[sig-network] Services [It] should be able to change the type from ExternalName to ClusterIP
[sig-network] Services [It] should be able to change the type from ExternalName to NodePort
[sig-network] EndpointSlice [It] should have Endpoints and EndpointSlices pointing to API Server
```
fix: Service type change from ExternalName type to other types
fix: default/kubernetes …
> Fix 3 conformance tests - Service type change + default/kubernetes EndpointSlices

- pkg/controllers/resources/pods/translate/translator.go
/kind bugfix
Syncer should not set pods nodeSelector when the scheduler is used.
Fixes:
```
[Fail] [sig-apps] Daemon set [Serial] [It] should run and stop complex daemon [Conformance] 
/workspace/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/test/e2e/apps/daemon_set.go:212
```
> fix: ommit nodeSelector when using scheduler

- charts/k0s/templates/networkpolicy.yaml
- charts/k3s/templates/networkpolicy.yaml
- charts/k8s/templates/networkpolicy.yaml
resolves #475
Allows vcluster isolation NetworkPolicy to be used in a host cluster that uses 6443 port for the API server.
I decided to go with a minimal fix - adding a new port to the list, so as not to go crazy with customizations in the helm chart. If more modifications of the NetworkPolicy are required, the user can always create it separately and disable the creation via our helm chart.
> Add 6443 port to controle plane egress NetworkPolicy

- charts/eks/templates/NOTES.txt
- charts/k0s/templates/NOTES.txt
- charts/k3s/templates/NOTES.txt
- charts/k8s/templates/NOTES.txt
- pkg/constants/annotation.go
- pkg/controllers/servicesync/servicesync.go
- pkg/controllers/syncer/fake_syncer.go
- pkg/controllers/syncer/syncer.go
- pkg/controllers/syncer/translator/cluster_translator.go
- pkg/controllers/syncer/translator/namespaced_translator.go
- pkg/util/translate/translate.go
/kind feature
**Release Notes**
- **syncer**: vcluster now supports a label `vcluster.loft.sh/controlled-by` that if set to a non empty value will omit syncing. This can be set either on the host cluster object or on the virtual cluster object and is very useful for writing plugins that want to handle their own objects.
> refactor: improve helm chart notes

- pkg/controllers/resources/pods/syncer.go
- pkg/plugin/plugin.go
/kind bugfix
- If vcluster loses track of a physical pod (for example if vcluster was paused and restarted) and that physical pod was deleted, vcluster will also delete it upon restart
- Fixed an issue where plugin hooks wouldn't be registered correctly initially
> fix: delete missing physical pods & plugin hooks registration

- cmd/vcluster/main.go
- pkg/server/filters/pprof.go
- pkg/server/server.go
When DEBUG env var is true, syncer profiling information will be served via built-in API server on the /debug/pprof/ path.
To consume the information first start a port forward command in a separate terminal:
`kubectl port-forward -n vcluster-namespace $(kubectl get pods -o name -l app=vcluster -n vcluster-namespace | head -n 1) 6060:8443`
To acquire a 10s sample run:
`curl -k -o timer.prof http://localhost:6060/debug/pprof/profile?seconds=10`
it will override the previous `timer.prof` file if one exists
To view the collected data run …
> feat: serve pprof info on port 6060

- .gitignore
- cmd/vclusterctl/cmd/connect.go
/kind feature
resolves #523 
Fixed an issue where vcluster ... connect command has flag to pass on the context-name which will overwrite the default context
> Allow context name as a flag to connect command for generated config

- .github/workflows/e2e-tests.yaml
- cmd/vcluster/cmd/start.go
- cmd/vclusterctl/cmd/app/create/types.go
- cmd/vclusterctl/cmd/app/localkubernetes/configure.go
- cmd/vclusterctl/cmd/app/localkubernetes/localkubernetes.go
- cmd/vclusterctl/cmd/app/podprinter/podprinter.go
- cmd/vclusterctl/cmd/connect.go
- cmd/vclusterctl/cmd/create.go
- cmd/vclusterctl/cmd/delete.go
- cmd/vclusterctl/cmd/disconnect.go
- cmd/vclusterctl/cmd/find/find.go
- cmd/vclusterctl/cmd/list.go
- cmd/vclusterctl/cmd/pause.go
- cmd/vclusterctl/cmd/resume.go
- cmd/vclusterctl/cmd/root.go
- cmd/vclusterctl/cmd/util.go
- cmd/vclusterctl/log/stdout_logger.go
- devspace.yaml
- e2e/framework/framework.go
- go.mod
- go.sum
- pkg/constants/annotation.go
- pkg/helm/helm.go
- pkg/helm/types.go
- pkg/helm/values/k3s.go
- vendor/github.com/mitchellh/go-homedir/LICENSE
- vendor/github.com/mitchellh/go-homedir/README.md
- vendor/github.com/mitchellh/go-homedir/homedir.go
- vendor/modules.txt
/kind feature
resolves #528
**BREAKING CHANGES**
- `vcluster create` now automatically does a connect. Can be disabled via `vcluster create --connect=false`
- `vcluster connect` now by default switches the current kube context to the vcluster context. Can be disabled via `vcluster connect --update-current=false`
- `vcluster delete` now by default deletes the namespace of the vcluster if it was created by vcluster before. Can be disabled via `vcluster delete --auto-delete-namespace=false`
- Refactored …
> feat: skip port-forwarding for local k8s distros

- charts/eks/templates/syncer-deployment.yaml
- charts/k0s/templates/statefulset.yaml
- charts/k3s/templates/statefulset.yaml
- charts/k8s/templates/syncer-deployment.yaml
Adds the plugin name from the `plugin.yaml` to the environment of the plugin container. This allows us in the plugin sdk to get rid of the name inside the code.
> refactor: add plugin name as env to plugin container

- cmd/vclusterctl/cmd/app/create/types.go
- cmd/vclusterctl/cmd/app/localkubernetes/configure.go
- cmd/vclusterctl/cmd/create.go
- pkg/helm/types.go
- pkg/helm/values/k3s.go
vcluster cli will now deploy vcluster with enabled node sync on local k8s distributions.
> refactor: deploy vcluster with node sync on local k8s

- charts/eks/templates/syncer-deployment.yaml
- charts/eks/values.yaml
- charts/k0s/templates/statefulset.yaml
- charts/k0s/values.yaml
- charts/k3s/templates/statefulset.yaml
- charts/k3s/values.yaml
- charts/k8s/templates/syncer-deployment.yaml
- charts/k8s/values.yaml
- cmd/vcluster/cmd/start.go
- cmd/vcluster/context/context.go
- cmd/vclusterctl/cmd/app/create/types.go
- cmd/vclusterctl/cmd/connect.go
- cmd/vclusterctl/cmd/create.go
- cmd/vclusterctl/cmd/util.go
/kind feature
resolves #561 and #554 
Fixed an issue where vcluster ...  kube-config-context-name flag is available for create command as well as syncer deployment
**What else do we need to know?** UpdateCurrent in create command is also set through flag now.
> Add kube-config-context-name flag for vcluster create and syncer

- .github/workflows/docs.yaml
- .github/workflows/e2e.yaml
- .github/workflows/lint.yaml
- .github/workflows/unit-tests.yaml
The workflow is triggered when a PR is created or updated, i.e when new commits are pushed. If a commit is pushed while the old run was in progress then GH triggers a new workflow without terminating the workflow in progress. So now at this time, there are be 2 GH actions running on PR, one is on the latest commit and one is on the old commit.
The changes in this PR are to ensure that the old workflow run is terminated if the PR is updated.
> enhancement: cancel old running workflows when the PR is updated

- charts/eks/templates/pre-install-hook-job.yaml
- charts/k8s/templates/pre-install-hook-job.yaml
/kind bugfix
N/A
Fixed an issue where pre-install job was not able to run in namespace where *Restricted* Pod Security Standard is enforced because of missing seccompProfile.
Related to #564 as I'm testing how tight we can harden vcluster environments.
> include seccompProfile to pre-install jobs if isolation mode is enabled

- cmd/vclusterctl/cmd/app/localkubernetes/configure.go
/kind bugfix
Fixes the use of port forwarding in connect command when direct connection is possible.
Before:
```
$ vcluster connect vcluster -n vcluster
info   Starting proxy container...
warn   Error exposing local vcluster, will fallback to port-forwarding: test connection: timed out waiting for the condition retrieve default namespace: Get "https://127.0.0.1:11436/api/v1/namespaces/default": dial tcp 127.0.0.1:11436: connect: connection refused
done √ Switched active kube context to vcluster_vcluster_vcluster_minikube
warn   Since you are using port-forwarding to connect, you will need …
```
> fix: vcluster connect edge case - deploying proxy for minikube when minikube VM is used

- charts/eks/templates/coredns.yaml
- charts/eks/values.yaml
- charts/k0s/templates/coredns.yaml
- charts/k0s/values.yaml
- charts/k3s/templates/coredns.yaml
- charts/k3s/values.yaml
- charts/k8s/templates/coredns.yaml
- charts/k8s/values.yaml
/kind bugfix
N/A
Fixed an issue where vcluster reserves a lot more resources that it actually needs.
I noticed that when deployed a lot of K8s based vclusters on top of same host cluster it stopped from scheduling pods with error "Insufficient cpu" when all nodes CPU usage was still under 30% (and I have not even enabled HA mode for those yet which would tribe number of those pods).
New values are based on fact that on multiple environments which I checked:
* syncer …
> fix: set more realistic resource requests

- devspace.yaml
Tooling enhancement - a devspace variable to pass additional values file. 
This will be used in the upcoming changes to the PR checks, to easily deploy different configurations.
Usage: `devspace run deploy --var VALUES_FILE=./values.yaml`
N/A
> tooling: option to pass values file to devspace

- cmd/vcluster/cmd/certs.go
- pkg/controllers/resources/nodes/nodeservice/node_service.go
- pkg/controllers/resources/pods/translate/envvars.go
- pkg/controllers/resources/pods/translate/translator.go
- pkg/util/translate/translate.go
Replace `strings.Replace(s, old, new, -1)` with `strings.ReplaceAll(s, old, new)`. `strings.ReplaceAll` is a wrapper function for `strings.Replace`, but `strings.ReplaceAll` is more readable and removes the hardcoded `-1`.
N/A, this is not a user-facing change
> refactor: replace strings.Replace with strings.ReplaceAll

- pkg/helm/values/k3s.go
The `addCommonReleaseValues` is used in cluster-api-provider-vcluster, where we will no longer be setting the CIDR value upfront. This produces an unnecessary entry in the generated values:
```
serviceCIDR: null
```
which won't be present after this change.
N/A
> feat: add serviceCIDR to values only when provided

- pkg/controllers/resources/pods/translate/translator.go
/kind bugfix
resolves #583
Fixed an issue where vcluster synced pods could end with an - in hostname
> fix: fixed an issue with - ending hostname

- cmd/vclusterctl/cmd/find/find.go
/kind bugfix
resolves N/A
When using devspace to work on vcluster/plugins and replacing one of the images in the statefulset with a dev image, devspace will scale the statefulset to zero and replace it with a devspace managed deployment. this causes there to be a statefulset *and* a deployment with the vcluster release label causing vcluster to report a duplicate of the same vcluster when using vcluster list.
example:
```
➜ vcluster list
NAME       NAMESPACE             STATUS    CONNECTED   CREATED                         AGE
vcluster   vcluster-plugin-dev   Running               2022-07-13 15:21:55 -0700 PDT   3m57s
vcluster   vcluster-plugin-dev …
```
> fix: resolves duplicate vclusters in list when using devspace

- pkg/server/filters/service.go
resolves #593
vcluster will now sync the specific node ports of a service during creation.
> refactor: allow node ports during service create

- charts/eks/templates/syncer-service.yaml
- charts/eks/values.yaml
- charts/k0s/templates/service.yaml
- charts/k0s/values.yaml
- charts/k3s/templates/service.yaml
- charts/k3s/values.yaml
- charts/k8s/templates/syncer-service.yaml
- charts/k8s/values.yaml
Allow setting the loadBalancerSourceRanges when the Service type is LoadBalancer
resolves https://github.com/loft-sh/vcluster/issues/606
relates to https://github.com/loft-sh/cluster-api-provider-vcluster/issues/15
Allow setting the loadBalancerSourceRanges when the Service type is LoadBalancer in the Helm charts
> Allow setting the loadBalancerSourceRanges when the Service type is LoadBalancer

- charts/eks/values.yaml
- charts/k0s/values.yaml
- charts/k3s/values.yaml
- charts/k8s/values.yaml
- docs/pages/operator/external-access.mdx
This was a request raised in the community Slack - https://loft-sh.slack.com/archives/C01N273CF4P/p1657916368544929 
**Breaking change:** Removed the "kubernetes.io/ingress.class" annotation from the Ingress created by the vcluster chart.
The "kubernetes.io/ingress.class" Ingress [annotation is "deprecated"](https://kubernetes.io/docs/concepts/services-networking/ingress/#deprecated-annotation), and .spec.ingressClassName field should be used …
> feat: remove the "kubernetes.io/ingress.class" Ingress annotation

- charts/eks/templates/init-configmap.yaml
- charts/eks/values.yaml
- charts/k0s/templates/init-configmap.yaml
- charts/k0s/values.yaml
- charts/k3s/templates/init-configmap.yaml
- charts/k3s/values.yaml
- charts/k8s/templates/init-configmap.yaml
- charts/k8s/values.yaml
/kind feature
Slack thread - https://loft-sh.slack.com/archives/C01NP55P8F6/p1658489200272449
vcluster user would like to be able to pass vcluster name inside of the cluster
feat(charts): add init.manifestsTemplate field to values, which can be used to create a helm templated manifest which can use helm values passed to vcluster chart, for example vcluster name - "{{ .Release.Name }}".
This is just an idea, I open to suggestions how to implement this better, or to …
> feat(charts): add helm templated init manifest

- charts/eks/templates/init-configmap.yaml
- charts/k0s/templates/init-configmap.yaml
- charts/k3s/templates/init-configmap.yaml
- charts/k8s/templates/init-configmap.yaml
- pkg/controllers/manifests/init.go
- pkg/controllers/manifests/types.go
- pkg/helm/helm.go
- pkg/util/applier/direct.go
- test/e2e/manifests/chart.go
- test/e2e/manifests/init.go
/kind bugfix
Add status annotations with error meassages where applicable to init manifests and charts.
Fixed an issue where vcluster init chart upgrade would fail/get stuck due to namespace mismatch
> add chart status tracking via annotations

- docs/pages/architecture/storage.mdx
Fixed a typo on the storage page of the main documentation website. Link to the page [here](https://www.vcluster.com/docs/architecture/storage).
> docs: corrected typo on the storage documentation page

- docs/pages/architecture/scheduling.mdx
Fixed a typo on the scheduling page of the main documentation website. Link to the page [here](https://www.vcluster.com/docs/architecture/scheduling)
> corrected typo on the scheduling documentation page

- cmd/vclusterctl/cmd/connect.go
/kind bugfix
running command under vcluster kube context doesn't provide the right exit code when commands fail:
```console
$ vcluster connect vcluster -- kubectl get ns nonexistent
Error from server (NotFound): namespaces "nonexistent" not found
$ echo $?
0
```
so it's much harder to exit the ci/cd pipeline
Fixed an issue where vcluster connect doesn't return non-zero exit code of failing command
> fix: return non-zero exit code on failing command

- pkg/controllers/resources/nodes/translate.go
/kind bugfix
Allocatable pods were calculated incorrectly. Calculation assumed that all pods in the targetNamespace were from vcluster, so the result was always off but at least 1 pod(vcluster itself).
Fixed an issue where nodes status would show an incorrect number of allocatable pods, which could cause scheduling problems.
> fix(syncer): allocatable pods calculation

- charts/k0s/templates/statefulset.yaml
fixes #648
/kind bugfix
resolves #648 
Fixed an issue where vcluster with the k0s distro would fail to create / upgrade to version `0.11.0` because of additional volume `/run/k0s`. We now only create this when rootless mode is enabled
> use run-k0s only when in rootless mode

- charts/eks/templates/rbac/role.yaml
- charts/k0s/templates/rbac/role.yaml
- charts/k3s/templates/rbac/role.yaml
- charts/k8s/templates/rbac/role.yaml
/kind bugfix
https://loft-sh.slack.com/archives/C01N273CF4P/p1659972352151499
Fixed an issue where vcluster would request `pods/ephemeralcontainers` RBAC permissions on Kubernetes host clusters that do not support this feature(v1.22 and earlier).
> fix(charts): add ephemeralcontainers permission only on k8s 1.23+

- docs/pages/operator/external-access.mdx
It was not clear to me as to why the ingress was not working even after setting up things as per the documentation, and it took a while to figure out that `ingressClassName` was missing from the example. 
Add `ingressClassName` to the example to make it easier for the users who're new to Kubernetes
> docs: add `ingressClassName` to the ingress example

- pkg/controllers/resources/pods/translate/translator.go
Resolves inability to distinguish pods without owners from pods spawned by jobs from within the host cluster.
Fixed an issue where vcluster was not setting the OwnerSetKind annotation on host-level pods translated from vcluster pods owned by a Job.
Nothing?
> Add OwnerSetKind annotation to Job pods

- .vscode/launch.json
Tooling improvement
Solves some tooling errors which were preventing inspection of the maps that contain interface{} while debugging remotely.
N/A
> tooling: improve debug config for VSCode

- docs/pages/operator/init-manifests.mdx
- docs/pages/operator/restricted-hosts.mdx
fixed typos in operator/init-manifests and operator/restricted-hosts documentation pages
> docs: fixed typos in operator/init-manifests and operator/restricted-hosts documentation pages 

- cmd/vclusterctl/cmd/disconnect.go
on vcluster disconnect, it shows a message saying it successfully disconnected and switched back to original context
/kind feature
resolves #677 
Fixed an issue where on vcluster disconnect, it shows a message saying it successfully disconnected and switched back to original context
screenshot below
> Updated Disconnect to display the message on exit

- pkg/controllers/resources/persistentvolumes/syncer.go
- pkg/controllers/resources/persistentvolumes/syncer_test.go
- pkg/controllers/resources/persistentvolumes/translate.go
/kind bugfix
It partially fixes issue #600. Enable SC & PV sync from virtual cluster to host cluster. When the SC (ReclaimPolicy is Retain), PVC & Pod were created on the VC and the PV was dynamically provisioned, a delete on the POD and then PVC, used to delete the PV as well. This fix now retains the PV, when the ReclaimPolicy is set to Retain.
Fixed an issue where a dynamically provisioned PersistentVolume is retained, when the PersistentVolumeReclaimPolicy is Retain.
**Issue Root Cause**
A check …
> Retain the PersistentVolume when the PersistentVolumeReclaimPolicy is 'Retain'.

- pkg/controllers/resources/nodes/fake_syncer.go
/kind bugfix
Resolves bug in fake node syncer where fake node hostname label values are not truncated when necessary.
Fixed an issue where vcluster fake node syncer was generating invalid values for the `kubernetes.io/hostname` label and thus failing to create fake nodes.
Nothing
> Ensure valid kubernetes.io/hostname label for fake nodes

- charts/k0s/templates/statefulset.yaml
/kind bugfix
improves the situation for #678 - it doesn't fully resolve it, but it should actually be "fixable" with a restart of the pod with this change
Fixed an issue where a rootless install of the k0s vcluster chart could leave a socket in place, wedging the cluster until the socket is manually removed.
This will store the status socket for k0s in the emptyDir `/run/k0s`, which would mean that if an instance hits #678 then it should be enough to restart it to …
> [Helm K0s] Try to avoid leaving a status.sock around between restarts

- charts/k0s/templates/statefulset.yaml
/kind bugfix
**What does this pull request do?** 
It adds envvar ETCD_UNSUPPORTED_ARCH=arm64 to k0s statefulset.
Fixed an issue where vcluster creation used to fail on arm64 machine for k0s distro because etcd does not fully support arm64 yet.
> fix: add envvar ETCD_UNSUPPORTED_ARCH=arm64 to run etcd on arm64

- charts/k8s/values.yaml
- pkg/helm/values/k8s.go
Adds support for Kubernetes 1.25 when using k8s distro of vcluster.
I am also running v1.25 conformance tests with this change.
If the tests finish successfully before this is merged, I'll add a commit with results too.
> feat: support 1.25 version with k8s distro

- pkg/controllers/resources/services/syncer.go
/kind bugfix
Resolves an issue where the Service syncer continuously updates a Service in the host cluster because the host cluster and vcluster both have Rancher controller installed. 
Fixed an issue where vcluster was updating a Service excessively. The "field.cattle.io/publicEndpoints" annotation will no longer be synced to Services that vcluster creates in the host cluster.
Example of the annotation on the host Service how vcluster updates it:
```
kind: Service …
```
> fix(syncer): stop syncing "field.cattle.io/publicEndpoints" Service annotation

- charts/eks/templates/controller-deployment.yaml
- charts/k0s/templates/secret.yaml
- charts/k3s/templates/statefulset.yaml
- charts/k8s/templates/controller-deployment.yaml
/kind bugfix
When the "node.alpha.kubernetes.io/ttl" annotation on the host node is not equal to "0", and sync of the real nodes is enabled, the "ttl" controller will be resetting the value of the annotation, and the syncer will keep updating it.
The issue is fixed by disabling Kubernetes "ttl" controller.
Fixed an issue where in specific scenarios vcluster was updating the nodes excessively.
Here is an explanation of what the "ttl" controller does - …
> fix: excessive node updates when syncing real nodes with ttl != 0

- pkg/controllers/resources/persistentvolumes/translate.go
/kind bugfix
resolves #708 
Fixed an issue where vcluster syncer container would panic when PersistentVolume sync is enabled and a PV without the .spec.claimRef is updated.
> fix: panic in PV syncer when ClaimRef is nil

- charts/eks/templates/api-deployment.yaml
- charts/eks/templates/controller-deployment.yaml
- charts/eks/templates/etcd-statefulset.yaml
- charts/eks/templates/syncer-deployment.yaml
- charts/eks/values.yaml
- charts/k0s/templates/statefulset.yaml
- charts/k0s/values.yaml
- charts/k3s/templates/statefulset.yaml
- charts/k3s/values.yaml
- charts/k8s/templates/api-deployment.yaml
- charts/k8s/templates/controller-deployment.yaml
- charts/k8s/templates/etcd-statefulset.yaml
- charts/k8s/templates/scheduler-deployment.yaml
- charts/k8s/templates/syncer-deployment.yaml
- charts/k8s/values.yaml
/kind feature
resolves #711 
The **podAnnotations** key now controls annotations of pod template in api, controller, syncer and etcd. 
> Add podAnnotations key for api, controller, syncer and etcd's pod template

- charts/k3s/templates/coredns.yaml
- charts/k3s/templates/ingress.yaml
- charts/k3s/templates/init-configmap.yaml
- charts/k3s/templates/limitrange.yaml
- charts/k3s/templates/networkpolicy.yaml
- charts/k3s/templates/rbac/clusterrole.yaml
- charts/k3s/templates/rbac/clusterrolebinding.yaml
- charts/k3s/templates/rbac/role.yaml
- charts/k3s/templates/rbac/rolebinding.yaml
- charts/k3s/templates/resourcequota.yaml
- charts/k3s/templates/service.yaml
- charts/k3s/templates/serviceaccount.yaml
- charts/k3s/templates/statefulset-service.yaml
- charts/k3s/templates/statefulset.yaml
- charts/k3s/templates/workloadserviceaccount.yaml
- charts/k3s/values.yaml
resolves #
Added helm value "global.annotations" to k3s chart that will add its annotations to all objects created in the chart. Annotations for specific objects have precedence over global ones.
I have a case where I want to add an annotation to all objects created in the vcluster release. I'm not super happy with using a `global` value because of its special meaning in helm, but I think if still kind of makes sense and I did not want to touch the …
> Allow annotation of all objects created by the chart

- charts/eks/templates/syncer-service.yaml
- charts/eks/values.yaml
- charts/k0s/templates/service.yaml
- charts/k0s/values.yaml
- charts/k3s/templates/service.yaml
- charts/k3s/values.yaml
- charts/k8s/templates/syncer-service.yaml
- charts/k8s/values.yaml
- Adds support for configuring `loadbalancerIP`
- Fixes `externalTrafficPolicy` logic (should be included in NodePort & LoadBalancer cases)
- Fixes `externalIPs` logic. This field should not be tightly bound with the LoadBalancer case. [External IPs](https://kubernetes.io/docs/concepts/services-networking/service/#external-ips) are [typically specified in conjunction with ClusterIP services](https://medium.com/swlh/kubernetes-external-ip-service-type-5e5e9ad62fcd).
Enhanced …
> Add loadBalancerIP; fix externalTrafficPolicy & externalIPs logic

- charts/eks/templates/pre-install-hook-job-role.yaml
- charts/k8s/templates/pre-install-hook-job-role.yaml
/kind bugfix
Resolves #704 
While using Helm deployment, a job runs which tries to create a fake service, an error occurs and we extract the correct service CIDR from this error message. This service CIDR gets assigned to the service-cidr configmap. Currently, the assigned value is incorrect because the service account being used did not have the rights to create the service. This causes the default CIDR value to be set to the configmap.
With this fix, the service creation rights is given to the service-account used by the job that allows the init container to get the correct CIDR.
**Please provide a short message that should …
> Provide service creation rights to the service account for correct service-cidr retrieval on vcluster-eks chart

- charts/eks/values.yaml
- charts/k0s/values.yaml
- charts/k3s/values.yaml
- charts/k8s/values.yaml
/kind bugfix
resolves N/A
Fixed an issue where vcluster resource limits for coredns were too low.
In GKE we encountered an error `Error syncing to physical cluster: pods "coredns-749456dcbf-8d729-x-kube-system-x-vc-cm-123" is forbidden: [minimum cpu usage per Container is 10m, but request is 3m, minimum memory usage per Container is 32Mi, but request is 16Mi]` which caused coredns pod to never get deployed.
> fix: increase minimum coredns resource requests

- charts/eks/templates/api-deployment.yaml
- charts/eks/templates/controller-deployment.yaml
- charts/eks/templates/coredns.yaml
- charts/eks/templates/etcd-statefulset.yaml
- charts/eks/templates/pre-install-hook-job.yaml
- charts/eks/templates/syncer-deployment.yaml
- charts/eks/values.yaml
- charts/k0s/templates/coredns.yaml
- charts/k0s/templates/statefulset.yaml
- charts/k0s/values.yaml
- charts/k3s/templates/coredns.yaml
- charts/k3s/templates/statefulset.yaml
- charts/k3s/values.yaml
- charts/k8s/templates/api-deployment.yaml
- charts/k8s/templates/controller-deployment.yaml
- charts/k8s/templates/coredns.yaml
- charts/k8s/templates/etcd-statefulset.yaml
- charts/k8s/templates/pre-install-hook-job.yaml
- charts/k8s/templates/scheduler-deployment.yaml
- charts/k8s/templates/syncer-deployment.yaml
- charts/k8s/values.yaml
This allows users to set labels on the pods that are created from the helm chart, including the coredns pod (subject to the usual translation unless `--sync-labels` syncer flag is used).
This is useful for example when Istio sidecar injection is enabled in the namespace where vcluster is installed. Then the user can disable it on the vcluster pods with the `sidecar.istio.io/inject: "false"` label.
chart: Added a helm value to set labels on the vcluster pods.
> feat(chart): helm values to set labels on vclusters pods

- cmd/vclusterctl/cmd/create.go
/kind bugfix
Solves this error:
```
$ vcluster create vcluster -n vcluster -f values_1.25.yaml
info   Detected local kubernetes cluster minikube. Will deploy vcluster with a NodePort & sync real nodes
info   officially unsupported host server version 1.25, will fallback to virtual cluster version v1.24
fatal  illegal base64 data at input byte 6
```
N/A - this was a regression from the last beta build, I don't think it's necessary to mention a fix for an issue which was not present in the previous GA …
> fix: vcluster create error - illegal base64 data at input byte x

- .github/workflows/e2e.yaml
- charts/k3s/values.yaml
- pkg/constants/coredns.go
- pkg/helm/values/k3s.go
Adding support for k3s v1.25 
Bump the k8s version of the KinD cluster used for e2e to v1.25.0
Adding support for k3s v1.25
> Add support for k3s v1.25

- charts/eks/templates/etcd-statefulset.yaml
- charts/k0s/templates/statefulset.yaml
- charts/k3s/templates/statefulset.yaml
- charts/k8s/templates/etcd-statefulset.yaml
/kind bugfix
The helm chart was checking wrong value in a condition for user-defined volumeClaimTemplates.
New condition use `hasKey` function in order to allow setting no volumeClaimTemplates.
Fixed an issue where vcluster chart was ignoring the `volumeClaimTemplates` (or `etcd.volumeClaimTemplates`) helm value. The `storage.volumeClaimTemplates` helm value is no longer needed.
> fix(chart): wrong condition for volumeClaimTemplates

- docs/pages/getting-started/connect.mdx
It mentioned `host-namespace-1` instead of `vcluster-my-vcluster`
> Fix wrong namespace name in getting-started docs

- cmd/vclusterctl/cmd/completion.go
- cmd/vclusterctl/cmd/connect.go
- cmd/vclusterctl/cmd/delete.go
- cmd/vclusterctl/cmd/get/get.go
- cmd/vclusterctl/cmd/pause.go
- cmd/vclusterctl/cmd/resume.go
- cmd/vclusterctl/cmd/root.go
/kind feature
resolves #673
Shell completion now suggests vcluster and namespace completions based on the running vclusters and existing namespaces.
- Commands with vcluster_name positional argument(connect, delete, pause, resume) now get autocompleted.
```
source <(vcluster completion bash)
$ vcluster connect #tab,tab
cluster1 cluster2
```
- Specifying the namespace flag also narrows down the cluster results
- Namespaces also get similarly autocompleted (kube-system is left out)
- The usage line for each now shows the positional argument …
> feat(cli): add dynamic shell completion for vcluster_name and namespaces

- docs/pages/architecture/synced-resources.mdx
resolves #
Starting with v0.12.0, vcluster will by default now not sync ingresses anymore. Updating the documentation to reflect this along with the inline example.
Update docs for synced resources to reflect change in default sync setting for ingresses
> Update docs for synced resources to reflect change in default sync setting for ingresses since v0.12.0

- charts/eks/templates/_helpers.tpl
- charts/eks/templates/rbac/clusterrole.yaml
- charts/eks/templates/rbac/clusterrolebinding.yaml
- charts/k0s/templates/_helpers.tpl
- charts/k0s/templates/rbac/clusterrole.yaml
- charts/k0s/templates/rbac/clusterrolebinding.yaml
- charts/k3s/templates/_helpers.tpl
- charts/k3s/templates/rbac/clusterrole.yaml
- charts/k3s/templates/rbac/clusterrolebinding.yaml
- charts/k8s/templates/_helpers.tpl
- charts/k8s/templates/rbac/clusterrole.yaml
- charts/k8s/templates/rbac/clusterrolebinding.yaml
/kind bugfix
resolves #765
refs #755
Fixed vcluster crashing when `sync.ingresses` is enabled
Thanks to @MPV for identifying the solution. This PR fixes it, but also implements a common function to prevent it from happening in the future as well.
> fix: vcluster crashing when `sync.ingresses` is enabled

- cmd/vclusterctl/cmd/create.go
- cmd/vclusterctl/cmd/delete.go
and corrected existing check to prevent namespace deletion incase another vcluster is running in the same namespace.
/kind bugfix
resolves # Regression of earlier fix
Allow multiple-vcluster-creation in a single namespace. If a vcluster is deleted and another vcluster is running in the same namespace, namespace won't be deleted.
> Allow multiple-vcluster-creation in a single namespace

- pkg/controllers/resources/persistentvolumes/syncer.go
- pkg/controllers/resources/persistentvolumes/syncer_test.go
/kind bugfix
This fixes the "issue 2" of the issue #600. With this fix, when the PV is dynamically provisioned and its reclaim policy is Delete, we now wait for the physical PV to be deleted and in-turn the CSI to delete the cloud provider volume naturally. Once the physical PV gets deleted, the existing code takes care of clearing the finalizers on the virtual PV and the same gets deleted eventually.
Releases the cloud provider volume when a dynamically provisioned PV with a reclaim policy of …
> Releases the cloud provider volume when a dynamically provisioned PV with a reclaim policy of 'Delete', is deleted.

- docs/pages/plugins/generic-crd-sync.mdx
- docs/sidebars.js
Documents the [vcluster generic crd sync plugin](https://github.com/loft-sh/vcluster-generic-crd-sync-plugin).
Added documentation for [vcluster generic CRD sync plugin](https://github.com/loft-sh/vcluster-generic-crd-sync-plugin).
At the moment of creation, there are two tables missing, I'll add those ASAP. Marked as draft until then.
> docs: add generic crd sync plugin

- charts/eks/templates/syncer-service.yaml
- charts/eks/values.yaml
- charts/k0s/templates/service.yaml
- charts/k0s/values.yaml
- charts/k3s/templates/service.yaml
- charts/k3s/values.yaml
- charts/k8s/templates/syncer-service.yaml
- charts/k8s/values.yaml
Allow setting the `LoadBalancerClass` if using an external LoadBalancer controller and running Kubernetes 1.22+ (stable in 1.24)
> Allow setting the LoadBalancerClass if using an external LoadBalancer controller

- charts/eks/templates/init-configmap.yaml
- charts/k0s/templates/init-configmap.yaml
- charts/k3s/templates/init-configmap.yaml
- charts/k8s/templates/init-configmap.yaml
/kind bugfix
Currently, we can't "easily" use the `init.manifestsTemplate` value because there is no carriage return between `init.manifest` and `init.manifestsTemplate` (because of the `trim` + `-` just before templating `init.manifestsTemplate`).  
I didn't create an issue because it's a short quick fix, but I can create a new one if needed.
Fixed merging issue between `manifest` and `manifestsTemplate` on the Helm chart
Here is an example with the following …
> Fix init-manifest merge issue on Configmap

- charts/eks/templates/init-configmap.yaml
- charts/k0s/templates/init-configmap.yaml
- charts/k3s/templates/init-configmap.yaml
- charts/k8s/templates/init-configmap.yaml
This PR does not solve any issue, it is rather a suggestion. The goal is to allow the use of `vcluster` as a subchart by adding some templates to the Helm values. With this we can use the actual values to inject them into the Helm map that will be deployed when the vcluster is created.
Allow templating with chart values inside the init-configmap
> Allow templating with chart values inside the init-configmap

- docs/pages/architecture/nodes.mdx
- docs/pages/architecture/scheduling.mdx
- pkg/controllers/resources/nodes/syncer.go
- pkg/controllers/resources/nodes/syncer_test.go
Adds an enhancement to allow nodes to be synced based on the NodeSelector or the pod workloads being run. 
Adds an enhancement to sync nodes with either the nodeSelector, or running pods. Previously if you supplied a nodeSelector it would ignore any nodes needed by a pod. 
The Test Suite should provide adequate coverage of the changes, but since I'm new to your project, it could require some modifications or additions.
> Add Node Sync on Labels and Pod Workloads

- cmd/vclusterctl/cmd/create.go
- cmd/vclusterctl/cmd/delete.go
- cmd/vclusterctl/cmd/util.go
As a prerequisite helm v2 is not currently supported and must be validated beforehand. Also, the version command for helm v2 without the '--client' flag will force the validation of a remote tiller deployment which could lead to a potential 'exit 1' error.
Issue: #803
/kind bugfix
resolves #803
Fixed an issue where vcluster allowed non-supported helm v2 binary to be used
> fix: validate helm's binary version

- cmd/vclusterctl/cmd/delete.go
- cmd/vclusterctl/cmd/list.go
/kind feature
resolves #389 
add aliases. `rm` for delete and `ls` for list.
I also briefly considered adding an alias for other commands. In all cases, however, one would have saved only 1 letter and there I thought, rather less aliases and for it a more comprehensible cli.
However, if anyone can think of a good alias for other commands, I'd be happy to add them.
>  Aliases for list/delete commands #389

- .github/workflows/release.yaml
- hack/embed-charts.sh
/kind bugfix
Fixes problems in the MacOS runner - `../../../hack/embed-charts.sh: line 8: realpath: command not found`
Updating to new runners:
The ubuntu-18.04 runner [is deprecated](https://github.blog/changelog/2022-08-09-github-actions-the-ubuntu-18-04-actions-runner-image-is-being-deprecated-and-will-be-removed-by-12-1-22/), and ubuntu-latest will move to ubuntu-22.04 on Dec 1st, so I am bumping to that.
Currently macos-latest = macos-11, but it will change to macos-12 on Dec 1st. [According to Readme](https://github.com/actions/runner-images/blob/main/images/macos/macos-12-Readme.md) …
> Fix release pipeline

- Dockerfile.cli
/kind bugfix
Fixes:
```
> [linux/amd64 builder 10/12] RUN go generate ./...:
#41 2.840 ../../../hack/embed-charts.sh: line 15: helm: command not found
#41 2.841 cmd/vclusterctl/cmd/create.go:43: running "../../../hack/embed-charts.sh": exit status 127
```
N/A
> fix(tooling): install Helm for build of Dockerfile.cli

- devspace.yaml
- hack/embed-charts.sh
/kind bugfix
Fixed an issue whereL
- You needed to run `go generate ./...` within the devspace syncer
- hack/embed-charts depended on realpath (not available by default on MacOS)
> Fix Chart generation experience for: `devspace dev` and macos 

- cmd/vclusterctl/cmd/create.go
- hack/embed-charts.sh
Signed-off-by: Rohan CJ <rohan.joseph@loft.sh>
/kind bugfix
The release pipeline sets RELEASE_VERSION to vx.y.z for cli, but to x.y.z in other places, the current code assumes the helm chart is bundled at x.y.z instead of vx.y.z.
resolves #
> fix: look for charts with 'v' version prefix

- charts/eks/templates/api-deployment.yaml
- charts/eks/templates/controller-deployment.yaml
- charts/eks/values.yaml
- charts/k0s/templates/statefulset.yaml
- charts/k0s/values.yaml
- charts/k3s/values.yaml
- charts/k8s/values.yaml
- go.mod
- go.sum
- vendor/github.com/loft-sh/utils/pkg/helm/values/eks.go
- vendor/github.com/loft-sh/utils/pkg/helm/values/k0s.go
- vendor/github.com/loft-sh/utils/pkg/helm/values/k3s.go
- vendor/github.com/loft-sh/utils/pkg/helm/values/k8s.go
- vendor/modules.txt
Bump loft-sh/utils dependency to pick up new releases for all distros.
Include support for Kubernetes 1.25 for the k3s(default), k0s, and k8s distros of vcluster. 
Include support for Kubernetes 1.24 for the EKS distro of vcluster. 
Update images used across all distros and all minor versions to the latest stable versions.
> chore: bump loft-sh/utils to pick up new releases for all distros

- cmd/vclusterctl/cmd/create.go
- hack/embed-charts.sh
/kind bugfix
A different approach to fix the same problem that we tried to fix with #819
The charts that we usually create with the release pipeline don't have the `v` prefix for the chart version. The chart version is used internally for the syncer image tag. Using the version with the `v` prefix caused ImagePullBackOff errors.
N/A
> fix: version format for the embeded chart

- conformance/v1.25/README.md
- devspace.yaml
- docs/pages/plugins/generic-crd-sync.mdx
/kind bugfix
The `devspace dev` was occasionally failing due to coredns manifests being mounted as ReadOnly volume.
The CPU limits are slowing down development when using devspace, so I bumped that up to 100 (I think 0 or empty didn't work when I tried it, but it was some time ago).
Added `&values` anchor to reuse parts of the config (namely helm values) and avoid duplication (yes, I am too lazy to scroll down through duplicate lines :joy: ).
Added regex example to the generic crd sync plugin page because someone mentioned that it would be nice to have :) 
**Please …
> Docs and dev enhancments

- charts/k8s/templates/api-deployment.yaml
- charts/k8s/templates/controller-deployment.yaml
- charts/k8s/templates/etcd-statefulset.yaml
- charts/k8s/templates/scheduler-deployment.yaml
- charts/k8s/templates/syncer-deployment.yaml
/kind bugfix
Fixes default podAntiAffinity for k8s HA. The k8s chart currently sets affinity twice and basicly overrides the default affinity set if HA mode is enabled (last one wins). This PR removes the duplicate affinity definition. Affinity is already set (if not empty) a few lines above. If it's empty the default affinity is used.
Fixed an issue where vcluster didn't apply a default podAntiAffinity when using k8s in HA mode
> fix(chart): do not override affinity in k8s

- docs/pages/operator/init-manifests.mdx
resolves [a question from Slack](https://loft-sh.slack.com/archives/C01N273CF4P/p1669187153875849)
Clarifies the order in which the syncer applies the init manifests(first) and init charts.
N/A
> docs: clarify order of init manifests/charts

- docs/pages/fragments/install/cli.mdx
This decreases chances of user having problems with helm when installing from the same folder where vcluster binary is still present. It would help avoid one of these two problems:
> vcluster create my-vcluster
> fatal  aborting vcluster creation. Current working directory contains a file or a directory with the name equal to the vcluster chart name - "vcluster". Please execute vcluster create command from a directory that doesn't contain a file or directory named "vcluster"
or 
> helm upgrade --install my-vcluster vcluster ...
> Release "my-vcluster" …
> docs: remove vcluster binary after installing it

- cmd/vcluster/context/flag_options.go
- pkg/controllers/resources/nodes/syncer.go
- pkg/controllers/resources/nodes/syncer_test.go
- pkg/controllers/resources/nodes/translate.go
This PR adds the capability to clear node images from the physical nodes when syncing down to the virtual node. 
Enabling `node-clear-image-status` clears all `status.images` from the node when it is synced to the virtual cluster. Images can leak information about a node when running in a multi-tenant environment where customers share the nodes they run on. Enabling this flag helps prevent information leaking.
> Add Flag to clear node images from node status

- pkg/controllers/resources/persistentvolumeclaims/translate.go
Added translation for the dataSourceRef field in PersistentVolumeClaim Spec
In Kubernetes v1.22, if the `AnyVolumeDataSource` feature gate is enabled, the `dataSourceRef` field is added, which behaves similarly to the dataSource field except that it allows arbitrary objects to be specified. The API server ensures that the two fields always have the same contents, and neither of them are mutable. The differences is that at creation time dataSource allows only PVCs or VolumeSnapshots, and ignores all other values, while dataSourceRef allows most types of …
> Add translation support for the dataSourceRef field in PersistentVolumeClaim Spec

- charts/k8s/values.yaml
- go.mod
- go.sum
- vendor/github.com/loft-sh/utils/pkg/helm/values/k8s.go
- vendor/modules.txt
Adds support for Kubernetes 1.26 when using k8s distro of vcluster.
I have run the conformance tests for this version and there are no failures.
Fixes ENG-754
> support 1.26 version with k8s distro

- charts/k0s/templates/secret.yaml
- charts/k0s/values.yaml
/kind feature
Partly resolves #397 . In comparison to k3s, the cluster domain cannot be passed as an argument to the [k0s controller](https://docs.k0sproject.io/v1.25.4+k0s.0/cli/k0s_controller/). instead it needs to be defined in the [k0s config](https://docs.k0sproject.io/v1.25.4+k0s.0/configuration/#specnetwork). This PR exposes the `spec.network.clusterDomain` configuration field as a helm value
clusterDomain can be passed to k0s
In case coredns managed by vcluster, a custom coredns.yaml must still be …
> allow setting clusterDomain in k0s helm chart

- charts/eks/templates/rbac/role.yaml
- charts/eks/templates/rbac/rolebinding.yaml
- charts/k0s/templates/rbac/role.yaml
- charts/k0s/templates/rbac/rolebinding.yaml
- charts/k3s/templates/rbac/role.yaml
- charts/k3s/templates/rbac/rolebinding.yaml
- charts/k8s/templates/rbac/role.yaml
- charts/k8s/templates/rbac/rolebinding.yaml
/kind bugfix
Fixes conflict that can occur when more than one multi-namespace vcluster is installed into the same host cluster. E.g.:
> error executing 'helm upgrade vcluster --values /tmp/710276097 --install --namespace vc ./charts/k3s --kube-context minikube': Error: rendered manifests contain a resource that already exists. Unable to continue with install: ClusterRole "vcluster" in namespace "" exists and cannot be imported into the current release: invalid ownership metadata; annotation validation error: key "meta.helm.sh/release-namespace" must equal "vc": current value is "mn" …
> fix(chart): ClusterRole name conflict in multi-namespace mode

- .github/workflows/e2e.yaml
/kind bugfix
For example in [this workflow run](https://github.com/loft-sh/vcluster/actions/runs/3800221712/jobs/6463528938) the "Wait until vcluster is ready" step was skipped because vcluster failed to install, and the "Collect deployment information in case vcluster fails to start" should have been started, but it was skipped instead. Current behavior wastes time (waiting for results and also CI minutes) before inevitably failing.
N/A for CI changes
> fix(ci): E2E workflow should fail faster if the vcluster wasn't ready

- docs/pages/plugins/tutorial.mdx
- pkg/controllers/resources/configmaps/translate.go
- pkg/controllers/resources/csidrivers/translate.go
- pkg/controllers/resources/csinodes/translate.go
- pkg/controllers/resources/csistoragecapacities/translate.go
- pkg/controllers/resources/endpoints/translate.go
- pkg/controllers/resources/ingressclasses/translate.go
- pkg/controllers/resources/ingresses/legacy/translate.go
- pkg/controllers/resources/ingresses/translate.go
- pkg/controllers/resources/namespaces/translate.go
- pkg/controllers/resources/networkpolicies/translate.go
- pkg/controllers/resources/nodes/fake_syncer.go
- pkg/controllers/resources/nodes/translate.go
- pkg/controllers/resources/persistentvolumeclaims/translate.go
- pkg/controllers/resources/persistentvolumes/translate.go
- pkg/controllers/resources/poddisruptionbudgets/translate.go
- pkg/controllers/resources/priorityclasses/translate.go
- pkg/controllers/resources/secrets/translate.go
- pkg/controllers/resources/serviceaccounts/translate.go
- pkg/controllers/resources/services/translate.go
- pkg/controllers/resources/storageclasses/host_sc_translate.go
- pkg/controllers/resources/storageclasses/translate.go
- pkg/controllers/resources/volumesnapshots/volumesnapshotclasses/translate.go
- pkg/controllers/resources/volumesnapshots/volumesnapshotcontents/translate.go
- pkg/controllers/resources/volumesnapshots/volumesnapshots/translate.go
- pkg/controllers/syncer/translator/util.go
Refactored newIfNil function using go generics
Trying to avoid use of reflection for checking if the updated object is nil. Benchmark says its not that bad, but still if we can find some way to avoid it.
```goos: linux
goarch: amd64
pkg: github.com/loft-sh/vcluster/pkg/controllers/syncer/translator
cpu: AMD Ryzen 5 5600U with Radeon Graphics         
BenchmarkNewIfNilGenerics-12    	 4560048	       336.8 ns/op	     624 B/op	       3 allocs/op
BenchmarkNewIfNilExisting-12    	 3870843	       287.5 ns/op	     624 B/op	       3 allocs/op
PASS
coverage: 4.0% of …
```
> Generics for syncer 'newIfNil' function

- cmd/vcluster/context/flag_options.go
- pkg/controllers/resources/namespaces/syncer.go
- pkg/controllers/resources/namespaces/translate.go
/kind feature
Adds an option to set additional labels on the namespaces synced in the multi-namespace mode.
Add --namespace-labels flag to allow setting additional labels on the namespaces synced in the multi-namespace mode.
Closes ENG-843
> feat(syncer): add --namespace-labels flag

- charts/eks/templates/rbac/rolebinding.yaml
- charts/k0s/templates/rbac/rolebinding.yaml
- charts/k8s/templates/rbac/rolebinding.yaml
/kind bugfix
N/A
Fixed an issue where vcluster non k3s templates had a small issue w/ role binding name
Guessing this just got missed in the other charts, so I made the non k3s charts look like the k3s one!
> fix(chart): fix non k3s charts rolebinding name

- charts/eks/templates/_helpers.tpl
- charts/eks/templates/rbac/clusterrole.yaml
- charts/eks/templates/rbac/role.yaml
- charts/eks/templates/rbac/rolebinding.yaml
- charts/k0s/templates/_helpers.tpl
- charts/k0s/templates/rbac/clusterrole.yaml
- charts/k0s/templates/rbac/role.yaml
- charts/k0s/templates/rbac/rolebinding.yaml
- charts/k3s/templates/_helpers.tpl
- charts/k3s/templates/rbac/clusterrole.yaml
- charts/k3s/templates/rbac/role.yaml
- charts/k3s/templates/rbac/rolebinding.yaml
- charts/k8s/templates/_helpers.tpl
- charts/k8s/templates/rbac/clusterrole.yaml
- charts/k8s/templates/rbac/role.yaml
- charts/k8s/templates/rbac/rolebinding.yaml
/kind bugfix
N/A
Fixed an issue where vcluster charts for Multinamespace mode would overwrite role/bindings causing syncer to have insufficient privileges
N/A
> fix(chart): fix overwriting second clusterrole/binding when using multinamespace mode

- pkg/controllers/register.go
- pkg/controllers/servicesync/servicesync.go
/kind bugfix
resolves #896 
Fixed an issue where vcluster doesn't clean up services that have been created via the `--map-virtual-service` option when the vcluster is delete.
> Add ownerreferences to synced services

- charts/eks/templates/_helpers.tpl
- charts/k0s/templates/_helpers.tpl
- charts/k3s/templates/_helpers.tpl
- charts/k8s/templates/_helpers.tpl
/kind bugfix
N/A
Fixed an issue where vcluster doesn't render role needed for multinamespace mode
think I didn't realize before in testing since I copied values I use for home dev vclusters which included ingress sync, which caused that template logic to be true, which made things work.
would it make sense to have a (cluster)role especially for multinamespace mode instead of tacking on extra conditionals to existing roles making things a bit more confusing?
> fix: always render the (cluster because multinamespace)role when multi ns enabled

- charts/eks/templates/controller-deployment.yaml
- charts/eks/values.yaml
- charts/k0s/values.yaml
- charts/k3s/values.yaml
- charts/k8s/values.yaml
- go.mod
- go.sum
- vendor/github.com/loft-sh/utils/pkg/helm/values/eks.go
- vendor/github.com/loft-sh/utils/pkg/helm/values/k0s.go
- vendor/github.com/loft-sh/utils/pkg/helm/values/k3s.go
- vendor/github.com/loft-sh/utils/pkg/helm/values/k8s.go
- vendor/modules.txt
Updated supported distros to v1.26
**What else do we need to know?**    
- updated k0s,k3s,k8s chart image to latest stable release for v1.26
- updated eks chart image to latest stable release for v1.24
Closes ENG-894
> Update supported distros to v1.26

- charts/eks/templates/_helpers.tpl
- charts/k0s/templates/_helpers.tpl
- charts/k3s/templates/_helpers.tpl
- charts/k8s/templates/_helpers.tpl
/kind bugfix
N/A
Fixed an issue where vclusters in multinamespace mode with long release names would not get the second cluster role created
basically just a better version of the previous "fix", this time hopefully for real :D
> fix: ensure multinamespace role name not broken by truncation

- pkg/controllers/servicesync/servicesync.go
/kind bugfix
resolves ENG-917 , #901 
Fixed an issue where vcluster `mapServices.fromVirtual....` option was not workign as expected in case of `headless` services
> add case for mapping headless service

- pkg/controllers/register.go
/kind bugfix
Allow virtual cluster to host cluster service mapping to work with multi-namespace mode
Currently, in case of Virtual->Host service mapping, the service that gets created on the host cluster relies on label-selector based method to map the workloads. This works for single-namespace mode, as the end service and workloads are in the same namespace. But, for multi-namespace, it doesn't work as the workload is in a different namespace.
With this PR, we are creating a headless service on the host and setting the endpoint for this service equal to the clusterIP of the …
> Allow virtual cluster to host cluster service mapping to work with multi-namespace mode

- charts/eks/templates/coredns.yaml
- charts/k0s/templates/coredns.yaml
- charts/k3s/templates/coredns.yaml
- charts/k8s/templates/coredns.yaml
- docs/pages/fragments/non-root-vcluster.mdx
- pkg/coredns/coredns.go
- fix(chart): ignoring .securityContext values for coredns
- feat(chart): expose .securityContext.runAsGroup for coredns
resolves #742 
resolves ENG-414
fix: pass securityContext.runAsGroup setting to coredns
Updated documentation as well
> feat(chart): expose .securityContext.runAsGroup

- charts/k0s/templates/coredns.yaml
resolves https://github.com/loft-sh/vcluster/issues/397 for k0s 
custom clusterDomain is added to coredns config for k0s clusters
This builds upon https://github.com/loft-sh/vcluster/pull/867 to additionally add the custom clusterDomain to the coredns config. There's no [workaround to build a custom coredns config](https://github.com/loft-sh/vcluster/issues/397#issuecomment-1062870644) necessary any more. Affects only k0s
> add custom clusterDomain to coredns

- pkg/controllers/register.go
- test/multins_values.yaml
/kind bugfix
Fixes incorrect behavior in multi-namespace mode and makes it match the behavior in the default mode - host namespace can be omitted in the mapping definition, the namespace where vcluster is installed is used in such case.
The change made to the `test/multins_values.yaml` would have resulted in test failure previously.
Fixed an issue where virtual-to-host service mapping validation would fail in multi-namespace mode if the host service namespace was omitted.
> fix: Virtual-to-Host service mapping should work with omitted Host namespace

- pkg/constants/indices.go
- pkg/controllers/resources/nodes/fake_syncer.go
- pkg/controllers/resources/nodes/fake_syncer_test.go
- pkg/controllers/resources/nodes/syncer_test.go
- pkg/controllers/resources/nodes/translate.go
- pkg/server/filters/nodename.go
- pkg/server/server.go
x509 certificate wildcards don't match subdomains, so we replace the
node address hostname dots with dashes, index that, and translate it
back to the nodename as necessary.
/kind bugfix
resolves ENG-1013
Fixed an issue where vcluster metrics were unreachable under certain conditions.
> fix(vcluster): ensure node addresses match certificate wildcard

- cmd/vclusterctl/cmd/create.go
- cmd/vclusterctl/cmd/get/service_cidr.go
- devspace_start.sh
- hack/test-config.yaml
- pkg/controllers/generic/export_syncer.go
- pkg/controllers/generic/import_syncer.go
- pkg/controllers/resources/services/syncer.go
- pkg/util/servicecidr/servicecidr.go
/kind bugfix
resolves #911 
resolves ENG-937
With this change the vcluster should use exactly the same "service-cluster-ip-range" as the host cluster, including the correct order of the IPv4/IPv6 CIDR rages in case of dual stack. The syncer will sync both IPs of the Kubernetes service.
Fixed an issue where vcluster would fail to start in a cluster that uses dual-stack networking, with IPv6 as the default option for the Service network.
I also fixed a few things …
> Improve dual stack support

- .github/workflows/docs.yaml
- .github/workflows/unit-tests.yaml
/kind chore
Should fix failing workflow runs:
https://github.com/loft-sh/vcluster/actions/runs/4231767129
N/A
> The Ubuntu-18.04 environment is deprecated and will be removed on April 1st, 2023. For more details, see https://github.com/actions/runner-images/issues/6002
> chore: update workflow runners to a newer ubuntu version

- cmd/vclusterctl/cmd/pause.go
- pkg/lifecycle/lifecycle.go
/kind feature
resolves ENG-920
Fixed an issue where vcluster when paused and running under multi namespace mode the host pods are not cleaned up
> add pod cleanup for pause in multi ns mode

- pkg/controllers/resources/pods/translate/hosts.go
/kind bugfix
Fixed an issue where vcluster would not correctly sync securityContext for StatefulSet workload
> Set runAsGroup field of securityContext for 'vcluster-rewrite-hosts' initContainer

- charts/eks/templates/syncer-service.yaml
- charts/k0s/templates/service.yaml
- charts/k3s/templates/service.yaml
- charts/k8s/templates/syncer-service.yaml
- cmd/vclusterctl/cmd/connect.go
- pkg/server/cert/syncer.go
- pkg/util/translate/lb_service_name.go
- pkg/util/translate/translate.go
Creates two services when vcluster is configured with `.Values.service.type` `LoadBalancer`(one of ClusterIP and one of LoadBalancer).
The new loadBalancer service is called `<vclustername>-lb`
TODO: 
/kind bugfix
resolves #930
resolves ENG-1006
Fixed an issue where vcluster LoadBalancer service failed to create
Pre-change, the diff for the templates of all distro services was nil except globalAnnotations was only in k3s. …
> fix: don't expose kubelet when using LoadBalancer svc

- .github/workflows/release.yaml
- hack/build-cli.sh
/kind chore
Resolves failing release pipeline and locks the versions to improve release pipeline stability.
Commands have been updated based on [the changelog for v2](https://github.com/sigstore/cosign/blob/main/CHANGELOG.md#v200).
N/A
> chore: lock cosign version and update commands to v2

- charts/eks/templates/api-service.yaml
- charts/eks/templates/coredns.yaml
- charts/eks/templates/etcd-service.yaml
- charts/eks/templates/etcd-statefulset-service.yaml
- charts/eks/templates/syncer-service.yaml
- charts/eks/values.yaml
- charts/k0s/templates/service.yaml
- charts/k0s/templates/statefulset-service.yaml
- charts/k0s/values.yaml
- charts/k3s/templates/service.yaml
- charts/k3s/templates/statefulset-service.yaml
- charts/k3s/values.yaml
- charts/k8s/templates/api-service.yaml
- charts/k8s/templates/etcd-service.yaml
- charts/k8s/templates/etcd-statefulset-service.yaml
- charts/k8s/templates/syncer-service.yaml
- charts/k8s/values.yaml
resolves #897 
Added a serviceAnnotations Helm value to all charts which can be used to set annotations for core vcluster services
Closes ENG-876
coredns component already has a helm value coredns.service.annotations which can be used for the same purpose
> Add serviceAnnotations helm value for all charts

- cmd/vcluster/context/flag_options.go
- pkg/controllers/resources/pods/validate_pod_security.go
The k8s admission library assumes the admission configuration pointer
is not nil and panics if it is not.
/kind bugfix
resolves ENG-1103
Fixed an edge-case where vcluster triggers a k8s bug.
Made a small edit to the flag doc.
> fix(syncer): don't trigger nil pointer bug in library

- charts/eks/templates/coredns.yaml
- charts/eks/values.yaml
- charts/k0s/templates/coredns.yaml
- charts/k0s/values.yaml
- charts/k3s/templates/coredns.yaml
- charts/k3s/values.yaml
- charts/k8s/templates/coredns.yaml
- charts/k8s/values.yaml
- devspace.yaml
- pkg/coredns/coredns.go
- pkg/coredns/resolv.go
/kind feature
resolves #955
Resolves ENG-1117
Added a new helm value `.Values.fallbackHostDns` that configured the coredns to fallback to the host dns if a service or domain couldn't be found within the vcluster.
> feat: add .Values.fallbackHostDns

- pkg/util/log/log_sink.go
/kind bugfix
resolves ENG-1137
Fixed an issue where vcluster would log debug-level messages by default.
> fix: log only the messages of the correct level

- pkg/util/certhelper/cert.go
- pkg/util/certhelper/cert_test.go
/kind bugfix
The `IsCertExpired` check that is used to determine if certificates need to be regenerated is currently broken. The current check doesn't check for cert's expiration date. This change adds a fix to that part of the code while also adding a test to make sure any future refactors don't cause regression.
Fixed an issue where vcluster has a bug for checking expiration of certs.
Hopefully the added test should catch if this issue should arise in future.
> fix: cert expiry should check for cert's expiry date

- pkg/config/config.go
- pkg/controllers/generic/export_syncer.go
- pkg/controllers/generic/import_syncer.go
- test/e2e_generic/values.yaml
resolves ENG-997 
Fixed an issue where vcluster would fail in case the specified resource in the import/export generic config does not exist on host cluster. We now have the concept of `optional` resources
> enable optional generic resource syncing

- cmd/vclusterctl/cmd/create.go
- pkg/util/servicecidr/servicecidr.go
I think this warning is distracting users from real errors too much, hopefully, downgrade to Info will eliminate that. 
N/A
> fix: switch a Warning to Info msg to avoid user confusion

- .github/workflows/release.yaml
Also push images to ghcr.io/loft-sh/
Images changed: `vcluster`, `vcluster-cli`
This PR does not change the references to the images.
I will do that in a follow-up once I confirm this works.
resolves #
> images: also push to ghcr.io

- .github/workflows/release.yaml
Hadn't noticed that permissions were set. The packages write permission is necessary to push images ghcr.io
/kind bugfix
resolves #
> fix: add package:write permission to push ghcr images

- .github/workflows/release.yaml
turns out read|write is invalid. I suppose write implies read?
The syntax doc for actions is confusing
/kind bugfix
resolves #
> fix: invalid workflow permission value

- pkg/constants/annotation.go
- pkg/lifecycle/lifecycle.go
/kind feature
resolves #981
Adds a `loft.sh/paused-date` annotation to vcluster's statefulset/deployment when a vcluster is paused. Annotation is removed once cluster resumed
> add `loft.sh/paused-date` annotation to paused clusters

- charts/eks/templates/syncer-deployment.yaml
- charts/eks/values.yaml
- charts/k0s/templates/statefulset.yaml
- charts/k0s/values.yaml
- charts/k3s/templates/statefulset.yaml
- charts/k3s/values.yaml
- charts/k8s/templates/syncer-deployment.yaml
- charts/k8s/values.yaml
- cmd/vcluster/context/flag_options.go
- pkg/constants/indices.go
- pkg/controllers/resources/nodes/fake_syncer.go
- pkg/controllers/resources/nodes/fake_syncer_test.go
- pkg/controllers/resources/nodes/nodeservice/node_service.go
- pkg/controllers/resources/nodes/register.go
- pkg/controllers/resources/nodes/syncer.go
- pkg/controllers/resources/nodes/syncer_test.go
- pkg/controllers/resources/nodes/translate.go
- pkg/controllers/syncer/fake_syncer.go
- pkg/server/cert/syncer.go
- pkg/server/filters/nodename.go
- pkg/server/server.go
- test/e2e_node/node.go
this is needed for proper resolution of kubelet metrics targets for prometheus
/kind bugfix
resolves ENG-1197
Fixed an issue where prometheus was not able to get kubelet metrics because the fake nodes did not have `Addresses` of type `InternalIP`
> reimplement fake kubelet services for node InternalIP addresses

- charts/eks/templates/coredns.yaml
- charts/k0s/templates/coredns.yaml
- charts/k3s/templates/coredns.yaml
- charts/k8s/templates/coredns.yaml
- pkg/controllers/resources/nodes/fake_syncer.go
- pkg/server/server.go
/kind bugfix
resolves #956 
Changed the hostname format for Node addresses of the "hostname" type. The name and namespace of the vcluster were removed from the path. This change is backward compatible in this release, but future releases may drop backward compatibility.
> fix: remove vcluster name and namespace from Node hostnames

- cmd/vcluster/cmd/start.go
- pkg/coredns/coredns.go
/kind bugfix
**What does this pull request do? 
resolves https://github.com/loft-sh/vcluster/issues/992
Fixed an issue where disabling coredns results in an error loop during syncer start up. The following PR adds a check for if the file exists and if not we exit the coredns loop and skip the apply of it.
> Bug Fix: Add check if coredns files exists before trying to apply

- pkg/controllers/resources/pods/translate/translator.go
/kind feature
resolves #845
Added ability to sync down the `spec.schedulingGates` property in the `calcSpecDiff` function for the pod translator package.
Used `rancher/k3s:v1.26.3-k3s1` image with `--kube-apiserver-arg=feature-gates=PodSchedulingReadiness=true` for the server args in the k3s chart for testing.
> Add support for spec.schedulingGates in calcDiffSpec

- cmd/vclusterctl/cmd/connect.go
/kind bugfix
This change increases the timeout for retrieving a list of vcluster pods in a running state. It was observed that when running a command such as `vcluster create --upgrade`, when changes deployed incurred redeploy of vcluster pods, it was seen that we hit a failure such as follows because it takes ~15s or so for the pods to come back:
```
fatal    finding vcluster pod: timed out waiting for the condition - can't find a running vcluster pod in namespace vcluster-testvc
```
Fixed an issue where vcluster would timeout on retrieving a …
> fix: increase timeout for retrieving working vcluster pods

- cmd/vcluster/context/flag_options.go
- docs/pages/config-reference.mdx
- docs/pages/operator/security.mdx
- pkg/controllers/generic/import_syncer.go
- pkg/controllers/resources/pods/syncer.go
- pkg/controllers/resources/pods/translate.go
- pkg/controllers/resources/pods/translate/sa_token_secret.go
- pkg/controllers/resources/pods/translate/translator.go
- pkg/controllers/resources/pods/translate/translator_test.go
- pkg/controllers/resources/pods/util.go
- pkg/controllers/syncer/syncer.go
- pkg/util/translate/translate.go
- test/commonValues.yaml
- test/e2e/syncer/pods/pods.go
add to index for secret syncer
/kind bugfix
resolves  ENG-1172 #968
Fixed an issue where vcluster service account token was mounted using downward API and annotation. We are now instead doing it with a dedicated secret containing all projected service account tokens
> move service account token to secret

- pkg/server/filters/metrics.go
/kind bugfix
~/Desktop/vcluster-debug   v0.15.0 ±✚  kubectl --kubeconfig ./pki/local.config top pods -A
Error from server (InternalError): invalid character 'k' looking for beginning of value
```
When using the vcluster proxy indicator, use the kubectl request, default is protobuf format,
But the data will be parsed later using json.Unmarshal,
This is where things go wrong
```
after change:
> http content-type json 

- pkg/controllers/resources/ingresses/syncer.go
- pkg/controllers/resources/ingresses/syncer_test.go
/kind bugfix
Fixes how `translateIngressAnnotations` handles namespaces.
- Motivation: The [nginx.ingress.kubernetes.io/auth-tls-secret](https://kubernetes.github.io/ingress-nginx/user-guide/nginx-configuration/annotations/#client-certificate-authentication) annotation requires the format `namespace/secret` to work
- Previous behaviour: Annotations with value `namespace/secret` were translated to `physicalSecret`
- Current behaviour: Annotations with value `namespace/secret` are translated to `physicalNamespace/physicalSecret`
Fixed how certain ingress annotations that points to a …
> Fixed how certain ingress annotations that points to a secret are synced when a namespace is also defined

- pkg/util/translate/translate.go
/kind bugfix
Conversation in #vcluster chat: https://loft-sh.slack.com/archives/C01N273CF4P/p1684448482227579
Fixed a panic in generic crd handling
To repro:
- install backendconfig crd: https://github.com/mstergianis/kubernetes-models-ts/blob/411c2f1e8af0b2a54bba4b6336b1e2f186cf4cf7/packages/gke/crd/backendconfigs.yaml#L4
- create vcluster with these values
```yaml
sync:
generic:
generic:
clusterRole:
extraRules:
- apiGroups: ["apiextensions.k8s.io"]
resources: ["customresourcedefinitions"]
verbs: ["get", "list", "watch"]
config: …
```
> fix: panic in CRD handling

- cmd/vclusterctl/cmd/connect.go
- cmd/vclusterctl/cmd/connect_test.go
/kind bugfix
resolves #1029
resolves ENG-1378
Fix panic during vcluster connect if kube-config-context-name is same as .Values.syncer.kubeConfigContextName
(The default value is "my-vcluster")
> fix(cli): panic for some values of --kube-config-context-name

- cmd/vclusterctl/cmd/list.go
/kind bugfix
The `list` command doesn't correctly return if the virtual cluster is connected when applying the global context filtering (option `--context`) in the `table` output format.
The `json` output format was also missing the `connected` and `age` fields available in the `table` format.
The solution for the connected logic is to run the routine to detect the current context and use that as a reference when looping over the existing virtual clusters. This is required because `cmd.Context` could contain the filtering context instead of the connected one.
For the `json` output, the …
> Fix: vclusterctl - Wrong connect logic for the list command

- go.mod
- go.sum
- vendor/github.com/loft-sh/utils/pkg/helm/values/eks.go
- vendor/github.com/loft-sh/utils/pkg/helm/values/k0s.go
- vendor/github.com/loft-sh/utils/pkg/helm/values/k3s.go
- vendor/modules.txt
resolves #
Introduced support for Kubernetes 1.27. Updated supported Kubernetes patch versions of the previous releases.
> chore: update supported and default k8s versions

- pkg/controllers/resources/pods/syncer.go
- pkg/controllers/resources/pods/syncer_test.go
- test/e2e_isolation_mode/isolated.go
/kind bugfix
resolves #1004 ENG-1290
Fixed an issue where vcluster would sync up extra container statuses in case of host injected sidecars
> fix extra conainer statuses syncing in case of host sidecar injection

- hack/build-cli.sh
/kind bugfix
resolves https://loft-sh.slack.com/archives/C01N273CF4P/p1686308243191459
Fixed an issue where vcluster v0.15.1 CLI would fail in environments with older glibc version.
v0.15.1 uses dynamically linked libc:
```
$  ldd $(which vcluster)
linux-vdso.so.1 (0x00007ffed80a9000)
libc.so.6 => /lib64/libc.so.6 (0x00007f7443e25000)
/lib64/ld-linux-x86-64.so.2 (0x00007f7444017000)
```
Building with this change produces static binary, just as it was in v0.15.0:
``` …
```
> fix: disable CGO when building CLI via build-cli.sh

- cmd/vclusterctl/cmd/disconnect.go
- cmd/vclusterctl/cmd/find/find.go
- cmd/vclusterctl/cmd/find/find_test.go
figure out which one to use based on the context name. Can occur if vcluster connects to user-provided context
/kind bugfix
resolves #1073 
Fixed an issue where `vcluster disconnect` wasn't able to determine the original context and failed if a custom context was provided 
> fix(vclusterctl): allow user to select different context if we can't

- pkg/controllers/resources/pods/translate/hosts.go
/kind bugfix
resolves #1085
Fixed an issue where vcluster was setting resource requests not equal to limits for the `vcluster-rewrite-hosts` init container, preventing proper usage of the static CPU policy in Kubernetes.
Full writeup of the issue can be found in https://github.com/loft-sh/vcluster/issues/1085
> set vcluster-rewrite-hosts resource requests equal to limits

- pkg/util/blockingcacheclient/client.go
Raise error in case blockingcacheclient is created without a cache. This should prevent unexpected behavior or a less descriptive error at a later execution stage.
N/A
> fix: add error for blockingcacheclient when cache is not passed

- charts/eks/templates/init-configmap.yaml
- charts/k0s/templates/init-configmap.yaml
- charts/k3s/templates/init-configmap.yaml
- charts/k8s/templates/init-configmap.yaml
/kind bugfix
resolves #1057
Fixed an issue when using a bundled helm chart in the init object, currently the helm template logic is using the `.chart` field when that field is not really available when `.bundle` is provided.
> fix: the usage of the Bundled helm chart

- pkg/controllers/resources/secrets/syncer.go
/kind bugfix
resolves #
Fixed an issue where vcluster did not correctly sync all secrets when both all secrets and ingress sync were enabled.
The all-secret synchronization flag was ignored when the ingresses sync was enabled.
> Fix secret syncer when both ingresses and all secret syncing are enabled

- charts/k0s/templates/coredns.yaml
- charts/k3s/templates/coredns.yaml
- charts/k8s/templates/coredns.yaml
/kind bugfix
Fixed an issue where vcluster coredns helm templates failed to use the defaultImageRegistry
> Added defaultImageRegistry to coredns templates

- cmd/vcluster/cmd/start.go
- pkg/metricsapiservice/register.go
/kind bugfix
Should resolve the following error:
> start.go:381] Error registering metrics apiservice: the cache is not started, can not read objects
Fixed an issue where vcluster would not initialize metrics proxy due to a race condition.
> fix: race condition, cache and metrics proxy

- docs/pages/architecture/synced-resources.mdx
Fix labelSelector documentation for virtual to host sync (see types)
Fix labelSelector documentation for virtual to host sync
> docs: fix labelSelector syntax for virtual to host sync

- charts/eks/templates/coredns.yaml
- charts/k0s/templates/coredns.yaml
- charts/k3s/templates/coredns.yaml
- charts/k8s/templates/coredns.yaml
- pkg/coredns/coredns.go
/kind bugfix
resolves ENG-1857 #1141 #1151 
Fixed an issue where vcluster coreDNS would fail to come up for the latest coreDNS release `1.11.0` due to lacking capabilities.
> add support for coredns 1.11.0

- generic-sync-examples/istio/host-only-gateways.yaml
/kind bugfix
When trying to apply the configuration from [istio generic-sync-examples](https://github.com/loft-sh/vcluster/blob/main/generic-sync-examples/istio/host-only-gateways.yaml) it failed because of an indentation issue in the sync config for the `reversePatches` field. This PR aims to fix this issue.
Fixed an issue in the istio generic-sync-examples config
> Fix reversePatches indentation in host-only-gateways.yaml

- charts/eks/templates/ingress.yaml
- charts/eks/values.yaml
- charts/k0s/templates/ingress.yaml
- charts/k0s/values.yaml
- charts/k3s/templates/ingress.yaml
- charts/k3s/values.yaml
- charts/k8s/templates/ingress.yaml
- charts/k8s/values.yaml
/kind feature
Adds optional TLS configuration for Ingress in `values.yaml` and the respective change in `templates/ingress.yaml` of all 4 distro charts. 
Added TLS support when exposing VCluster's with Ingress reources.
- Although including standard comments in the `values.yaml` file, this may need to be documented in the products documentation (`docs/`).
- I only tested with the default k3s distro chart. Here is a quick command to checkout the template:
```bash
helm template my-vcluster ./charts/k3s \
--set ingress.enabled=true \ …
```
> Add TLS support to Ingress

- cmd/vclusterctl/cmd/create.go
- pkg/util/servicecidr/servicecidr.go
/kind bugfix
Fixed an issue where vcluster create command would print a warning each time of not being able to find IPv6 serviceCIDR even if it works fine with IPv4 serviceCIDR.
Changed the message log level from info to debug, so it will not show-up under normal usage but is still available when run in debug mode.
Closes ENG-1920
> Change servicecidr warning from info to debug

- pkg/controllers/resources/persistentvolumeclaims/translate.go
/kind bugfix
resolves https://github.com/loft-sh/vcluster/issues/1126
Ability to sync `PersistentVolumeClaims` with empty `storageClassName` to host cluster when `StorageClass` sync is enabled
All the details in the issue above.
> Unable to sync `PersistentVolumeClaims` to host cluster when `StorageClass` sync is enabled

- charts/eks/templates/coredns.yaml
- charts/k0s/templates/coredns.yaml
- charts/k3s/templates/coredns.yaml
- charts/k8s/templates/coredns.yaml
Signed-off-by: San Nguyen <vinhsannguyen91@gmail.com>
/kind bugfix
resolves #
Fixed an issue where coredns deployment breaks the Security policy for dropping ALL caps and only add NET_BIND_SERVICE 
This is a regression. We added NET_BIND_SERVICE when updating coredns image but removed the drop: ALL in securityContext.capabilities.
> fix: coredns deploy psp cap

- pkg/controllers/resources/events/syncer.go
/kind bugfix
Fixed an issue where vcluster would fail event reconciliation on cache miss of objects belonging to non default namespace of the cache.
Closes ENG-2024
> Skip Event Reconciliation on cache miss due to object of non-default namespace

- charts/eks/templates/coredns.yaml
original issue was at #251
original PR was at #353 
Remove tolerations for CoreDNS pods on EKS chart
The original PR addressed the issue by removing this from the regular chart, which can be seen here: https://github.com/loft-sh/vcluster/blob/de1552f073c4b9600f6c13b89fcbee29fc9a8bf8/charts/k8s/templates/coredns.yaml
This PR brings the EKS chart to parity with that chart.
> Remove tolerations on EKS chart

- charts/eks/templates/init-configmap.yaml
- charts/eks/values.yaml
- charts/k0s/templates/init-configmap.yaml
- charts/k0s/values.yaml
- charts/k3s/templates/init-configmap.yaml
- charts/k3s/values.yaml
- charts/k8s/templates/init-configmap.yaml
- charts/k8s/values.yaml
- docs/pages/operator/init-manifests.mdx
/kind bugfix
resolves #1211 
This fixes an issue where the `bundle` attribute was starting a new list entry and cutting off any provided `chart` information which is needed for extracting the tar file into a specific filename.
Also updated the documentation example and values.yaml files to provide more information on the `init` helm chart entries.
Fixed an issue where vcluster could not apply more than one bundled helm chart.
The `init` code …
> fix: bundle should not start a new list entry

- cmd/vclusterctl/cmd/app/create/pro.go
- cmd/vclusterctl/cmd/create.go
- go.mod
- go.sum
- pkg/pro/version.go
- pkg/strvals/strvals.go
- pkg/strvals/strvals_test.go
- pkg/upgrade/upgrade.go
- vendor/github.com/loft-sh/loftctl/v3/pkg/client/helper/helper.go
- vendor/github.com/loft-sh/utils/pkg/downloader/commands/helm_v3.go
- vendor/github.com/loft-sh/utils/pkg/helm/types.go
- vendor/github.com/loft-sh/utils/pkg/helm/values/default.go
- vendor/github.com/loft-sh/utils/pkg/helm/values/eks.go
- vendor/github.com/loft-sh/utils/pkg/helm/values/k0s.go
- vendor/github.com/loft-sh/utils/pkg/helm/values/k3s.go
- vendor/github.com/loft-sh/utils/pkg/helm/values/k8s.go
- vendor/modules.txt
> feat: add vcluster create without templates

- charts/eks/templates/coredns.yaml
- charts/k0s/templates/coredns.yaml
- charts/k0s/templates/secret.yaml
- charts/k3s/templates/coredns.yaml
- charts/k3s/values.yaml
- charts/k8s/templates/coredns.yaml
> fix: remove ports & bind-address 127.0.0.1

- charts/eks/templates/coredns.yaml
- charts/eks/values.yaml
- charts/k0s/templates/coredns.yaml
- charts/k0s/values.yaml
- charts/k3s/templates/coredns.yaml
- charts/k3s/values.yaml
- charts/k8s/templates/coredns.yaml
- charts/k8s/values.yaml
Add Values.coredns.nodeSelector for coredns Deployment
/kind bugfix
kind enhancement
/kind feature
/kind test
resolves #
Adds Values.coredns.nodeSelector with coredns deployment. This allows deploying a vcluster with coredns enabled to a GKE arm64 based node pool (as well as ensuring it gets deployed to an arm64 node in other multi-arch clusters).
Added `Values.coredns.nodeSelector` support for coredns
> Add coredns `nodeSelector` Values

- cmd/vclusterctl/cmd/app/create/pro.go
- cmd/vclusterctl/cmd/pause.go
- cmd/vclusterctl/cmd/resume.go
> fix: vcluster sleep & resume

- charts/eks/values.yaml
- charts/k0s/values.yaml
- charts/k3s/values.yaml
- charts/k8s/values.yaml
- go.mod
- go.sum
- vendor/github.com/loft-sh/utils/pkg/helm/values/eks.go
- vendor/github.com/loft-sh/utils/pkg/helm/values/k0s.go
- vendor/github.com/loft-sh/utils/pkg/helm/values/k3s.go
- vendor/github.com/loft-sh/utils/pkg/helm/values/k8s.go
- vendor/modules.txt
Adds support for Kubernetes 1.28 for all distros of vcluster.
Closes ENG-1932
> Add v1.28 support for all distros

- charts/k0s/templates/statefulset.yaml
/kind bugfix
Because of a small mistake in the Helm chart for k0s, the Pro image was not used when deploying vCluster.Pro distro.
Fixed an issue vCluster.Pro distro would use the wrong syncer image with the k0s.
> fix: k0s Pro chart is not using Pro image

- .github/workflows/e2e.yaml
- pkg/controllers/resources/nodes/fake_syncer.go
- pkg/controllers/resources/nodes/fake_syncer_test.go
- pkg/controllers/resources/nodes/syncer_test.go
- pkg/controllers/resources/nodes/translate.go
- test/e2e_node/node.go
/kind bugfix
/kind test
resolves #1001 ENG-1289
Fixed an issue where vcluster node were syncing as `fake-$NAME`. Use `$NAME.nodes.vcluster.com` instead
> fix node labels syncing

- charts/eks/templates/rbac/role.yaml
- charts/k0s/templates/rbac/role.yaml
- charts/k3s/templates/rbac/role.yaml
- charts/k8s/templates/rbac/role.yaml
/kind bugfix
resolves #1286
Migrate version check for Kubernetes from `.Capabilities.KubeVersion.Minor` to `semverCompare`
Refer to issue
> fix: ephermeral containers not working on EKS clusters

- cmd/vclusterctl/cmd/delete.go
/kind bugfix
resolves #1215 
Fixed an issue where vcluster deletes the cluster but gives option to delete-configmap
> Added option to delete config map for vcluster delete

- charts/eks/templates/_helpers.tpl
- charts/k0s/templates/_helpers.tpl
- charts/k3s/templates/_helpers.tpl
- charts/k8s/templates/_helpers.tpl
resolves issue related to coredns plugin giving preference to kubernetes first followed by coredns plugin
> change vcluster plugin order

- pkg/constants/indices.go
- pkg/controllers/resources/nodes/syncer.go
- pkg/controllers/resources/nodes/translate.go
when using the vcluster scheduler we take into account consumed resources in the pod, but don't immediately trigger the node syncer to do this. This sometimes leads to scheduling resources onto nodes where they don't fit.
/kind bugfix
/kind feature
/kind test
resolves ENG-2340
Fixed an issue where vcluster scheduler was late to see resource consumption
> fix: watch and enqueue node events when scheduler enabled

- charts/eks/templates/_helpers.tpl
- charts/eks/templates/rbac/clusterrole.yaml
- charts/k0s/templates/_helpers.tpl
- charts/k0s/templates/rbac/clusterrole.yaml
- charts/k3s/templates/_helpers.tpl
- charts/k3s/templates/rbac/clusterrole.yaml
- charts/k8s/templates/_helpers.tpl
- charts/k8s/templates/rbac/clusterrole.yaml
/kind bugfix
resolves ENG-2307
Fixed an issue where vcluster.Pro was missing clusterrole permission to get pods for other vclusters as targets
> create clusterrole and pod permissions when coredns plugin enabled

- pkg/setup/initialize.go
/kind bugfix
resolves #1365 
resolves eng-2433 
regression happened in #1336 
Fixed an issue where vcluster's etcd would not come up when in HA mode
bugfix: resolves etcd cert issue
> fixed etcd ha not coming up

- docs/pages/networking/networking.mdx
Updated the figure caption and alt text from vcluster to vCluster in networking.mdx
docs: update figure caption and alt text vCluster capitalization for networking.mdx
> Updated spelling of the figure label and alt text to vCluster

- charts/k0s/templates/service-monitor.yaml
- charts/k8s/templates/service-monitor.yaml
/kind bugfix
resolves #
Fixed an issue where vcluster's service monitor could not work because the server name was not set properly in k8s and k0s
> fix: added server name for service monitor

- charts/k0s/templates/statefulset.yaml
- charts/k0s/values.yaml
- pkg/k0s/k0s.go
- pkg/k3s/k3s.go
- pkg/setup/initialize.go
- pkg/util/loghelper/klog.go
resolves eng-2478
k0s is now run from inside the syncer container
> k0s is now run from the syncer container

- pkg/k0s/k0s.go
- pkg/telemetry/collect.go
/kind bugfix
Fixes #1408 
Fixes #1400
> fix: potential nil pointer in telemetry & delete k0s folder

- docs/pages/deploying-vclusters/supported-distros.mdx
> basic comp matrix for vcluster distro versions

- generic-sync-examples/traefik/README.md
- generic-sync-examples/traefik/config.yaml
Adding initial Generic Sync Example for Traefik IngressRoute, IngressRouteTCP, and IngressRouteUDP objects.
resolves #1430
Added initial Generic Sync Example for Traefik IngressRoute, IngressRouteTCP, and IngressRouteUDP objects.
> Adding initial Generic Sync Example for Traefik

- docs/pages/o11y/logging/central_hpm.mdx
Clarifies that a vCluster.Pro license is required for the central hostpath mapper.
> docs: Clarified CHPM license requirements

- docs/pages/using-vclusters/access.mdx
keeps the user in our docs when configuring ingress so they won't have to leave and look at the nginx documentation. troubleshooting this took me longer than it should have and I had to end up referring to an old blog post that I wrote a year ago to remember how I got it to work.
(docs) added the exact config change needed to enable-ssl-passthrough
> added how to eneable-ssl-passthrough so users can avoid leaving the docs

- .github/workflows/e2e.yaml
- .gitignore
Fixes ENG-2637
Prebuilding ginkgo e2e binaries and downloading during e2e runs.
This reduces the duration needed to run GitHub Actions.
> ci(e2e): Prebuilding ginkgo e2e binaries

- docs/pages/config-reference.mdx
- pkg/setup/options/flags.go
Add hint about wildcard support for sync-labels field
Closes ENG-2678
> Add hint about wildcard support for sync-labels field in docs

- cmd/vclusterctl/cmd/delete.go
- cmd/vclusterctl/cmd/find/find.go
/kind feature
resolves #771 
Added --ignore-not-found flag to prevent errors when the virtual cluster or the namespace was not found
This was partially based on #989 which got closed to due to inactivity
> feat(cli): add ignore-not-found flag

- charts/k0s/templates/_migrate.tpl
- charts/k0s/templates/syncer.yaml
- charts/k0s/values.yaml
- charts/k3s/templates/_migrate.tpl
- charts/k3s/templates/rbac/role.yaml
- charts/k3s/templates/syncer.yaml
- charts/k3s/values.yaml
/kind feature
part of eng-2715 
deprecates `replicas` in favour of `syncer.replicas` to converge different distros configs
> now handles both deprecated `replicas` and `syncer.replicas`

- charts/k8s/templates/syncer.yaml
/kind bugfix
Fixed an issue where vcluster would not evict pods correctly when scheduler was enabled
> Fix failing  Conformance test - evicts pods with minTolerationSeconds

- pkg/controllers/resources/nodes/fake_syncer.go
- pkg/controllers/resources/nodes/fake_syncer_test.go
/kind bugfix
I'm running vCluster in a cluster consisting of ARM64 nodes. I encountered an arch label mismatch when migrating applications from the host cluster to vCluster. However, the issue was resolved by updating the fake node architecture to match that of the host node.
Resolved an issue where running applications in vCluster on ARM64 nodes were encountering architecture label mismatches.
* just build-snapshot -> ok
* go test ./pkg/controllers/resources/nodes/ …
> Fix: Update fake node arch the same as host node

- charts/k0s/templates/syncer.yaml
- charts/k0s/values.yaml
- go.mod
- go.sum
- vendor/github.com/loft-sh/vcluster-values/values/k0s.go
- vendor/modules.txt
/kind bugfix
resolves 
Fixed an issue where k0s wouldn't start because we were disabling an option that was removed in the k0s 1.29 
> renamed kubelet-config to worker-config as it is removed in k0s 1.29

- pkg/telemetry/helpers.go
When using vcluster pro, the vcluster telemetry will send the user email with events like create/error instead of a username like `admin`
resolves ENG-2665
> feat(pro): use email as platform id when available

- pkg/upgrade/upgrade.go
/kind bugfix
resolves ENG-2833
Fixed an issue where vcluster upgrade download the wrong release asset
> fix: ensure vcluster upgrade downloads correct binary

- .github/workflows/e2e.yaml
See https://docs.github.com/en/actions/using-workflows/events-that-trigger-workflows#pull_request
`By default, a workflow only runs when a pull_request event's activity type is opened, synchronize, or reopened`
No need to rerun when edited.
/kind bugfix
> fix: don't rerun e2e when PR text/title edited

- pkg/certs/ensure.go
/kind bugfix
resolves eng-2901 
Fixed an issue where vcluster would not be able to go from 0.18 to 0.19
> now makes sure that the secret references localhost instead of old service name

- go.mod
- go.sum
- vendor/github.com/loft-sh/analytics-client/client/client.go
- vendor/modules.txt
/kind bugfix
Resolves ENG-2817
Upgrade anayltics-client so that analytics are sent over https
> chore: update analytics-client

- Dockerfile
> refactor: remove embed charts from Dockerfile

- docs/pages/deploying-vclusters/high-availability.mdx
- docs/pages/fragments/install/cli.mdx
- docs/pages/help&tutorials/bootstrapping.mdx
- docs/pages/help&tutorials/helm-provisioning.mdx
I updated the docs to use the official Loft tap when installing vCluster via brew.
> docs(brew): Updated docs to reference loft homebrew tap

- charts/eks/values.yaml
- charts/k8s/values.yaml
/kind bugfix
resolves #1582
Fixed eks and k8s values by moving allowPrivilegeEscalation under securityContext
> fix: move allowPrivilegeEscalation into correct section

- pkg/specialservices/proxy_service_syncer.go
- pkg/specialservices/service_syncer.go
/kind bugfix
resolves ENG-3024
fixes #1587
Fixed an issue where vcluster has incorrectly 
> fix: IPFamilyPolicy not synced for default vcluster service

- config/config.go
A few nits:
- "vCluster" has a copyright, so we need to use virtual cluster when not talking about the product/app. 
- a few changes to standardize terms and products
Note: Pascal showed me what to do to generate the partials needed for the docs, so I can do that after this PR merges.
> Schema comments: change vCluster to virtual cluster when not referring to the product itself

- .github/workflows/sync-config.yaml
> build: add sync config workflow

- docs/pages/architecture/control_plane/k8s_distros.mdx
- docs/pages/deploying-vclusters/high-availability.mdx
- docs/pages/deploying-vclusters/supported-distros.mdx
- docs/pages/fragments/high-availability-k3s.mdx
- docs/pages/fragments/high-availability-k8s.mdx
/kind bugfix 
resolves #
resolves #1599 
Fixes broken links to chart values for v0.19
Requires another release of the 0.19 docs
> fix #1599: Point docs to v0.19 branch

- .github/workflows/sync-config.yaml
> build: update sync-config.yaml

- pkg/util/clihelper/clihelper.go
/kind bugfix
I had problems to find out the root cause for connection issues. The related error message was dropped. Let's print out this to make debuggung easier
resolves #1584
print error on cli connection problems
> print error on cli connection problems

- cmd/vcluster/cmd/start.go
- pkg/plugin/v2/config.go
- pkg/plugin/v2/plugin.go
- pkg/setup/config.go
> refactor: improvements for plugins

- chart/values.schema.json
- config/config.go
- pkg/config/validation.go
- pkg/config/validation_test.go
> refactor: add concrete webhook types

- pkg/controllers/resources/pods/translate/translator.go
- pkg/controllers/resources/pods/translate/translator_test.go
- chore: go mod tidy && go mod vendor
- fix: affinity label selector overriden by namespace selector
/kind bugfix
part-of ENG-2759
fixes #1484
Fixed an issue where vcluster mistranslated affinity terms.
> fix: affinity label selector overriden by namespace selector

- docs/pages/architecture/control_plane/k8s_distros.mdx
- docs/pages/deploying-vclusters/high-availability.mdx
- docs/pages/deploying-vclusters/supported-distros.mdx
- docs/pages/fragments/high-availability-k3s.mdx
- docs/pages/fragments/high-availability-k8s.mdx
- docs/pages/getting-started/deployment.mdx
/kind bugfix
resolves #
The docs under vcluster.com are served from the main branch, where the chart has already been consolidated (folder has been renamed from `charts` to `chart`. Though, the docs in main still refer to vcluster v19 where there are separate charts per distro, so the links are currently broken.  
> Change chart links

- docs/pages/architecture/control_plane/k8s_distros.mdx
- docs/pages/getting-started/deployment.mdx
/kind bugfix
resolves #
Two remaining spots where we reference main where the charts folder does not exist anymore.
> Reference helm charts for v0.19

- chart/tests/coredns-configmap_test.yaml
- chart/values.schema.json
- chart/values.yaml
- config/config.go
- config/diff.go
- config/values.yaml
- pkg/config/config.go
- pkg/config/legacyconfig/config.go
- pkg/config/legacyconfig/migrate.go
- pkg/config/legacyconfig/migrate_test.go
- pkg/config/legacyconfig/options.go
- pkg/plugin/v1/plugin.go
- pkg/setup/controller_context.go
/kind feature
Resolves ENG-3085
**What does it do?**
* This PR adds a migration function that is able to convert the old helm `values.yaml` into the new `vcluster.yaml` format.
* Changes the default value of `fallbackHostDns` back to `false`, which was a mistake introduced when changing the `values.yaml` format
> feat: add migration function

- CONTRIBUTING.md
- README.md
- chart/README.md
- docs/pages/cli/vcluster_pro_start.md
- docs/pages/getting-started/setup.mdx
resolves #1654
We use `{{ continue }}` and `{{ break }}` inside helm templates, which rely on go 1.18, which is used by helm in version >= v3.10.0.
> Explicitly mention that Helm must be >= v3.10.0

- pkg/server/server.go
/kind bugfix
resolves #
Fixed an issue where vcluster plugins wouldn't get the context info because it's not there yet 
> moved withinterceptor so it can catch the info from the context

- pkg/controllers/syncer/syncer_test.go
resolves #
fix function name in comment 
> chore: fix function name in comment

- cmd/vclusterctl/cmd/create.go
/kind bugfix
Resolves ENG-3230
Fixed an issue where vcluster upgrade leads to a 404 when upgrading a vcluster that was created before the unified Helm Chart. 
> Do not encode distro name into Chart URL

- cmd/vclusterctl/cmd/migrate/migrate.go
- cmd/vclusterctl/cmd/migrate/values.go
- cmd/vclusterctl/cmd/root.go
Resolves ENG-3274
Add "migrate values" command to vcluster in order to convert the old values format to the new format introduced with 0.20
Current caveat is that the passed in values actually match`--distro`. Otherwise the `MigrateLegacyConfig` currently will simply create new default values for the given distro in the new format. So I made `--distro` mandatory with a warning that it should exactly match the provided values.
> feat: add "migrate values" command to migrate to new values format

- cmd/vclusterctl/cmd/create.go
- config/config.go
- config/config_test.go
Resolves ENG-3334
Fixed an issue where vcluster would pass the values file to `helm install` without validating them beforehand.
> chore: validate passed in values files before passing it to helm

- pkg/config/validation.go
> added check for k0s to make sure we don't use incompatible options

- Dockerfile
- chart/values.schema.json
- cmd/vcluster/cmd/start.go
- cmd/vclusterctl/cmd/create.go
- cmd/vclusterctl/cmd/pro/start.go
- config/config.go
- config/config_test.go
- devspace.yaml
- pkg/config/config.go
- test/proValues.yaml
resolves ENG-3327
Log a message if user attempt to use a pro feature before supported
Currently logs a message any time *any* pro feature is enabled, but an additional way to disable the check may be desired.
Also adds missing pro attributes for schema partials generation.
> feat: show a message if user attempts to use pro / platform features

- pkg/constants/coredns.go
/kind bugfix
resolves #
fix: add coredns version map with kubernetes version equales to 1.26 item
According to https://github.com/coredns/deployment/blob/master/kubernetes/CoreDNS-k8s_version.md
when instsall kubernetes version 1.26,  it is supposed to install coredns/coredns:1.9.3 respectively
so I add this bug fix
> fix: add coredns version map with key equales to 1.26 item

- cmd/vclusterctl/cmd/create.go
Resolves ENG-3303
Really hacky. Interims solution until we have the functionality to check for distro/backingStore switches coming with https://github.com/loft-sh/vcluster/pull/1668. This PR only does an early-exist when we try to upgrade a currently running virtual cluster without providing a values file (which might switch distros under the hood). We also print an info message to upgrade values if we connect to a currently running virtual cluster < v0.20.
**What else do we need to …
> chore: perform early exit when no values file is given for vcluster < v0.20

- cmd/vclusterctl/cmd/create.go
- cmd/vclusterctl/cmd/delete.go
helm version check now fails if helm prints any warnings like:
```
WARNING: Kubernetes configuration file is group-readable. This is insecure. Location: ...
```
/kind bugfix
/kind feature
/kind test
resolves #
> fix: ignore stderr in helm version check

- pkg/util/loghelper/klog.go
/kind bugfix
This fixes an issue where we weren't parsing some log lines correctly, resulting in missing information when printing the log line through klog
> fix: omitted log messages

- pkg/controllers/k8sdefaultendpoint/k8sdefaultendpoint.go
- pkg/setup/controller_context.go
/kind bugfix
resolves ENG-3440
> fix: flaking k8sdefaultendpoint syncing

- cmd/vclusterctl/cmd/platform/start.go
* Platform (Loft) versions below v3.5 will require `--chart-name vcluster-control-plane` to work
* Platform (Loft) versions v3.5 and above work now without an extra flag
> chore: change vcluster start chart name to vcluster-platform

- pkg/cli/create_helm.go
Resolves ENG-3573
Provide checks that abort "vcluster create" when using pre-v0.20 formatting in values.yaml.
> chore(vclusterctl): check for pre 0.20 values

- config/config.go
- pkg/cli/create_helm.go
- pkg/cli/create_platform.go
> refactor: throw error if using pro feature but not logged in

- chart/templates/_coredns.tpl
- chart/templates/service.yaml
- chart/tests/service_test.yaml
- pkg/controllers/resources/nodes/fake_syncer.go
- pkg/controllers/resources/nodes/nodeservice/node_service.go
- pkg/controllers/resources/nodes/syncer.go
- pkg/controllers/resources/nodes/translate.go
> fix: proxy kubelets loadbalancer

- config/legacyconfig/migrate.go
- config/legacyconfig/migrate_test.go
/kind bugfix
Part of ENG-3708
Fixed an issue where vcluster did not convert a legacy config with a deprecated HPM flag.
> chore(config): also enable hpm when using deprecated flag

- pkg/k8s/k8s.go
/kind bugfix
resolves #
Fixed an issue where vcluster would time out if kine wasn't found, now fails early and displays a message 
> fail early if kine can't start

- cmd/vclusterctl/cmd/platform/access_key.go
- cmd/vclusterctl/cmd/platform/connect/cluster.go
- cmd/vclusterctl/cmd/platform/connect/connect.go
- cmd/vclusterctl/cmd/platform/reset.go
- cmd/vclusterctl/cmd/platform/start.go
resolves #
Fixed an issue where vcluster would display deprecated pro cmd instead of platform.
> chore(vclusterctl): rename pro to platform

- chart/templates/coredns-configmap.yaml
- chart/tests/coredns-configmap_test.yaml
- chart/values.schema.json
- chart/values.yaml
- config/config.go
- config/values.yaml
Ref https://github.com/loft-sh/vcluster/issues/1718
Ref ENG-3563
> allow users to define a default priorityClass

- chart/templates/etcd-statefulset.yaml
- chart/templates/statefulset.yaml
- chart/tests/etcd-statefulset_test.yaml
- chart/tests/statefulset_test.yaml
- chart/values.schema.json
- chart/values.yaml
- config/config.go
- config/values.yaml
/kind test
resolves ENG-3500
resolves #1708 
Added the ability to disable service links for the etcd STS as they can cause problems in a cluster with thousands of services.
vcluster.yaml docs should be updated as well.
👇 Demo showing creating one vCluster for each of the new `enableServiceLinks` config options.  Then getting the STS yaml, and parsing out the value that should, and does, read false in both cases:
> Adds enableServiceLinks to the STS config for controlPlane and controlPlane.backingStore

- pkg/cli/activate_platform.go
the current functionality depends on a mangement api that is gone
> fix: use agent pod label to get cluster name

- cmd/vclusterctl/cmd/platform/add/cluster.go
- cmd/vclusterctl/cmd/platform/backup/backup.go
- cmd/vclusterctl/cmd/platform/backup/management.go
- cmd/vclusterctl/cmd/platform/connect/connect.go
- cmd/vclusterctl/cmd/platform/connect/management.go
- cmd/vclusterctl/cmd/platform/get/cluster.go
- cmd/vclusterctl/cmd/platform/get/cluster_access_key.go
- cmd/vclusterctl/cmd/platform/get/get.go
- cmd/vclusterctl/cmd/platform/get/secret.go
- cmd/vclusterctl/cmd/platform/get/user.go
- cmd/vclusterctl/cmd/platform/list/clusters.go
- cmd/vclusterctl/cmd/platform/list/list.go
- cmd/vclusterctl/cmd/platform/list/secrets.go
- cmd/vclusterctl/cmd/platform/list/teams.go
- cmd/vclusterctl/cmd/platform/platform.go
- cmd/vclusterctl/cmd/platform/pro.go
- cmd/vclusterctl/cmd/platform/set/secret.go
- cmd/vclusterctl/cmd/platform/set/set.go
- cmd/vclusterctl/cmd/root.go
- go.mod
Earlier, `vcluster platform add cluster` had an uninitialized config.
I think generating from GlobalFlags reduces the need to drill down another var
/kind bugfix
> fix/refactor: remove need to pass cli.Config to subcommands

- .github/workflows/e2e.yaml
/kind bugfix
Made `kubectl wait` retry once after sleep in case the resource is missing when it tries
> fix: e2e flakes when waiting for vcluster to come up

- pkg/cli/create_platform.go
/kind bugfix
resolves #
Fixed an issue where vcluster would reject creation with empty Owner field.
vcluster create is rejected when user and team are set to empty string in owner field. So we have to fill this field conditionally.
> fix(vclusterctl): only fill out owner when given

- cmd/vclusterctl/cmd/platform/access_key.go
- cmd/vclusterctl/cmd/platform/connect/space.go
- cmd/vclusterctl/cmd/platform/create/space.go
- pkg/cli/connect_platform.go
- pkg/cli/create_helm.go
- pkg/cli/create_platform.go
- pkg/cli/find/find.go
- pkg/cli/import_helm.go
- pkg/cli/list_helm.go
- pkg/cli/list_platform.go
- pkg/platform/client.go
- pkg/platform/helper.go
- pkg/platform/secret.go
resolves #
Clean up platform client interface.
No new functionality. Only cleanup/moving.
Most of the platform related functions are outside the client already. Let's thin out the client functionality and by that make the interface smaller. Furthermore, remove methods of the interface that are not called anywhere.
> chore(platform): thin out platform client

- cmd/vcluster/cmd/start.go
> [backport] fix: Use workload client when setting global owner

- go.mod
- pkg/cli/start/login.go
- pkg/cli/start/success.go
/kind bugfix
resolves ENG-3846
Fixed an issue where vcluster platform start would use old client to write config.
> fix(vclusterctl): use platform client instead of loftctl client

- chart/values.yaml
- config/values.yaml
- docs/pages/config-reference.mdx
- pkg/config/config.go
resolves #
ENG-3835
Update alpine image used to creating the override hosts file to 3.20
> Update the alpine image used to creating the override hosts file

- cmd/vclusterctl/cmd/connect.go
- pkg/cli/connect_helm.go
- pkg/cli/connect_platform.go
This reverts commit f8e61acb54c7c4319392eda201b2bf186783f210.
/kind bugfix
resolves #
Fixed an issue where "vcluster connect --manager=platform" contained functionality of "vcluster platform share vcluster"
> Revert "chore(vclusterctl): add loftctl flags to vcluster connect (#1823)

- cmd/vclusterctl/cmd/platform/get/cluster.go
- cmd/vclusterctl/cmd/platform/list/vclusters.go
/kind bugfix
resolves eng-3863
The logger wasn't instantiated on the cluster and vcluster commands leading to nil reference panics
> Instantiating logger on a couple commands.

- cmd/vclusterctl/cmd/connect.go
/kind bugfix
resolves ENG-3850
Fixed an issue where vcluster would fail to create a kubeconfig with ServiceAccount for platform vClusters
> fix(vclusterctl): limit updating vCluster server address to local for OSS vClusters only

- cmd/vclusterctl/cmd/platform/share/space.go
- cmd/vclusterctl/cmd/platform/share/vcluster.go
/kind bugfix
resolves #
Fixed an issue where vcluster would print out wrong info messages when sharing vclusters/spaces
> fix(vclusterctl): info messages for connect when sharing

- cmd/vclusterctl/cmd/connect.go
- cmd/vclusterctl/cmd/create.go
- cmd/vclusterctl/cmd/delete.go
- cmd/vclusterctl/cmd/pause.go
- cmd/vclusterctl/cmd/platform/connect/connect.go
- cmd/vclusterctl/cmd/platform/connect/vcluster.go
- cmd/vclusterctl/cmd/platform/create/create.go
- cmd/vclusterctl/cmd/platform/create/space.go
- cmd/vclusterctl/cmd/platform/create/vcluster.go
- cmd/vclusterctl/cmd/platform/delete/delete.go
- cmd/vclusterctl/cmd/platform/delete/space.go
- cmd/vclusterctl/cmd/platform/delete/vcluster.go
- cmd/vclusterctl/cmd/platform/sleep/vcluster.go
- cmd/vclusterctl/cmd/platform/wakeup/vcluster.go
- cmd/vclusterctl/cmd/resume.go
- cmd/vclusterctl/cmd/root.go
- pkg/cli/completion/completion.go
- pkg/cli/flags/connect/connect.go
- pkg/cli/flags/create/create.go
- pkg/cli/flags/delete/delete.go
resolves ENG-3874
Provide `vcluster platform connect/create/delete vcluster` commands
I moved the common/platform/helm related flags to respective packages, in order to not duplicate them in two places. The `--manager` flag was removed from the `platform` sub commands, as it does not make sense there.
> Add vcluster related commands under platform

- .github/workflows/release.yaml
- .goreleaser.yaml
/kind bugfix
resolves #
goreleaser v2 was [announced on June 4th](https://goreleaser.com/blog/goreleaser-v2/). When using v2 (e.g. locally) we cannot issue e.g. `just build-snapshot` anymore:
```bash
⨯ build failed after 0s                    error=only configurations files on  version: 2  are supported, yours is  version: 1 , please update your configuration
```
> chore: upgrade to goreleaser v2

- cmd/vclusterctl/cmd/platform/create/space.go
/kind bugfix
resolves ENG-3900
Fixed an issue where `vcluster platform create space` would not work when only the --cluster flag was provided.
Passing true (allowClusterOnly) to the helper func returned an empty string for project, which won't qualify as the default project in subsequent functions calls (e.g. ListTemplates).
> fix(vclusterctl): select default project when only cluster flag is given

- .github/workflows/e2e.yaml
- go.mod
- pkg/certs/ensure.go
- pkg/setup/config.go
- pkg/setup/initialize.go
- test/commonValues.yaml
/kind bugfix
resolves #
When using isolated control plane, the owner for the cert should be the service in the control plane namespace.
> fix: set control plane svc as cert secret owner

- cmd/vcluster/cmd/start.go
- go.mod
- pkg/certs/ensure.go
- pkg/setup/initialize.go
- **fix: set control plane svc as cert secret owner**
- **fix: bump go version**
/kind bugfix
backport of #1859 
resolves #
When using isolated control plane, the owner for the cert should be the service in the control plane namespace.
>  [backport]fix: set control plane svc as cert secret owner

- cmd/vclusterctl/cmd/list.go
- go.mod
**What does this pull request do? Which issues does it resolve?**  
resolves #ENG-3822
Omits OSS clusters where the name/namespace matches pro clusters with the `loft.sh/imported-by-agent` annotation.
> Omit OSS vCluster that were imported into pro vClusters.

- pkg/cli/config/config.go
/kind bugfix
Fixed an issue where vcluster cli would error if no driver is selected
> fix: parse driver error

- pkg/cli/add_vcluster_helm.go
- pkg/cli/create_helm.go
- pkg/cli/flags/create/create.go
resolves #
Renamed activate flag to add in vcluster create in order to be more consistent
Also moved the field to helm flags, otherwise it would appear also in `vcluster platform create vcluster` where a `--add=false` does not make sense?!
> chore: rename activate flag to add and move to helm flags

- .github/workflows/release.yaml
/kind bugfix
Unblocks release process
> Temporarily allow runme failure

- charts/eks/templates/syncer.yaml
- charts/eks/values.yaml
- charts/k0s/templates/syncer.yaml
- charts/k0s/values.yaml
- charts/k3s/templates/syncer.yaml
- charts/k3s/values.yaml
- charts/k8s/templates/syncer.yaml
- charts/k8s/values.yaml
- go.mod
- go.sum
- pkg/config/helmvalues/values_test.go
- vendor/github.com/loft-sh/vcluster-values/helmvalues/common.go
- vendor/modules.txt
There are cases where an emptyDir volume of sufficient size can not be provided, so users should be allowed to override the /binaries volume with an alternative.
Additionally, current ephemeral storage requests are no sufficient for some distros:
```
k0s
203.2M	/binaries/k0s
k8s
108.3M	/binaries/kube-apiserver
100.9M	/binaries/kube-controller-manager
69.4M	/binaries/vcluster
eks
105.8M	/binaries/kube-apiserver
98.4M	/binaries/kube-controller-manager
69.4M	/binaries/vcluster
```  …
> Improve binaries volume config

- pkg/cli/create_platform.go
/kind bugfix
part of ENG-3891
While authoring docs, I found it was not possible to edit a previously created virtual cluster using the CLI command like:
```shell
vcluster create my-vcluster --values tests/vcluster.yaml --project default --use
```
This was due to several issues that are addressed by this PR:
- the platform driver incorrectly detected that the virtual cluster was deployed by helm
- the platform driver was applying option values if *any* option had changed, resulting in several getting overwritten
> fix: allow updating the virtual cluster using the platform driver

- .github/workflows/release.yaml
/kind bugfix
resolves issue with access to vcluster-docs repo from CI
> Use correct access token when trigerring runme

- pkg/platform/version.go
Update the default platform version to `v4.0.0-alpha.18`
> Update platform version to v4.0.0-alpha.18

- pkg/cli/create_helm.go
- pkg/cli/delete_platform.go
- pkg/cli/pause_platform.go
- pkg/cli/resume_platform.go
> No agent found with Sleep Mode configured: vCluster logs, CLI output

- chart/templates/statefulset.yaml
/kind bugfix
resolves # n/a
Fixed an issue where when `controlPlane.statefulSet.pods.annotations` is set helm gives the error `Error: UPGRADE FAILED: YAML parse error on vcluster/templates/statefulset.yaml: error converting YAML to JSON: yaml: line 32: did not find expected key` due to the `vClusterConfigHash` key being indented one space instead of two.
vcluster chart version: `0.20.0-beta.11`
> [bug] Fix indentation of statefulset pod annotations

- .devcontainer/Dockerfile
/kind bugfix
Using devpod with this repo was not working because go version was not updated. Go version is already updated for the vcluster code but its not updated in dev container dockerfile.
Fix golang version for devpod
NA
> Fix goversion for devpod

- pkg/controllers/resources/namespaces/syncer.go
- pkg/controllers/resources/namespaces/translate.go
Improves syncing of namespaces by using the new patchers
> migrated to new patchers and syncers

- pkg/controllers/register.go
- pkg/patcher/patcher.go
- pkg/util/translate/translate.go
* Prints what exactly has been patched in debug mode
* Do not run initializers in parallel as this is unexpected and can lead to race conditions in integration / plugins
> refactor: improve patcher & crd sync

- Justfile
- chart/templates/_rbac.tpl
- chart/templates/platform-rbac.yaml
- chart/tests/platform-secret-role_test.yaml
- config/config.go
> feat(helm): Automatically create role & bindings for namespace containing platform secret

- pkg/controllers/resources/endpoints/syncer.go
- pkg/controllers/resources/endpoints/translate.go
> added patcher logic for endpoints

- chart/templates/_coredns.tpl
/kind bugfix
resolves #ENG-4151
Fixed an issue where vcluster would fallback to hostDNS when a resolveDNS rule was specified
> bugfix(chart): enable fallthrough for cluster.local queries only when .Values.networking.advanced.fallbackHostCluster is true

- pkg/controllers/resources/events/syncer.go
- pkg/controllers/resources/events/translate.go
> Events patcher

- chart/templates/_coredns.tpl
/kind bugfix
Fixed an issue where vcluster would fallback to hostDNS when a resolveDNS rule was specified
> BACKPORT v0.20 bugfix(chart): enable fallthrough for cluster.local queries only when .Values.networking.advanced.fallbackHostCluster is true

- pkg/controllers/resources/serviceaccounts/syncer.go
- pkg/controllers/resources/serviceaccounts/translate.go
> added patcher logic to service accounts

- pkg/controllers/resources/poddisruptionbudgets/syncer.go
- pkg/controllers/resources/poddisruptionbudgets/syncer_test.go
- pkg/controllers/resources/poddisruptionbudgets/translate.go
> added patcher logic for pdb

- pkg/controllers/resources/csistoragecapacities/translator.go
- pkg/controllers/resources/events/syncer.go
- pkg/controllers/resources/nodes/syncer.go
- pkg/controllers/resources/nodes/translate.go
- pkg/controllers/resources/persistentvolumes/syncer.go
- pkg/controllers/resources/persistentvolumes/translate.go
- pkg/controllers/resources/volumesnapshots/volumesnapshotcontents/syncer.go
- pkg/controllers/syncer/translator/generic_translator.go
- pkg/controllers/syncer/translator/mirror_translator.go
- pkg/controllers/syncer/types/syncer.go
- pkg/controllers/syncer/types/translator.go
- pkg/mappings/generic/mapper.go
- pkg/mappings/generic/mirror.go
- pkg/mappings/resources/csistoragecapacities.go
- pkg/mappings/resources/events.go
- pkg/mappings/types.go
- pkg/util/translate/multi_namespace.go
- pkg/util/translate/single_namespace.go
- pkg/util/translate/types.go
PR Changes:
* Combine IsManaged & IsManagedCluster
* Get rid of LegacyTargetNamespace()
* Move IsManaged into mapper so that we can centrally control what objects should be managed by vCluster
> refactor: combine IsManaged & IsManagedCluster

- cmd/vclusterctl/cmd/list.go
- cmd/vclusterctl/cmd/platform/list/list.go
- cmd/vclusterctl/cmd/platform/list/projects.go
- cmd/vclusterctl/cmd/platform/list/vclusters.go
- cmd/vclusterctl/cmd/platform/platform.go
- pkg/cli/list_platform.go
> Add projects

- pkg/controllers/resources/volumesnapshots/volumesnapshotclasses/syncer.go
- pkg/controllers/resources/volumesnapshots/volumesnapshotclasses/translate.go
> added logic for patcher snapshot class

- pkg/controllers/resources/services/syncer.go
- pkg/controllers/resources/services/syncer_test.go
- pkg/controllers/resources/services/translate.go
- pkg/controllers/syncer/context/context.go
> added patch logic for services

- charts/k3s/templates/_coredns.tpl
/kind bugfix
resolves #ENG-4127
Fixed an issue where vcluster would fallback to hostDNS when coredns plugin is enabled
> BACKPORT v0.19 bugfix(chart): enable fallthrough for cluster.local queries only when fallbackHostDns is true

- pkg/controllers/resources/events/translate.go
> fix: event name & namespace

- pkg/controllers/resources/nodes/syncer_test.go
> Test cleanup

- docs/pages/deploying-vclusters/high-availability.mdx
- docs/pages/deploying-vclusters/supported-distros.mdx
- docs/pages/help&tutorials/helm-provisioning.mdx
- docs/pages/what-are-virtual-clusters.mdx
resolves #DOC-211
Only docs updates
> Add EKS deprecation banners and add EKS back as a supported distro

- cmd/vclusterctl/cmd/convert/config.go
resolves ENG-4188
Made the usage of `vcluster convert config` more clear
Backport to v20?!
> chore: make usage of vcluster convert config more clear

- pkg/platform/helper.go
/kind bugfix
resolves eng-4210
> now checks for the users

- .github/workflows/backport.yaml
- config/config.go
- pkg/cli/create_helm.go
- pkg/config/config.go
High availability setups do not work with embedded sqlite. We are now validating that that high availability and embedded sqlite are not both enabled.
/kind bugfix
resolves #1910
High availability setups do not work with embedded sqlite. We are now validating that that high availability and embedded sqlite are not both enabled.
Embedded etcd _is_ supported and can be used if embedded is desired.
> Prevent unsupported HA setup

- cmd/vclusterctl/cmd/platform/add/cluster.go
- cmd/vclusterctl/cmd/resume.go
- config/config.go
- pkg/cli/add_vcluster_helm.go
- pkg/cli/create_helm.go
- pkg/cli/find/find.go
- pkg/cli/pause_helm.go
- pkg/cli/pause_platform.go
- pkg/cli/resume_helm.go
- pkg/cli/resume_platform.go
- pkg/kube/meta.go
- pkg/lifecycle/lifecycle.go
- pkg/platform/helper.go
- pkg/platform/sleepmode/sleepmode.go
resolves #ENG-4157
resolves #ENG-4158
resolves #ENG-4159
Sleep and wake features used across drivers (platform/helm) are more intelligent when the `--driver` flag is omitted, still providing useful information for failures if the wrong driver is explicitly used from the command.
> Sleep wake cli

- cmd/vclusterctl/cmd/platform/add/cluster.go
- cmd/vclusterctl/cmd/resume.go
- config/config.go
- pkg/cli/add_vcluster_helm.go
- pkg/cli/create_helm.go
- pkg/cli/find/find.go
- pkg/cli/pause_helm.go
- pkg/cli/pause_platform.go
- pkg/cli/resume_helm.go
- pkg/cli/resume_platform.go
- pkg/kube/meta.go
- pkg/lifecycle/lifecycle.go
- pkg/platform/helper.go
- pkg/platform/sleepmode/sleepmode.go
This will backport the following commits from `main` to `v0.20`:
- [Merge pull request #1983 from zerbitx:sleep-wake-cli](https://github.com/loft-sh/vcluster/pull/1983)
ENG-4157
ENG-4158
ENG-4159
> [v0.20] Backport sleep wake cli

- pkg/k8s/k8s.go
/kind bugfix
resolves ENG-4263
> [BACKPORT V0.20]: fix: k8s startup issue

- cmd/vclusterctl/cmd/connect.go
- test/e2e_cli/connect/connect.go
/kind bugfix
resolves ENG-4270
Fix replaces the `Log` if `--print` flag is set. This new Log instance will log all non-error logs to `io.Discard`. Also, added two e2e tests:
1. First executes `vcluster connect -n vcluster --print vcluster` and writes it to temporary file, and then uses `kubectl --kubeconfig=<temporary-file> get pods -A` to check if outputed kubeconfig can be used to connect to virtual cluster.
2. Second tests checks if the `vcluster connect -n vcluster --print NOT_EXISTING_CLUSTER_NAME` still outputs error.
**Please provide a short message that should be published in the …
> bugfix: do not output logs in vcluster connect if --print is set

- chart/templates/statefulset.yaml
- chart/tests/statefulset_test.yaml
- chart/values.schema.json
- chart/values.yaml
- config/config.go
- config/values.yaml
> refactor: make data volume configurable

- .github/workflows/e2e.yaml
- hack/vcluster-install-scripts/test-helm-install.sh
- hack/vcluster-install-scripts/test-kubectl-install.sh
/kind test
- But this is for testing the GHA with some minor changes.
- Original PR: https://github.com/loft-sh/vcluster/pull/2011
- If this works, depending on how we want to proceed, I might close of these PRs
- fixed comments from here - https://github.com/loft-sh/vcluster/pull/2011#pullrequestreview-2213293663
**Details:**
- Implemented a module for running the install and delete commands for virtual cluster through helm and kubectl in the `e2e.yaml` GHA workflow file. 
- Added bash scripts for the actions - helm and kubectl
**To-do in next PR** 
- once this PR is merged - install and delete using argoCD and terraform
Adds a test - install and delete vcluster …
> PR for Adding tests for installing and deleting virtual cluster from kubectl

- pkg/controllers/resources/services/syncer.go
- pkg/controllers/resources/services/translate.go
- pkg/controllers/servicesync/servicesync.go
- pkg/server/filters/service.go
- pkg/util/translate/labels.go
- pkg/util/translate/translate_test.go
- pkg/util/translate/types.go
Improves the way vCluster rewrites labels as we only rewrite the release label, because `app` label is quite commonly used. This still avoids conflicts with the vCluster resources themselves. We also avoid adding the namespace label and marker label if the host labels exist and didn't include that yet.
> refactor: only rewrite release label

- chart/templates/_rbac.tpl
- chart/templates/clusterrole.yaml
- chart/values.schema.json
- chart/values.yaml
- config/config.go
- config/values.yaml
- pkg/controllers/resources/register.go
- pkg/controllers/resources/runtimeclasses/syncer.go
- pkg/controllers/resources/runtimeclasses/syncer_test.go
/kind feature
part of  eng-3155
Added syncer for runtime classes
> added runtime classes sync

- chart/templates/_init-containers.tpl
- chart/tests/statefulset_test.yaml
- chart/values.schema.json
- chart/values.yaml
- config/config.go
- config/config_test.go
- config/values.yaml
- hack/test.sh
… intergration
resolves ENG-2725
`controlPlane.distro.k8s.version` is a shortcut to set image tags for.
- controlPlane.distro.k8s.apiServer.image.tag
- controlPlane.distro.k8s.controllerManager.image.tag
- controlPlane.distro.k8s.schedule.image.tag
New behavior: `controlPlane.distro.k8s.version` will override image tags only if they're not specified by user (so they're different than current default tag, `v1.30.3`. This only affects `k8s` distro.
Add …
> feature: add controlPlane.distro.k8s.version chart value for CAPI

- pkg/cli/create_helm.go
resolves eng-4308
Fixed an issue where vcluster would let users create multiple virtual clusters in the same ns
> [enhancement] now refuses to create multiple virtual clusters in same ns

- chart/templates/_rbac.tpl
- chart/templates/clusterrole.yaml
- chart/values.schema.json
- chart/values.yaml
- config/config.go
- config/values.yaml
- pkg/controllers/resources/priorityclasses/syncer.go
- pkg/controllers/resources/priorityclasses/syncer_test.go
- pkg/controllers/resources/priorityclasses/translate.go
- pkg/controllers/resources/register.go
- pkg/mappings/resources/register.go
/kind feature
resolves eng-4179
> [feat] added priorityclass syncing from host

- pkg/k8s/k8s.go
Prior, an empty datasource was accepted when external database was enabled. An empty datasource causes kine to use sqlite which is embedded- not external. Now, passing an empty datasource while external database is enabled will result in an error.
/kind bugfix
Fixes ENG-4330
> Reject empty datasource if external database is enabled

- config/default_extra_values.go
> [BACKPORT v0.20] fix: set controlPlane.distro.k8s.version by default

- chart/templates/limitrange.yaml
- chart/templates/resourcequota.yaml
- chart/tests/limitrange_test.yaml
- chart/tests/resourcequota_test.yaml
- chart/values.schema.json
- chart/values.yaml
- config/config.go
- config/legacyconfig/migrate.go
- config/values.yaml
> refactor: enable limitRange / resourceQuota in duo

- cmd/vclusterctl/cmd/create.go
- pkg/cli/create_helm.go
> [enhancement] added hidden flag to override number of virtual cluster restriction

- cmd/vclusterctl/cmd/describe.go
- cmd/vclusterctl/cmd/root.go
- pkg/cli/describe_helm.go
- pkg/cli/describe_platform.go
/kind feature
resolves eng-4313
Output example : 
```yaml
Backing Store: embedded-database
Distro: k8s
Image tags:
apiServer: registry.k8s.io/kube-apiserver:v1.29.6
controllerManger: registry.k8s.io/kube-controller-manager:v1.29.6
scheduler: registry.k8s.io/kube-scheduler:v1.29.6
syncer: ghcr.io/loft-sh/vcluster-pro:0.20.0-beta.15
Version: 0.20.0-beta.15
```
> [feature] add describe command

- pkg/controllers/resources/nodes/syncer_test.go
- pkg/controllers/resources/nodes/translate.go
/kind feature
resolves ENG-4177
vcluster will now ignore updates to Rancher managed annotations inside the virtual cluster when node syncing is enabled.
> feat: Ignore updates to Rancher managed annotations

- pkg/controllers/resources/ingresses/syncer.go
- pkg/pro/import.go
- pkg/syncer/importer.go
- pkg/syncer/syncer.go
- pkg/syncer/types/syncer.go
> refactor: importer adjustments

- hack/load-testing/tests/throughput/throughput.go
- pkg/controllers/resources/nodes/syncer_test.go
- pkg/controllers/resources/nodes/translate.go
- pkg/controllers/syncer/syncer.go
- pkg/setup/controller_context.go
/kind feature
resolves ENG-4356
vcluster will now ignore updates to Rancher managed annotations inside the virtual cluster when node syncing is enabled.
> [v0.20] feat: Ignore updates to Rancher managed annotations (#2075)

- .github/workflows/e2e.yaml
- cmd/vclusterctl/cmd/create.go
- hack/load-testing/tests/throughput/throughput.go
- pkg/controllers/resources/nodes/syncer_test.go
- pkg/controllers/resources/nodes/translate.go
- pkg/controllers/syncer/syncer.go
- pkg/setup/controller_context.go
/kind feature
resolves ENG-4358
vcluster will now ignore updates to Rancher managed annotations inside the virtual cluster when node syncing is enabled.
> [v0.19] feat: Ignore updates to Rancher managed annotations (#2075)

- chart/templates/statefulset.yaml
- chart/tests/statefulset_test.yaml
- chart/values.schema.json
- config/config.go
- values.yaml
/kind feature
Add dnsPolicy, dnsConfig config options for the controlPlane ti be able to set these fields in the pod spec of the vcluster pod.
Added dnsPolicy and dnsConfig config options for the controlPlane field in vcluster.yaml
> feat: add dnsPolicy, dnsConfig config options for the controlPlane

- pkg/server/cert/syncer.go
- pkg/server/server.go
/kind bugfix
resolves #2086
Fixed an issue where vcluster would not add the ingress host automatically to the extra SANs of its self-signed certificate
> fix: add ingress host automatically to certificate

- pkg/server/cert/cert.go
- pkg/server/cert/syncer.go
/kind bugfix
resolves #2086
Fixed an issue where vcluster would not add the ingress host automatically to the extra SANs of its self-signed certificate
> [BACKPORT V0.20] fix: add ingress host automatically to certificate

- chart/values.schema.json
- config/config.go
> refactor: allow empty path

- .github/workflows/sync-config-schema.yaml
- .github/workflows/sync-config.yaml
part of ENG-4185
add a separate workflow to sync `values.schema.json` only on the latest release
tested workflow triggers in the playground repo https://github.com/hidalgopl/gh-actions-playground
> sync values.schema.json only on the latest release

- cmd/vcluster/cmd/start.go
- pkg/pro/platform.go
vCluster is now able to request a data source from vCluster Platform. vCluster is only able to use the data source if it attempts to connect to the vCluster Platform prior to deploying its own control plane. vCluster Platform is now connected before control plane is deployed but the platform controllers and tailscale server are started after because they require the control plane to be running.
/kind feature
Part of ENG-4279
Part of enabling using the same database server credential for multiple vcluster datastores by creating new database and user, then returning credentials for the …
> Connect to vCluster Platform earlier

- config/default_extra_values.go
- pkg/cli/create_helm.go
- pkg/cli/create_platform.go
/kind bugfix
Fixes ENG-4480
Prior, an extra value, distro.k8s.version, could be set for a vcluster with a version that does not support the distro.k8s.version field. This would lead to a panic in vcluster. Now, the value is only set if the vcluster chart version is known to support it. Otherwise, it is left empty, leading to the omission of the field and no panic.
Fixed an issue where older vcluster versions may panic due to being passed an unsupported value.
> Check if vcluster chart version supports k8s version

- config/legacyconfig/migrate.go
- config/legacyconfig/migrate_test.go
if we cannot unmarshal it into legacy config in vcluster config convert
/kind bugfix
resolves ENG-4307
Fixed an issue where vcluster config convert fails even if valid config is provided
I initially thought that we can return no error here, but I guess it may be confusing, as it will output an empty diff `{}`.
> fallback to checking if config is in correct format 

- chart/values.schema.json
- hack/schema/main.go
This dynamically adds `config/config.go#PlatformConfig` in the schema generation script to `values.schema.json`
part of ENG-4185
add PlatformConfig under `external.platform` in generated `values.schema.json`
> dynamically add config.Config.PlatformConfig to the generated schema

- pkg/cli/delete_helm.go
/kind bugfix
fixes ENG-4405
Fixed an issue where vcluster looked for the matching virtualcluster instance using a non existent label. Now, it will check the virtualclusterinstance.status.serviceUID field to find the matching vcluster to delete.
> fix: external delete should check status field for service uid

- cmd/vclusterctl/cmd/ui.go
- pkg/cli/start/login.go
> fix: improve error logging around attempting to open browser

- cmd/vclusterctl/cmd/platform/reset.go
- cmd/vclusterctl/cmd/platform/start.go
> Fix: reset password namespace & start chart name

- cmd/vclusterctl/cmd/platform/reset.go
> [BACKPORT v0.20] fix: wrong namespace for vcluster

- pkg/upgrade/upgrade.go
part of ENG-4354
a continuation of #2131  with logging to give the user some guidance
screenshot:
> fix(cli): improve UX around vcluster upgrade command

- cmd/vclusterctl/cmd/platform/add/vcluster.go
- pkg/cli/add_vcluster_helm.go
/kind feature
resolves ENG-4109
Adds `--all` flag to `vcluster platform add vcluster`. This can be used to import all vClusters from host cluster to the platform.
> add --all flag to vcluster platform add vcluster

- chart/templates/coredns-configmap.yaml
- chart/tests/coredns-configmap_test.yaml
- chart/values.schema.json
- chart/values.yaml
- config/config.go
- config/values.yaml
I want to add tolerance and taint for coredns pod, I have verified it in the development environment but we are using v0.18.1 version of chart.
> feat: coredns pod supports affinity and stain tolerance

- pkg/syncer/syncer.go
/kind bugfix
resolves eng-3892
> fixed an issue for generic sync that deleted referenced objects

- cmd/vclusterctl/cmd/platform/add/cluster.go
/kind bugfix
resolves #ENG-4585
Fixed an issue where if the helm command to add a cluster failed, the error wouldn't be reported quickly because waiting for the pod began before the helm error was checked.
> Captures helm error before trying to call WaitForReadyLoftPod

- cmd/vclusterctl/cmd/platform/start.go
- pkg/cli/start/start.go
/kind bugfix
Fixes ENG-4635.
Part of ENG-4400
Prior, the reset flag indicated that resources should be uninstalled. However, if an existing deployment was not detected, all other resources were removed regardless of the reset flag's value. Now, reset must be set to true to uninstall any existing vCluster Platform resources. This is more in line with how a reinstall performed with helm behaves and is more predictable for the user. The usage description has been updated to reflect the change.
Fixed an …
> Only uninstall if reset flag is true

- cmd/vclusterctl/cmd/platform/add/cluster.go
- cmd/vclusterctl/cmd/platform/backup/management.go
- cmd/vclusterctl/cmd/platform/get/secret.go
- cmd/vclusterctl/cmd/platform/reset.go
- cmd/vclusterctl/cmd/platform/set/secret.go
- cmd/vclusterctl/cmd/platform/start.go
- pkg/cli/start/success.go
- pkg/platform/clihelper/clihelper.go
Adds function to look up loft deployment's namespace
resolves #ENG-4560
Tries to look up the platform install's deployment to get the namespace rather than assuming "loft" if the user doesn't specify and the flag default isn't vcluster-platform.
> Changes fallback ns to vcluster-platform

- cmd/vclusterctl/cmd/platform/add/cluster.go
- cmd/vclusterctl/cmd/platform/add/vcluster.go
/kind bugfix
resolves ENG-4638
backport of #2153 
Fixed an issue where vcluster platform add cluster was setting additionalCA for loft-agent when it was set in cluster access. Instead, now user can pass additionalCA for given loft agent as a command flag
> [Backport-to-v0.20 set additional ca in platform add cluster

- cmd/vclusterctl/cmd/platform/add/cluster.go
after changes made in https://github.com/loft-sh/loft-enterprise/pull/3187 , `--ca-data` flag in `vcluster platform add cluster` is redundant; it's actually better if user can configure additionalCA once for platform, and then connected clusters will automatically use it, instead of forcing user to pass it to the `vcluster platform add cluster` command every single time.
It reverts #2159 but keeps `--ca-data` flag for `platform add vcluster` commands visible
> [v0.20] revert adding --ca-data flag to vcluster platform add cluster

- cmd/vclusterctl/cmd/platform/add/cluster.go
after changes made in https://github.com/loft-sh/loft-enterprise/pull/3187 , --ca-data flag in vcluster platform add cluster is redundant; it's actually better if user can configure additionalCA once for platform, and then connected clusters will automatically use it, instead of forcing user to pass it to the vcluster platform add cluster command every single time.
It reverts https://github.com/loft-sh/vcluster/pull/2153 but keeps --ca-data flag for platform add vcluster commands visible
> revert adding --ca-data flag to vcluster platform add cluster

- cmd/vclusterctl/cmd/platform/add/cluster.go
/kind bugfix
part of #eng-4516
Fixed an issue where vcluster platform add referenced `loft` instead of the new platform references. 
> fix: update platform add command to reference the platform instead of loft

- pkg/controllers/resources/pods/translate/hostpath.go
/kind bugfix
resolves ENG-4427
Fixed an issue where bind mounts for hostpath mapping would not forward changes correctly when mountpath contained a trailing forward-slash
> fix: handle trailing slash in mount paths for hostpath mapper

- pkg/controllers/resources/pods/translate/hostpath.go
/kind bugfix
resolves ENG-4672
Fixed an issue where bind mounts for hostpath mapping would not forward changes correctly when mountpath contained a trailing forward-slash
> [v0.19] fix: handle trailing slash in mount paths for hostpath mapper

- pkg/controllers/resources/pods/translate/translator_test.go
/kind test
Tests added for #2169 as requested by @hidalgopl :slightly_smiling_face:
> test: Add tests for volumes and volumeMounts translation with hostpathmapper enabled

- pkg/controllers/resources/persistentvolumes/syncer_test.go
- pkg/controllers/resources/volumesnapshots/volumesnapshotcontents/syncer_test.go
- pkg/mappings/generic/mapper.go
- pkg/mappings/resources/persistentvolumes.go
- pkg/mappings/resources/volumesnapshotcontents.go
/kind bugfix
resolves ENG-4679
> fix: pv syncing

- .goreleaser.yaml
- Justfile
- hack/assets/main.go
- hack/assets/separate/main.go
- pkg/constants/coredns.go
/kind bugfix
/kind feature
/kind test
resolves #
> build: Generate image list files for distro and version

- pkg/controllers/resources/pods/translate/translator_test.go
**What issue type does this pull request address?** (keep at least one, remove the others)
/kind test
Tests added for https://github.com/loft-sh/vcluster/pull/2169 as requested by @hidalgopl 🙂
> [v0.20] test: Add tests for volumes and volumeMounts translation with hostpathmapper enabled

- pkg/controllers/resources/pods/translate/translator_test.go
/kind test
Tests added for https://github.com/loft-sh/vcluster/pull/2169 as requested by @hidalgopl 🙂
> [v0.19] test: Add tests for volumes and volumeMounts translation with hostpathmapper enabled

- pkg/authentication/bearertoken/bearertoken.go
- pkg/authentication/delegatingauthenticator/delegatingauthenticator.go
- pkg/server/server.go
> refactor: allow extra authenticators for vcluster pro

- chart/templates/_helper.tpl
- chart/templates/headless-service.yaml
- chart/templates/service.yaml
- chart/templates/statefulset.yaml
- chart/tests/headless-service_test.yaml
- chart/tests/service_test.yaml
- devspace.yaml
- pkg/certs/ensure.go
- pkg/cli/connect_helm.go
- pkg/cli/find/find.go
- pkg/config/parse.go
- pkg/controllers/resources/nodes/nodeservice/node_service.go
- pkg/setup/config.go
- pkg/util/translate/types.go
- test/framework/framework.go
/kind bugfix
resolves ENG-4551
Make it possible to create virtual clusters with digits only name
In order to be able to create virtual clusters with a digits-only name we have to change the way how we create services based on the name. Previously we just used the name verbatim which in case of pure digits violates the DNS-1035 naming convention for service names used by Kubernetes. 
It turned out this change cannot only be made to our helm templates as there have …
> Make it possible to create virtual clusters with numbers only name

- chart/tests/role_test.yaml
- chart/tests/statefulset_test.yaml
- chart/values.schema.json
- config/config.go
> fix: expression schema error & rename

- cmd/vcluster/cmd/root.go
- hack/load-testing/tests/throughput/throughput.go
- pkg/setup/controller_context.go
- pkg/syncer/syncer.go
> refactor: change info to error

- chart/templates/limitrange.yaml
- chart/tests/limitrange_test.yaml
- chart/values.schema.json
- chart/values.yaml
- config/config.go
- config/values.yaml
The LimitRange resource lacks options for `min` and `max`.
Add min and max options to LimitRange
> Adds min and max to LimitRange

- pkg/controllers/resources/configmaps/syncer.go
- pkg/controllers/resources/csistoragecapacities/syncer.go
- pkg/controllers/resources/endpoints/syncer.go
- pkg/controllers/resources/endpoints/translate.go
- pkg/controllers/resources/ingresses/syncer.go
- pkg/controllers/resources/ingresses/translate.go
- pkg/controllers/resources/namespaces/syncer.go
- pkg/controllers/resources/networkpolicies/syncer.go
- pkg/controllers/resources/networkpolicies/translate.go
- pkg/controllers/resources/persistentvolumeclaims/syncer.go
- pkg/controllers/resources/persistentvolumeclaims/translate.go
- pkg/controllers/resources/persistentvolumes/syncer.go
- pkg/controllers/resources/persistentvolumes/syncer_test.go
- pkg/controllers/resources/poddisruptionbudgets/syncer.go
- pkg/controllers/resources/poddisruptionbudgets/translate.go
- pkg/controllers/resources/pods/translate/diff.go
- pkg/controllers/resources/runtimeclasses/syncer.go
- pkg/controllers/resources/secrets/syncer.go
- pkg/controllers/resources/serviceaccounts/syncer.go
- pkg/controllers/resources/services/syncer.go
- pkg/controllers/resources/storageclasses/syncer.go
- pkg/controllers/resources/volumesnapshotcontents/syncer.go
- pkg/controllers/resources/volumesnapshotcontents/syncer_test.go
- pkg/controllers/resources/volumesnapshots/syncer.go
- pkg/syncer/testing/testing.go
- pkg/syncer/wrapper.go
/kind bugfix
/kind feature
/kind test
resolves ENG-4808
> feat: Added bi-directional annotation and label syncing

- pkg/cli/start/success.go
/kind bugfix
resolves ENG-4867
Fixed an issue where `vcluster platform start` command printed the wrong type of vcluster create command
> ENG-4867: Fixes platform create output so it prints internal vcluster create command instead of external

- .github/workflows/e2e.yaml
- Justfile
- cmd/vclusterctl/cmd/create.go
- cmd/vclusterctl/cmd/platform/add/cluster.go
- cmd/vclusterctl/cmd/platform/create/vcluster.go
- pkg/cli/util/args.go
> feat: prompt for missing vcluster name in create command

- config/default_extra_values.go
- docs/pages/deploying-vclusters/compat-matrix.mdx
N/A
Bump Kubernetes 1.27 from 1.27.15 to 1.27.16
Kubernetes 1.27 is EOL, meaning 1.27.16 is the last release and there will not be any other. Thus, I think it makes a lot of sense to upgrade to it.
> build: bump kubernetes 1.27 from 1.27.15 to 1.27.16

- chart/templates/_init-containers.tpl
- chart/tests/statefulset_test.yaml
- chart/values.yaml
- config/default_extra_values.go
- config/values.yaml
- docs/pages/deploying-vclusters/compat-matrix.mdx
/kind bugfix
/kind feature
/kind test
part of ENG-4861
> chore: update k8s versions in version maps and default version

- cmd/vclusterctl/cmd/create.go
- cmd/vclusterctl/cmd/platform/add/cluster.go
- cmd/vclusterctl/cmd/platform/create/vcluster.go
- pkg/cli/util/args.go
/kind bugfix
/kind feature
/kind test
resolves #
> fix: Panic when passing too many args

- pkg/setup/controllers.go
/kind bugfix
resolves #2226 
Fixed an issue where vCluster would omit adding the certificate authority data to the `vc-NAME` secret.
> fix: Add missing ca data when using exportKubeConfig

- config/config.go
- config/config_test.go
> fix: Added fromHost crd sync pro check

- cmd/vclusterctl/cmd/platform/backup/management.go
Prior, we were using a kubeconfig client during setup of the platform commands. The client uses the command "vcluster platform token". This would cause an endless loop like the following:
1. you run the "vcluster platform ..." command
2. vcluster makes request to /deployments endpoint, before running the intended command.
3. the k8s client uses vcluster to authenticate the request
4. return to step 2 The request was being made to detect the platform namespace and set it as the default namespace for the backup management command. Now, there is not a default that is set ahead of running the command but if a value was not passed, the CLI will then search for the platform namespace.
/kind bugfix
**What …
> Remove use of client from CLI setup

- Justfile
- devspace.yaml
- pkg/syncer/handler.go
- pkg/syncer/synccontext/events.go
- pkg/syncer/syncer.go
- test/conformanceValues.yaml
/kind bugfix
resolves ENG-4924
Fixed an issue where the vcluster syncer would mistakenly re-create a resource when reconciling the update event that adds the `deletionTimestamp`
The syncer incorrectly re-creates a resource while it's being deleted. The sequence of events observed:
- A replicationcontroller with a `terminationGracePeriod` == 0 is deleted and its pods are garbage collected
- An update event that sets the deletionTimestamp is queued
- An delete event …
> Prevent recreating virtual cluster resource during delete

- .github/workflows/sync-config-schema.yaml
/kind bugfix
I noticed that sync-config.yaml on main had a few issues:
- determining if version is latest was broken (it pulled the latest version from github API in the workflow that run on the release creation, so "latest" was actually the previous latest)
- it was running two times on one release (because it had on.release.types set to released & published - now it's on released only
- added an option to manually trigger this workflow with a release tag as an input. This will allow to retrospectively update the `values.schema.yaml` in vcluster-config repo.
mirror PR: https://github.com/loft-sh/loft-enterprise/pull/3367
> update sync-config-schema, allow for manual trigger

- pkg/controllers/deploy/start.go
/kind bugfix
/kind feature
/kind test
resolves #
> fix(helm): Do not download helm if not needed

- pkg/controllers/deploy/start.go
Backports: https://github.com/loft-sh/vcluster/pull/2254
Conflict forced a manual backport
> [0.20] fix(helm): Do not download helm if not needed

- chart/values.schema.json
- chart/values.yaml
- config/config.go
- config/values.yaml
/kind feature
Part of ENG-4279
> Add db fields

- pkg/controllers/resources/persistentvolumeclaims/syncer.go
- pkg/controllers/resources/pods/ephemeral_containers.go
- pkg/controllers/resources/pods/syncer.go
- pkg/controllers/resources/services/syncer.go
- pkg/controllers/resources/volumesnapshotcontents/syncer.go
- pkg/controllers/resources/volumesnapshots/syncer.go
Each of these object cache update come after calls to the client that will go through the SyncController's reconciliation that handles updating the cache.  These changes still pass the certified-conformance tests.
> fix: removes object cache updates from syncers.

- pkg/controllers/resources/ingresses/syncer.go
- pkg/controllers/resources/ingresses/syncer_test.go
- pkg/controllers/resources/ingresses/translate.go
- pkg/controllers/resources/services/syncer.go
/kind feature
resolves ENG-4976
vcluster will now ignore updates to Rancher managed annotations when syncing ingress to & from the virtual cluster.
> Exclude rancher managed annotation from ingress sync

- .golangci.yml
- pkg/controllers/resources/ingresses/syncer.go
- pkg/controllers/resources/ingresses/syncer_test.go
- pkg/controllers/resources/nodes/syncer.go
- pkg/controllers/resources/services/syncer.go
- pkg/helm/time.go
- pkg/util/encoding/helper.go
/kind feature
resolves ENG-5034
vcluster will now ignore updates to Rancher managed annotations when syncing ingress to & from the virtual cluster.
> [v0.20] feat: exclude Rancher managed annotations while syncing ingress (#2259)

- cmd/vclusterctl/cmd/platform/add/cluster.go
resolves #
This makes it possible that the agent picks up the current dev image when adding a cluster to the platform during development via `DEVELOPMENT=true vcluster platform add cluster <cluster_name>`
> Populate AGENT_IMAGE env var during development

- pkg/controllers/resources/ingresses/syncer.go
- pkg/controllers/resources/ingresses/syncer_test.go
- pkg/controllers/resources/services/syncer.go
/kind feature
resolves ENG-5035
vcluster will now ignore updates to Rancher managed annotations when syncing ingress to & from the virtual cluster.
> [v0.19] feat: exclude Rancher managed annotations while syncing ingress (#2259)

- cmd/vclusterctl/cmd/platform/destroy.go
- cmd/vclusterctl/cmd/platform/logout.go
- cmd/vclusterctl/cmd/platform/platform.go
- cmd/vclusterctl/cmd/platform/start.go
- pkg/cli/destroy/destroy.go
- pkg/cli/start/docker.go
- pkg/cli/start/start.go
- pkg/platform/clihelper/clihelper.go
/kind feature
resolves ENG-3980
Add a new cli command: vcluster platform destroy
The command will wait for each resource type to finish cleaning up before proceeding to the next, so that resource types that depend on each other will not prevent cleanup. (Remove a cluster object before a virtualclusterinstance running on it, etc)
`vcluster platform destroy` (no args) on v4.0.0:
```
16:28:54 info found platform installation in namespace "vcluster-platform"
16:28:54 …
```
> feat(cli): implement platform destroy command

- pkg/controllers/resources/networkpolicies/syncer.go
- pkg/controllers/resources/networkpolicies/syncer_test.go
- pkg/mappings/registry.go
- pkg/mappings/resources/networkpolicies.go
- pkg/mappings/resources/register.go
/kind bugfix
resolves ENG-5193
Fixed an issue where vcluster restarts when enabling networkpolicy syncing
> fix: prevent vcluster crash when network policy syncing is enabled

- chart/templates/etcd-headless-service.yaml
- chart/values.schema.json
- chart/values.yaml
- config/config.go
- config/legacyconfig/migrate.go
- config/values.yaml
- pkg/etcd/client.go
- pkg/k0s/k0s.go
- pkg/k3s/k3s.go
- pkg/k8s/k8s.go
- pkg/setup/initialize.go
/kind bugfix
resolves ENG-5249
Fixed an issue where vcluster would always set etcd endpoints to the regular etcd service instead of based on config values
When non-embedded etcd is used for the backing store, we have both the regular as well as a headless service pointing to the etcd statefulset, for use by default. However, if one wishes to use just the headless service and disable the regular one, it is not possible, as the regular service name is hardcoded and …
> bugfix: set correct etcdEndpoints for non embedded etcd based on vcluster config

- chart/templates/etcd-headless-service.yaml
- chart/values.schema.json
- chart/values.yaml
- config/config.go
- config/legacyconfig/migrate.go
- config/values.yaml
- pkg/k0s/k0s.go
- pkg/k3s/k3s.go
- pkg/k8s/k8s.go
- pkg/setup/initialize.go
This will backport the following commits from `main` to `v0.20`:
- [Merge pull request #2297 from neogopher/fix-set-etcd-headless-endpoints-correctly](https://github.com/loft-sh/vcluster/pull/2297)
Closes ENG-5286
> [v0.20] Merge pull request #2297 from neogopher/fix-set-etcd-headless-endpoints-correctly

- cmd/vclusterctl/cmd/platform/destroy.go
- pkg/cli/config/config.go
- pkg/cli/destroy/destroy.go
- pkg/cli/start/start.go
- pkg/platform/client.go
- pkg/platform/clihelper/clihelper.go
/kind bugfix
ENG-5254
resolves ENG-5254
resolves ENG-5244
vcluster platform destroy will now prompt the user to type "delete" to confirm destruction, unless the --non-interactive flag is passed
vcluster platform destroy now properly cleans up config.json, and a few clusterroles/bindings it missed before
prompt example:
> fix(cli): clean up clusteroles/bindings, config.json, add prompt

- cmd/vclusterctl/cmd/upgrade.go
- pkg/upgrade/helpers.go
- pkg/upgrade/upgrade.go
- pkg/upgrade/upgrade_test.go
/kind bugfix
resolves ENG-5127
Fixed an issue where vcluster upgrade command would fail for older releases
> bugfix(cli): change process of finding specified binary releases

- chart/templates/coredns-configmap.yaml
- chart/templates/networkpolicy.yaml
- chart/tests/coredns-configmap_test.yaml
- chart/values.yaml
- config/values.yaml
- test/framework/util.go
Changed vcluster coredns app label. The previous app label would trigger cilium to restart the coredns pod.
/kind bugfix
Fixes ENG-5194
Fixed an issue where vcluster coredns pods were repeatedly restarted if cilium was installed in the host cluster.
I am concerned that this would interfere with a cilium install in the vcluster.
> Change vcluster coredns app label

- pkg/controllers/resources/nodes/translate.go
/kind bugfix
resolves ENG-5382
> bugfix: set allocatable resources to 0 when free capacity goes negative

- pkg/controllers/resources/nodes/translate.go
/kind bugfix
resolves ENG-5381
> [v0.22] bugfix: set allocatable resources to 0 when free capacity goes negative

- pkg/controllers/resources/nodes/translate.go
/kind bugfix
resolves ENG-5380
> [v0.21] bugfix: set allocatable resources to 0 when free capacity goes negative

- config/diff.go
- config/legacyconfig/migrate.go
- config/legacyconfig/migrate_test.go
/kind bugfix
resolves ENG-5301
Fixed an issue where vcluster convert config skipped statefulset affinity rules
> vcluster config convert statefulSet.affinity bugfix

- chart/values.schema.json
- config/config.go
Moves native sleepmode config under Experimental
> move sleep mode to experimental

- .github/workflows/sync-config-schema.yaml
- chart/values.schema.json
- chart/values.yaml
- config/config.go
- hack/schema/main.go
- add checking for invalid characters that will break .mdx generation  in docs to hack/schema/main.go;
- fix sync-config-schema.yaml vcluster-config syncing
Enhancement: do not allow invalid characters in config/config.go comments
> Validate comments in config/config.go before generating jsonschema

- cmd/vclusterctl/cmd/platform/destroy.go
- pkg/cli/destroy/destroy.go
resolves ENG-5245
resolves ENG-5264
Adds prompt for this flag, also changes logging to mention that externally deployed vclusters are not cleaned up.
> fix(cli): add --force-remove-finalizers to platform destroy

- pkg/controllers/resources/services/syncer.go
/kind bugfix
Fixed an issue where vcluster would not sync service label selectors correctly on upgrade
> fix: service label sync problems

- pkg/cli/connect_helm.go
/kind bugfix
resolves #
This PR adds a check to prevent the creation of a background proxy container when already connected to the specified vCluster. For example, if the command `vcluster connect vcluster-test` is run while already connected to `vcluster-test`, the unnecessary proxy container will no longer be created.
> fix: avoid unnecessary proxy container creation for already connected vCluster

- chart/templates/_coredns.tpl
- chart/tests/coredns-configmap_test.yaml
- pkg/k8s/k8s.go
/kind bugfix
resolves #2315 
The PR adds the correct service account issuer to the apiserver in case custom clusterdomain is set using ```networking.advanced.clusterDomain```.
It also fixes _coredns.tpl in the chart to correctly use custom clusterdomain in coredns configuration.
Fixed an issue where vcluster was setting wrong service-account-issuer in case of custom clusterDomain.
in case of the custom cluster domain the service account token for the vcluster pods …
> bugfix: use correct service-account-issuer in case of custom clusterDomain 

- pkg/setup/controllers.go
Prior, if the coredns deployment was using the old label, "kube-dns",
it would not be updated during the coredns manifests apply. This was
because label selectors are immutable. Now, if the label is outdated
on the deployment, the deployment is deleted prior to the coredns
manifests apply.
/kind bugfix
Part of ENG-5232
Fixed an issue where vcluster dns would stop working on upgrade.
> Fix coredns

- pkg/platform/clihelper/clihelper.go
- pkg/platform/helper.go
Fixed an issue where vcluster platform was referencing to loft in helper.go files
> fixed code referencing to loft in helper.go file

- pkg/cli/connect_helm.go
- pkg/cli/localkubernetes/configure.go
- pkg/util/kubeconfig/kubeconfig.go
For new enough versions (`4.34`+) of Docker Desktop, users can "[opt in](https://docs.docker.com/engine/network/tutorials/host/#prerequisites)" and this PR is unecessary.
If we want compatibility when they haven't opted in on non-linux systems this PR
* Flips the discovery so the docker container can find the host via `host.docker.internal` instead of the host finding a docker VM IP.
* Runs a different docker command, mapping the ports directly rather than using host networking.
/kind bugfix
resolves #ENG-5521
> Have container reach host instead of host discover vm IP

- pkg/controllers/resources/persistentvolumeclaims/syncer.go
- pkg/controllers/resources/persistentvolumes/translate.go
/kind bugfix
resolves #2384
Fixes ENG-5519
Fixed an issue where vcluster would not correctly sync the storage class name for persistent volumes
> fix: storage class sync error

- pkg/cli/email/validate.go
This change ignores any errors in trying to get the disposable domains list and only returns an error if the domain being used is found in the list.
I tested this by providing a disposable domain to get the error and by using a list in an invalid json format to get the logging, and see it ignore the error.
/kind bugfix
resolves #ENG-5542
> fix: Only error when we verify they're using a disposable domain.

- pkg/controllers/resources/pods/syncer.go
- pkg/controllers/resources/pods/syncer_test.go
- pkg/controllers/resources/pods/translate/translator.go
- test/e2e/syncer/pods/pods.go
/kind bugfix
resolves ENG-5474
vcluster will now show fake Node IPs under pod status.HostIP field when fakeKubeletIPs is enabled
> [v0.19] Set fake Node IP for the virtual pod status.HostIP field when fakeKubeletIPs is enabled

- pkg/controllers/resources/pods/syncer.go
- pkg/controllers/resources/pods/syncer_test.go
- pkg/controllers/resources/pods/translate/translator.go
- test/e2e/syncer/pods/pods.go
/kind bugfix
resolves ENG-5385
vcluster will now show fake Node IPs under pod status.HostIP field when ProxyKubelets.ByIP is enabled
> Set fake Node IP for the virtual pod status.HostIP field when ProxyKubelets.ByIP is enabled

- pkg/server/filters/nodechanges.go
… host
/kind bugfix
resolves ENG-5578
Fixed an issue where vcluster would not allow cordoning a node from within the virtual cluster context
> sync spec.Schedulable field while syncing nodeChanges from virtual to host

- pkg/server/filters/nodechanges.go
/kind bugfix
resolves ENG-5600
Fixed an issue where vcluster would not allow cordoning a node from within the virtual cluster context
> sync spec.Unschedulable field while syncing nodeChanges from virtual to host

- pkg/controllers/resources/services/syncer.go
/kind bugfix
This brings the selector syncing inline with the [CopyBidirectional](https://github.com/loft-sh/vcluster/blob/main/pkg/patcher/sync.go#L17-L21) logic.
resolves #ENG-5654
Fixed an issue where the host service selector should have been synced to the virtual, but it was nullified to match the virtual instead.
Example of what occurred 
- Selector was removed from host service
- The change was synced down to the virtual cluster removing it
- The selector was …
> fix: fix host to virtual service selector syncing

- .github/workflows/sync-config-schema.yaml
so we can sync on betas and RCs. It was causing CI not to run on "pre-release" type of releases.
/kind bugfix
> bugfix: sync config on release published, not only released

- pkg/controllers/resources/nodes/translate.go
/kind bugfix
resolves ENG-5440
Fixed an issue where vcluster would calculate allocatable resources inside the virtual cluster incorrectly when virtual cluster scheduler was enabled
With this PR, we are updating the code to use the same utility function that kubectl uses for the resource calculation.
> bugfix: node allocatable resources correction

- config/default_extra_values.go
- pkg/cli/create_helm.go
- pkg/cli/create_platform.go
- pkg/cli/flags/create/create.go
/kind bugfix
resolves #2294
resolves ENG-5242
Remove the `kubernetes-version` flag in `vcluster create`command, kubernetes version can now be configured from values.yaml.
> fix: remove kubernetes-version flag in vcluster create

- pkg/server/filters/nodechanges.go
/kind bugfix
resolves ENG-5676
Fixed an issue where vcluster would incorrectly throw a "context deadline exceeded" error when syncing node changes to host
> bugfix(syncer): fix misplaced function parameters in wait.PollUntilContextTimeout function in nodeChanges server filter

- pkg/config/parse.go
- pkg/config/parse_test.go
- pkg/config/validation.go
- pkg/config/validation_test.go
- pkg/setup/config.go
- pkg/syncer/from_host_syncer.go
/kind bugfix
/kind test
resolves ENG-5739
Fixed an issue where vcluster was allowing invalid values in from host sync mapping entries
this contains config validation that got lost in the revert + better organization of functions in `pkg/syncer/from_host_syncer.go`, so we can use them in other repo.
> From host sync additional config validation

- chart/values.schema.json
- chart/values.yaml
- config/config.go
- config/values.yaml
- pkg/controllers/resources/pods/syncer_test.go
- pkg/controllers/resources/pods/translate/translator.go
/kind feature
resolves ENG-5095
With this PR we are:
- Adding sync.toHost.pods.priorityClassName config field which will add the specified priorityClassName to all workloads pods being synced to the host
- Fixing a bug that prevented the priorityClassName to be applied correctly when sync.fromHost.priorityClasses.enabled is true.
> feat: add sync.toHost.pods.priorityClassName

- .github/workflows/e2e.yaml
- config/default_extra_values.go
- docs/pages/deploying-vclusters/compat-matrix.mdx
- pkg/controllers/resources/pods/syncer.go
- pkg/controllers/resources/pods/translate/diff.go
- test/e2e/syncer/pods/pods.go
resolves ENG-5390
Update K8s dependencies to 1.32
- vcluster is breaking on k0s 1.32 as seen in the CI failure in [this](https://github.com/loft-sh/vcluster/pull/2495) PR, hence  downgrading the support for k0s to 1.30.
- This also fixes E2E tests for QOSClass field after upgrading kind image to 1.32. Earlier the tests were being run on k8s version 1.30
> Downgrade k0s version supported to 1.30 and update kindest node image in E2E tests to 1.32 

- chart/values.schema.json
- chart/values.yaml
- cmd/vcluster/cmd/start.go
- cmd/vclusterctl/cmd/create.go
- config/config.go
- config/values.yaml
- pkg/cli/create_helm.go
/kind bugfix
resolves ENG-5363
- Deprecate the `reuse-namespace` flag.
- Add a flag `reuse-namespace` in vcluster config with immediate deprecation warning.
**Testing**:
- CLI: here's the deprecation warning coming up if someone uses flag `reuse-namespace`:
- Using helm, multiple vcluster creation is allowed but with a note about `reuse-namespace` config and a deprecation warning like this:
> Deprecate creation of multiple vclusters in same namespace

- .github/workflows/release.yaml
/kind bugfix
Adding outputs to the previous job and passing to the notification action.
resolves OPS-60
> fix(ci): slack notification

- chart/values.schema.json
- chart/values.yaml
- cmd/vcluster/cmd/start.go
- cmd/vclusterctl/cmd/create.go
- config/config.go
- config/values.yaml
- pkg/cli/create_helm.go
/kind bugfix
resolves ENG-5363
Fixed the deprecation warning message for multiple vcluster creation scenario and move the `reuse-namespace` config to controlPlane/advanced section.
> Update deprecation warning message and move reuse-namespace to controlPlane/advanced section

- test/e2e/syncer/fromhost/configmaps.go
- test/e2e/values.yaml
/kind test
adding tests for fromHostsync feature
- Sync specific config maps from host namespace to a different namespace in vCluster
- Delete configmap in Host, configmap in vCluster is also deleted
- Sync all config maps from host namespaces to the same namespace in vCluster
> Adding tests for fromHostSync

- config/config.go
- pkg/authentication/delegatingauthenticator/delegatingauthenticator.go
- pkg/authorization/delegatingauthorizer/authorizer.go
- pkg/authorization/delegatingauthorizer/cache.go
- pkg/authorization/impersonationauthorizer/authorizer.go
- pkg/authorization/kubeletauthorizer/authorizer.go
- pkg/cli/localkubernetes/configure.go
Changes:
* Caches the subjectaccessreview calls
* Reduces the timeout to wait for local k8s connection before falling back to background proxy
> refactor: cache authorizer & short local k8s timeout

- pkg/cli/connect_helm.go
- test/e2e_cli/connect/connect.go
/kind bugfix
resolves ENG-5488
Fixed an issue where `vcluster connect` command was giving positive result even when vcluster is not exposed on the endpoint provided in `server` flag
With this PR, the `vcluster connect` command will perform an additional check of verifying the vcluster is accessible with the additional flags that are provided in the command. This is done by checking if we are able to list the `default` service account is in the vcluster.
eg: …
> fix: Check if vcluster is reachable with the additional flags provided as input in `vcluster connect` command

- Dockerfile
Fixes some linting regarding caps and key/value separation
- Consistency on Dockerfile casing
- Use of "ENV key=value" over "ENV key value"
> Fix some Dockerfile linting

- cmd/vcluster/cmd/start.go
- cmd/vclusterctl/cmd/create.go
- pkg/cli/create_helm.go
resolves ENG-5919
For v0.24, it will be mandatory set `reuse-namespace=true` in vcluster config to create multiple vclusters in same ns, failing to which the vcluster pod won't come up. This applies to both via CLI and helm.
**Testing scenarios:**
- Using helm, when the user creates another vcluster without giving setting `reuse-namespace` config to true:
- When user created it using CLI in v0.22 and upgrades to v0.24 then also the pod should fail …
> Enforce reuse-namespace config for creating multiple vClusters in same ns

- pkg/cli/destroy/destroy.go
/kind bugfix
resolves ENG-5881
Fixed an issue where vcluster where platform destroy command was giving incorrect warning.
> Fix warning message for platform destroy

- .golangci.yml
- chart/values.schema.json
- chart/values.yaml
- config/config.go
- config/legacyconfig/migrate.go
- config/legacyconfig/migrate_test.go
- pkg/config/config.go
- pkg/config/validation.go
- pkg/config/validation_test.go
- pkg/setup/controller_context.go
- pkg/setup/controllers.go
- pkg/setup/controllers_test.go
- test/e2e/coredns/coredns.go
- test/e2e/syncer/pvc/pvc.go
- test/framework/framework.go
- test/framework/util.go
/kind feature
resolves ENG-5486
Add `exportKubeConfig.additionalSecrets` config and deprecate `exportKubeConfig.secret`.
You can set either old `exportKubeConfig.secret` or the new `exportKubeConfig.additionalSecrets`.
All previous usages of `exportKubeConfig.Secret` have been removed and the only two places where the `exportKubeConfig.Secret` property is now used are:
- `GetAdditionalSecrets()` func in `config/config.go` which returns either old …
> Add exportKubeConfig.additionalSecrets config

- pkg/certs/ensure.go
- pkg/setup/controllers.go
- pkg/util/kubeconfig/kubeconfig.go
/kind bugfix
resolves #2283 .The pull request adds labels to two secrets that contain a kubeconfig and a certificate. These labels help improve the organization and management of the secrets.
Fixed an issue where vcluster 2 secrets containing a kubeconfig and a certificate were missing labels.
This PR cherry-picks @maheshbaliga's fixes from https://github.com/loft-sh/vcluster/pull/2330 in order to resolve merge conflicts, as we had multiple changes around exporting …
> bugfix: set labels to kubeconfig and cert secrets

- cmd/vclusterctl/cmd/login.go
* Updates command description to reflect depreciation. 
This is a tidy up activity for something left over from `0.20` release.
> fix: update `login.go` to reflect `vcluster login` is deprecated

- cmd/vclusterctl/cmd/platform/destroy.go
/kind bugfix
resolves ENG-6027
Fixed an issue where vcluster platform destroy flag `timeout-minutes` refers to incorrect flag name for force removing finalizers
> Fix CLI command's help text for platform destroy flag

- pkg/cli/destroy/destroy.go
/kind bugfix
resolves ENG-5882
Fixed an issue where vcluster platform destroy gets stuck due to networkpeer deletion times-out.
> Change deletion order for network peer to fix time-out issue

- chart/templates/_exportKubeConfig.tpl
- chart/templates/statefulset.yaml
- chart/tests/statefulset_test.yaml
resolves #ENG-6128
Fixed an issue where `vcluster create` command does not fail when both `exportKubeConfig.secret` and `exportKubeConfig.additionalSecrets` are set.
vCluster creation was already failing. This is an improvement, so that the `vcluster create` command (and Helm chart deployment) fails before trying to create the vCluster.
**Examples**
When both secret and additional secrets are set like this:
```yaml
exportKubeConfig:
secret:
name: …
```
> Validate exportKubeConfig in Helm chart

- config/experimental_helper.go
- pkg/cli/create_helm.go
/kind bugfix
resolves #ENG-6136
New Behavior:
- If the current configuration as sleepMode under experimental and they're upgrading to 0.24+
- Show advice on how to update their config
- Prompt if they'd like to proceed, warning that the experimental feature will be lost
- Fail if they choose no
- Proceed if they agree
In non-interactive terminals it warns, but proceeds otherwise.  Without proceeding, if it just returned the error they would be incapable of upgrading since their already deployed values won't validate against a new schema.   
Example Usage:
> feat: warn of experimental feature changes

- Justfile
/kind bugfix
Fixed the `just` build target `build-dev-image` when building on a darwin/arm64 (MacbookPro M4)
> fix: Fix justfile for build-dev-image

- pkg/cli/start/login.go
/kind bugfix
resolves #ENG-6079
Fixed an issue where vcluster would always login with insecure when starting the platform rather than abiding by the platform config
> fix: respect platform config insecure value on login

- cmd/vclusterctl/cmd/platform/login.go
- pkg/platform/client.go
resolves #ENG-6079
* If cert works, only write insecure if explicitly provided via --insecure flag
* If cert does not work,
* and platform config has insecure configured, write insecure in file
* and platform config has nothing configured, fail and tell user that --insecure flag is required to be used
Write to the config whatever was specified on the command line, defaulting to false and always makes an attempt at a secure login, even if it ultimately falls back to insecure and/or writes `insecure: true` to the platform config allowing insecure logins to virtual clusters …
> feat: Try secure login first, and only overwrite platform config if --insecure is specified

- pkg/platform/client.go
modify c.config inst…ead in  pkg/platform/client.go#client.mgmtLogin()
/kind bugfix
resolves #
Fixed an issue where vcluster platform login was using incorrect access key
> bugfix: do not assign a copy of platform config

- cmd/vclusterctl/cmd/list.go
- cmd/vclusterctl/cmd/platform/list/vclusters.go
- pkg/cli/describe_platform.go
- pkg/cli/find/find.go
- pkg/cli/list_helm.go
- pkg/cli/list_platform.go
- pkg/platform/helper.go
/kind feature
resolves ENG-6351
resolves ENG-5468
Users can list vclusters by logged-in user by new flag `--owner` added to `vcluster platform list vclusters --owner`
**Tests Executed :**
**Test Setup:**
- Added 3 Users `AK`, `Test User1` and `Test User2` to vcluster platform
- Added a team `default-team` which has only 1 member `TestUser1`
- Added 4 vclusters : 1 owned by `AK` user, 1 owned by  `TestUser1`, 1 owned by team `default-team` and 1 …
> Filter vclusters owned by logged in user

- pkg/controllers/servicesync/servicesync_test.go
/kind test
towards #ENG-5567
Add basic unit tests for ServiceSyncer.
This PR is adding basic unit tests that would serve as a basic safety net when making changes needed to fix #ENG-5567. It's not trying to cover all possible service replication scenarios and there are definitely more tests that should be added.
Work on #ENG-5567 got stuck (pending decision on how to proceed forward), but these tests I wrote while doing that work add value on their own, so opening a …
> Add basic ServiceSyncer unit tests

- .github/workflows/release.yaml
Backport from `main` to `v0.19`
Original PR Nr.: #2642
- 9197b540 fix(ci): improve branch calculation from tags (#2642)
[object Object]
> [v0.19] fix(ci): improve branch calculation from tags (#2642)

- .github/workflows/release.yaml
Backport from `main` to `v0.20`
Original PR Nr.: #2642
- 9197b540 fix(ci): improve branch calculation from tags (#2642)
[object Object]
> [v0.20] fix(ci): improve branch calculation from tags (#2642)

- .github/workflows/release.yaml
Backport from `main` to `v0.22`
Original PR Nr.: #2642
- 9197b540 fix(ci): improve branch calculation from tags (#2642)
[object Object]
> [v0.22] fix(ci): improve branch calculation from tags (#2642)

- .github/workflows/release.yaml
Backport from `main` to `v0.23`
Original PR Nr.: #2642
- 9197b540 fix(ci): improve branch calculation from tags (#2642)
[object Object]
> [v0.23] fix(ci): improve branch calculation from tags (#2642)

- pkg/setup/cleanup.go
- pkg/setup/cleanup_test.go
- pkg/setup/controllers.go
- test/e2e/servicesync/removestale.go
- test/e2e/values.yaml
/kind bugfix
towards #ENG-5567
Fixed an issue where vcluster does not delete services that were synced from host to virtual, but should not be synced anymore, because from host syncing for services has been disabled.
How it's tested:
- Added unit tests
- Added e2e test
- Tested manually with the following config that enables syncing services from host:
```
networking:
replicateServices:
fromHost:
- from: host-hello/my-host-service
to: …
```
> Delete previously replicated services after disabling from host syncing

- pkg/k8s/migrate.go
- pkg/setup/controllers.go
- pkg/setup/initialize.go
vCluster will recreate pods and delete "kube-root-ca.crt" configmaps on k3s -> k8s migration if an external backing store was used
> chore: recreate pods & configmaps on migration

- Dockerfile
- Dockerfile.cli.release
- Dockerfile.release
This PR bumps the version of helm to 3.17.3 and kine to 0.13.14 to fix CVE
resolves ENG-5980
Bumped helm (3.17.3) and kine (0.13.14) versions
> chore: bumps helm and kine version to fix CVE

- pkg/cli/destroy/destroy.go
- pkg/cli/util/args.go
/kind bugfix
resolves ENG-5245
Fixed an issue where vcluster platform deletion gets stuck due to finalizer not getting removed. Added a prompt allowing user to remove the finalizer and continue the destroy op.
The platform code changes regarding this are in [this PR](https://github.com/loft-sh/loft-enterprise/pull/4116).
The prompt would look like this:
> Add a prompt for deleting cleanup finalizers when connector secret is not found

- pkg/util/clihelper/clihelper.go
- pkg/util/clihelper/clihelper_test.go
/kind bugfix
resolves https://github.com/loft-sh/vcluster/issues/2545
CheckHelmVersion function adapts version that do not begin with 'v'
nothing
> Helm version check fails with Fedora packaged Helm

- cmd/vclusterctl/cmd/platform/get/secret.go
CLI expects secret name when trying to list all secrets in a namespace
/kind bugfix
resolves ENG-5650
Fixed an issue where vcluster CLI fails to list all secrets due to missing secret name
> fix: CLI from expecting secret name when listing secrets

- .github/workflows/e2e.yaml
- .github/workflows/lint.yaml
- .github/workflows/unit-tests.yaml
- .github/workflows/update-cache.yaml
The reason we need this extra workflow is that github actions by default does not allow cache sharing across branches / forks / prs. The workaround to mitigate this issue is to build the binaries and tests as soon as a PR is merged and dependencies are changed and then this cache can be reused across all branches. For more information check https://medium.com/@everton.spader/how-to-cache-package-dependencies-between-branches-with-github-actions-e6a19f33783a
> build: add update-cache workflow

- pkg/setup/controllers.go
- pkg/setup/controllers_test.go
/kind bugfix
Fixed an issue where using `exportKubeConfig.insecure` would yield an error when trying to connect to the vCluster since insecure and ca data would be set for the server.
> fix: using insecure in exportKubeConfig

- pkg/platform/version.go
/kind bugfix
resolves ENG-6469
Fixed an issue where vcluster platform start command installs the platform with latest version even if that is an alpha or rc version. Ideally, it should start with last stable release version, for eg. v4.2.3
> [v0.24] Platform should start with last released stable version, by default

- pkg/platform/version.go
/kind bugfix
resolves ENG-6503
Fixed an issue where vcluster platform start command installs the platform with latest version even if that is an alpha or rc version. Ideally, it should start with last stable release version, for eg. v4.2.3
> [v0.25] Platform should start with last released stable version, by default

- chart/templates/_rbac.tpl
- chart/tests/clusterrole_test.yaml
- pkg/config/validation.go
- pkg/config/validation_test.go
/kind bugfix
resolves #
- creates cluster role if istio integration is enabled
- adds vcluster.yaml validation to reject istio CRDs in `sync.toHost.customResources` section if istio integraiton is enabled
Fixed an issue where vcluster was not creating cluster role when istio integration is enabled
> istio config validation + helm chart fix

- chart/values.schema.json
- chart/values.yaml
- cmd/vcluster/cmd/start.go
- cmd/vclusterctl/cmd/create.go
- config/config.go
- config/values.yaml
- pkg/cli/create_helm.go
/kind bugfix
resolves ENG-5920
- v0.25 onwards, the user will not be allowed to create multiple vclusters inside same namespace.
- `reuse-namespace` flag and config both have been removed now.
> Disallow multiple vclusters creation inside same namespace

- cmd/vclusterctl/cmd/delete.go
- cmd/vclusterctl/cmd/platform/delete/vcluster.go
- pkg/cli/delete_helm.go
- pkg/cli/delete_platform.go
- pkg/cli/find/find.go
- pkg/cli/find/kubeclient.go
- pkg/platform/kube/client.go
/kind bugfix
fixes ENG-6256
Fixed an issue where `vcluster delete` command would delete virtual clusters with `loft.sh/non-deletable: true`.
This fix has certain limitations. See the following scenarios where those limitations are described.
**1\. You are logged into the host cluster (where the platform runs).**
✅ In this case `vcluster delete` can always see if "Prevent deletion" is enabled for any cluster, so command fails correctly for protected clusters.
In this …
> Fix vcluster delete CLI when "Prevent deletion" is enabled via platform

- cmd/vclusterctl/cmd/delete.go
- cmd/vclusterctl/cmd/platform/delete/vcluster.go
- pkg/cli/delete_helm.go
- pkg/cli/delete_platform.go
- pkg/cli/find/find.go
- pkg/cli/find/kubeclient.go
Manually backport #2697 and #2725 (additional fix).
towards ENG-5839
/kind bugfix
ENG-6256
Fixed an issue where `vcluster delete` command would delete virtual clusters with `loft.sh/non-deletable: true`.
This fix has certain limitations. See the following scenarios where those limitations are described.
**1\. You are logged into the host cluster (where the platform runs).**
✅ In this case `vcluster delete` can always see if "Prevent deletion" is enabled for any …
> [v0.24] Fix vcluster delete CLI when "Prevent deletion" is enabled via platform

- cmd/vclusterctl/cmd/platform/add/cluster.go
/kind feature
resolves https://github.com/loft-sh/vcluster/issues/2546
> feat: Add `create-namespace` flag to `vcluster platform add cluster` command

- pkg/controllers/resources/pods/syncer.go
/kind bugfix
resolves ENG-6760
Fixed an issue where vcluster was applying istio patches only on host object creation
otherwise the pods won't be labeled if the namespace was label after the pod creation
> sync istio patches in pod controller .Sync

- .github/workflows/release.yaml
- hack/changelog/go.mod
- hack/changelog/go.sum
- hack/changelog/log/log.go
- hack/changelog/main.go
- hack/changelog/note.go
- hack/changelog/pull-requests/pr.go
- hack/changelog/releases/releases.go
- hack/linear-sync/go.mod
- hack/linear-sync/go.sum
- hack/linear-sync/linear.go
- hack/linear-sync/linear_test.go
- hack/linear-sync/main.go
- hack/linear-sync/pr.go
References OPS-94
* Add linear-sync tool to update Linear issues when a release is created
* Sync with changelog library to extract PRs between releases
* Add sync_linear job to GitHub Actions release workflow
* Update Linear issues to "Released" state when code is released
* Extract Linear issue IDs from PR bodies and branch names
* Add release date and version comments to Linear issues
Unit tests results
```go
     === RUN   TestMoveIssueLogic
=== RUN   TestMoveIssueLogic/ENG-1234
=== RUN   TestMoveIssueLogic/ENG-5678
=== RUN   TestMoveIssueLogic/ENG-9012
=== RUN …
```
> feat(ci): linear issues sync

- pkg/util/patch/patch.go
- pkg/util/patch/patch_test.go
/kind bugfix
part of ENG-6763
Fixed an issue where vcluster was not patching if path has multiple wildcards
`getNextValue` returns a list correctly for patch path like `spec.servers[*].hosts[*]`. But in the Translate & Set we were returning after processing first element if it was equal to `"*"` so only first element in that list was processed
> support multiple wildcards in patch.Translate and patch.Set

- chart/values.schema.json
- chart/values.yaml
- config/config.go
- config/values.yaml
- pkg/config/config.go
- pkg/config/validation.go
- pkg/controllers/resources/nodes/syncer.go
- pkg/controllers/resources/persistentvolumeclaims/syncer.go
- pkg/controllers/resources/pods/scheduling/config.go
- pkg/controllers/resources/pods/syncer.go
- pkg/controllers/resources/pods/syncer_test.go
- pkg/controllers/resources/pods/translate/translator.go
/kind feature
towards ENG-6600
Added Hybrid Scheduling config and syncer error if Hybrid Scheduling is enabled, since it is a Pro feature.
Hybrid scheduling check should be also added in few places in the Helm chart, but I will add that in another PR, as Hybrid Scheduling does not work in the vcluster OSS and this PR is towards the first alpha release for testing.
> feat: Hybrid Scheduling config and check if enabled

- .github/workflows/release.yaml
/kind bugfix
`vendor` directory does not exist in `hack/linear-sync` nor in any other `hack/*` module/directory, so updating the run command here (and not adding `vendor` directory).
> fix: Don't use `-mod vendor` when running linear-sync

- chart/templates/_rbac.tpl
- chart/templates/clusterrole.yaml
- chart/tests/clusterrole_test.yaml
/kind bugfix
resolves ENG-6840
Fixed an issue where vcluster logs errors when Hybrid Scheduling is enabled without also enabling FromHost sync for CSINodes, CSIStorageCapacities and CSIDrivers.
> fix: Permissions needed for Hybrid Scheduling

- pkg/cli/printhelper/printhelper.go
This pr fixes commands and some old references of loft changed to vcluster platform in printhelper.go
> Fixed minor issues in printhelper.go

- chart/templates/service.yaml
- pkg/cli/create_helm.go
- pkg/platform/clihelper/clihelper.go
/kind bugfix
resolves ENG-5603
Fixed an issue where vcluster was allowed to be installed in the platform namespace
**_Helm_**
1. When the platform installation exists, and the helm command is targeted towards the same namespace, it throws an error and exits.
2. When the helm install is targeted to a different namespace, it proceeds correctly.
**_vCluster CLI_**
1. When the platform installation exists, and the CLI command is targeted towards the same namespace, it …
> bugfix: disallow users from creating a vCluster in the platform namespace

- pkg/constants/cli.go
Bumps background proxy version of kubectl
Bumps kubectl version
> chore: bumps kubectl version

- config/config.go
- pkg/setup/config.go
/kind bugfix
Fixes #6900
v0.25.0 included a fix where vClusters with external fields set to non-empty values but with enabled not set to "true" would run with the external data store. A result of the fix was that some vClusters that ran with an external data store before would run with a fresh SQLite data store instead. If this was not desired, validation in vCluster would prevent the external data store enabled flag from being toggled to "true". Now, a vCluster that has been updated to v0.25.1+ can …
> Fix compatibility

- config/config.go
- pkg/setup/config.go
/kind bugfix
Fixes ENG-6900
A release note was not written covering the bug from the parent issue because there is not a release in v0.24.x that introduces it. This backport is preventative in nature.
> Fix compatibility v0.24

- .github/workflows/push-head-images.yaml
- .goreleaser.head_images.yaml
Disables archives for the push-head-images workflow.
Fixes the issue with failed builds: https://github.com/loft-sh/vcluster/actions/runs/15180935198/job/42690610054
We don't need to publish archives in this build, only docker images.
> ci: disable archives for head images build

- .github/workflows/push-head-images.yaml
Installs QEMU and buildx actions for multiarch docker builds.
> ci: add qemu and buildx actions for push-head-images

- cmd/vclusterctl/cmd/connect.go
- cmd/vclusterctl/cmd/create.go
- cmd/vclusterctl/cmd/delete.go
- pkg/cli/flags/connect/connect.go
- pkg/cli/flags/create/create.go
- pkg/cli/flags/delete/delete.go
- pkg/cli/flags/flags.go
- test/framework/framework.go
resolves ENG-5648
Fixed an issue where vcluster would silently ignore platform flags when using driver helm.
> Log error when using platform flags with driver helm

- chart/values.schema.json
- config/config.go
- config/diff.go
- pkg/controllers/resources/ingressclasses/syncer.go
- pkg/controllers/resources/ingresses/syncer.go
- pkg/controllers/resources/persistentvolumeclaims/syncer.go
- pkg/controllers/resources/persistentvolumes/syncer.go
- pkg/controllers/resources/pods/syncer.go
- pkg/controllers/resources/pods/syncer_test.go
- pkg/controllers/resources/priorityclasses/syncer.go
- pkg/controllers/resources/runtimeclasses/syncer.go
- pkg/controllers/resources/storageclasses/host_syncer.go
/kind feature
resolves ENG-6782
Add label selectors to fromHost resources
That's the list of selectors and it's resources:
- sync.fromHost.ingressClasses.selector -> Ingress
- sync.fromHost.storageClasses.selector -> PersistentVolumeClaim & PersistentVolume
- sync.fromHost.runtimeClasses.selector -> Pod
- sync.fromHost.priorityClasses.selector -> Pod
> [ENG-6782] feat(class limits): Add label selectors to fromHost resources

- pkg/controllers/resources/ingressclasses/syncer.go
- pkg/controllers/resources/priorityclasses/syncer.go
- pkg/controllers/resources/runtimeclasses/syncer.go
- pkg/controllers/resources/storageclasses/host_syncer.go
At this point the virtual part doesn't exist, so no need for a deletion. Just print a `Warning` instead.
/kind bugfix
resolves #
Skip deletion on `SyncToVirtual` because the virtual part doesn't exist at this point.
Just log a warning instead
> fix: Remove the deletion on `SyncToVirtual`

- .github/workflows/e2e.yaml
- cmd/vcluster/cmd/portforward.go
- cmd/vcluster/cmd/root.go
- pkg/cli/localkubernetes/configure.go
- pkg/constants/cli.go
- pkg/util/portforward/portforward.go
Backport from `main` to `v0.24`
Original PR Nr.: #2872
Resolves: ENG-7159
- 74e339e4 fix: add vcluster port-forward command to use as the background proxy… (#2872)
* fix: add vcluster port-forward command to use as the background proxy process until https://github.com/containerd/containerd/issues/9875 is resolved
* feat: allow setting the background proxy image via environment variable
> [v0.24] fix: add vcluster port-forward command to use as the background proxy… (#2872)

- .github/workflows/e2e.yaml
- cmd/vcluster/cmd/portforward.go
- cmd/vcluster/cmd/root.go
- pkg/cli/localkubernetes/configure.go
- pkg/constants/cli.go
- pkg/util/portforward/portforward.go
Backport from `main` to `v0.25`
Original PR Nr.: #2872
Resolves: ENG-7158
- 74e339e4 fix: add vcluster port-forward command to use as the background proxy… (#2872)
* fix: add vcluster port-forward command to use as the background proxy process until https://github.com/containerd/containerd/issues/9875 is resolved
* feat: allow setting the background proxy image via environment variable
> [v0.25] fix: add vcluster port-forward command to use as the background proxy… (#2872)

- .github/workflows/e2e.yaml
- cmd/vcluster/cmd/portforward.go
- cmd/vcluster/cmd/root.go
- pkg/cli/localkubernetes/configure.go
- pkg/constants/cli.go
- pkg/server/filters/service.go
- pkg/util/portforward/portforward.go
Backport from `main` to `v0.23`
Original PR Nr.: #2872
Resolves: ENG-7160
- 74e339e4 fix: add vcluster port-forward command to use as the background proxy… (#2872)
* fix: add vcluster port-forward command to use as the background proxy process until https://github.com/containerd/containerd/issues/9875 is resolved
* feat: allow setting the background proxy image via environment variable
> [v0.23] fix: add vcluster port-forward command to use as the background proxy… (#2872)

- .goreleaser.yaml
- Justfile
- hack/assets/assets.go
Example output for version 1.2.3:
```
$ go run -mod vendor ./hack/assets/cmd/main.go 1.2.3 --latest
ghcr.io/loft-sh/vcluster-pro:1.2.3
ghcr.io/loft-sh/kubernetes:v1.32.1
coredns/coredns:1.11.3
```
```
$ go run -mod vendor ./hack/assets/cmd/main.go 1.2.3 --optional
ghcr.io/loft-sh/vcluster-oss:1.2.3
library/alpine:3.20
ghcr.io/loft-sh/kubernetes:v1.31.1
ghcr.io/loft-sh/kubernetes:v1.30.2
registry.k8s.io/etcd:3.5.21-0
registry.k8s.io/etcd:3.5.15-0
registry.k8s.io/etcd:3.5.13-0
rancher/k3s:v1.32.1-k3s1
rancher/k3s:v1.31.1-k3s1
rancher/k3s:v1.30.2-k3s1
```
resolves #ENG-6910 …
> [ENG-6910] Further slim down images.txt

- pkg/cli/localkubernetes/configure.go
/kind bugfix
resolves ENG-7008
> fix: improve error message when background proxy image fails due to invalid or expired ghcr.io credentials.

- config/config.go
- config/config_test.go
/kind bugfix
Fixed an issue where `vcluster create` did not show error when using Hybrid Scheduling pro feature without pro license.
There is already the pro feature / license check in the syncer (so syncer wouldn't start without the proper license), but the check was missing in the config check which is used by the CLI when the cluster is created (earlier in the vcluster creation process).
> Add pro feature config check for Hybrid scheduling

- pkg/platform/helper.go
/kind bugfix
resolves ENG-6899
Fixed an issue where vcluster platform connect cluster had invalid .server path
> vcluster platform connect: fix server path for kubeconfig

- pkg/cli/create_helm.go
- pkg/config/lint.go
- pkg/config/parse.go
- pkg/controllers/resources/pods/syncer.go
resolves ENG-7235
Added warning when the virtual scheduler and the hybrid scheduling are both enabled, but the host schedulers have not been set.
> Lint vcluster config: Warn about hybrid scheduling without effect

- pkg/cli/create_helm.go
Orbstack doesn't need a node port for local connection so we can skip it safely
> fix: remove nodeport for orbstack

- pkg/controllers/resources/persistentvolumes/syncer.go
- pkg/mappings/generic/mapper.go
/kind bugfix
resolves #2384
Fixed an issue where vcluster would falsely translate names in PV spec when using toHost PV syncing
> PV SC fixes

- test/e2e_limit_classes/limitClasses/ingressClasses.go
- test/e2e_limit_classes/limitClasses/storageClasses.go
What issue type does this pull request address? (keep at least one, remove the others)
/kind test
What does this pull request do? Which issues does it resolve? (use resolves #<issue_number> if possible)
resolves #
Warning Message for the unavailable classes in resources created was not found within the given time. Added gomega eventually so that event will be consistently checked before triggering the error.
Please provide a short message that should be published in the vcluster release notes
Fixing the flaky test in e2e_limit_classes for ingressClasses and storageClasses.
> Fixing the flaky test in e2e_limit_classes

- pkg/cli/delete_helm.go
- pkg/constants/coredns.go
- pkg/coredns/coredns.go
- pkg/setup/controllers.go
- test/framework/util.go
/kind bugfix
resolves ENG-7242
Fixed an issue where coreDNS components don't get deleted during vcluster delete operation
> Delete coreDNS components during vcluster delete op

- pkg/controllers/resources/persistentvolumes/syncer.go
- test/e2e/syncer/pvc/pvc.go
- test/e2e/values.yaml
- test/framework/util.go
A Released PV would not trigger a sync on the Delete event from the host.
/kind bugfix
resolves #2939 
Fixed an issue where the deletion of a Released PV in the host cluster would not be propagate to the virtual cluster until vcluster was restarted or the object modified again.
This change does not change anything in the behavior of the syncer itself.
It changes what events are enqueued for reconciliation through the `shouldSync` and therefore `IsManaged` function …
> fix: Clean up Released PVs in virtual cluster

- chart/values.schema.json
- chart/values.yaml
- config/config.go
- config/config_test.go
- config/legacyconfig/migrate.go
- config/legacyconfig/migrate_test.go
- config/values.yaml
- pkg/config/config.go
- pkg/controllers/resources/pods/translate/hosts.go
- pkg/controllers/resources/pods/translate/translator.go
- pkg/controllers/resources/pods/translate/translator_test.go
BREAKING CHANGE: Change config.sync.toHost.pods.rewriteHosts.initContainer.image from string to struct.
/kind feature
This changes the config for the "rewriteHosts" feature to be in line with other places.
The init container will now also use the `config.controlPlane.advanced.defaultRegistry`.
Allow to use a custom registry for the rewriteHosts init container.
BREAKING CHANGE: replaced the config string `sync.toHost.pods.rewriteHosts.initContainer.image` with object that takes `registry`, …
> feat: RewriteHosts initContainer image may use override image

- cmd/vcluster/cmd/certs/certs.go
- cmd/vcluster/cmd/certs/check.go
- cmd/vcluster/cmd/certs/rotate.go
- cmd/vcluster/cmd/root.go
- cmd/vcluster/cmd/snapshot.go
- cmd/vcluster/cmd/start.go
- cmd/vclusterctl/cmd/certs/certs.go
- cmd/vclusterctl/cmd/certs/check.go
- cmd/vclusterctl/cmd/certs/rotate.go
- cmd/vclusterctl/cmd/root.go
- pkg/certs/ensure.go
- pkg/certs/rotate.go
- pkg/cli/certs/check_helm.go
- pkg/cli/certs/rotate_helm.go
- pkg/server/cert/cert.go
- pkg/setup/config/config.go
- pkg/setup/initialize.go
- pkg/util/podhelper/pod.go
- pkg/util/podhelper/wait.go
- test/e2e_certs/certs/rotate.go
- test/e2e_certs/e2e_suite_test.go
- test/e2e_certs/values.yaml
- test/framework/util.go
/kind feature
resolves ENG-7787
resolves ENG-7788
resolves ENG-7789
Add vcluster cert rotation commands
This PR introduces following new commands:
- `vcluster certs rotate`: Rotate client/server leaf certificates using the current CA.
- `vcluster certs rorate-ca`: Rotate all certificates including the CA.
- `vcluster certs check`: Display basic infos about the current certificates.
Most of the actual rotation functionality is under `cmd/vcluster/cmd/certs` resp. …
> Cert rotation

- pkg/controllers/resources/events/translate.go
- pkg/mappings/resources/events.go
- test/e2e/e2e_suite_test.go
- test/e2e/syncer/events/events.go
resolves ENG-6860
Added ability to force sync Events that don't have an `involvedObject` that is synced from vCluster. These events will be synced into the default namespace.
> feat: add ability to force sync an event into default namespace

- pkg/constants/coredns.go
- pkg/coredns/coredns.go
/kind feature
resolves #ENG-8049
This version hasn't officially made it into the coredns docs yet.  There's a PR with version `0.12.0` [here](https://github.com/coredns/deployment/pull/306/files?w=1)
> Adds coredns version mapping for k8s 1.33

- pkg/controllers/resources/pods/translate/translator.go
- pkg/controllers/resources/pods/translate/translator_test.go
/kind bugfix
resolves ENG-8053
> Fix: advanced.defaultRegistry takes precedence over image.registry field

- pkg/controllers/resources/pods/syncer.go
- pkg/controllers/resources/pods/syncer_test.go
/kind bugfix
resolves ENG-8084
Fixed an issue where vcluster creates an invalid patch when syncing pod hostIPs
This is a timing issue between the pod & node service creation. The node / node service is created lazily when the first pod on that node is created, but the pod syncer did not handle the node service not found error, created an invalid patch, and the error resulted in an event getting recorded.
> fix: update pod hostIP syncing to better handle missing node service

- .github/workflows/publish-chart.yaml
- .github/workflows/release.yaml
Use a standalone workflow to publish the Helm chart. This makes it possible to be triggered by another workflow or from external repositories.
related to OPS-206
> chore(ci): decouple helm release action

- cmd/vcluster/cmd/root.go
- cmd/vcluster/cmd/snapshot/delete.go
- cmd/vcluster/cmd/snapshot/list.go
- cmd/vcluster/cmd/snapshot/restore.go
- cmd/vcluster/cmd/snapshot/snapshot.go
- pkg/cli/snapshot_helm.go
- pkg/snapshot/container/store.go
- pkg/snapshot/oci/store.go
- pkg/snapshot/s3/store.go
- pkg/snapshot/snapshot.go
- pkg/snapshot/types/types.go
Backport from `main` to `v0.25`
Original PR Nr.: #3021
- 1e45f69f Snapshot List and Delete (#3021)
* feat: implement vcluster snapshot list command
* feat: implement vcluster snapshot delete command
* fix: update snapshot validation for list command
* fix: modify commands to error if the configuration cannot be parsed from the environment
* fix: use full URL in list results
* fix: only list objects in the &quot;current directory&quot; of the bucket
The default s3 behavior is to list everything under a prefix. If a bucket is used for multiple purposes, this could include non-snapshot resources.
* fix: handle list input with file key at the bucket root
> [v0.25] Snapshot List and Delete (#3021)

- cmd/vclusterctl/cmd/platform/login.go
resolves ENG-4877
Fixed an issue where vcluster platform login opened a browser every time to login. Now, if access-key is stored in platform config, it will use that to login. Only if the access-key is not provided in the command line args and also not stored in the platform config, then it will open the browser to login.
> Fix platform login UX

- .github/workflows/release.yaml
Don't run sync-linear job for `-next.X` releases.
related to OPS-281
> chore(ci): skip sync-linear on next releases

- chart/values.schema.json
- chart/values.yaml
- config/config.go
**What does this pull request do? Which issues does it resolve?** (use `resolves #<issue_number>` if possible)
Deprecates features:
- target namespace
- virtual cluster kubeconfig
To be removed in 0.29.0.
Part of ENG-8507
> Deprecate features

- pkg/platform/kubeconfig/kubeconfig.go
Actually the creation is creating with a `-` (minus sign) instead of a `_` (underscore).
When creating with the underscore, the disconnect code starts to work again.
I'm not sure if this could break somebodies scripts.
/kind bugfix
resolves #ENG-8294
> fix: Fixes the name of the management context on its creation

- pkg/controllers/resources/pods/syncer.go
- pkg/controllers/resources/pods/syncer_test.go
- pkg/controllers/resources/pods/translate/diff.go
- pkg/controllers/resources/pods/translate/translator.go
/kind bugfix
resolves ENG-8629
When `proxyKubelets.byIP` is set to true (which is the default), attempting to patch the status of the physical pod there is an edge case that when running kubelet in version < 1.28 with an apiserver >= 1.28 that it only patches `hostIP` and not `hostIPs[0]`, which will then fail at the validation with following error:
```
is invalid: status.hostIPs[0].ip: Invalid value: \"1.2.3.4\": must be equal to …
```
> fix: patch virtual instead of physical and always add host ip annotations to physical

- pkg/cli/create_helm.go
/kind bugfix
resolves ENG-8545
fixes ENG-8545
Fixed preventing vcluster from being recreated from a snapshot when vcluster pod is scale down
> fix: preventing vcluster from being recreated when pod is down

- pkg/kubeadm/config.go
part of ENG-8987
Fixed an issue where vcluster standalone was hardcoding cluster name to "kubernetes" in the kubeconfig
> set cluster name in the kubeconfig for standalone

- .devcontainer/Dockerfile
- .github/workflows/lint.yaml
- .golangci.yml
- CONTRIBUTING.md
- Dockerfile
- Dockerfile.cli
- go.mod
> chore: bump go version to 1.25

- chart/templates/_vclusterconfighash.tpl
Fixes an issue where vCluster wouldn't calculate the hash correctly and vCluster wouldn't restart
> fix: calculate vcluster has correctly

- pkg/controllers/resources/endpointslices/syncer.go
/kind bugfix
resolves #
Fixed an issue where endpointSlices deleted from virtual cluster does not sync to host i.e. host eps still persisted. This PR resolves that.
> Fix endpointSlice deletion issue

- pkg/snapshot/options.go
- pkg/snapshot/request.go
- pkg/snapshot/restorerequest.go
resolves ENG-9388
This PR adds the snapshot URL to the snapshot request, so snapshot requests can be correlated to the stored snapshots.
Snapshot URL is added to the snapshot request `.spec.url` field, e.g.
```
kubectl get cm -n $vcluster nik235-snapshot-request-rxdbw -o yaml | yq '.data["snapshotRequest"]' | jq
{
"metadata": {
"name": "nik235-snapshot-request-rxdbw",
"creationTimestamp": "2025-10-07T09:41:11Z"
},
"spec": {
"url": "container:///data/snap-1",
"volumeSnapshots": {}
},
"status": {
"phase": "Completed",
"volumeSnapshots": { …
```
> Add snapshot URL to the snapshot request
