loft-sh/vcluster

- cmd/vclusterctl/cmd/connect.go
- fix: fixes an issue where vcluster connect --update-current would not work correctly
> fix: fixes an issue where vcluster connect --update-current would not work correctly

- pkg/server/filters/redirect.go
- Fixes an issue where `nodes/proxy`, `pods/proxy` and `services/proxy` requests would fail if they included `https:` or `:port`
> fix: fix issue in proxy subresource forwarding

- cmd/vclusterctl/main.go
- docs/pages/operator/external-datastore.mdx
- **docs**: Update wording in external datastore page
> docs: update wording in external datastore page

- chart/templates/statefulset.yaml
- chart/values.yaml
- conformance/v1.20/README.md
- docs/pages/operator/external-datastore.mdx
- **chart**: Added options to define `nodeSelector`, `affinity` and `tolerations` for vcluster
- **docs**: Update conformance README
> NodeSelector, Affinity & Tolerations

- chart/templates/rbac/clusterrole.yaml
- chart/templates/rbac/role.yaml
- **chart**: Remove `*` verbs in role to allow vcluster creation with `admin` role
> build: update rbac permissions in vcluster role

- CONTRIBUTING.md
- README.md
- chart/templates/statefulset.yaml
- devspace.yaml
- Added a contributing readme
- Added `syncer.command` to the chart
- Refactored the devspace.yaml
> chore: refactor devspace.yaml & add CONTRIBUTING.md

- chart/templates/service.yaml
- chart/values.yaml
- cmd/vclusterctl/cmd/create.go
> Add --port flag to specify service port on the create command

- cmd/vclusterctl/cmd/completion.go
- cmd/vclusterctl/cmd/delete.go
- cmd/vclusterctl/cmd/root.go
add cli bash completion support for bash and zsh.
tested by running hack/build-cli on amd64 darwin for bash
closes: #90
> [Feat:CLI] add completion for cl

- docs/pages/operator/external-access.mdx
- **docs**: Added a hint to enable SSL passthrough
> docs: add hint to enable SSL passthrough

- chart/values.yaml
- **chart**: set default requests & limits (#62)
> build(chart): set default resource requests

- cmd/vclusterctl/cmd/create.go
- Updated the internal k3s versions
> chore: update k3s versions

- pkg/controllers/resources/secrets/syncer.go
- Fixed an issue where the wrong index was used for secrets & ingresses sync
> fix: fixes an issue in secrets & ingresses syncer

- chart/values.yaml
- cmd/vclusterctl/cmd/create.go
- **cli**: Update newest k3s version to v1.22.2-k3s1
> chore: update k3s version to v1.22.2-k3s1

- cmd/vclusterctl/cmd/connect.go
- **cli**: improve `vcluster connect` and make the command work without requiring a statefulset
> refactor: improve cli connect mechanism

- pkg/constants/indices.go
- pkg/controllers/resources/events/backward.go
- pkg/controllers/resources/events/backward_test.go
- pkg/controllers/resources/generic/cluster_translator.go
- pkg/controllers/resources/generic/namespaced_translator.go
- pkg/controllers/resources/generic/syncer.go
- pkg/controllers/resources/persistentvolumeclaims/syncer.go
- pkg/controllers/resources/persistentvolumes/syncer.go
- pkg/controllers/resources/persistentvolumes/syncer_test.go
- pkg/controllers/resources/pods/translate/translator.go
- pkg/controllers/resources/priorityclasses/syncer.go
- pkg/controllers/resources/services/syncer.go
- pkg/metrics/helper.go
- pkg/server/filters/metrics.go
- pkg/util/translate/metadata.go
- **syncer**: Fixed an issue where persistent volumes were not correctly synced if `--fake-persistent-volumes=false`
> fix: fixed issues with persistent volume sync

- chart/templates/secret.yaml
- chart/templates/statefulset.yaml
- chart/values.yaml
- cmd/vcluster/context/context.go
- cmd/vcluster/main.go
- cmd/vclusterctl/cmd/create.go
- docs/pages/operator/other-distributions.mdx
- docs/sidebars.js
- pkg/controllers/resources/pods/translate/translator.go
- Added support for k0s (#167)
> refactor: add k0s support

- hack/build-cli.sh
Signed-off-by: Batuhan Apaydın <batuhan.apaydin@trendyol.com>
Co-authored-by: Furkan Türkal <furkan.turkal@trendyol.com>
Fixes #204 
cc: @dentrax
> feat: remove file name from the sha256 file

- pkg/server/server.go
- **syncer**: Fixed an issue where vcluster would use the wrong client to check admission requests (#213)
> fix: fix webhook issue with wrong client

- pkg/controllers/resources/nodes/nodeservice/node_service.go
- pkg/controllers/resources/nodes/syncer.go
- pkg/controllers/resources/pods/syncer.go
- pkg/controllers/resources/pods/translate/translator.go
- **syncer**: Fixed an issue where nodes wouldn't get deleted correctly
- **syncer**: Fixed an issue where generated node name services got invalid names
> fix: fix node name service & node deletion

- pkg/util/kubeconfig/kubeconfig.go
This PR exposes additional connection details in the kubernetes secret.
```bash
➜  vcluster git:(kubeconfig) k describe secret vc-cluster-1 -n cluster-1
Name:         vc-cluster-1
Namespace:    cluster-1
Labels:       <none>
Annotations:  vcluster.loft.sh/apply:
{"kind":"Secret","apiVersion":"v1","metadata":{"name":"vc-cluster-1","namespace":"cluster-1","resourceVersion":"75170","creationTimestamp"...
Type:  Opaque
Data
====
certificate-authority:  566 bytes
client-certificate:     1173 bytes
client-key:             227 bytes
config:                 2979 bytes
```
fixes #226
> expose ca data, client certificate and key in connection details

- pkg/controllers/resources/pods/translate/translator.go
- **syncer**: Fixed an issue where ordering of environment variables could be wrong
> fix: fixed an issue in environment variable resolution

- docs/pages/architecture/networking.mdx
Let me know if I should go into more detail on how this works under the hood, or whether I should explicitly mention that cross namespaces policies are also supported.
> docs: describe network policy support

- .vscode/launch.json
- devspace_start.sh
- e2e/framework/util.go
- e2e/test/syncer/pods/pods.go
- e2e/test/syncer/services/services.go
Two tests have been failing intermittently due to race conditions(IMHO). This PR should fix them.
I run the tests 50x in a loop and there was no failure, hopefully, behavior in CI is the same :).
I also updated debugging configuration to use a new flag(easier to understand) and a new container path(fixes breakpoints).
> Improve test stability

- charts/k8s/values.yaml
- cmd/vclusterctl/cmd/app/create/values/k8s.go
Bumping k8s to 1.23.
k0s and k3s don't have 1.23 releases yet.
> feat: bump k8s flavour to 1.23

- charts/k3s/values.yaml
- cmd/vclusterctl/cmd/app/create/values/k3s.go
- devspace.yaml
- hack/build-cli.sh
- Remove v1.22 support for k3s until #264 is fixed
> fix: remove v1.22 support for k3s

- charts/k3s/values.yaml
- cmd/vclusterctl/cmd/app/create/values/k3s.go
- hack/build-cli.sh
- **cli**: Remove v1.22 k3s support until #264 is fixed
> fix: backport k3s removal

- .github/workflows/e2e-tests.yaml
> test: trigger e2e check on manifests/** changes

- .github/workflows/e2e-tests.yaml
- charts/k3s/templates/statefulset.yaml
- cmd/vclusterctl/cmd/app/create/values/k3s.go
- devspace.yaml
- e2e/README.md
- e2e/framework/framework.go
backport commit 624fd29 from the main branch
> Fix k3s not starting & add v1.23 support

- pkg/controllers/resources/services/syncer_test.go
- pkg/controllers/resources/services/translate.go
- pkg/server/filters/service.go
Cherry-pick of the #291 for v0.5
- fix: syncer cache race condition after Service creation
> fix: cache race condition after Service creation

- e2e/e2e_suite_test.go
- e2e/framework/framework.go
- e2e/framework/kubectlcmd.go
- e2e/test/webhook/webhook.go
Adding the `should be able to deny attaching pod` test case from the conformance test suite.
> test (e2e): should be able to deny attaching pod

- e2e/framework/helper.go
- e2e/framework/kubectlcmd.go
- e2e/test/webhook/webhook.go
- pkg/server/server.go
The test was not failing when it should have, so the first commit fixes the test and the flaw in the test suite that stayed hidden thanks to the bad test.
**Note:** This test should fail now due to a bug in the syncer. I will first let it run and fail to prove that the test is fixed, and afterward, I'll push a commit with a fix for the bug and then it should pass.
> Fix webhooks executed in the syncer

- pkg/server/server.go
:cherries: Cherry-picking the bugfix from #316 
P.S.: webhook tests are not present on v0.5 branch. Let me know if you want to copy them too.
> Admission webhook bug fix for v0.5

- cmd/vclusterctl/cmd/create.go
- cmd/vclusterctl/cmd/get/get.go
- cmd/vclusterctl/cmd/get/service_cidr.go
- cmd/vclusterctl/cmd/root.go
- pkg/helm/values/k3s.go
Adds `get service-cidr` command to vcluster cli.
```
vcluster get service-cidr
10.96.0.0/12
```
> feat: add get service-cidr cmd to vcluster cli

- cmd/vcluster/cmd/start.go
- cmd/vcluster/context/context.go
- pkg/controllers/register.go
- pkg/controllers/resources/nodes/fake_syncer.go
- pkg/controllers/resources/nodes/fake_syncer_test.go
- pkg/controllers/resources/nodes/register.go
- pkg/controllers/resources/nodes/syncer.go
- pkg/controllers/resources/nodes/syncer_test.go
- pkg/controllers/resources/persistentvolumes/fake_syncer.go
- pkg/controllers/resources/pods/syncer.go
- pkg/controllers/syncer/context/context.go
- pkg/controllers/syncer/testing/context.go
- Removes shared mutex between pod and node controllers
- Removes node service and lock factory from register context
> Remove shared mutex between pod & node controllers

- cmd/vclusterctl/cmd/create.go
- **cli**: Allows `vcluster create ... -f https://.../my-values.yaml`
> refactor: allow url values files

- docs/pages/plugins/tutorial.mdx
- docs/sidebars.js
~Draft for an early review.~
The doc is complete. Example is also pushed to its own repo - https://github.com/loft-sh/vcluster-plugin-example
> Docs: Plugin developement tutorial

- .github/workflows/release.yaml
- hack/build-cli.sh
Signed-off-by: Batuhan Apaydın <batuhan.apaydin@trendyol.com>
Fixes #220 
👉 publish-cli: https://github.com/developer-guy/vcluster/runs/4947923465?check_suite_focus=true#step:6:12
👉 publish-images: https://github.com/developer-guy/vcluster/runs/4941268675?check_suite_focus=true#step:11:1
> feat: sign container image and sha file

- docs/pages/plugins/overview.mdx
- docs/sidebars.js
> Plugin docs

- charts/k0s/templates/rbac/role.yaml
- charts/k3s/templates/rbac/role.yaml
- charts/k8s/templates/rbac/role.yaml
- cmd/vcluster/context/context.go
- pkg/controllers/register.go
- pkg/controllers/resources/poddisruptionbudgets/syncer.go
- pkg/controllers/resources/poddisruptionbudgets/syncer_test.go
- pkg/controllers/resources/poddisruptionbudgets/translate.go
This is PR is regarding issue  #72. It adds syncer for the `PodDisruptionBudget`.
> Add PodDisruptionBudget syncer

- charts/k0s/templates/statefulset.yaml
- charts/k3s/templates/statefulset.yaml
- **chart**: Fixed an issue where volumes indentation for statefulset in k3s and k0s was wrong (#359)
> fix: fix volumes intendation

- pkg/helm/values/k3s.go
- **cli**: Fixed an issue where vcluster cli couldn't determine the cluster's Service CIDR correctly
> fix: fix service cidr discovery

- .github/ISSUE_TEMPALTE/bug-report.yaml
- .github/ISSUE_TEMPALTE/config.yaml
- .github/ISSUE_TEMPALTE/feature-request.yaml
- .github/PULL_REQUEST_TEMPLATE.md
- .github/SECURITY.md
> enhancement: add PR, bug report and feature request template

- cmd/vclusterctl/cmd/list.go
/kind bugfix
resolves #364 
Fixed an issue where vcluster list does not list virtual clusters created by kubectl
> fix: change vcluster list approach

- cmd/vclusterctl/cmd/app/create/types.go
- cmd/vclusterctl/cmd/create.go
/kind feature
resolves #
Add a flag to use the local helm chart of vcluster.
> feat: add support for local vcluster charts

- charts/k0s/templates/limitrange.yaml
- charts/k0s/templates/resourcequota.yaml
- charts/k0s/templates/statefulset.yaml
- charts/k0s/values.yaml
- charts/k3s/templates/limitrange.yaml
- charts/k3s/templates/resourcequota.yaml
- charts/k3s/templates/statefulset.yaml
- charts/k3s/values.yaml
- charts/k8s/templates/limitrange.yaml
- charts/k8s/templates/resourcequota.yaml
- charts/k8s/templates/syncer-deployment.yaml
- charts/k8s/values.yaml
- cmd/vclusterctl/cmd/app/create/types.go
- cmd/vclusterctl/cmd/create.go
- pkg/helm/types.go
- pkg/helm/values/k3s.go
/kind feature
resolves #
Isolate modes add workload isolation and run vcluster as non-root(k3s).
> feat: add support for isolated mode

- docs/pages/operator/external-access.mdx
- docs/pages/operator/security.mdx
- docs/pages/plugins/overview.mdx
- pkg/controllers/resources/endpoints/syncer.go
> docs: add isolated mode documentation

- cmd/vcluster/cmd/start.go
- pkg/controllers/resources/pods/validatePodSecurity.go
Improves output if vcluster has denied a pod due to a violating security standard
> refactor: improve violation event

- pkg/controllers/resources/pods/translate/hosts.go
- pkg/coredns/coredns.go
vcluster will now run the init container for statefulsets as non root
> refactor: run statefulset init as non root

- charts/k0s/templates/limitrange.yaml
- charts/k0s/values.yaml
- charts/k3s/templates/limitrange.yaml
- charts/k3s/values.yaml
- charts/k8s/templates/limitrange.yaml
- charts/k8s/values.yaml
- devspace.yaml
- docs/pages/operator/security.mdx
resolves #406
Improved vcluster resource quota & limit range settings
> refactor: improve resource quota & limit range

- devspace.yaml
> tests: fix e2e tests

- .github/workflows/e2e-tests.yaml
- e2e/e2e_suite_test.go
- e2e/framework/util.go
- e2e/test/syncer/pvc/pvc.go
/kind test
Adds e2e test for `persistentvolumeclaims`
Tests for PVC
> add e2e test for persistentvolumeclaims

- charts/eks/templates/rbac/role.yaml
- charts/eks/templates/syncer-deployment.yaml
- charts/eks/values.yaml
- charts/k0s/templates/rbac/role.yaml
- charts/k0s/templates/statefulset.yaml
- charts/k0s/values.yaml
- charts/k3s/templates/rbac/role.yaml
- charts/k3s/templates/statefulset.yaml
- charts/k3s/values.yaml
- charts/k8s/templates/rbac/role.yaml
- charts/k8s/templates/syncer-deployment.yaml
- charts/k8s/values.yaml
- cmd/vcluster/cmd/start.go
- cmd/vcluster/context/context.go
- e2e/e2e_suite_test.go
- e2e/test/k8sdefaultendpoint/k8sdefaultendpoint.go
- pkg/controllers/k8sdefaultendpoint/k8sdefaultendpoint.go
- pkg/controllers/register.go
- pkg/controllers/resources/endpoints/syncer.go
- pkg/controllers/resources/endpoints/syncer_test.go
- pkg/controllers/resources/services/syncer.go
- pkg/controllers/resources/services/translate.go
- pkg/server/filters/service.go
- pkg/server/server.go
> feat: sync service and endpoints without service by default

- pkg/controllers/resources/nodes/translate.go
- pkg/controllers/resources/pods/translate/translator.go
- pkg/controllers/resources/services/syncer.go
- pkg/controllers/resources/services/translate.go
/kind bugfix
resolves #431
Fixed an issue where vcluster wouldn't sync ClusterIP to LoadBalancer change correctly
Fixed an issue where basic preemption was not working correctly if scheduler was enabled
> fix: fix clusterip to loadbalancer change issue

- pkg/controllers/resources/persistentvolumeclaims/syncer.go
- pkg/controllers/resources/persistentvolumeclaims/syncer_test.go
- pkg/controllers/resources/persistentvolumes/syncer.go
vcluster will now recreate a PVC inside the virtual cluster if there is a corresponding host PVC with a different volume name
> refactor: recreate pvc if volumename is different

- charts/eks/templates/pre-install-hook-serviceaccount.yaml
- charts/eks/templates/syncer-deployment.yaml
- charts/eks/templates/workloadserviceaccount.yaml
- charts/k0s/templates/statefulset.yaml
- charts/k0s/templates/workloadserviceaccount.yaml
- charts/k3s/templates/statefulset.yaml
- charts/k3s/templates/workloadserviceaccount.yaml
- charts/k8s/templates/pre-install-hook-serviceaccount.yaml
- charts/k8s/templates/syncer-deployment.yaml
- charts/k8s/templates/workloadserviceaccount.yaml
/kind feature
resolves #439 
Fixed an issue where vcluster now will be able to pull images from a private registry.
> feat: update service accounts to accommodate imagePullSecrects

- cmd/vclusterctl/cmd/root.go
- cmd/vclusterctl/cmd/version.go
/kind feature
resolves #
This PR adds a version command to print the version of vcluster.
> feat: add version command

- pkg/controllers/resources/ingresses/syncer.go
- pkg/controllers/resources/ingresses/syncer_test.go
- pkg/controllers/resources/ingresses/translate.go
/kind bugfix
resolves #351 
vcluster will now rewrite certain ingress annotations
> refactor: translate certain ingress annotations

- docs/pages/architecture/networking.mdx
- docs/pages/architecture/nodes.mdx
- docs/pages/architecture/scheduling.mdx
> docs: add scheduler & service mapping docs

- docs/pages/operator/backup.mdx
- docs/sidebars.js
> docs: add backup documentation

- charts/k8s/templates/api-deployment.yaml
- charts/k8s/templates/controller-deployment.yaml
- charts/k8s/templates/etcd-statefulset.yaml
- charts/k8s/templates/scheduler-deployment.yaml
/kind bugfix
resolves #467
Fixed an issue where service account and image pull secrets were not correctly applied in k8s distro
> chart: add service account to k8s api server, etcd & controller

- docs/pages/architecture/scheduling.mdx
> docs: remove quotes for flags

- pkg/controllers/manifests/init.go
/kind bugfix
Fixed an issue where syncer would panic while applying init manifests
> fix: fix init manifests panic

- docs/pages/operator/init-manifests.mdx
- docs/sidebars.js
Adding documentation for applying manifests at init, as introduced in v0.8.0.
> Adding init-manifests content

- charts/eks/templates/rbac/clusterrole.yaml
- charts/k0s/templates/rbac/clusterrole.yaml
- charts/k3s/templates/rbac/clusterrole.yaml
- charts/k8s/templates/rbac/clusterrole.yaml
- pkg/controllers/resources/persistentvolumeclaims/syncer.go
- pkg/controllers/resources/persistentvolumeclaims/translate.go
/kind bugfix
Fixed an issue where creating a PVC with a WaitForFirstConsumer storage class and scheduler enabled would be stuck pending.
> fix: fix WaitForFirstConsumer with scheduler enabled

- README.md
- docs/pages/fragments/deploy-vcluster.mdx
> docs: make isolated mode more prominent in README and quickstart

- charts/eks/templates/api-deployment.yaml
- charts/eks/templates/controller-deployment.yaml
- charts/eks/templates/etcd-statefulset.yaml
- charts/eks/templates/pre-install-hook-job.yaml
- charts/eks/templates/syncer-deployment.yaml
- charts/eks/values.yaml
- charts/k0s/templates/statefulset.yaml
- charts/k0s/values.yaml
- charts/k3s/templates/statefulset.yaml
- charts/k3s/values.yaml
- charts/k8s/templates/api-deployment.yaml
- charts/k8s/templates/controller-deployment.yaml
- charts/k8s/templates/etcd-statefulset.yaml
- charts/k8s/templates/pre-install-hook-job.yaml
- charts/k8s/templates/scheduler-deployment.yaml
- charts/k8s/templates/syncer-deployment.yaml
- charts/k8s/values.yaml
/kind feature
resolves #487 
Fixed an issue where vcluster now supports priorityClassName in syncer, api, controller deployments, etcd stateful set and pre-install job through helm chart and separate configuration
> helmchart update with priorityClassName

- pkg/controllers/register.go
/kind bugfix
resolves #482
Fixed an issue where vcluster wouldn't apply init manifests correctly if a target namespace was specified
> fix: target namespace not working with init manifests

- cmd/vclusterctl/cmd/list.go
/kind feature
resolves #485 
Fixed an issue where vcluster ...now list command has status column showing state of the vclusters. Now paused vclusters will also be shown in list output.
> Status column to list command and paused vclusters are part of the list output

- charts/eks/templates/coredns.yaml
- charts/eks/values.yaml
- charts/k0s/templates/coredns.yaml
- charts/k0s/values.yaml
- charts/k3s/templates/coredns.yaml
- charts/k3s/values.yaml
- charts/k8s/templates/coredns.yaml
- charts/k8s/values.yaml
/kind feature
resolves #488 
Fixed an issue where vcluster ... now supports coredns configuration to be pushed from helm chart
> Add coredns.resources property to externalise coredns config

- Dockerfile
- charts/eks/templates/api-deployment.yaml
- charts/eks/templates/controller-deployment.yaml
- charts/eks/templates/pre-install-hook-job.yaml
- charts/eks/templates/pre-install-hook-role.yaml
- charts/eks/values.yaml
- charts/k0s/templates/secret.yaml
- charts/k0s/templates/statefulset.yaml
- charts/k0s/values.yaml
- charts/k3s/templates/statefulset.yaml
- charts/k3s/values.yaml
- charts/k8s/templates/api-deployment.yaml
- charts/k8s/templates/controller-deployment.yaml
- charts/k8s/templates/pre-install-hook-job.yaml
- charts/k8s/templates/pre-install-hook-role.yaml
- charts/k8s/values.yaml
- cmd/vcluster/cmd/certs.go
- cmd/vcluster/cmd/start.go
- cmd/vclusterctl/cmd/create.go
- cmd/vclusterctl/cmd/get/service_cidr.go
- devspace.yaml
- pkg/helm/values/k3s.go
- pkg/util/servicecidr/servicecidr.go
resolves #461 
Enhanced the vcluster syncer to discover the correct value of the service CIDR range automatically.
> feat: init container to discover service CIDR

- pkg/controllers/coredns/nodehosts.go
Sort node hosts before applying
> refactor: sort node addresses

- pkg/controllers/resources/configmaps/syncer.go
- pkg/controllers/resources/endpoints/syncer.go
- pkg/controllers/resources/events/syncer.go
- pkg/controllers/resources/ingresses/legacy/syncer.go
- pkg/controllers/resources/ingresses/syncer.go
- pkg/controllers/resources/networkpolicies/syncer.go
- pkg/controllers/resources/nodes/syncer.go
- pkg/controllers/resources/persistentvolumeclaims/syncer.go
- pkg/controllers/resources/persistentvolumes/syncer.go
- pkg/controllers/resources/poddisruptionbudgets/syncer.go
- pkg/controllers/resources/pods/syncer.go
- pkg/controllers/resources/priorityclasses/syncer.go
- pkg/controllers/resources/secrets/syncer.go
- pkg/controllers/resources/serviceaccounts/syncer.go
- pkg/controllers/resources/services/syncer.go
- pkg/controllers/resources/storageclasses/legacy_syncer.go
- pkg/controllers/resources/storageclasses/syncer.go
- pkg/controllers/resources/volumesnapshots/volumesnapshotclasses/syncer.go
- pkg/controllers/resources/volumesnapshots/volumesnapshotcontents/syncer.go
- pkg/controllers/resources/volumesnapshots/volumesnapshots/syncer.go
- pkg/controllers/syncer/translator/util.go
vcluster will now print the modification made on update sync to console
> refactor: print more information on update

- cmd/vclusterctl/cmd/app/localkubernetes/configure.go
> refactor: wait longer for direct connection contexts

- cmd/vclusterctl/cmd/app/localkubernetes/configure.go
This is a follow up on #530 
`vcluster connect` can now generate kube config without port forwarding for minikube instances that use certain drivers, such as KVM on linux.
> feat: local connect support for minikube VM driver

- cmd/vclusterctl/cmd/app/podprinter/podprinter.go
- cmd/vclusterctl/cmd/connect.go
- cmd/vclusterctl/cmd/util.go
> refactor: only show events on critical status

- README.md
- docs/pages/architecture/basics.mdx
- docs/pages/architecture/networking.mdx
- docs/pages/architecture/nodes.mdx
- docs/pages/architecture/scheduling.mdx
- docs/pages/architecture/storage.mdx
- docs/pages/architecture/synced-resources.mdx
- docs/pages/fragments/connect.mdx
- docs/pages/fragments/delete-vcluster.mdx
- docs/pages/fragments/deploy-to-openshift.mdx
- docs/pages/fragments/deploy-vcluster.mdx
- docs/pages/fragments/high-availability.mdx
- docs/pages/fragments/non-root-vcluster.mdx
- docs/pages/getting-started/connect.mdx
- docs/pages/getting-started/deployment.mdx
- docs/pages/operator/accessing-vcluster.mdx
- docs/pages/operator/external-access.mdx
- docs/pages/operator/other-distributions.mdx
- docs/pages/operator/pausing-vcluster.mdx
- docs/pages/operator/security.mdx
- docs/pages/quickstart.mdx
- docs/pages/what-are-virtual-clusters.mdx
> docs: updates for v0.10

- pkg/util/kubeconfig/kubeconfig.go
resolves #539 
Fixed an issue where vcluster where vcluster would emit unnecessary events in the case of non-root
> refactor: remove failed to create log

- docs/pages/plugins/overview.mdx
- docs/pages/plugins/tutorial.mdx
> docs: update plugin documentation

- charts/eks/README.md
- charts/k0s/README.md
- charts/k3s/README.md
- charts/k8s/README.md
> docs: add helm chart readme's

- charts/eks/README.md
- charts/k0s/README.md
- charts/k3s/README.md
- charts/k8s/README.md
> docs: improve helm readmes

- cmd/vclusterctl/cmd/disconnect.go
/kind bugfix
Fixed an issue where `vcluster disconnect` would falsely error if the vcluster was already deleted
> fix: fixes an issue where vcluster disconnect would error

- cmd/vclusterctl/cmd/find/find.go
Increase timeout before vcluster will fail searching
> refactor: increase timeout

- charts/eks/Chart.yaml
- charts/eks/templates/pre-install-hook-job-role.yaml
- charts/eks/templates/pre-install-hook-job-rolebinding.yaml
- charts/eks/templates/pre-install-hook-job-serviceaccount.yaml
- charts/eks/templates/pre-install-hook-job.yaml
- charts/k8s/templates/pre-install-hook-job-role.yaml
- charts/k8s/templates/pre-install-hook-job-rolebinding.yaml
- charts/k8s/templates/pre-install-hook-job-serviceaccount.yaml
- charts/k8s/templates/pre-install-hook-job.yaml
fixes #553
/kind bugfix
resolves #553 
Fixed an issue where vcluster `k8s` and `eks` charts would fail on an upgrade because of immutable job manifest
> revert job to a pre-install hook

- docs/pages/operator/security.mdx
> docs: update network policy defaults

- cmd/vclusterctl/cmd/completion.go
/kind feature
resolves #560 
Fixed an issue where vcluster ...now supports fish shell
> added support for fish shell

- docs/pages/operator/cluster-api-provider.mdx
- docs/sidebars.js
resolves #490 
Added a docs page about [cluster-api-provider-vcluster](https://github.com/loft-sh/cluster-api-provider-vcluster)
> docs: add page about cluster-api-provider-vcluster

- charts/eks/templates/coredns.yaml
- charts/eks/templates/limitrange.yaml
- charts/eks/templates/networkpolicy.yaml
- charts/eks/templates/resourcequota.yaml
- charts/eks/templates/syncer-deployment.yaml
- charts/eks/values.yaml
/kind feature
Add isolation mode to EKS distro.
> feat: add isolation mode to eks

- .github/workflows/e2e.yaml
> enhancement: add --local-chart-dir option to create vcluster from local charts

- docs/pages/operator/init-manifests.mdx
/kind feature
Add documentation for init helm charts feature. Added by PR #515 
Add docs for init helm charts
> add init charts documentation

- pkg/controllers/resources/ingresses/legacy/syncer_test.go
- pkg/controllers/resources/ingresses/legacy/translate.go
- pkg/controllers/resources/ingresses/syncer_test.go
- pkg/controllers/resources/ingresses/translate.go
- pkg/controllers/resources/ingresses/util/util.go
/kind feature
resolves #532 
Fixed an issue where vcluster ...serviceNames are translated to vcluster way of services
> added support for actions and conditions for alb ingress controller

- .github/workflows/e2e.yaml
- charts/k0s/templates/statefulset.yaml
- charts/k0s/values.yaml
- test/e2e_node/node.go
- test/e2e_rootless/e2e_rootless_mode_suite_test.go
- test/e2e_rootless/rootlessmode.go
- test/e2e_rootless/values.yaml
**What issue type does this pull request address?** (keep at least one, remove the others)
/kind test
resolves #503
> test: add e2e test for rootless mode

- test/e2e/e2e_suite_test.go
- test/e2e/node/node.go
- test/e2e/values.yaml
**What issue type does this pull request address?** (keep at least one, remove the others)
/kind test
**What does this pull request do? Which issues does it resolve?** #503
> test: add e2e test for node selector

- pkg/controllers/resources/services/translate.go
- pkg/controllers/syncer/translator/namespaced_translator.go
/kind bugfix
resolves #609 
Fixed an issue where vcluster Services of a nested vcluster were not working correctly.
> fix: label translation in nested vcluster

- test/e2e_node/node.go
> fix: update test

- test/e2e_pause_resume/e2e_pause_resume_vcluster_test.go
- test/e2e_pause_resume/values.yaml
- test/e2e_pause_resume/vcluster.go
> test: add e2e test for vcluster pause and resume feature

- pkg/controllers/resources/nodes/translate.go
/kind bugfix
resolves #612 
Fixed an issue where vcluster ...allocatable pods has proper value
> Fix for allocatable pods sync when scheduler enabled

- charts/eks/templates/rbac/role.yaml
- charts/k0s/templates/rbac/role.yaml
- charts/k3s/templates/rbac/role.yaml
- charts/k8s/templates/rbac/role.yaml
- pkg/controllers/resources/pods/conditions.go
- pkg/controllers/resources/pods/ephemeral_containers.go
- pkg/controllers/resources/pods/syncer.go
- test/e2e/syncer/pods/pods.go
- test/framework/util.go
/kind bugfix
resolves #619
Fixed an issue where vcluster ...where conditions in status will be synced to physical pod now
> Sync readiness conditions to physical pod

- pkg/helm/helm.go
> refactor: remove debug output

- conformance/v1.23/README.md
/kind bugfix
Fixes a typo in the sonobuoy command in the conformance/v1.23/README.md
N/A
> fix: typo in conformance/v1.23/README.md

- docs/pages/architecture/networking.mdx
Fixed a typo on the networking page of the main documentation website. Link to the page [here](https://www.vcluster.com/docs/architecture/networking)
> corrected typo on the networking documentation page

- docs/pages/architecture/storage.mdx
Fixed a typo on the storage page of the main documentation website. Link to the page [here](https://www.vcluster.com/docs/architecture/storage)
> corrected typo on the storage documentation page

- charts/k3s/templates/statefulset.yaml
/kind bugfix
resolves #622
Fixed an issue where vcluster ...emptyDir will be mounted on /etc/rancher path
> added emptyDir to /etc/rancher path

- charts/eks/values.yaml
- charts/k0s/values.yaml
- charts/k3s/values.yaml
- charts/k8s/values.yaml
Provides a hint on how to set image pull secret for the vcluster pods.
_N/A - Not necessary IMHO_
> charts: add imagePullSecrets example in values.yaml

- Dockerfile
> enhancement: install dlv for arm64 arch

- charts/eks/templates/syncer-deployment.yaml
- charts/k0s/templates/statefulset.yaml
- charts/k3s/templates/statefulset.yaml
- charts/k8s/templates/syncer-deployment.yaml
- pkg/controllers/resources/nodes/syncer.go
- pkg/controllers/resources/nodes/translate.go
> enhancement: prevent scale down of node where vcluster is running

- CONTRIBUTING.md
- devspace.yaml
Set default namespace for vcluster development in devspace.yaml
> refactor: update devspace.yaml & CONTRIBUTING.md

- test/commonValues.yaml
- test/e2e/values.yaml
- test/e2e_isolation_mode/e2e_isolation_mode_test.go
- test/e2e_isolation_mode/isolated.go
- test/e2e_isolation_mode/values.yaml
> test: add e2e test for isolated mode

- pkg/controllers/resources/nodes/syncer.go
- pkg/controllers/resources/nodes/syncer_test.go
- pkg/controllers/resources/nodes/translate.go
/kind bugfix
resolves #416 
Fixed an issue where Daemonset created in vcluster couldn't schedule pods on nodes with taints tolerated by vcluster's `--enforce-tolerations` flag.
**Issue Root Cause**
Tolerations are enforced on a pod level. It works nicely for Deployment and StatefulSet kinds, as they create the required number of pods in Pending state. These pods are then available to be scheduled on eligible nodes by K8s scheduler.
The vcluster syncer syncs these pods to host cluster and applies the …
> Allow syncer to omit taints that match the enforced tolerations

- test/e2e_node/e2e_node_suite_test.go
> test: add general tests for node sync

- charts/k0s/templates/statefulset.yaml
- charts/k0s/values.yaml
> fix: use socket in volume only in rootless mode

- charts/eks/templates/syncer-deployment.yaml
- charts/eks/values.yaml
- charts/k0s/templates/statefulset.yaml
- charts/k3s/templates/statefulset.yaml
- charts/k8s/templates/syncer-deployment.yaml
- charts/k8s/values.yaml
- test/e2e_rootless/e2e_rootless_mode_suite_test.go
- test/e2e_rootless/values.yaml
> test: add general tests for e2e_rootless testsuite

- test/e2e_target_namespace/e2e_target_namespace_test.go
- test/e2e_target_namespace/targetNamespace.go
- test/e2e_target_namespace/values.yaml
> test: add e2e test for target namespace

- pkg/server/cert/syncer.go
Add vcluster service name to allowed tls names
> feat: add service and service.ns to extra sans

- docs/pages/fragments/high-availability.mdx
**What issue type does this pull request address?** (keep at least one, remove the others)
resolves #674
> docs: add configuration for HA in rootless mode

- cmd/vclusterctl/cmd/create.go
resolves #
Added code to convert base64 encoded value passed in --extra-values, to values file. 
> Convert base64 encoded value passed in --extra-values, to values file

- pkg/controllers/resources/nodes/syncer.go
- pkg/controllers/resources/nodes/translate.go
/kind bugfix
Improved node allocatable calculation:
* vcluster now uses an index to retrieve pods that are scheduled on a specific node
* vcluster now only calculates that information if scheduler is enabled
> refactor: improve node allocatable calculation

- charts/eks/templates/coredns.yaml
- charts/eks/values.yaml
- charts/k0s/templates/coredns.yaml
- charts/k0s/values.yaml
- charts/k3s/templates/coredns.yaml
- charts/k3s/values.yaml
- charts/k8s/templates/coredns.yaml
- charts/k8s/values.yaml
/kind bugfix
resolves #709 
Pass resources config to coredns deployment through values.yaml to its deployment. New key (manifests) for passing all coredns-config to its deployment.
> Rectify resources key in coredns helm config

- charts/eks/templates/coredns.yaml
- charts/eks/values.yaml
- charts/k0s/templates/coredns.yaml
- charts/k0s/values.yaml
- charts/k3s/templates/coredns.yaml
- charts/k3s/values.yaml
- charts/k8s/templates/coredns.yaml
- charts/k8s/values.yaml
/kind feature
resolves #719 
Add podAnnotations key in coredns config to control coredns pod annotations
> Add podAnnotations key in coredns config to control coredns pod annotations

- pkg/controllers/resources/persistentvolumes/syncer.go
- pkg/controllers/resources/persistentvolumes/syncer_test.go
> Revert "Delete the cloud provider volume when the PersistentVolumeReclaimPolicy is 'Delete'"

- docs/pages/fragments/install/cli.mdx
Updates documentation with working install commands
Updated install CLI commands
> docs: update install commands

- README.md
> fix: install links for vcluster cli

- docs/pages/operator/monitoring.mdx
resolves #737 
Add metrics-server related information in the docs as the default metrics-server config does't work anymore with k3s 1.22 onwards.
> Add metrics-server related information in the docs

- README.md
- docs/pages/fragments/install/cli.mdx
Replaces `chmod`/`mv` in install docs with `install -c`.
Simplied installation docs
Change requested by @FabianKramm
> docs: replace chmod/mv with install command

- pkg/controllers/servicesync/servicesync.go
/kind feature
resolves #732 
Services created by vcluster based on the configured service mapping are lacking status. This PR sync the loadbalancer status from host service to service created in vcluster
> sync loadbalancer status from host service

- pkg/controllers/resources/persistentvolumeclaims/syncer.go
- pkg/controllers/resources/persistentvolumeclaims/translate.go
Signed-off-by: Rohan CJ <rohan.joseph@loft.sh>
/kind bugfix
A dynamically provisioned PV that has nodeAffinity set (e.g. because the host cluster spans multiple AZs) might become unusable by the pod that requested it, making the pod unschedulable.
This happens because of our workaround in vcluster, which sets the volume.kubernetes.io/selected-node annotation incorrectly. A node from the wrong AZ gets selected, which prevents scheduling.
This PR disables the workaround for when the scheduler is enabled and storageclass sync is on. The workaround is no longer necessary in this case as the scheduler correctly sets the annotation.
**What does this pull request do? Which issues does it resolve?** (use …
> Remove one case of PV provisioning workaround 

- charts/eks/templates/init-configmap.yaml
- charts/k0s/templates/init-configmap.yaml
- charts/k3s/templates/init-configmap.yaml
- charts/k8s/templates/init-configmap.yaml
/kind bugfix
Fix the wrong indentation inside the `init-manifest` template
Fixed the wrong indentation inside the `init-manifest` template
> Fix wrong indentation on init-manifest template

- .github/workflows/e2e.yaml
- devspace.yaml
- test/README.md
This PR also updates the e2e gh workflow to skip runs if only `.md` files are updated.
Fixes ENG-696
> e2e: update devspace.yaml and documentation to run e2e tests

- charts/k3s/values.yaml
> docs: remove comment about service cidr

- pkg/controllers/syncer/translator/namespaced_translator.go
This enhancement is targeted for a multi-namespace mode where a race condition may cause errors about "namespace not found" to be logged. In most cases, this error will be false, the namespace reconciler will create the namespace a moment later and the next reconciliation will succeed.
N/A - Not necessary IMHO
> fix(syncer): dont log error if namespace doesn't exist yet

- charts/eks/templates/syncer-deployment.yaml
- charts/eks/values.yaml
- charts/k0s/templates/statefulset.yaml
- charts/k0s/values.yaml
- charts/k3s/templates/statefulset.yaml
- charts/k3s/values.yaml
- charts/k8s/templates/syncer-deployment.yaml
- charts/k8s/values.yaml
- cmd/vcluster/context/flag_options.go
- pkg/controllers/resources/configmaps/syncer.go
- pkg/controllers/resources/secrets/syncer.go
resolves ENG-804
Enables the option for syncing all configmaps and secrets if set
> Add option to sync all secrets and cm

- pkg/controllers/manifests/init.go
- pkg/controllers/manifests/init_test.go
/kind bugfix
/kind feature
/kind test
resolves #744 
Fixes ENG-411
> Fix: cache key does not take into account helm repo

- pkg/controllers/syncer/translator/util.go
- pkg/controllers/syncer/translator/util_test.go
> refactor: remove reflect from NewIfNil

- charts/eks/templates/daemonset-hostpath-mapper.yaml
- charts/eks/values.yaml
- charts/k0s/templates/daemonset-hostpath-mapper.yaml
- charts/k0s/values.yaml
- charts/k3s/templates/daemonset-hostpath-mapper.yaml
- charts/k3s/values.yaml
- charts/k8s/templates/daemonset-hostpath-mapper.yaml
- charts/k8s/values.yaml
resolves #881 
hostpathMapper.resources added to values.yaml
I am completely new to helm, kubernetes and vCluster. I am very open to suggestions and improvements.
I have seen commented resource blocks with suggestions for cpu and memory, which seems really helpful for beginners like me. If someone has a suggestion which values are suitable, please edit or comment. The values I added are random and just a placeholder.
> [ENHANCEMENT] Exposing hostpathMapper.resources to values.yaml

- pkg/controllers/resources/pods/translate/hosts.go
/kind bugfix
resolves #846 
Fixed an issue where vcluster would not correctly sync securityContext for StatefulSet workload
Closes ENG-748
> Set all required fields of securityContext for 'vcluster-rewrite-hosts' initContainer

- devspace.yaml
- devspace_start.sh
- hack/test-config.yaml
- pkg/config/config.go
- pkg/controllers/generic/export_syncer.go
- pkg/controllers/generic/import_syncer.go
- pkg/controllers/generic/patcher.go
- pkg/controllers/register.go
- pkg/controllers/resources/namespaces/syncer.go
- pkg/controllers/resources/namespaces/translate.go
- pkg/controllers/syncer/syncer.go
- pkg/util/translate/multi_namespace.go
- pkg/util/translate/single_namespace.go
- pkg/util/translate/types.go
/kind feature
Adds support for the resource "imports" - generically configured sync of host cluster resources into vcluster. This is only supported in multi-namespace mode.
_TODO_
There is a couple "TODO:" comments in there, I'll resolve them ASAP.
> feat: allow generic sync from Host cluster to Virtual

- cmd/vclusterctl/cmd/delete.go
- hack/test-config.yaml
- pkg/controllers/generic/export_syncer.go
- pkg/controllers/generic/import_syncer.go
- pkg/controllers/generic/patcher.go
- pkg/controllers/syncer/syncer.go
- pkg/controllers/syncer/types.go
- pkg/util/translate/translate.go
/kind bugfix
Fixed an issue where vcluster would not correctly sync tekton resources
> fix: multiple smaller problems in generic sync

- pkg/util/translate/multi_namespace.go
/kind bugfix
Fixed an issue where vcluster multi namespace suffixes where not unique
> fix: make sure multi namespace suffix is unique

- .github/workflows/e2e.yaml
- test/e2e/servicesync/servicesync.go
- test/e2e/syncer/pods/pods.go
- test/e2e/syncer/pvc/pvc.go
- test/e2e/syncer/services/services.go
- test/e2e_isolation_mode/isolated.go
- test/e2e_target_namespace/targetNamespace.go
- test/framework/framework.go
- test/framework/util.go
- test/multins_values.yaml
/kind test
I've pushed the e2e workflow changes on behalf of @neogopher, who doesn't have push permissions in this repo. This way we can test everything at once, without merging untested workflow changes.
For now, I suggested that we run these tests on PRs only with k3s.
N/A
> Support multi-namespace in e2e tests and GH workflow

- docs/pages/operator/init-manifests.mdx
resolves #618
Document templated init manifests.
> docs: document templated init manifests.

- docs/pages/operator/cluster-api-provider.mdx
IMHO significant improvement over the previous command - should work on OSX (which was missing -z flag on sed), supports double quotes inside the values file, and probably covers edge cases I am not even aware of.
N/A - not necessary IMHO
> docs: improve steps for using Helm values with CAPI provider

- docs/pages/architecture/synced-resources.mdx
- generic-sync-examples/README.md
- generic-sync-examples/cert-manager/config.yaml
- generic-sync-examples/dapr/config.yaml
- generic-sync-examples/dapr/dapr.yaml
- generic-sync-examples/istio/README.md
- generic-sync-examples/istio/config.yaml
- generic-sync-examples/istio/host-only-gateways.yaml
- generic-sync-examples/knative/config.yaml
- generic-sync-examples/tekton-pipelines/README.md
- generic-sync-examples/tekton-pipelines/config.yaml
resolves ENG-947, ENG-804
Add examples and documentation to vcluster for the generic CRD config 
> add examples and link in docs

- pkg/controllers/servicesync/servicesync.go
/kind bugfix
resolves #901, ENG-917
Fixed an issue where vcluster would not map headless service properly from host to virtual
> copy subsets from endpoint for headless service

- cmd/vcluster/context/enable_controllers.go
/kind bugfix
resolves some typo in logging
Fixed a typo in logging when scheduler is enabled but some feature is explicitly disabled
> fix typo in enable_controllers.go

- docs/pages/architecture/synced-resources.mdx
Fixed a link to examples in a GitHub repo
> Fix link to generic-sync-examples

- generic-sync-examples/cert-manager/README.md
- generic-sync-examples/cert-manager/config.yaml
/kind bugfix
fixes the existing cert-manager generic sync example according to the newer spec
fixes the existing cert-manager generic sync example according to the newer spec
> fix cert manager example with latest spec

- pkg/util/servicecidr/servicecidr.go
/kind bugfix
resolves #944 
Fixed an issue where vcluster would not start on a Kubernetes v1.20 and older due to wrong Service CIDR detection.
The problem was reproducible only on Kubernetes v1.20 and earlier.
> fix: service CIDR retirieval on k8s < v1.20

- assets/push-images.sh
- charts/eks/templates/daemonset-hostpath-mapper.yaml
- charts/eks/templates/pre-install-hook-job.yaml
- charts/eks/templates/syncer-deployment.yaml
- charts/eks/values.yaml
- charts/k0s/templates/daemonset-hostpath-mapper.yaml
- charts/k0s/templates/statefulset.yaml
- charts/k0s/values.yaml
- charts/k3s/templates/daemonset-hostpath-mapper.yaml
- charts/k3s/templates/statefulset.yaml
- charts/k3s/values.yaml
- charts/k8s/templates/daemonset-hostpath-mapper.yaml
- charts/k8s/templates/pre-install-hook-job.yaml
- charts/k8s/templates/syncer-deployment.yaml
- charts/k8s/values.yaml
- cmd/vclusterctl/cmd/app/localkubernetes/configure.go
- hack/assets/main.go
Will rebase and test after we do a beta release with pushed images.
TODO: review docs
resolves #
> images: replace docker.io references with ghcr.io

- pkg/controllers/resources/namespaces/syncer.go
> Add vcluster name/ns labels to Namespaces in multinamespace mode

- docs/pages/operator/external-access.mdx
resolves #
It adds a warning about costs for load balancers
I don't think it needs to be mentioned in the release notes.
Following the documentation right now can be very expensive for people that use Cloud vendors and use multiple virtual clusters.
> docs: Mention cloud costs for load balancer

- charts/eks/templates/etcd-statefulset.yaml
- charts/k0s/templates/statefulset.yaml
- charts/k3s/templates/statefulset.yaml
- charts/k8s/templates/etcd-statefulset.yaml
resolves #122 
Fixed an issue where vcluster helm storageClass template is passing nil value to storageClassName field if className is not set/passed in the values.yaml
> Fix statefulset broken tamplate

- generic-sync-examples/istio/config.yaml
- generic-sync-examples/knative/config.yaml
- generic-sync-examples/tekton-pipelines/config.yaml
/kind bugfix
resolves #1002
Fixed issue with the generic sync examples
> fix missing enable multi namespace mode

- pkg/controllers/coredns/nodehosts.go
/kind bugfix
Resolves an issue where syncer would create coredns/kube-system ConfigMap even when coredns was disabled in the helm values. However, if this Configmap is created by the user, it will still reconcile the Nodehost data key.
Fixed an issue where vcluster would create coredns/kube-system Configmap in the virtual cluster even when the coredns was disabled via helm value.
> fix: don't create coredns Configmap when not enabled

- Dockerfile.cli
/kind bugfix
Fixes this failure: https://github.com/loft-sh/vcluster/actions/runs/4694782365/jobs/8323259069
N/A
> fix: build problem with CLI container image

- .devcontainer/Dockerfile
- .devcontainer/devcontainer.json
- devspace_start.sh
> refactor: improve vcluster dev experience

- .devcontainer/devcontainer.json
> chore: start k8s cluster automatically

- charts/eks/templates/rbac/clusterrole.yaml
- charts/eks/values.yaml
- charts/k0s/templates/rbac/clusterrole.yaml
- charts/k0s/values.yaml
- charts/k3s/templates/rbac/clusterrole.yaml
- charts/k3s/values.yaml
- charts/k8s/templates/rbac/clusterrole.yaml
- charts/k8s/values.yaml
- test/e2e_isolation_mode/values.yaml
/kind feature
resolves #937
Remove the node/proxy permission from the cluster role when isolated mode is enabled.
Add a new Helm value to optionally allow original behavior even in the isolated mode.
> Disable node/proxy functionality in Isolated mode

- cmd/vclusterctl/cmd/delete.go
Now CLI can clean up etcd pvc volumes when using k8s and eks distros as well.
/kind bugfix
resolves #799 
Now CLI cleans up etcd pvc volumes when using k8s and eks distros as well.
> WIP: CLI now cleans up etcd pvc volume when using k8s or eks distros

- docs/pages/operator/external-access.mdx
It helps users with installation to understand what ingress controllers they can have.
> docs: mention other ingress controllers that support SSL passthrough

- pkg/controllers/resources/nodes/fake_syncer.go
- pkg/controllers/resources/nodes/fake_syncer_test.go
- pkg/controllers/resources/nodes/nodeservice/node_service.go
- pkg/controllers/resources/nodes/syncer.go
- pkg/controllers/resources/nodes/syncer_test.go
- pkg/controllers/resources/nodes/translate.go
- pkg/server/server.go
> refactor: remove unnecessary namespace

- docs/pages/fragments/telemetry-opt-out.mdx
- docs/pages/telemetry.mdx
- docs/sidebars.js
Adds a missing page about telemetry
> docs: add a page about telemetry

- .devcontainer/Dockerfile
- .devcontainer/devcontainer.json
- .devcontainer/mount-docker/devcontainer.json
> chore: add mount-docker configuration

- docs/pages/operator/monitoring-logging.mdx
resolves ENG-1001 Docs - add documentation for metrics proxy
> add metrics server proxy docs

- .github/workflows/release.yaml
- .gitignore
- Dockerfile
- Dockerfile.cli
- cmd/vclusterctl/cmd/create.go
- devspace_start.sh
- hack/build-cli.sh
- hack/embed-charts.sh
- pkg/embed/embed_disabled.go
- pkg/embed/embed_enabled.go
> build: make embedded charts optional

- docs/pages/operator/external-access.mdx
For some reason the "AWS ALB" link was added, but it pointed to docs that describe nginx ingress. AWS ALB doesn't support SSL pass-through, so I am removing the link.
> Update external-access.mdx - remove incorrect link

- cmd/vcluster/cmd/start.go
- pkg/metricsapiservice/register.go
- pkg/server/cert/syncer.go
> refactor: metrics package

- charts/eks/templates/init-configmap.yaml
- charts/k0s/templates/init-configmap.yaml
- charts/k0s/templates/rbac/role.yaml
- charts/k3s/templates/init-configmap.yaml
- charts/k3s/templates/rbac/role.yaml
- charts/k8s/templates/init-configmap.yaml
- cmd/vcluster/cmd/certs.go
- cmd/vcluster/cmd/start.go
- cmd/vcluster/context/context.go
- pkg/controllers/register.go
- pkg/controllers/resources/nodes/nodeservice/node_service.go
- pkg/util/servicecidr/servicecidr.go
> refactor: improve headless and easy vcluster import

- charts/eks/templates/pre-install-hook-job.yaml
- charts/eks/templates/syncer-deployment.yaml
- charts/eks/values.yaml
- charts/k0s/templates/statefulset.yaml
- charts/k0s/values.yaml
- charts/k3s/templates/statefulset.yaml
- charts/k3s/values.yaml
- charts/k8s/templates/pre-install-hook-job.yaml
- charts/k8s/templates/syncer-deployment.yaml
- charts/k8s/values.yaml
> feat(chart): add extraVolumeMounts & job options

- charts/eks/templates/api-service.yaml
- charts/eks/templates/etcd-service.yaml
- charts/eks/templates/etcd-statefulset-service.yaml
- charts/eks/templates/syncer-service.yaml
- charts/k0s/templates/service.yaml
- charts/k0s/templates/statefulset-service.yaml
- charts/k3s/templates/service.yaml
- charts/k3s/templates/statefulset-service.yaml
- charts/k8s/templates/api-service.yaml
- charts/k8s/templates/etcd-service.yaml
- charts/k8s/templates/etcd-statefulset-service.yaml
- charts/k8s/templates/syncer-service.yaml
> chore: add serviceAnnotations correctly

- pkg/server/filters/metrics.go
- pkg/server/filters/metrics_server.go
/kind bugfix
resolves ENG-1371 #1025 
Fixed an issue where vcluster metrics server proxy was not translating the label selectors
> Translate labelselectors metrics proxy

- pkg/server/server.go
> feat: add variable for setting additional filters in the syncer (proxy) server package

- docs/pages/fragments/deploy-vcluster.mdx
> docs: update deploy-vcluster.mdx - fix #1058

- charts/eks/templates/_helpers.tpl
- charts/k0s/templates/_helpers.tpl
- charts/k3s/templates/_helpers.tpl
- charts/k8s/templates/_helpers.tpl
resolves #1050
Few unused chart helper definitions were removed
> remove unused helper definitions

- cmd/vcluster/context/context.go
- pkg/server/server.go
- pkg/server/types/types.go
Improve code structure and allow for customizations.
N/A
> feat: refactor extra server filters and add original User to req context

- docs/pages/pro-features/admission-checks.mdx
- docs/sidebars.js
Added a documentation page about the "Admission checks" feature of vcluster.pro
> docs: add page about admission checks

- docs/pages/pro-features/central-hostpath-mapper.mdx
- docs/sidebars.js
resolves ENG-1551 add docs for vcluster.pro central hostpath mapper
adds docs for vcluster.pro central hostpath mapper
> add docs for central hostpath mapper

- docs/pages/pro-features/generic-resource-patches.mdx
- docs/pages/pro-features/integrated-coredns.mdx
- docs/sidebars.js
resolves ENG-1564
Added docs on how to use the generic resource patches feature of vcluster.pro
> docs: Generic Resource Patches

- pkg/config/config_test.go
- pkg/config/parse.go
/kind bugfix
resolves #1129
Fixed an issue where generic syncer patches were erroneously reported as invalid
> Add missing patch types to validator function

- .github/workflows/e2e.yaml
- cmd/vclusterctl/cmd/create.go
/kind bugfix
resolves #1134
Added QoL change regarding isolated mode and local exposing
> Do not expose local in isolated mode

- docs/pages/architecture/control_plane/control_plane.mdx
- docs/pages/syncer/other_resources/overview.mdx
- docs/pages/using-vclusters/access.mdx
- docs/pages/using-vclusters/backup-restore.mdx
- docs/pages/using-vclusters/kube-context.mdx
- docs/pages/using-vclusters/pausing-vcluster.mdx
- docs/sidebars.js
> Docs: using vclusters

- pkg/coredns/coredns.go
> fix: pin coredns to 1.10.1

- .goreleaser.yaml
> Removed v prefix from image name & removed unused archs

- .github/workflows/e2e.yaml
- .github/workflows/release.yaml
- .goreleaser.yaml
- Justfile
- hack/assets/main.go
> Fixed binary format and uploading missing files

- .github/workflows/e2e.yaml
- .github/workflows/release.yaml
> Added missing step in e2e action

- .github/workflows/release.yaml
- .goreleaser.yaml
> Changed back asset upload

- .goreleaser.yaml
- Justfile
> Fixed charts embedding

- .github/workflows/e2e.yaml
- pkg/constants/coredns.go
/kind test
resolves ENG-1856
Update the kind host cluster to `v1.27.3` for vcluster e2e setup
> update CI kind version and corresponding coredns version map

- docs/pages/o11y/metrics/metrics_server.mdx
- docs/pages/o11y/metrics/metrics_server_proxy.mdx
- docs/pages/o11y/metrics/monitoring_vcluster.mdx
> fix metrics to nodes links

- docs/pages/deploying-vclusters/high-availability.mdx
- docs/pages/deploying-vclusters/init-charts.mdx
- docs/pages/deploying-vclusters/init-manifests.mdx
- docs/pages/deploying-vclusters/integrations-openshift.mdx
- docs/pages/deploying-vclusters/persistence.mdx
- docs/pages/deploying-vclusters/supported-distros.mdx
- docs/sidebars.js
> Organise pages for Deploying vclusters section

- docs/pages/advanced-topics/plugins-development.mdx
- docs/pages/advanced-topics/plugins-overview.mdx
- docs/pages/advanced-topics/telemetry.mdx
- docs/sidebars.js
> Docs advanced topics

- docs/pages/community.mdx
- docs/pages/operator/security.mdx
- docs/pages/what-are-virtual-clusters.mdx
- docs/sidebars.js
> initial page for help and trouble shooting

- docs/pages/architecture/control_plane/isolated_control_planes.mdx
- docs/pages/networking/integrated_coredns.mdx
- docs/pages/o11y/logging/central_hpm.mdx
- docs/pages/syncer/generic_resource_patches.mdx
- docs/sidebars.js
> Add Pro Docs

- .github/workflows/e2e.yaml
- .github/workflows/release.yaml
> Switched to nightly goreleaser

- .github/workflows/e2e.yaml
- .github/workflows/lint.yaml
- .github/workflows/release.yaml
- .github/workflows/unit-tests.yaml
- go.mod
- go.sum
> Updated go to 1.21.0

- cmd/vclusterctl/cmd/find/find.go
- cmd/vclusterctl/cmd/list.go
Displays the vcluster version when executing `vcluster list`
Display vcluster version in vcluster list
> Show vcluster version in list

- .github/workflows/e2e.yaml
- .github/workflows/release.yaml
> Install goreleaser nightly from source in actions

- .github/workflows/e2e.yaml
- .github/workflows/release.yaml
> Pinned goreleaser to latest nightly

- pkg/server/server.go
> fix: fail on error in authentication

- charts/eks/values.yaml
resolves #1206
Updated vcluster-eks chart to 1.27-eks-11
> upd eks images to 1-27-eks-11

- charts/eks/templates/_helpers.tpl
- charts/eks/templates/coredns.yaml
- charts/eks/templates/integrated-coredns.yaml
- charts/eks/templates/pre-install-hook-job.yaml
- charts/eks/templates/rbac/clusterrole.yaml
- charts/eks/templates/rbac/role.yaml
- charts/eks/templates/syncer-deployment.yaml
- charts/eks/values.yaml
- charts/k0s/templates/_helpers.tpl
- charts/k0s/templates/coredns.yaml
- charts/k0s/templates/integrated-coredns.yaml
- charts/k0s/templates/rbac/clusterrole.yaml
- charts/k0s/templates/rbac/role.yaml
- charts/k0s/templates/statefulset.yaml
- charts/k0s/values.yaml
- charts/k3s/templates/_helpers.tpl
- charts/k3s/templates/coredns.yaml
- charts/k3s/templates/integrated-coredns.yaml
- charts/k3s/templates/rbac/clusterrole.yaml
- charts/k3s/templates/rbac/role.yaml
- charts/k3s/templates/statefulset.yaml
- charts/k3s/values.yaml
- charts/k8s/templates/_helpers.tpl
- charts/k8s/templates/coredns.yaml
- charts/k8s/templates/integrated-coredns.yaml
- charts/k8s/templates/pre-install-hook-job.yaml
- charts/k8s/templates/rbac/clusterrole.yaml
- charts/k8s/templates/rbac/role.yaml
- charts/k8s/templates/syncer-deployment.yaml
- charts/k8s/values.yaml
Includes vCluster.Pro chart changes into the main chart
> refactor: include vcluster.pro

- cmd/vclusterctl/cmd/app/create/pro.go
- cmd/vclusterctl/cmd/app/create/types.go
- cmd/vclusterctl/cmd/create.go
- cmd/vclusterctl/cmd/delete.go
- cmd/vclusterctl/cmd/find/find.go
- go.mod
- go.sum
- pkg/helm/helm.go
- pkg/pro/create.go
- vendor/github.com/loft-sh/loftctl/v3/cmd/loftctl/cmd/create/space.go
- vendor/github.com/loft-sh/loftctl/v3/cmd/loftctl/cmd/create/vcluster.go
- vendor/github.com/loft-sh/loftctl/v3/pkg/client/helper/helper.go
- vendor/modules.txt
> feat: allow vcluster pro via vcluster create & delete

- cmd/vclusterctl/cmd/root.go
- cmd/vclusterctl/cmd/ui.go
- go.mod
- go.sum
- vendor/github.com/loft-sh/loftctl/v3/cmd/loftctl/cmd/root.go
- vendor/github.com/loft-sh/loftctl/v3/cmd/loftctl/cmd/ui.go
- vendor/modules.txt
> Added UI command

- cmd/vclusterctl/cmd/find/find.go
- cmd/vclusterctl/cmd/list.go
resolves ENG-2085
Adds pro vcluster support to CLI
`Status` is based off the virtual cluster instance status and not the pod for pro
`Version` will require additional loading of pod resources, so have postponed that until confirmed it should be supported
> feat: vcluster list pro support

- cmd/vclusterctl/cmd/app/create/pro.go
- cmd/vclusterctl/cmd/connect.go
- cmd/vclusterctl/cmd/create.go
- cmd/vclusterctl/cmd/delete.go
- cmd/vclusterctl/cmd/disconnect.go
- cmd/vclusterctl/cmd/find/find.go
- cmd/vclusterctl/cmd/util.go
- test/framework/framework.go
> feat: add vcluster connect

- cmd/vclusterctl/cmd/create.go
- cmd/vclusterctl/cmd/delete.go
- cmd/vclusterctl/cmd/find/find.go
- cmd/vclusterctl/cmd/logout.go
- pkg/helm/helm.go
- pkg/pro/client.go
> refactor: usability improvements

- go.mod
- go.sum
- vendor/github.com/loft-sh/utils/pkg/helm/values/k0s.go
- vendor/github.com/loft-sh/utils/pkg/helm/values/k3s.go
- vendor/modules.txt
> Updated loft utils

- .github/workflows/e2e.yaml
- .github/workflows/release.yaml
> Switched back to latest version of goreleaser

- go.mod
- go.sum
- pkg/pro/version.go
- vendor/github.com/loft-sh/loftctl/v3/pkg/start/login.go
- vendor/github.com/loft-sh/loftctl/v3/pkg/start/success.go
- vendor/modules.txt
> refactor: update loftctl & bump vcluster.pro version

- go.mod
- go.sum
- vendor/github.com/loft-sh/loftctl/v3/pkg/start/login.go
- vendor/modules.txt
> refactor: update loftctl dependency

- cmd/vclusterctl/cmd/import.go
- cmd/vclusterctl/cmd/root.go
- pkg/util/compress/compress.go
> Add vcluster import command

- cmd/vclusterctl/cmd/app/create/pro.go
- go.mod
- go.sum
> chore: update loft api dependencies

- pkg/pro/create.go
- pkg/pro/version.go
> Updated pro subcomand to fetch most recent compatible version

- charts/eks/templates/syncer-deployment.yaml
- charts/k0s/templates/statefulset.yaml
- charts/k8s/templates/syncer-deployment.yaml
/kind bugfix
resolves ENG-2118
Fixed an issue where vcluster distros were missing the integrated coredns syncer flag
> add integrated coredns flag in syncer args

- cmd/vclusterctl/cmd/app/create/pro.go
> refactor: enable integrated coredns by default

- cmd/vclusterctl/cmd/find/find.go
- cmd/vclusterctl/cmd/import.go
- go.mod
- go.sum
- vendor/github.com/loft-sh/api/v3/pkg/apis/management/v1/project_importvirtualcluster_types.go
- vendor/github.com/loft-sh/api/v3/pkg/apis/management/v1/zz_generated.conversion.go
- vendor/github.com/loft-sh/api/v3/pkg/apis/management/zz_generated.api.register.go
- vendor/modules.txt
> Add --disable-upgrade flag for import cmd to not upgrade automatically

- pkg/controllers/resources/nodes/syncer.go
- pkg/controllers/resources/nodes/syncer_test.go
> Fixed node-syncer not requeuing after status update

- cmd/vclusterctl/cmd/login.go
- cmd/vclusterctl/cmd/pro/generate_kube_config.go
- cmd/vclusterctl/cmd/pro/pro.go
> feat: add vcluster pro generate-kube-config

- go.mod
- go.sum
- vendor/github.com/loft-sh/loftctl/v3/cmd/loftctl/cmd/login.go
- vendor/github.com/loft-sh/loftctl/v3/pkg/client/client.go
- vendor/modules.txt
> Updated loftctl to latest version

- cmd/vcluster/cmd/start.go
- pkg/controllers/resources/services/syncer.go
- pkg/controllers/resources/services/syncer_test.go
- pkg/specialservices/resolver.go
- pkg/specialservices/service_syncer.go
> refactor: sync kubernetes service

- pkg/controllers/resources/pods/translate.go
- pkg/specialservices/resolver.go
> refactor: allow dns namespace override

- docs/pages/community.mdx
- docs/pages/deploying-vclusters/high-availability.mdx
- docs/pages/help&tutorials/bootstrapping.mdx
- docs/pages/help&tutorials/helm-provisioning.mdx
- docs/pages/help&tutorials/troubleshooting.mdx
- docs/sidebars.js
modified HA page to provide explanatory walkthrough
resolves ENG-1988
/kind bugfix
/kind feature
/kind test
resolves #
> added tutorials for provisioning with Helm, bootstrapping vclusters

- charts/eks/templates/_helpers.tpl
- charts/eks/templates/syncer-deployment.yaml
- charts/eks/values.yaml
- charts/k0s/templates/_helpers.tpl
- charts/k0s/templates/statefulset.yaml
- charts/k0s/values.yaml
- charts/k3s/templates/_helpers.tpl
- charts/k3s/templates/statefulset.yaml
- charts/k3s/values.yaml
- charts/k8s/templates/_helpers.tpl
- charts/k8s/templates/syncer-deployment.yaml
- charts/k8s/values.yaml
/kind feature
resolves ENG-2167
Fixed an issue where vcluster coredns plugin related chart changes need to be added
> add coredns plugin to charts

- Dockerfile.cli.release
resolves ENG-2163
Added tools required for GitLab usage example
> build: add devspace, helm, and kubectl to the vcluster-cli image

- pkg/controllers/resources/nodes/fake_syncer.go
- pkg/controllers/resources/nodes/fake_syncer_test.go
- pkg/controllers/resources/nodes/syncer_test.go
- pkg/controllers/resources/nodes/translate.go
- test/e2e_node/node.go
> Revert "fix node labels syncing"

- pkg/controllers/generic/export_syncer.go
resolves ENG-1349
fixes #1018 
/kind bugfix
/kind feature
/kind test
resolves #
> fix: beta generic label selector is inverted

- hack/load-testing/README.md
- hack/load-testing/main.go
- hack/load-testing/tests/events/events.go
- hack/load-testing/tests/framework/framework.go
- hack/load-testing/tests/secrets/secrets.go
> chore: add basic performance tests

- charts/eks/templates/_helpers.tpl
- charts/eks/values.yaml
- charts/k0s/templates/_helpers.tpl
- charts/k0s/values.yaml
- charts/k3s/templates/_helpers.tpl
- charts/k3s/values.yaml
- charts/k8s/templates/_helpers.tpl
- charts/k8s/values.yaml
- cmd/vcluster/cmd/values/v1/base_values.go
- cmd/vcluster/cmd/values/v1/k8s_values.go
- cmd/vcluster/cmd/values/v1/values.go
- cmd/vcluster/cmd/values/v1/values_test.go
- pkg/telemetry/collect.go
- pkg/telemetry/types/types.go
/kind feature
resolves ENG-2132
Fixed an issue where vcluster helm chart values can be validated against a set of go struct values
> struct for mapping values

- README.md
Adding the "open in DevPod" button
Resolve ENG-1389
> chore: add open in DevPod button

- pkg/util/translate/multi_namespace.go
- pkg/util/translate/single_namespace.go
> refactor: make physical name reusable

- hack/load-testing/README.md
- hack/load-testing/tests/events/events.go
- hack/load-testing/tests/secrets/secrets.go
- pkg/controllers/resources/pods/translate/translator.go
> fix: concurrent map writes

- charts/k3s/templates/token-secret.yaml
- charts/k3s/values.yaml
- devspace.yaml
- pkg/config/helmvalues/base_values.go
> fix: allow custom k3s token

- cmd/vclusterctl/cmd/list.go
Added Cluster Name and Distro column to vcluster list output
Closes ENG-2154
> Add Cluster and Distro column to vcluster list output

- pkg/setup/controller_context.go
- pkg/setup/controllers.go
> refactor: make it easier to reuse setup package

- charts/eks/templates/etcd-statefulset.yaml
- charts/eks/values.yaml
- charts/k0s/templates/statefulset.yaml
- charts/k0s/values.yaml
- charts/k3s/templates/statefulset-service.yaml
- charts/k3s/templates/statefulset.yaml
- charts/k3s/values.yaml
- charts/k8s/templates/etcd-statefulset.yaml
- charts/k8s/values.yaml
- pkg/config/helmvalues/k0s.go
- pkg/config/helmvalues/k3s.go
- pkg/config/helmvalues/k8s.go
> feat: add autoDeletePersistentVolumeClaims

- pkg/certs/ensure.go
> refactor: add embedded etcd server sans

- charts/k3s/templates/statefulset.yaml
- pkg/certs/ensure.go
> refactor: add localhost / 127.0.0.1 to cert sans

- charts/k3s/templates/rbac/role.yaml
- charts/k3s/templates/statefulset.yaml
- charts/k3s/values.yaml
- pkg/certs/ensure.go
- pkg/setup/initialize.go
> refactor: remove enableHA for k3s

- pkg/constants/indices.go
- pkg/controllers/coredns/nodehosts.go
- pkg/controllers/k8sdefaultendpoint/k8sdefaultendpoint.go
- pkg/controllers/manifests/init.go
- pkg/controllers/podsecurity/podsecurity.go
- pkg/controllers/register.go
- pkg/controllers/servicesync/servicesync.go
- pkg/controllers/syncer/fake_syncer.go
- pkg/controllers/syncer/syncer.go
> refactor: remove init configmap manager & default sync timeout

- charts/k3s/values.yaml
> refactor: disable egress selector mode

- pkg/controllers/manifests/init.go
> refactor: remove init manifests debug statement

- charts/eks/templates/etcd-statefulset.yaml
- charts/k0s/templates/statefulset.yaml
- charts/k3s/templates/statefulset.yaml
- charts/k8s/templates/etcd-statefulset.yaml
> refactor: remove whenScaled: Delete

- .github/workflows/e2e.yaml
- Dockerfile
- charts/k3s/templates/statefulset.yaml
- pkg/k3s/k3s.go
- test/e2e_target_namespace/role.yaml
- test/e2e_target_namespace/targetNamespace.go
> fix: k3s migration

- charts/eks/values.yaml
- charts/k0s/values.yaml
- charts/k3s/values.yaml
- charts/k8s/values.yaml
comments in helm values file changed and tested
resolves #1349 
> fix: incorrect example chart values.yaml

- docs/pages/o11y/metrics/monitoring_vcluster.mdx
- docs/pages/security/other-topics.mdx
- docs/pages/storage.mdx
- docs/pages/syncer/config.mdx
- docs/pages/syncer/core_resources.mdx
- docs/pages/using-vclusters/access.mdx
> docs: fix typos

- .github/workflows/e2e.yaml
> test: only deploy metrics proxy if needed

- pkg/controllers/resources/pods/translate/sa_token_secret.go
> fix: delete sa token if already exists

- charts/k3s/values.yaml
> refactor: remove memory limits on vcluster syncer

- charts/eks/templates/service-monitor.yaml
- charts/eks/values.yaml
- charts/k0s/templates/service-monitor.yaml
- charts/k0s/values.yaml
- charts/k3s/templates/service-monitor.yaml
- charts/k3s/values.yaml
- charts/k8s/templates/service-monitor.yaml
- charts/k8s/values.yaml
/kind feature
resolves ENG-2402
added option to deploy a service monitor next to the vcluster
> feat: added service monitor to the chart

- docs/pages/what-are-virtual-clusters.mdx
Updates to wording and capitalizing vCluster
Updated wording and capitalization within the What are Virtual Clusters documentation.
> Few updates to wording and capitalizing vCluster

- docs/sidebars.js
Updates the sidebar to use the new capitalization of vCluster
> Updated vCluster capitalization in the sidebar

- pkg/config/helmvalues/k3s.go
> chore: add monitoring values

- docs/pages/architecture/overview.mdx
Fixes the spelling of vCluster and updates some of the wording in the Overview page.
Updated wording and spelling of vCluster in overview.mdx
> Updated wording in overview and updated spelling of vCluster

- docs/pages/networking/coreDNS.mdx
Updated wording in the coreDNS.mdx file
docs: updated wording in the coreDNS.mdx file
> Updated wording in coreDNS.mdx

- .github/workflows/e2e.yaml
- test/values_ha.yaml
/kind test
resolves #eng-2438
added e2e testing for ha setup
> feat: added testing for ha

- pkg/k3s/k3s.go
improved flow of ifs in ensureK3sToken
> simplified flow in ensureK3sToken

- pkg/certs/ensure.go
- pkg/setup/initialize.go
> refactor: allow api suffix for certs

- charts/eks/values.yaml
- charts/k0s/values.yaml
- charts/k3s/values.yaml
- charts/k8s/values.yaml
/kind bugfix
resolves ENG-2416
Fixed an issue where vcluster under isolation mode and very less limitrange set for `ephemeral-storage` would crash
> set default ephemeral storage for the syncer container

- pkg/telemetry/collect.go
- pkg/telemetry/types.go
> refactor: allow string for telemetry disable

- docs/pages/security/isolated-mode.mdx
updates warn to warning in the warning note
updates warn to warning in the warning note for isolated-mode docs
> updated warn to warning in warning note

- cmd/vclusterctl/cmd/app/create/pro.go
- cmd/vclusterctl/cmd/app/create/types.go
- cmd/vclusterctl/cmd/create.go
- docs/pages/cli/vcluster_create.md
- docs/pages/cli/vcluster_delete.md
/kind feature
resolves ENG-2356
[PRO] Allow setting labels/annotations to the CRD from the cli 
> feat: allow setting labels and annotations via cli flags

- .github/workflows/unit-tests.yaml
/kind bugfix
resolves issue where unittests are not executed in case the changes are only in charts
> execute unittest for chart changes

- charts/eks/templates/syncer-deployment.yaml
- charts/eks/values.yaml
- charts/k0s/templates/statefulset.yaml
- charts/k0s/values.yaml
- charts/k3s/templates/statefulset.yaml
- charts/k3s/values.yaml
- charts/k8s/templates/syncer-deployment.yaml
- charts/k8s/values.yaml
- pkg/config/helmvalues/k3s.go
/kind feature
part of eng-2316
added the options for admission hook syncing
> added admission options to helm

- pkg/constants/distro.go
- pkg/controllers/k8sdefaultendpoint/k8sdefaultendpoint.go
- pkg/controllers/resources/pods/syncer_test.go
- pkg/metricsapiservice/register.go
- pkg/server/cert/syncer.go
- pkg/setup/initialize.go
- pkg/setup/options/flags.go
- pkg/setup/options/options.go
- pkg/specialservices/resolver.go
> refactor: determine distro by binary

- cmd/vclusterctl/cmd/create.go
- docs/pages/deploying-vclusters/supported-distros.mdx
- pkg/util/servicecidr/servicecidr.go
/kind bugfix
resolves eng-2549
Fixed an issue where vcluster would crash if k0s was running on dualstack host cluster
> disabled dualstack for k0s

- .github/workflows/e2e.yaml
- charts/k8s/values.yaml
- pkg/values/k8s.go
/kind feature
/kind test
resolves ENG-2571
> bump k8s to 1.29 and kind to 1.28

- cmd/vclusterctl/cmd/find/find.go
> fix: show pro vclusters if not logged in

- charts/k0s/templates/secret.yaml
- charts/k0s/templates/statefulset.yaml
- charts/k0s/values.yaml
- pkg/util/servicecidr/servicecidr.go
resolves eng-2582
Fixed an issue where k0s config wasn't updated in time when updating the secret
> now writes the config to disk to avoid race condition with secret update

- charts/k0s/values.yaml
- charts/k3s/values.yaml
> fix: increase limits for init containers

- cmd/vcluster/cmd/cp.go
- cmd/vcluster/cmd/root.go
- pkg/util/cp/cp.go
/kind feature
part of eng-2540
added cp subcommand as some distroless containers don't let us copy from them without a fat binary
> added the cp subcommand

- pkg/util/cp/cp.go
part of eng-2540
improves cp by not needing to read the whole file in memory 
> now cp doesn't read the whole file in memory

- charts/eks/templates/syncer-service.yaml
- charts/k0s/templates/service.yaml
- charts/k3s/templates/service.yaml
- charts/k8s/templates/syncer-service.yaml
> feat: add node port config

- charts/eks/templates/etcd-statefulset.yaml
- charts/eks/templates/syncer-deployment.yaml
- charts/k0s/templates/statefulset.yaml
- charts/k3s/templates/statefulset.yaml
- charts/k8s/templates/etcd-statefulset.yaml
- charts/k8s/templates/syncer-deployment.yaml
> fix: wrong volumes check

- pkg/setup/controller_context.go
- pkg/setup/controllers.go
- pkg/util/kubeconfig/kubeconfig.go
> refactor: add isRemote to WriteKubeConfigToSecret

- charts/eks/templates/rbac/clusterrole.yaml
- charts/k0s/templates/rbac/clusterrole.yaml
- charts/k3s/templates/rbac/clusterrole.yaml
- charts/k8s/templates/rbac/clusterrole.yaml
- pkg/server/cert/syncer.go
> refactor: allow extra sans

- charts/eks/templates/syncer-deployment.yaml
- charts/k8s/templates/syncer-deployment.yaml
- charts/k8s/values.yaml
- pkg/config/helmvalues/k8s.go
- pkg/constants/distro.go
- pkg/controllers/k8sdefaultendpoint/k8sdefaultendpoint.go
- pkg/metricsapiservice/register.go
- pkg/server/cert/cert.go
- pkg/server/cert/syncer.go
- pkg/setup/initialize.go
- pkg/specialservices/resolver.go
> remove special cases for setup with k8s 

- .github/workflows/go-licenses.yaml
/kind bugfix
/kind feature
/kind test
resolves #
> ci(licenses): Fixed branch name trigger

- .github/workflows/go-licenses-check.yaml
ref ENG-2639
Runs go-licenses check whenever something in the go.mod changes.
> license(check): Added license check on dependency changes

- charts/eks/templates/syncer-deployment.yaml
- charts/k0s/templates/statefulset.yaml
- charts/k0s/values.yaml
- charts/k3s/templates/statefulset.yaml
- charts/k3s/values.yaml
- charts/k8s/templates/syncer-deployment.yaml
- pkg/constants/distro.go
part of eng-2649
changed the distro detection mechanism
> changed distro detection

- charts/eks/templates/syncer-service.yaml
- charts/eks/values.yaml
- charts/k0s/templates/service.yaml
- charts/k0s/values.yaml
- charts/k3s/templates/service.yaml
- charts/k3s/values.yaml
- charts/k8s/templates/syncer-service.yaml
- charts/k8s/values.yaml
- pkg/config/helmvalues/k3s.go
resolves #1425 
I added the `service.loadBalancerAnnotations` field to helm charts to be able to add load-balancer-specific annotations.
> feat(helm): Added field to specify dedicated loadbalancer annotations

- pkg/plugin/v2/grpc.go
- pkg/plugin/v2/plugin.go
- pkg/types/types.go
> fix: plugin v2 problems

- cmd/vclusterctl/cmd/info.go
- cmd/vclusterctl/cmd/root.go
/kind feature
resolves eng-2693
adds a new command to display relevant infos about cli and platform
> added cli info command

- Dockerfile
- Dockerfile.cli
- Dockerfile.release
- pkg/constants/container.go
- pkg/controllers/resources/volumesnapshots/volumesnapshotclasses/crd.go
- pkg/controllers/resources/volumesnapshots/volumesnapshotclasses/syncer.go
- pkg/controllers/resources/volumesnapshots/volumesnapshotcontents/crd.go
- pkg/controllers/resources/volumesnapshots/volumesnapshotcontents/syncer.go
- pkg/controllers/resources/volumesnapshots/volumesnapshots/crd.go
- pkg/controllers/resources/volumesnapshots/volumesnapshots/syncer.go
- pkg/coredns/coredns.go
- pkg/util/crds.go
> refactor: remove manifests

- .goreleaser.yaml
> build: remove manifests from goreleaser

- charts/eks/templates/syncer.yaml
- charts/k8s/templates/syncer.yaml
- pkg/k8s/k8s.go
- pkg/setup/initialize.go
- pkg/util/servicecidr/servicecidr.go
/kind bugfix
resolves eng-2717 
Fixed an issue where vcluster wouldn't start without a cidr param, instead of inferring it 
> fix serviceCIDR bug

- cmd/vcluster/cmd/start.go
- pkg/plugin/plugin.go
- pkg/plugin/v2/config.go
- pkg/plugin/v2/plugin.go
- pkg/setup/controller_context.go
- pkg/setup/controllers.go
- pkg/setup/initialize.go
> refactor: controller context

- pkg/etcd/util.go
- pkg/k8s/k8s.go
- pkg/setup/initialize.go
> refactor: improve startup

- pkg/metricsapiservice/register.go
- pkg/server/filters/metrics_server.go
> fix: metrics server

- charts/eks/templates/syncer.yaml
- charts/eks/tests/syncer_test.yaml
- charts/k8s/templates/syncer.yaml
- charts/k8s/tests/syncer_test.yaml
> added volume mount

- charts/k3s/templates/syncer.yaml
> migrated all replicas to new format

- pkg/plugin/v2/plugin.go
- pkg/util/pluginhookclient/client.go
> fix: plugin v2 hooks

- charts/eks/templates/rbac/clusterrole.yaml
- charts/k0s/templates/rbac/clusterrole.yaml
- charts/k3s/templates/rbac/clusterrole.yaml
- charts/k8s/templates/rbac/clusterrole.yaml
- pkg/controllers/servicesync/servicesync.go
- test/commonValues.yaml
- test/e2e/servicesync/servicesync.go
- test/e2e_rootless/values.yaml
/kind bugfix
resolves #1401 
Fixed an issue where vcluster would not sync endpoint updates for headless services
Closes ENG-2533
> Sync endpoint updates for service mappings of headless services

- charts/eks/values.yaml
- charts/k0s/values.yaml
- charts/k3s/values.yaml
- charts/k8s/values.yaml
part of eng-2694
changes the default for autodeletepvc 
> changed the default to not delete the persistent volume claim

- docs/pages/plugins/overview.mdx
- docs/pages/plugins/tutorial.mdx
> docs: update plugin docs

- charts/k0s/templates/syncer.yaml
- charts/k0s/tests/syncer.yaml
- charts/k3s/templates/syncer.yaml
- charts/k3s/tests/syncer.yaml
/kind bugfix
resolves #1491
Fixed an issue where vcluster would create pvcs even with persistence disabled
> fixed #1491

- charts/eks/templates/etcd-service.yaml
- charts/eks/templates/etcd-statefulset-service.yaml
- charts/eks/templates/etcd-statefulset.yaml
- charts/eks/templates/syncer.yaml
- charts/eks/values.yaml
- charts/k8s/templates/etcd-service.yaml
- charts/k8s/templates/etcd-statefulset-service.yaml
- charts/k8s/templates/etcd-statefulset.yaml
- charts/k8s/templates/syncer.yaml
- charts/k8s/values.yaml
- go.mod
- go.sum
- vendor/github.com/loft-sh/vcluster-values/helmvalues/k3s.go
- vendor/github.com/loft-sh/vcluster-values/helmvalues/k8s.go
- vendor/modules.txt
/kind feature
part of eng-2648
preparation work for the migration feature
> helm changes to enable migration of etcd

- pkg/controllers/generic/import_syncer.go
- pkg/controllers/resources/csistoragecapacities/syncer.go
- pkg/controllers/resources/csistoragecapacities/translator.go
- pkg/controllers/resources/events/syncer.go
- pkg/controllers/resources/nodes/syncer.go
- pkg/controllers/resources/persistentvolumes/syncer.go
- pkg/controllers/resources/volumesnapshots/volumesnapshotcontents/syncer.go
- pkg/controllers/syncer/syncer.go
- pkg/controllers/syncer/translator/cluster_translator.go
- pkg/controllers/syncer/translator/mirror_name_translator.go
- pkg/controllers/syncer/translator/namespaced_translator.go
- pkg/controllers/syncer/translator/translator.go
- pkg/types/types.go
> refactor: add syncer watch on host

- pkg/k0s/k0s.go
- pkg/k3s/k3s.go
- pkg/k8s/k8s.go
- pkg/util/commandwriter/commandwriter.go
- pkg/util/ringbuffer/ringbuffer.go
- pkg/util/translate/multi_namespace.go
- pkg/util/translate/types.go
> refactor: show vcluster only in debug

- charts/eks/templates/syncer.yaml
- charts/k8s/templates/syncer.yaml
/kind bugfix
part-of  eng-2648
> fixed a typo

- pkg/controllers/resources/events/syncer.go
- pkg/controllers/resources/events/syncer_test.go
> refactor: events controller

- cmd/vclusterctl/cmd/telemetry/disable.go
- cmd/vclusterctl/cmd/telemetry/enable.go
- cmd/vclusterctl/cmd/telemetry/telemetry.go
- docs/pages/cli/vcluster_telemetry.md
- docs/pages/cli/vcluster_telemetry_disable.md
- docs/pages/cli/vcluster_telemetry_enable.md
> Update docs link for telemetry section

- docs/pages/advanced-topics/plugins-development.mdx
- docs/pages/plugins/tutorial.mdx
- pkg/controllers/resources/configmaps/syncer.go
- pkg/controllers/resources/endpoints/syncer.go
- pkg/controllers/resources/ingresses/legacy/syncer.go
- pkg/controllers/resources/ingresses/syncer.go
- pkg/controllers/resources/networkpolicies/syncer.go
- pkg/controllers/resources/persistentvolumeclaims/syncer.go
- pkg/controllers/resources/poddisruptionbudgets/syncer.go
- pkg/controllers/resources/pods/syncer.go
- pkg/controllers/resources/secrets/syncer.go
- pkg/controllers/resources/serviceaccounts/syncer.go
- pkg/controllers/resources/services/syncer.go
- pkg/controllers/resources/volumesnapshots/volumesnapshots/syncer.go
- pkg/controllers/syncer/syncer_test.go
- pkg/controllers/syncer/translator/namespaced_translator.go
- pkg/controllers/syncer/translator/translator.go
> refactor: rename syncdown

- test/e2e_plugin/plugin.go
- test/e2e_plugin/values.yaml
> test: add plugin e2e test

- charts/eks/templates/_coredns.tpl
- charts/eks/values.yaml
- charts/k0s/templates/_coredns.tpl
- charts/k0s/values.yaml
- charts/k3s/templates/_coredns.tpl
- charts/k3s/values.yaml
- charts/k8s/templates/_coredns.tpl
- charts/k8s/values.yaml
- go.mod
- go.sum
- vendor/github.com/loft-sh/vcluster-values/helmvalues/common.go
- vendor/modules.txt
/kind feature
resolves eng-2558
resolves #1406
Fixed an issue where vcluster would fallback to 8.8.8.8 in isolated mode without any way to configure it
> added coredns.fallback parameter

- go.mod
- go.sum
- vendor/github.com/loft-sh/analytics-client/client/client.go
- vendor/modules.txt
/kind bugfix
resolves eng-2767
Fixed an issue where vcluster would be waiting forever if the analytics server didn't answer
> updated analytics client lib

- charts/eks/values.yaml
- charts/k0s/values.yaml
- charts/k3s/values.yaml
- charts/k8s/values.yaml
> chore: improve coredns values

- charts/eks/templates/syncer.yaml
- charts/eks/values.yaml
- charts/k0s/templates/syncer.yaml
- charts/k0s/values.yaml
- charts/k3s/templates/syncer.yaml
- charts/k3s/values.yaml
- charts/k8s/templates/syncer.yaml
- charts/k8s/values.yaml
- go.mod
- go.sum
- vendor/github.com/loft-sh/vcluster-values/helmvalues/common.go
- vendor/github.com/loft-sh/vcluster-values/helmvalues/k0s.go
- vendor/modules.txt
> central admission slight refactor

- charts/k0s/templates/syncer.yaml
> fix: request-head-ca-cert for k0s

- charts/k0s/templates/secret.yaml
- charts/k0s/templates/statefulset-service.yaml
- charts/k0s/templates/syncer.yaml
- charts/k0s/values.yaml
- cmd/vclusterctl/cmd/get/service_cidr.go
- cmd/vclusterctl/cmd/telemetry/disable.go
- cmd/vclusterctl/cmd/telemetry/enable.go
- pkg/certs/constants.go
- pkg/certs/ensure.go
- pkg/controllers/coredns/nodehosts.go
- pkg/controllers/resources/priorityclasses/syncer.go
- pkg/k0s/k0s.go
- pkg/server/filters/k3s_connect.go
- pkg/setup/initialize.go
- pkg/util/crds.go
- pkg/util/translate/multi_namespace.go
- pkg/util/translate/single_namespace.go
/kind feature
part of eng-2695
added support for embedded Etcd in k0s
> added support for embedded etcd

- charts/k0s/templates/secret.yaml
> K0s fix secret

- pkg/controllers/resources/events/syncer.go
> fix: event syncer problem

- .github/workflows/lint.yaml
> trying a temporary fix for the CI failurs

- docs/pages/deploying-vclusters/high-availability.mdx
> updated the docs for HA

- docs/pages/deploying-vclusters/supported-distros.mdx
- docs/pages/fragments/high-availability-k8s.mdx
> removed controller and api replicas references

- cmd/vclusterctl/cmd/list.go
/kind bugfix
resolves eng-2862 and #1546 
> now uses the context for list

- .github/workflows/compatibility.yaml
- Justfile
- docs/pages/deploying-vclusters/compat-matrix.mdx
- docs/pages/deploying-vclusters/supported-distros.mdx
- docs/sidebars.js
- go.mod
- hack/compat-matrix/main.go
- hack/compat-matrix/matrix-template.tmpl
- known_issues.yaml
- vendor/modules.txt
> Version auto update

- docs/pages/deploying-vclusters/compat-matrix.mdx
- hack/compat-matrix/main.go
- hack/compat-matrix/matrix-template.tmpl
resolves eng-2754
updated the docs
> rephrased the compat matrix description

- docs/pages/advanced-topics/telemetry.mdx
resolves eng-2818
added infos on telemetry in the docs 
> added docs about telemetry data

- docs/pages/syncer/other_resources/generic_sync.mdx
- docs/pages/using-vclusters/access.mdx
- docs/pages/using-vclusters/kube-context.mdx
- docs/src/css/custom.css
Adds videos to documentation
Added videos to documentation for users who want to see a demo / video of the same content
Adding video demo / tutorials to documentation
> Added vCluster Tips videos to the appropriate documentation pages

- cmd/vclusterctl/cmd/pro/pro.go
- cmd/vclusterctl/cmd/pro/token.go
> feat(pro): Added token command

- docs/README.md
Add a note about appending `docs/` to Netlify's generated deploy preview link so you can preview your changes.
> Docs: Update README with note about deploy preview link

- docs/pages/deploying-vclusters/compat-matrix.mdx
- hack/compat-matrix/main.go
> fix: don't format compat matrix headers

- charts/k0s/templates/syncer.yaml
/kind bugfix
resolves #1562 
k0s: setting resources for vcluster initContainer
> fix(helm): resources not embedded in initContainer for k0s

- charts/eks/values.yaml
- charts/k8s/values.yaml
> added defaults for k8s to run the syncer as root, to follow k3s

- charts/eks/templates/syncer.yaml
- charts/k8s/templates/syncer.yaml
resolves eng-2926
we can now set limits for init containers 
> added resources for eks and k8s

- .github/workflows/e2e.yaml
- .github/workflows/release.yaml
- .github/workflows/unit-tests.yaml
- Dockerfile
- Dockerfile.cli
- charts/eks/templates/syncer.yaml
- charts/k0s/templates/syncer.yaml
- charts/k3s/templates/syncer.yaml
- charts/k8s/templates/syncer.yaml
> refactor: add startup probes

- docs/pages/advanced-topics/plugins-overview.mdx
> docs: improve plugin example

- chart/values.schema.json
> chore: bump values schema

- .github/workflows/e2e.yaml
- chart/values.schema.json
- pkg/controllers/deploy/start.go
> fix: only apply deploy config once

- .github/workflows/sync-config.yaml
> build: update sync-config.yaml

- pkg/controllers/resources/nodes/fake_syncer.go
- pkg/controllers/resources/nodes/syncer.go
- pkg/controllers/resources/nodes/syncer_test.go
- pkg/controllers/syncer/syncer.go
- pkg/controllers/syncer/syncer_test.go
> fix: delete unused nodes correctly

- pkg/controllers/resources/endpoints/syncer.go
- pkg/controllers/resources/endpoints/syncer_test.go
/kind bugfix
resolves ENG-3092
> fix: override endpoints if service selector is empty

- docs/pages/o11y/logging/hpm.mdx
Fixes broken documentation
Update hpm docs with correct helm command to install vcluster-hpm
Thanks for building vcluster!
> docs: fix helm install command

- .github/workflows/e2e.yaml
- .github/workflows/lint.yaml
- .github/workflows/unit-tests.yaml
- charts/k0s/templates/_storage.tpl
- charts/k3s/templates/_storage.tpl
- charts/k3s/tests/syncer_test.yaml
> fix: check for storage persistence

- .github/workflows/release.yaml
> build: remove hardcoded cosign

- docs/pages/deploying-vclusters/high-availability.mdx
- docs/pages/deploying-vclusters/persistence.mdx
- docs/pages/fragments/high-availability-k3s.mdx
> Fix remaining reference to top level storage: config

- docs/pages/deploying-vclusters/high-availability.mdx
- docs/pages/deploying-vclusters/persistence.mdx
- docs/pages/fragments/high-availability-k3s.mdx
> Fix storage config docs that referenced old yaml structure

- pkg/pro/external_database.go
> refactor: make function replaceable

- docs/pages/cli/vcluster_create.md
- docs/pages/cli/vcluster_delete.md
> Regenerate CLI docs

- docs/pages/cli/vcluster_pro_connect.md
- docs/pages/cli/vcluster_pro_connect_cluster.md
- docs/pages/cli/vcluster_pro_token.md
These files have been missing from the PR before
> Files missing from CLI docs regen

- Justfile
> Added build target to generate schema

- chart/templates/_backingstore.tpl
- chart/tests/headless-service_test.yaml
- chart/tests/statefulset_test.yaml
- chart/values.schema.json
- chart/values.yaml
- config/config.go
- config/values.yaml
- pkg/k0s/k0s.go
- test/e2e/k8sdefaultendpoint/k8sdefaultendpoint.go
- test/e2e/manifests/chart.go
- test/e2e/servicesync/servicesync.go
> refactor: rename embeddedSqlite to embedded

- docs/pages/o11y/metrics/monitoring_vcluster.mdx
Added an info section, suggesting required helm values for scraping kubelet targets in Isolated mode
Closes ENG-3194
> docs: suggest required helm values for scraping kubelet targets in Isolated mode

- pkg/controllers/resources/pods/translate/translator.go
- pkg/controllers/resources/pods/translate/translator_test.go
/kind bugfix
part-of ENG-2759
fixes https://github.com/loft-sh/vcluster/issues/1484 
Fixed an issue where vcluster mistranslated affinity terms.
> [Backport] fix: affinity label-selector overriden by namespace selector

- docs/pages/help&tutorials/helm-provisioning.mdx
/kind bugfix
resolves #
Found another one. This had `blob` rather than `tree` so I did not find it initially 🙈 
> Fix another chart reference

- chart/values.yaml
- config/values.yaml
/kind bugfix
resolves #
Fixes comment about the default distro.
> Fix comment about default distro

- cmd/vclusterctl/cmd/app/create/pro.go
- cmd/vclusterctl/cmd/create.go
- config/default_extra_values.go
- pkg/controllers/resources/configmaps/syncer.go
- pkg/controllers/resources/configmaps/translate.go
- pkg/controllers/resources/configmaps/util.go
- pkg/controllers/resources/pods/syncer.go
- pkg/controllers/resources/pods/translate/translator.go
- pkg/controllers/syncer/translator/namespaced_translator.go
- pkg/controllers/syncer/translator/translator.go
> refactor: make distro optional for default values

- chart/values.schema.json
- chart/values.yaml
- config/config.go
- config/values.yaml
- hack/schema/main.go
- pkg/config/legacyconfig/config.go
> chore: generate values.yaml comments

- pkg/controllers/resources/configmaps/syncer.go
- pkg/controllers/syncer/syncer.go
- pkg/controllers/syncer/syncer_test.go
- pkg/plugin/v2/plugin.go
- pkg/util/translate/multi_namespace.go
> fix: multi-namespace mode configmap sync

- pkg/plugin/v2/config.go
- pkg/plugin/v2/interceptor_test.go
- pkg/plugin/v2/plugin.go
resolves #
removed handler name from interception rules 
> replaced handlername with interceptor wide name

- .goreleaser.yaml
- chart/templates/_helper.tpl
- chart/values.schema.json
- chart/values.yaml
- config/config.go
- config/values.yaml
- pkg/config/legacyconfig/migrate.go
> build: release ghcr.io/loft-sh/vcluster-oss

- cmd/vclusterctl/cmd/app/localkubernetes/configure.go
- cmd/vclusterctl/cmd/app/localkubernetes/localkubernetes.go
- cmd/vclusterctl/cmd/connect.go
- pkg/util/clihelper/clihelper.go
Fixes an issue where `vcluster create` would print an unexpected error
Added support for orbstack to use direct connection
> Fix vcluster create & support orbstack for direct connection

- cmd/vclusterctl/cmd/create.go
- cmd/vclusterctl/cmd/delete.go
- pkg/util/clihelper/clihelper.go
Related to https://github.com/loft-sh/vcluster/issues/1654
> chore: adjust helm version check to be more explicit

- chart/values.schema.json
- config/config.go
/kind bugfix
resolves #ENG-3269
Fixes an issue that the config.go did not indicate the pro features which allows for the schema to be used in docs to generate which features are pro.
> Add product:pro to all pro features in config.go

- pkg/controllers/k8sdefaultendpoint/k8sdefaultendpoint.go
> fix: unhandled error in endpoints sync

- cmd/vclusterctl/cmd/import.go
- cmd/vclusterctl/cmd/login.go
- cmd/vclusterctl/cmd/logout.go
- cmd/vclusterctl/cmd/ui.go
> chore: prevent certain pro commands from executing with v0.20

- chart/values.schema.json
- config/config.go
> Update pro flags in config.go

- pkg/config/legacyconfig/migrate.go
- pkg/config/legacyconfig/migrate_test.go
> fix: migrate sync ingresses correctly

- cmd/vclusterctl/cmd/create.go
> fix: migrate command name has changed

- .gitignore
> fix: rename embed chart

- pkg/server/server.go
part of eng-2922
improved interception flow 
> moved the interceptor to after authz so plugins don't have to do it themselves

- cmd/vcluster/cmd/start.go
- pkg/pro/platform.go
/kind bugfix
/kind feature
/kind test
resolves #
> refactor(platform): Remove unnecessary platform params

- .github/workflows/sync-config.yaml
resolves #
Fixed an issue where vcluster was imported as transitive dependency when using vcluster-config.
> fix: replace vcluster/config with vcluster-config/config when syncing

- chart/templates/_rbac.tpl
- chart/templates/clusterrole.yaml
- chart/tests/clusterrole_test.yaml
- cmd/vclusterctl/cmd/login.go
- pkg/setup/proxy.go
> Isolated control plane fix & --use-manager

- CONTRIBUTING.md
- Dockerfile
- devspace_start.sh
Updated based on comments in #1713.
@facchettos - I don't know if everyone else uses the `just build-snapshot`, which is why I didn't make your changes. 
@heiko-braun - I've created a branch in this repo so you an push changes.
> Contributing guide

- docs/docusaurus.config.js
resolves DOC-52
Remove docs search bar since the legacy docs search doesn't work as expected.
https://deploy-preview-1732--vcluster-docs.netlify.app/docs/v0.19/what-are-virtual-clusters
> DOC-52 Remove site search

- cmd/vclusterctl/cmd/create.go
resolves ENG-3441
Deprecate distro flag in vcluster create, as the distro is now configurable via values.yaml
> chore: deprecate distro flag in vcluster create

- cmd/vcluster/cmd/start.go
- devspace.yaml
- pkg/pro/platform.go
- pkg/scheme/scheme.go
> fix: Updated ConnectToPlatform function signature

- cmd/vclusterctl/cmd/activate.go
- pkg/cli/activate_helm.go
- pkg/cli/activate_platform.go
- pkg/cli/create_helm.go
- pkg/platform/secret.go
/kind bugfix
Fixed an issue where the vCluster name was not set correctly and therefore the platform secret was not named correctly
> fix: set import-name correctly

- pkg/pro/controllers.go
- pkg/setup/controllers.go
/kind feature
part of ENG-3625
> feat(pro): Added controller registration

- go.mod
- go.sum
- pkg/cli/connect_platform.go
- pkg/cli/create_platform.go
- pkg/cli/delete_platform.go
- pkg/cli/list_platform.go
- pkg/cli/pause_platform.go
- pkg/cli/resume_platform.go
- vendor/github.com/loft-sh/loftctl/v3/cmd/loftctl/cmd/devpod/up.go
- vendor/github.com/loft-sh/loftctl/v3/cmd/loftctl/cmd/use/cluster.go
- vendor/github.com/loft-sh/loftctl/v3/cmd/loftctl/cmd/use/vcluster.go
- vendor/modules.txt
/kind bugfix
resolves ENG-3621
Fixed an issue where vcluster was not handling agentless virtual clusters correctly
> fix: handle helm created vclusters correctly

- CONTRIBUTING.md
- assets/push-images.sh
- chart/templates/_helper.tpl
- chart/templates/_init-containers.tpl
- chart/templates/_plugin.tpl
- chart/templates/coredns-configmap.yaml
- chart/templates/etcd-statefulset.yaml
- chart/tests/etcd-statefulset_test.yaml
- chart/tests/statefulset_test.yaml
- chart/values.schema.json
- chart/values.yaml
- config/config.go
- config/legacyconfig/migrate.go
- config/legacyconfig/migrate_test.go
- config/values.yaml
- devspace.yaml
- pkg/controllers/resources/pods/translate/hosts.go
- pkg/coredns/coredns.go
- test/commonValues.yaml
> refactor: add image.registry to configure registry separately

- pkg/cli/delete_helm.go
> feat: delete vCluster instance on helm delete

- config/default_extra_values.go
- config/legacyconfig/migrate.go
- pkg/cli/create_helm.go
- pkg/cli/create_platform.go
> fix: vcluster create merge values & default values

- .github/workflows/e2e.yaml
- config/config.go
- pkg/cli/create_helm.go
- pkg/cli/create_platform.go
- pkg/setup/config.go
resolves ENG-3435
Add checks that prevent disallowed changes to currently running virtual clusters.
> Prevent distro store switch vclusterctl

- cmd/vclusterctl/cmd/platform/connect/cluster.go
> feat: add --insecure flag to connect cluster

- pkg/config/parse.go
> fix: vcluster start --set

- pkg/cli/create_helm.go
> fixed a var shadowing issue that cause nil pointer when creating from helm 

- cmd/vclusterctl/cmd/platform/platform.go
/kind bugfix
resolves #
Fixed an issue where vcluster would print a wrong deprecation message.
> chore(vclustectl): do not print deprecated for platform cmd

- chart/values.yaml
- config/values.yaml
> refactor: add syncLabels

- cmd/vclusterctl/cmd/platform/connect/cluster.go
> fix: Add kube context to helm install command

- cmd/vclusterctl/cmd/platform/connect/cluster.go
> dx: Add option to specify development image in cluster connect

- .gitignore
- Justfile
- cmd/vclusterctl/cmd/credits/credits.go
- cmd/vclusterctl/cmd/credits/licenses/.gitignore
- cmd/vclusterctl/cmd/credits/licenses/readme.txt
- cmd/vclusterctl/cmd/root.go
- go.mod
/kind feature
resolves eng-3725
adds a credits subcommand to display OSS infos 
> Credits cmd

- pkg/certs/ensure.go
- pkg/setup/config.go
- pkg/setup/controllers.go
/kind bugfix
resolves ENG-3531
vcluster cert secrets now have owner references
> fix: set owner reference on cert secrets

- Justfile
/kind bugfix
part of ENG-3803
Fixed an issue where vcluster credits was not properly populated
> fix: credits command not working

- cmd/vclusterctl/cmd/platform/get/cluster_access_key.go
- cmd/vclusterctl/cmd/platform/get/get.go
/kind feature
resolves eng-3735
> Cluster access key

- cmd/vclusterctl/cmd/platform/list/clusters.go
- cmd/vclusterctl/cmd/platform/list/list.go
- cmd/vclusterctl/cmd/platform/list/secrets.go
- cmd/vclusterctl/cmd/platform/list/teams.go
/kind feature
resolves eng-3733
depends on #1790 
> List teams 

- cmd/vclusterctl/cmd/platform/get/get.go
- cmd/vclusterctl/cmd/platform/get/user.go
- go.mod
> feat: Added get current-user sub-command

- cmd/vclusterctl/cmd/platform/reset.go
- pkg/platform/random/random.go
> removed dep on loftctl for reset 

- cmd/vclusterctl/cmd/platform/platform.go
- cmd/vclusterctl/cmd/root.go
> now sets the cache dir correctly

- cmd/vclusterctl/cmd/platform/backup.go
- cmd/vclusterctl/cmd/platform/backup/backup.go
- cmd/vclusterctl/cmd/platform/backup/management.go
- cmd/vclusterctl/cmd/platform/connect/cluster.go
- cmd/vclusterctl/cmd/platform/connect/connect.go
- cmd/vclusterctl/cmd/platform/connect/management.go
- cmd/vclusterctl/cmd/platform/platform.go
- cmd/vclusterctl/cmd/platform/pro.go
- cmd/vclusterctl/cmd/root.go
- pkg/platform/backup/backup.go
/kind feature
resolves eng-3724
> Management

- chart/templates/statefulset.yaml
- chart/tests/statefulset_test.yaml
/kind bugfix
resolves #1815 
Fixed an issue where the vcluster helm chart did not apply the passed label values.
> fix(chart): Fixed labels not getting applied to statefulset

- cmd/vclusterctl/cmd/connect.go
- pkg/cli/connect_helm.go
- pkg/cli/connect_platform.go
resolves #
Fixed an issue where vcluster connect was missing flags.
Addresses https://github.com/loft-sh/vcluster/pull/1821/files#r1622306873
> chore(vclusterctl): add loftctl flags to vcluster connect

- charts/eks/templates/etcd-statefulset.yaml
- charts/eks/templates/syncer.yaml
/kind bugfix
resolves ENG-3836
Fixed an issue with chart templating causing kustomize to fail for eks charts
> fix(chart) - Fix duplicate affinity sections in eks chart

- pkg/setup/config.go
> fix: Use workload client when setting global owner

- Justfile
resolves #
removes gun-license from the single target build-snapshot used for development as it is not useful and is slowing down dev cycles. 
> removed license gen in single target build-snapshot

- .golangci.yml
resolves #
Removes (probably unwanted) noise from golangci-lint
> Do not lint licences dir per default

- cmd/vclusterctl/cmd/connect.go
- cmd/vclusterctl/cmd/create.go
- cmd/vclusterctl/cmd/delete.go
- cmd/vclusterctl/cmd/import.go
- cmd/vclusterctl/cmd/list.go
- cmd/vclusterctl/cmd/pause.go
- cmd/vclusterctl/cmd/resume.go
/kind bugfix
resolves ENG-3851
Fixed an issue where vcluster would not consider the --manager flag.
> fix(vclusterctl): also parse manager type from --manager flag

- pkg/cli/create_platform.go
/kind bugfix
resolves #
Fixed an issue where vcluster would not respect the given namespace when a virtual cluster is created from a template
> fix(vclusterctl): also consider given namespace when using a template

- pkg/platform/version.go
> chore(platform): Updated minimum version tag

- pkg/platform/client.go
> refactor: Readded ManagementConfig to platform client

- pkg/cli/create_helm.go
/kind bugfix
resolves #
Fixed an issue where vcluster would not take create-namespace flag into account for vcluster create
> fix(vclusterctl): pass create-namespace flag to helm client

- chart/templates/clusterrole.yaml
- chart/tests/clusterrole_test.yaml
- pkg/telemetry/collect_controlplane.go
- pkg/telemetry/helpers.go
> feat(telemetry): Add creation_timestamp and virtualclusterinstance_id fields to the vcluster_start telemetry event

- cmd/vclusterctl/cmd/connect.go
/kind feature
resolves ENG-3860
Fixed an issue where `vcluster connect --server` wouldn't work with the platform
> fix: allow --server when using platform on vcluster connect

- cmd/vclusterctl/cmd/create.go
resolves #
Fixed an issue where vcluster had multiple flags for the same functionality
> removed duplicate flag

- .github/workflows/e2e.yaml
> bumped goreleaser

- cmd/vclusterctl/cmd/platform/connect/connect.go
- cmd/vclusterctl/cmd/platform/connect/space.go
- cmd/vclusterctl/cmd/platform/create/create.go
- cmd/vclusterctl/cmd/platform/create/space.go
- cmd/vclusterctl/cmd/platform/delete/delete.go
- cmd/vclusterctl/cmd/platform/delete/space.go
- cmd/vclusterctl/cmd/platform/list/list.go
- cmd/vclusterctl/cmd/platform/list/spaces.go
- cmd/vclusterctl/cmd/platform/share/share.go
- cmd/vclusterctl/cmd/platform/share/space.go
- cmd/vclusterctl/cmd/platform/share/vcluster.go
- cmd/vclusterctl/cmd/platform/sleep/sleep.go
- cmd/vclusterctl/cmd/platform/sleep/space.go
- cmd/vclusterctl/cmd/platform/wakeup/space.go
- cmd/vclusterctl/cmd/platform/wakeup/wakeup.go
- pkg/cli/util/args.go
resolves ENG-3880
Renamed space subcommands to namespace
> chore(vclusterctl): rename space to namespace

- cmd/vclusterctl/cmd/platform/add/cluster.go
- cmd/vclusterctl/cmd/platform/connect/space.go
- cmd/vclusterctl/cmd/platform/create/space.go
- cmd/vclusterctl/cmd/platform/get/cluster_access_key.go
- pkg/platform/client.go
> fix: incorrect version check

- cmd/vclusterctl/cmd/create.go
- cmd/vclusterctl/cmd/delete.go
- cmd/vclusterctl/cmd/pause.go
- cmd/vclusterctl/cmd/platform/add/vcluster.go
- pkg/cli/add_vcluster_helm.go
- pkg/cli/create_helm.go
- pkg/platform/secret.go
> refactor: add flags to platform add vcluster

- cmd/vclusterctl/cmd/logout.go
- pkg/cli/connect_helm.go
- pkg/cli/create_helm.go
- pkg/cli/flags/connect/connect.go
- pkg/cli/flags/create/create.go
- pkg/cli/localkubernetes/configure.go
- pkg/util/kubeconfig/kubeconfig.go
/kind bugfix
Resolves ENG-3937
Fixed an issue where `background-proxy` flag was not working correctly
> fix: background-proxy flag

- cmd/vclusterctl/cmd/platform/connect/space.go
- cmd/vclusterctl/cmd/platform/create/space.go
- cmd/vclusterctl/cmd/platform/delete/space.go
- cmd/vclusterctl/cmd/platform/list/spaces.go
- cmd/vclusterctl/cmd/platform/sleep/space.go
- cmd/vclusterctl/cmd/platform/wakeup/space.go
resolves ENG-3946
Provide space alias for namespace subcommands for compatibility reasons
> chore: provide space aliases for platform namespace subcommands

- pkg/cli/find/find.go
- pkg/cli/localkubernetes/configure.go
- pkg/upgrade/upgrade.go
> fix: strip non alphanumeric characters in background-proxy

- chart/templates/manifests.yaml
- chart/tests/manifests_test.yaml
- chart/values.schema.json
- chart/values.yaml
- config/README.md
- config/config.go
- config/legacyconfig/migrate.go
- config/values.yaml
- pkg/cli/create_helm.go
- pkg/controllers/deploy/deploy.go
- test/e2e/values.yaml
- test/e2e_isolation_mode/values.yaml
- test/e2e_node/values.yaml
- test/e2e_rootless/values.yaml
- test/e2e_scheduler/values.yaml
> refactor: rename config fields

- .github/workflows/release.yaml
/kind feature
resolves #ENG-3943
Adds trigger to workflow in vcluster-docs to run documentation tests
> ENG-3943 | Add trigger for docs CI to release workflow

- chart/templates/statefulset.yaml
- chart/tests/statefulset_test.yaml
- chart/values.schema.json
- chart/values.yaml
- config/config.go
- config/legacyconfig/config.go
- config/legacyconfig/migrate.go
- config/legacyconfig/migrate_test.go
- config/values.yaml
resolves ENG-3953
Fixed an issue where vcluster would request too little ephemeral storage.
> V0.20 improve binaries volume config

- config/config.go
- config/config_test.go
> feat: update IsProFeatureEnabled for external.platform features

- .github/workflows/e2e.yaml
- chart/values.yaml
- config/default_extra_values.go
- config/values.yaml
- docs/pages/deploying-vclusters/compat-matrix.mdx
- hack/compat-matrix/main.go
- pkg/coredns/coredns.go
> chore: bump kubernetes versions

- chart/templates/coredns-configmap.yaml
- chart/tests/coredns-configmap_test.yaml
- chart/values.schema.json
- chart/values.yaml
- config/config.go
- config/values.yaml
/kind feature
resolves #1834
make topologySpreadConstraints configurable from helm chart/values
> move topologySpreadConstraints to values

- .github/workflows/e2e.yaml
- test/e2e/syncer/services/services.go
- test/e2e_isolation_mode/values.yaml
> chore: bump pipeline e2e to v1.30

- chart/templates/_coredns.tpl
> refactor: move vcluster plugin up in the coredns chain

- cmd/vcluster/cmd/root.go
- cmd/vcluster/main.go
- pkg/config/controller_context.go
- pkg/server/server.go
- pkg/server/types/types.go
> refactor: sanitize hooks & main

- cmd/vclusterctl/cmd/platform/backup/management.go
/kind bugfix
resolves #ENG-4063
> Update the backup command's default ns to vcluster-platform

- pkg/cli/start/success.go
resolves #
Renamed some legacy commands in the info logs when a vCluster platform is started
> chore: rename some legacy commands in info logs

- docs/pages/getting-started/connect.mdx
resolves #
Documented how to obtain a vcluster kubeconfig in legacy docs
> chore: document how to obtain a vcluster kubeconfig in legacy docs

- chart/templates/_rbac.tpl
- chart/templates/clusterrole.yaml
- chart/templates/role.yaml
- chart/tests/clusterrole_test.yaml
- chart/tests/role_test.yaml
- chart/values.schema.json
- chart/values.yaml
- config/config.go
- config/values.yaml
- pkg/controllers/generic/export_syncer.go
- pkg/controllers/generic/import_syncer.go
- pkg/controllers/generic/patcher.go
- pkg/controllers/register.go
/kind feature
resolves ENG-4056
> feat: add vCluster side of kubevirt integration

- devspace.yaml
- pkg/controllers/resources/configmaps/syncer.go
- pkg/controllers/resources/priorityclasses/syncer.go
- pkg/controllers/resources/priorityclasses/translate.go
- pkg/controllers/resources/secrets/syncer.go
- pkg/controllers/resources/secrets/translate.go
- pkg/controllers/syncer/context/context.go
- pkg/controllers/syncer/syncer.go
- pkg/patcher/patcher.go
- pkg/patcher/utils.go
Allow bidirectional sync of certain secret fields
> feat: add patcher

- .golangci.yml
- chart/values.schema.json
- config/config.go
- pkg/apiservice/generic.go
- pkg/config/controller_context.go
- pkg/controllers/syncer/context/context.go
- pkg/integrations/metricsserver/metricsserver.go
- pkg/server/server.go
/kind bugfix
Fixed an issue where vcluster would still not properly forward openapi requests
> fix: properly forward apiservice

- pkg/patcher/patcher.go
> refactor: add no status sub resource as option

- pkg/controllers/resources/ingressclasses/syncer.go
- pkg/controllers/resources/ingressclasses/translate.go
> added logic with patcher for ingressclasses

- pkg/controllers/resources/csistoragecapacities/syncer.go
- pkg/controllers/resources/csistoragecapacities/translate.go
> added patch logic for csistorage

- pkg/controllers/resources/csidrivers/syncer.go
- pkg/controllers/resources/csidrivers/translate.go
> added logic with patch for csidriver

- pkg/controllers/resources/csinodes/syncer.go
- pkg/controllers/resources/csinodes/translate.go
> update logic to patcher for csi nodes

- pkg/controllers/resources/ingresses/syncer.go
> added event emittion

- .github/workflows/e2e.yaml
- .github/workflows/lint.yaml
- .github/workflows/unit-tests.yaml
- pkg/cli/create_platform.go
> fix: adjust distro check

- .github/workflows/e2e.yaml
- .github/workflows/lint.yaml
- .github/workflows/unit-tests.yaml
- pkg/cli/create_platform.go
/kind bugfix
Fixed an issue where vcluster would not allow creating vclusters with a template
> BACKPORT v0.20 fix: adjust distro check

- .goreleaser.yaml
/kind bugfix
/kind feature
/kind test
resolves #
> [v0.20] chore: Release jsonschema file alongside binaries

- pkg/controllers/resources/nodes/fake_syncer.go
- pkg/controllers/resources/nodes/nodeservice/node_service.go
- pkg/controllers/resources/nodes/syncer.go
- pkg/controllers/resources/nodes/syncer_test.go
- pkg/controllers/resources/nodes/translate.go
- pkg/controllers/resources/nodes/translate_test.go
/kind bugfix
/kind feature
/kind test
resolves #
> Node patcher

- pkg/controllers/syncer/testing/testing.go
resolves #
Fixed testing library to use subtest and remove now useless focus field from tests. This allows to run specific tests with the `go test -run=testname/subtestname` and shows much more clearly what tests are run 
> improved test library

- pkg/controllers/resources/configmaps/syncer.go
- pkg/controllers/resources/configmaps/translate.go
- pkg/controllers/syncer/testing/testing.go
> added cm patcher

- pkg/controllers/resources/networkpolicies/syncer.go
- pkg/controllers/resources/networkpolicies/translate.go
> added patcher logic for network policies

- pkg/controllers/resources/storageclasses/host_sc_syncer.go
- pkg/controllers/resources/storageclasses/host_sc_translate.go
- pkg/controllers/resources/storageclasses/syncer.go
- pkg/controllers/resources/storageclasses/translate.go
> added patcher to storage classes

- pkg/controllers/resources/persistentvolumeclaims/syncer.go
- pkg/controllers/resources/persistentvolumeclaims/syncer_test.go
- pkg/controllers/resources/persistentvolumeclaims/translate.go
- pkg/controllers/resources/pods/ephemeral_containers.go
- pkg/controllers/resources/pods/syncer.go
- pkg/controllers/resources/pods/syncer_test.go
- pkg/controllers/resources/pods/translate.go
- pkg/controllers/resources/pods/translate/conditions.go
- pkg/controllers/resources/pods/translate/conditions_test.go
- pkg/controllers/resources/pods/translate/diff.go
- pkg/controllers/resources/pods/translate/translator.go
- pkg/controllers/resources/storageclasses/syncer_test.go
- pkg/controllers/resources/volumesnapshots/volumesnapshots/syncer.go
- pkg/controllers/resources/volumesnapshots/volumesnapshots/translate.go
- pkg/controllers/syncer/testing/testing.go
Part of ENG-4168
Changes:
* Pod Controller
* Persistent Volume Claim Controller
* Volume Snapshots Controller
> refactor: use patcher for pod controller

- pkg/controllers/resources/persistentvolumes/syncer.go
- pkg/controllers/resources/persistentvolumes/syncer_test.go
- pkg/controllers/resources/persistentvolumes/translate.go
- pkg/controllers/resources/volumesnapshots/volumesnapshotcontents/syncer.go
- pkg/controllers/resources/volumesnapshots/volumesnapshotcontents/translate.go
> Refactor persistent volume & volume snapshot contents syncers

- pkg/controllers/resources/nodes/syncer_test.go
- pkg/controllers/resources/nodes/translate_test.go
- pkg/syncer/testing/testing.go
> Test cleanup

- pkg/controllers/generic/export_patcher.go
- pkg/controllers/generic/import_patcher.go
- pkg/controllers/register.go
- pkg/controllers/resources/events/syncer.go
- pkg/controllers/resources/events/translate.go
- pkg/controllers/resources/networkpolicies/syncer_test.go
- pkg/controllers/resources/networkpolicies/translate.go
- pkg/controllers/resources/persistentvolumeclaims/translate.go
- pkg/controllers/resources/poddisruptionbudgets/syncer_test.go
- pkg/controllers/resources/poddisruptionbudgets/translate.go
- pkg/controllers/resources/pods/syncer_test.go
- pkg/controllers/resources/pods/translate/diff.go
- pkg/controllers/resources/pods/translate/translator.go
- pkg/controllers/resources/pods/translate/translator_test.go
- pkg/controllers/resources/secrets/syncer.go
- pkg/controllers/resources/secrets/syncer_test.go
- pkg/controllers/resources/services/syncer.go
- pkg/controllers/resources/services/syncer_test.go
- pkg/controllers/resources/services/translate.go
- pkg/controllers/servicesync/servicesync.go
- pkg/integrations/metricsserver/metricsserver.go
- pkg/server/filters/service.go
- pkg/util/translate/multi_namespace.go
- pkg/util/translate/single_namespace.go
- pkg/util/translate/translate.go
- pkg/util/translate/types.go
- test/e2e/servicesync/servicesync.go
- test/e2e/syncer/pods/pods.go
> refactor: label translation

- charts/eks/README.md
Part of # DOC-209
Added a deprecation notice on the EKS helm chart as this distribution for vCluster is deprecated. 
> Update README for EKS Helm Chart

- cmd/vclusterctl/cmd/convert/config.go
- config/config.go
- config/legacyconfig/migrate.go
/kind bugfix
resolves eng-4189
> fixed issue with eks migration backport 0.20

- pkg/cli/create_helm.go
resolves ENG-4187
Print more clearly how to use the vcluster convert config command when passing a legacy config
> chore: be more clear how to use the vcluster convert config command

- .github/workflows/e2e.yaml
- config/config_test.go
- config/diff.go
- config/legacyconfig/migrate.go
- config/legacyconfig/migrate_test.go
- hack/wait-for-pod.sh
/kind bugfix
resolves ENG-4125
Fixed an issue where vcluster would not correctly migrate certain fields from v0.19
Fixed e2e tests flake where we were not correctly waiting for pods
> fix: migrate maps

- .github/workflows/e2e.yaml
- config/config_test.go
- config/diff.go
- config/legacyconfig/migrate.go
- config/legacyconfig/migrate_test.go
- hack/wait-for-pod.sh
/kind bugfix
resolves ENG-4125
Fixed an issue where vcluster would not correctly migrate certain fields from v0.19
Fixed e2e tests flake where we were not correctly waiting for pods
> BACKPORT-v0.20: fix: migrate maps

- pkg/platform/helper.go
/kind bugfix
resolves eng-4210
> now checks for the users v20 backport

- .backportrc.json
> Added backportrc.json to enable CLI workflows

- config/config.go
- pkg/cli/add_vcluster_helm.go
nil check
formatting
/kind bugfix
Some changes were made to a backport PR that need to make it back to main.
> Sync changes from a backport

- .github/workflows/backport.yaml
- pkg/k8s/k8s.go
/kind bugfix
resolves ENG-4263
Fixed an issue where vcluster with k8s distro would not startup in time
> fix: k8s startup issue

- .github/workflows/lint.yaml
/kind bugfix
/kind feature
/kind test
resolves #
> Remove lint workflow from on release

- .github/workflows/backport.yaml
> chore: fix backport.yaml

- .github/workflows/lint.yaml
/kind bugfix
/kind feature
/kind test
resolves #
> [Backport 0.19] Remove on release from lint workflow 

- chart/templates/networkpolicy.yaml
- chart/values.schema.json
- chart/values.yaml
- config/config.go
- config/values.yaml
/kind bugfix
resolves eng-4234
> [BACKPORT v0.20] [fix] add exception for the platform in network policy

- pkg/apiservice/generic.go
- pkg/integrations/metricsserver/metricsserver.go
/kind bugfix
resolves ENG-4260
resolves #2006
> fix: metrics server hpa problem

- chart/values.schema.json
- chart/values.yaml
- config/config.go
- pkg/apiservice/generic.go
- pkg/config/controller_context.go
- pkg/integrations/metricsserver/metricsserver.go
- pkg/server/server.go
/kind bugfix
resolves ENG-4260
> [BACKPORT v0.20] Metrics server fixes

- pkg/cli/create_helm.go
- pkg/util/clihelper/clihelper.go
…ased on the action taken
resolves ENG-4190 ENG-4198
Minor log improvements in vcluster create
> minor log improvements in vcluster create

- cmd/vclusterctl/cmd/login.go
- cmd/vclusterctl/cmd/logout.go
- cmd/vclusterctl/cmd/platform/login.go
- cmd/vclusterctl/cmd/platform/logout.go
- cmd/vclusterctl/cmd/platform/platform.go
resolves ENG-4288
deprecated `vcluster login` in favor of `vcluster platform login`
> [UX] moved login from root level to platform subcommand

- config/default_extra_values.go
- pkg/cli/create_helm.go
> refactor: remove auto syncing of node syncing for kind

- .github/workflows/release.yaml
> Add workflow to trigger doc PR in vcluster-docs

- pkg/controllers/resources/csistoragecapacities/mapper.go
- pkg/mappings/generic/mapper.go
- pkg/mappings/generic/recorder.go
- pkg/mappings/generic/recorder_test.go
- pkg/mappings/resources/configmaps.go
- pkg/mappings/resources/secrets.go
- pkg/mappings/store/mapping.go
- pkg/mappings/store/store.go
- pkg/mappings/store/store_test.go
- pkg/syncer/synccontext/mapper.go
> fix: store watches & delete references

- pkg/mappings/store/store_test.go
- pkg/util/testing/client.go
> test: add test rest mapper for unit testing

- chart/values.schema.json
- config/config.go
- pkg/util/translate/labels.go
- pkg/util/translate/translate_test.go
> feat: add labels patch

- chart/values.schema.json
- config/config.go
- pkg/mappings/generic/mapper_test.go
- pkg/mappings/generic/recorder_test.go
- pkg/util/testing/client.go
- pkg/util/testing/mapper.go
> Test improvement & kindPath & apiVersionPath

- pkg/mappings/resources/services.go
- pkg/syncer/synccontext/mapper.go
> fix: map default/kubernetes correctly

- chart/values.schema.json
- chart/values.yaml
- config/config.go
- config/values.yaml
/kind feature
part of eng-3892
added the external secrets integration config
> added config for external secret integration

- chart/templates/_rbac.tpl
- chart/templates/clusterrole.yaml
- chart/templates/role.yaml
- chart/tests/clusterrole_test.yaml
- chart/tests/role_test.yaml
/kind feature
part of eng-3892
> updated rbac template for eso integration 

- chart/templates/role.yaml
- chart/tests/role_test.yaml
/kind feature
part of  eng-3892
> added options to sync the secret stores in eso integration

- chart/templates/clusterrole.yaml
- chart/tests/clusterrole_test.yaml
> add cluster secret store sync to helm chart for eso 

- pkg/cli/connect_platform.go
- pkg/cli/create_platform.go
respect the --config flag and it's defaults
part of ENG-4398
> fix: use proper config location

- pkg/controllers/generic/export_syncer.go
/kind bugfix
resolves eng-4474 and #2108 
> [fix] : now prevents the generic syncer from continuously deleting objs

- pkg/controllers/resources/csidrivers/syncer_test.go
- pkg/controllers/resources/csinodes/syncer_test.go
- pkg/controllers/resources/csistoragecapacities/syncer_test.go
- pkg/controllers/resources/endpoints/syncer_test.go
- pkg/controllers/resources/ingressclasses/syncer_test.go
- pkg/controllers/resources/ingresses/syncer_test.go
- pkg/controllers/resources/persistentvolumeclaims/syncer.go
- pkg/controllers/resources/runtimeclasses/syncer_test.go
- pkg/controllers/resources/services/syncer_test.go
- pkg/mappings/generic/recorder_test.go
- pkg/mappings/resources/namespaces_test.go
- pkg/patcher/patcher.go
> refactor: update instead of patch & more tests

- pkg/upgrade/upgrade.go
> fix(cli): do not upgrade if latest stable is older(eg: beta)

- cmd/vclusterctl/cmd/platform/reset.go
> fix: wrong namespace for vcluster

- pkg/lifecycle/lifecycle.go
fixes ENG-4534
s/Delete Pods/Relaunching Pods
> [trivial] fix(cli): reword logs for clarity

- chart/templates/clusterrole.yaml
- chart/tests/clusterrole_test.yaml
/kind bugfix
resolves eng-3892
Fixed an issue where vcluster would not create the right permissions for webhook sync
> added clusterrole rule for eso and webhook

- pkg/upgrade/upgrade.go
/kind bugfix
resolves #eng-4637
manual backport of https://github.com/loft-sh/vcluster/pull/2136 as adding the label after it's merged doesn't work
> [v0.20] fix(cli): do not upgrade if latest stable is older(eg: beta)

- cmd/vclusterctl/cmd/platform/add/cluster.go
- cmd/vclusterctl/cmd/platform/backup/management.go
- cmd/vclusterctl/cmd/platform/get/secret.go
- cmd/vclusterctl/cmd/platform/reset.go
- cmd/vclusterctl/cmd/platform/set/secret.go
- cmd/vclusterctl/cmd/platform/start.go
- pkg/cli/start/success.go
- pkg/platform/clihelper/clihelper.go
> [BACKPORT v0.20] Changes fallback ns to vcluster-platform

- chart/templates/_persistence.tpl
- chart/tests/statefulset_test.yaml
/kind bugfix
/kind feature
/kind test
resolves #
> fix(pro): Force StatefulSet for embedded etcd

- cmd/vclusterctl/cmd/platform/reset.go
> Improve vcluster platform reset error message

- cmd/vclusterctl/cmd/platform/add/vcluster.go
- cmd/vclusterctl/cmd/platform/platform.go
- pkg/cli/add_vcluster_helm.go
- pkg/cli/config/types.go
- pkg/cli/create_helm.go
- pkg/k8s/k8s.go
- pkg/platform/secret.go
ref ENG-4706
ref ENG-4604
ref ENG-4522
> refactor: use separate access key per vCluster

- cmd/vclusterctl/cmd/platform/access_key.go
- pkg/cli/config/config.go
- pkg/cli/connect_platform.go
- pkg/platform/clihelper/clihelper.go
- pkg/platform/helper.go
- pkg/platform/kubeconfig/kubeconfig.go
> Use regular access key for all vCluster types

- chart/templates/_init-containers.tpl
- chart/tests/statefulset_test.yaml
- config/default_extra_values.go
- pkg/cli/create_helm.go
- pkg/cli/create_platform.go
> refactor: figure out k8s version in helm chart

- pkg/controllers/generic/export_syncer.go
> fix: check for selector be nil

- Dockerfile
- Dockerfile.release
/kind bugfix
resolves #2104
resolves ENG-4455
> fix: add tzdata to Dockerfile

- Dockerfile
- Dockerfile.release
/kind bugfix
resolves #2152
resolves ENG-4627
> fix: bump kine version

- pkg/cli/connect_helm.go
- pkg/cli/delete_helm.go
- pkg/cli/localkubernetes/configure.go
- test/framework/framework.go
> refactor: vcluster connect prefer background proxy

- chart/values.schema.json
- chart/values.yaml
- config/config.go
- config/values.yaml
- pkg/cli/connect_helm.go
- pkg/cli/connect_platform.go
- pkg/setup/controller_context.go
- pkg/setup/controllers.go
- pkg/util/kubeconfig/kubeconfig.go
- pkg/util/serviceaccount/serviceaccount.go
/kind feature
resolves #2141
resolves ENG-4575
> feat: add service account to export kube config

- chart/templates/_rbac.tpl
- chart/templates/clusterrole.yaml
- chart/templates/role.yaml
- chart/tests/clusterrole_test.yaml
- chart/tests/role_test.yaml
- chart/values.schema.json
- config/config.go
> refactor: rename sync.customResourceDefinitions -> customResources

- pkg/cli/find/find.go
/kind bugfix
resolves ENG-4782
> fix: exclude partially deployed vClusters from listing

- chart/tests/role_test.yaml
- chart/tests/statefulset_test.yaml
- chart/values.schema.json
- chart/values.yaml
- config/config.go
- pkg/controllers/resources/configmaps/syncer.go
- pkg/controllers/resources/ingresses/syncer.go
- pkg/controllers/resources/persistentvolumeclaims/syncer.go
- pkg/controllers/resources/pods/syncer.go
- pkg/controllers/resources/secrets/syncer.go
- pkg/controllers/resources/services/syncer.go
resolves ENG-4775
Renamed translate field to patches
> chore: Update translate to patches

- chart/values.schema.json
- config/config.go
/kind bugfix
/kind feature
/kind test
Part of ENG-4807
> feat: Added patches to sync from host CRs

- pkg/platform/clihelper/clihelper.go
/kind bugfix
resolves ENG-4790
> fix: remove unneeded --reuse-values

- pkg/platform/helper.go
> fix: change warnings to info, increase time between messages

- cmd/vclusterctl/cmd/platform/add/cluster.go
- pkg/cli/podprinter/podprinter.go
- pkg/controllers/resources/pods/ephemeral_containers.go
- pkg/controllers/resources/pods/syncer.go
- pkg/platform/helper.go
resolves ENG-4834
resolves ENG-4841
ref ENG-4789
ref #2197
> refactor: faster selecting vclusters / spaces, fix ephemeral containers & better logging

- pkg/config/coredns_plugin_validation.go
> feat: allow wildcard for dns hostname

- pkg/controllers/resources/configmaps/syncer.go
- pkg/controllers/resources/csidrivers/syncer.go
- pkg/controllers/resources/csinodes/syncer.go
- pkg/controllers/resources/csistoragecapacities/syncer.go
- pkg/controllers/resources/endpoints/syncer.go
- pkg/controllers/resources/events/syncer.go
- pkg/controllers/resources/ingressclasses/syncer.go
- pkg/controllers/resources/ingresses/syncer.go
- pkg/controllers/resources/networkpolicies/syncer.go
- pkg/controllers/resources/nodes/syncer.go
- pkg/controllers/resources/persistentvolumeclaims/syncer.go
- pkg/controllers/resources/persistentvolumes/syncer.go
- pkg/controllers/resources/poddisruptionbudgets/syncer.go
- pkg/controllers/resources/pods/syncer.go
- pkg/controllers/resources/priorityclasses/syncer.go
- pkg/controllers/resources/runtimeclasses/syncer.go
- pkg/controllers/resources/secrets/syncer.go
- pkg/controllers/resources/serviceaccounts/syncer.go
- pkg/controllers/resources/services/syncer.go
- pkg/controllers/resources/storageclasses/host_syncer.go
- pkg/controllers/resources/storageclasses/syncer.go
- pkg/controllers/resources/volumesnapshotclasses/syncer.go
- pkg/controllers/resources/volumesnapshotcontents/syncer.go
- pkg/controllers/resources/volumesnapshots/syncer.go
- pkg/patcher/patcher.go
- pkg/pro/patches.go
> refactor: reverse expression for fromHost

- test/e2e/syncer/networkpolicies/networkpolicies.go
- test/e2e/syncer/pods/pods.go
- test/e2e/syncer/services/services.go
- test/framework/framework.go
- test/framework/util.go
/kind test
resolves ENG-4809
Added two e2e tests for testing bidirectional sync of host cluster and vCluster annotations.
> test: Added e2e tests for bidirectional annotation & label sync

- config/config.go
- config/config_test.go
/kind bugfix
Add custom resources to host syncing to pro check
> fix: Added custom resources to host to pro check

- .custom-gcl.yml
/kind bugfix
/kind feature
/kind test
resolves #
> bump lint to cause panic

- .custom-gcl.yml
- .github/workflows/compatibility.yaml
- .github/workflows/e2e.yaml
- .github/workflows/lint.yaml
- .github/workflows/release.yaml
- .github/workflows/unit-tests.yaml
- CONTRIBUTING.md
- Dockerfile
- README.md
- go.mod
- pkg/config/validation.go
- pkg/controllers/resources/volumesnapshotclasses/syncer_test.go
- pkg/controllers/resources/volumesnapshotcontents/syncer_test.go
- pkg/controllers/resources/volumesnapshots/syncer_test.go
- pkg/mappings/generic/mapper.go
- pkg/mappings/generic/mirror.go
- pkg/mappings/generic/recorder.go
- pkg/mappings/resources/volumesnapshotclasses.go
- pkg/mappings/resources/volumesnapshotcontents.go
- pkg/syncer/testing/testing.go
/kind bugfix
/kind feature
/kind test
resolves #
> fix: Separate volumesnapshot mappers into individual configurations

- .github/workflows/e2e.yaml
- .golangci.yml
- .goreleaser.yaml
- Dockerfile.release
- Justfile
- cmd/vcluster/cmd/debug/etcd/keys.go
- hack/schema/main.go
- pkg/cli/add_vcluster_helm.go
- pkg/etcd/client.go
- pkg/mappings/generic/recorder.go
- pkg/mappings/store/backend.go
- pkg/mappings/store/etcd_backend.go
- pkg/mappings/store/store.go
- pkg/setup/controller_context.go
- vcluster.yaml
/kind bugfix
resolves #
Fixed an issue where vCluster mappings garbage collection would hang and cause the entire syncer process to deadlock.
> fix: Only get PartialObjectMetadata in mappings GC

- chart/templates/_helper.tpl
- chart/tests/headless-service_test.yaml
- chart/tests/service_test.yaml
- go.mod
- pkg/cli/find/find.go
- pkg/config/config.go
- pkg/config/parse.go
/kind bugfix
related to ENG-4551
Fixed an issue where vcluster could not create virtual clusters that started with digits and ended with non-digit characters.
**TODO after merge**
> Also allow name that starts with digits

- pkg/mappings/store/backend.go
- pkg/mappings/store/backend_etcd.go
- pkg/mappings/store/backend_memory.go
- pkg/mappings/store/store.go
- pkg/mappings/store/store_test.go
/kind bugfix
* Fixed the underlying dead-lock for store
* Fixed the potential memory leak for store etcd events
> fix: garbage collection deadlock & mappings memory leak

- chart/templates/_helper.tpl
- chart/templates/headless-service.yaml
- chart/templates/service.yaml
- chart/templates/statefulset.yaml
- chart/tests/headless-service_test.yaml
- chart/tests/service_test.yaml
- devspace.yaml
- pkg/certs/ensure.go
- pkg/cli/connect_helm.go
- pkg/cli/find/find.go
- pkg/config/config.go
- pkg/config/parse.go
- pkg/controllers/resources/nodes/nodeservice/node_service.go
- pkg/setup/config.go
- pkg/util/translate/types.go
- test/framework/framework.go
/kind bugfix
related to ENG-4551
> Revert possibility to create virtual clusters starting with digits

- pkg/controllers/resources/endpoints/syncer_test.go
- pkg/controllers/resources/ingresses/syncer_test.go
- pkg/controllers/resources/networkpolicies/syncer_test.go
- pkg/controllers/resources/persistentvolumeclaims/syncer_test.go
- pkg/controllers/resources/persistentvolumes/syncer_test.go
- pkg/controllers/resources/poddisruptionbudgets/syncer_test.go
- pkg/controllers/resources/pods/syncer_test.go
- pkg/controllers/resources/secrets/syncer_test.go
- pkg/controllers/resources/services/syncer.go
- pkg/controllers/resources/services/syncer_test.go
- pkg/controllers/resources/services/translate.go
- pkg/controllers/resources/storageclasses/syncer_test.go
- pkg/controllers/resources/volumesnapshotcontents/syncer_test.go
- pkg/controllers/resources/volumesnapshots/syncer_test.go
- pkg/patcher/sync.go
- pkg/syncer/syncer_test.go
- pkg/util/generics/generics.go
- pkg/util/translate/labels.go
- pkg/util/translate/translate.go
/kind test
resolves ENG-5033
Updating unit tests after the syncer refactoring
> Fix unit tests for sync-refactoring

- Dockerfile
- Dockerfile.cli.release
- Dockerfile.release
/kind bugfix
resolves ENG-5080
Upgrades helm and kine. Did a scan of the release notes and couldn't find breaking changes.
> Upgrades helm and kine

- pkg/controllers/resources/events/syncer.go
- pkg/mappings/store/store.go
- pkg/patcher/apply.go
- pkg/server/filters/redirect.go
- pkg/syncer/syncer.go
- pkg/syncer/syncer_test.go
> fix: lost host event information

- pkg/patcher/apply.go
- pkg/server/filters/redirect.go
- pkg/syncer/syncer.go
> refactor: update object cache correctly

- pkg/platform/secret.go
/kind bugfix
resolves ENG-5097
Fixed an issue where vcluster would create a virtual cluster in the platform with an incorrect version
> Create virtualcluster with CLI version during platform secret create

- pkg/cli/email/validate.go
/kind bugfix
resolves #ENG-5104
Some ISPs block the SMTP ports so trying to dial will always fail even though the email is valid.  This changes it to accept the email address as long as the domain returns at least one MX record.
> fix: Skip trying to dial an MX record's domain

- chart/tests/clusterrole_test.yaml
- chart/values.schema.json
- config/config.go
- pkg/config/validation.go
> refactor: add customResources.scope & require scope for fromHost customResources

- pkg/setup/controllers.go
/kind bugfix
resolves #2234
Fixed issue where custom server setting in `exportKubeConfig` was overwriting the default kubeconfig secret.
> Apply exportKubeconfig server setting only to additional kubeconfig secret

- Dockerfile
- Dockerfile.release
> chore: Updated to latest kine version

- cmd/vclusterctl/cmd/debug/collect.go
- cmd/vclusterctl/cmd/debug/debug.go
- cmd/vclusterctl/cmd/root.go
- pkg/helm/secrets.go
> feat: add vcluster debug collect

- .github/workflows/sync-config-schema.yaml
on alpha / beta releases, generate vcluster.schema.json for main docs version and create PR in vcluster-docs directly
resolves ENG-3393
On alpha / beta releases, generate partials in the vcluster-docs repo
> Generate partials in docs on alpha/beta releases

- chart/values.schema.json
- config/config.go
/kind feature
resolves #ENG-5133
> feat: Native sleep mode config

- cmd/vclusterctl/cmd/debug/collect.go
> fix: debug collect command

- chart/templates/_rbac.tpl
- chart/templates/clusterrole.yaml
- chart/templates/role.yaml
- chart/tests/clusterrole_test.yaml
- chart/tests/role_test.yaml
- chart/values.schema.json
- chart/values.yaml
- config/config.go
- config/values.yaml
- pkg/patcher/sync.go
/kind feature
resolves ENG-5190
feat: cert-manager integration to re-use cert manager from host cluster
I added some minor non-functional changes that didn't seem worth a seperate PR. Removing an unused variable and 
adding some comments on some functions.
> feat: cert-manager integration spec

- chart/values.schema.json
- config/config.go
> Update Durations type to string to correct json schema

- pkg/controllers/resources/persistentvolumes/translate.go
- pkg/util/translate/labels.go
- pkg/util/translate/labels_test.go
- pkg/util/translate/translate.go
/kind bugfix
resolves ENG-5252
> fix: ignore excluded annotations on create

- .github/workflows/sync-config-schema.yaml
enhancement: sync vcluster-config on beta, rc and stable versions; sync vcluster-docs main version on beta and rc releases
resolves ENG-3393
[Fixed an issue where vcluster ...](enhancement: sync vcluster-config on beta, rc and stable versions; sync vcluster-docs main version on beta and rc releases)
Based on the discussions, we want to sync docs on beta & rc versions and sync vcluster-config on beta, rc and stable versions.
> adjust sync-config CI workflow

- cmd/vclusterctl/cmd/upgrade.go
- pkg/controllers/resources/nodes/syncer.go
- pkg/helm/time.go
- pkg/upgrade/helpers.go
- pkg/upgrade/upgrade.go
- pkg/upgrade/upgrade_test.go
- pkg/util/encoding/helper.go
/kind bugfix
resolves ENG-5323
Fixed an issue where vcluster upgrade command would fail for older releases
> [v0.19] bugfix(cli): change process of finding specified binary releases

- pkg/controllers/resources/nodes/translate.go
/kind bugfix
resolves ENG-4484
> bugfix: set allocatable resources to 0 when free capacity goes negative

- pkg/controllers/resources/nodes/translate.go
/kind bugfix
resolves ENG-5379
> [v0.20] bugfix: set allocatable resources to 0 when free capacity goes negative

- .github/workflows/sync-config-schema.yaml
/kind bugfix
Fixed an issue with vcluster docs auto update
> fix paths in update docs partials workflow

- cmd/vclusterctl/cmd/platform/destroy.go
- cmd/vclusterctl/cmd/platform/start.go
- pkg/cli/start/start.go
/kind bugfix
resolves #ENG-5351
> Bypass email prompt for upgrades if installed

- config/diff.go
- config/legacyconfig/migrate.go
- config/legacyconfig/migrate_test.go
/kind bugfix
resolves ENG-5541
Fixed an issue where vcluster convert config skipped statefulset affinity rules
backport of #2329
> [backport-to-v0.22] Fix cli convert cmd

- .github/workflows/sync-config-schema.yaml
/kind bugfix
spotted a typo in output var name
Fixed an issue where vcluster config sync does not work if triggered manually
> fix manual trigger for config sync schema workflow

- pkg/cli/delete_helm.go
- pkg/controllers/resources/secrets/syncer.go
> fix: clean up PriorityClasses associated with vCluster

- pkg/mappings/generic/mapper.go
/kind bugfix
Fixed an issue where installing multiple vClusters in the same namespace would cause issues
> fix: exclude import by other vclusters

- pkg/cli/localkubernetes/configure.go
/kind bugfix
Fixed an issue where background proxy wouldn't work correctly with docker desktop
> fix: create background proxy container

- pkg/platform/client.go
Fixed an issue where vcluster platform for client.go file by replacing loft with vCluster platform
> fixed client.go code - loft with vCluster platform

- Justfile
- pkg/syncer/syncer.go
/kind bugfix
resolves ENG-5478
> fix: set resource version to 1 on old

- pkg/cli/localkubernetes/localkubernetes.go
/kind bugfix
For the code present, we get this error:
```
tautological condition: non-nil != nil
```
Fixed an issue where vcluster contained a redundant tautological condition (non-nil != nil) in the code, improving code clarity and maintainability.
No effect to the functionality of vcluster.
> fix the tautological condition

- pkg/setup/controllers.go
> Fix panic when using exportKubeConfig.name without exportKubeConfig.server

- .github/workflows/release.yaml
> chore: add step to trigger vcluster bump workflow for CAPVC

- chart/values.schema.json
- chart/values.yaml
- config/config.go
- config/values.yaml
- pkg/controllers/resources/pods/translate/translator.go
/kind feature
resolves ENG-5547
> feat: add sync.toHost.pods.runtimeClassName

- .backportrc.json
- .github/workflows/backport.yaml
Closes OPS-37
Enhanced backport CI workflow to pull the original PR description and add it to the bakcport PR. This helps to easier identify what is being backported.
> ci(backport): fetch original PR description

- docs/docusaurus.config.js
> docs: adding version announcement bar

- pkg/controllers/resources/services/syncer.go
- pkg/controllers/resources/services/translate.go
> Remove the ServiceBlockDeletion Annotation once the virtual service exists

- Dockerfile.cli.release
Part of ENG-5669
Follow up from: https://github.com/loft-sh/vcluster/pull/2450
> Bump helm in cli dockerfile

- charts/eks/templates/syncer.yaml
- charts/k0s/templates/syncer.yaml
- charts/k3s/templates/syncer.yaml
- charts/k8s/templates/syncer.yaml
- pkg/server/filters/nodechanges.go
/kind bugfix
resolves ENG-5662
Fixed an issue where vcluster would incorrectly throw a "context deadline exceeded" error when syncing node changes to host
> bugfix: fix discrepancies when syncing node changes from virtual to host

- pkg/platform/client.go
/kind bugfix
resolves #2457
Fixed a typo in "vcluster platform list" error message.
This is my first PR for vcluster.  Please let me know if there are protocols I should be following.
> Fix typo in error message in client.go

- .github/workflows/release.yaml
This reverts commit 200ad53e8bc53859cf96ef2fd49e27ab4dba9f8d.
/kind bugfix
/kind feature
/kind test
resolves #
Not needed as we change the CAPVC controller to default to the latest stable release.
> Revert "chore: add step to trigger vcluster bump workflow for CAPVC (#2417)"

- .github/workflows/release.yaml
> ci: add slack release notification

- .github/workflows/release.yaml
> Revert "ci: add slack release notification"

- chart/templates/clusterrole.yaml
- chart/tests/clusterrole_test.yaml
- chart/values.schema.json
- chart/values.yaml
- config/config.go
- config/values.yaml
- pkg/config/validation.go
- pkg/config/validation_test.go
- pkg/controllers/resources/configmaps/from_host_syncer.go
- pkg/controllers/resources/poddisruptionbudgets/syncer_test.go
- pkg/controllers/resources/secrets/from_host_syncer.go
- test/e2e/values.yaml
part of ENG-5885
Renamed `selector.mappings` to `mappings.byName` in the  from host sync config.
> rename .selector.mappings to .mappings.byName

- chart/templates/statefulset.yaml
- pkg/k8s/k8s.go
> fix: probe timeout & apiserver flags

- pkg/controllers/resources/services/syncer.go
/kind bugfix
Fixed an issue where vcluster upgrades wouldn't rewrite the service labels correctly anymore (regression)
> fix: service label sync

- cmd/vcluster/cmd/snapshot.go
- pkg/pro/embedded_etcd.go
- pkg/setup/initialize.go
- test/e2e/snapshot/snapshot.go
> fix: e2e tests for embedded etcd & snpashot

- test/e2e_cli/connect/connect.go
/kind bugfix
resolves (minor issue that I observed, it's a recent change in framework's field name which caused it)
> Minor update in framework's field name to align with latest changes

- chart/values.schema.json
- config/config.go
> feat: move new sleep mode to top level of config

- chart/values.schema.json
- config/config.go
> feat: move auto wake config and rename to be consistent with autoSleep

- .github/workflows/release.yaml
- fix variable name for the release branch
- add code calculating the source branch
/kind bugfix
resolves #
OPS-93
> fix(ci): slack notification workflow

- .github/workflows/e2e.yaml
> Revert "fix(ci): permissions for accessing org secrets"

- cmd/vcluster/cmd/restore.go
- cmd/vcluster/cmd/snapshot.go
- cmd/vclusterctl/cmd/restore.go
- cmd/vclusterctl/cmd/snapshot.go
- pkg/cli/create_helm.go
- pkg/cli/restore_helm.go
- pkg/cli/snapshot_helm.go
- pkg/mappings/store/backend_etcd.go
- pkg/server/filters/service.go
- pkg/snapshot/container/store.go
- pkg/snapshot/oci/store.go
- pkg/snapshot/s3/store.go
- pkg/snapshot/snapshot.go
- test/e2e/snapshot/snapshot.go
/kind bugfix
resolves ENG-5964
resolves ENG-5967
resolves ENG-5966
resolves ENG-5955
> refactor: remove flags & fixes

- test/e2e/e2e_suite_test.go
- test/e2e/syncer/runtimeclass/runtimeclass.go
- test/e2e/values.yaml
/kind test
for  #ENG-5581
Added a test to sync runtimeclass from Host to vCluster
> Adding tests for syncing runtimeclass from host

- cmd/vclusterctl/cmd/login.go
- docs/pages/cli/vcluster_login.md
- pkg/cli/start/success.go
resolves #DOC-354
- Update docs to reflect `vcluster platform login` command 
- Relates to https://github.com/loft-sh/vcluster/pull/2577
- Relates to https://github.com/loft-sh/vcluster-docs/pull/502
> fix: update login command

- chart/templates/service-monitor.yaml
- chart/templates/service.yaml
- chart/templates/statefulset.yaml
- chart/tests/service-monitor_test.yaml
- pkg/server/filters/k8s_metrics.go
- pkg/server/server.go
> feat: expose scheduler & controller-manager metrics

- .golangci.yml
- cmd/vcluster/cmd/restore.go
- pkg/cli/create_helm.go
- pkg/cli/snapshot_helm.go
- pkg/snapshot/oci/store.go
- pkg/snapshot/options/options.go
- pkg/snapshot/pod/pod.go
- pkg/snapshot/s3/store.go
- pkg/snapshot/snapshot.go
- pkg/snapshot/snapshot_test.go
/kind bugfix
resolves ENG-6129
resolves ENG-6110
resolves ENG-5967
resolves ENG-5981
resolves ENG-5966
resolves ENG-6109
> fix: snapshot & restore fixes

- pkg/snapshot/options/options.go
/kind bugfix
resolves ENG-6129
> fix: trim newline / spaces while parsing

- .github/workflows/e2e.yaml
> fix: fix e2e workflow step name

- cmd/vclusterctl/cmd/platform/login.go
/kind bugfix
resolves #ENG-6298
> fix: use access key from cli if specified before checking login details

- .golangci.yml
- charts/k0s/templates/_helpers.tpl
- charts/k0s/templates/syncer.yaml
- charts/k0s/tests/syncer_test.yaml
- charts/k0s/values.yaml
- charts/k3s/templates/_helpers.tpl
- charts/k3s/templates/syncer.yaml
- charts/k3s/tests/syncer_test.yaml
- charts/k3s/values.yaml
- charts/k8s/templates/_helpers.tpl
- charts/k8s/templates/syncer.yaml
- charts/k8s/tests/syncer_test.yaml
- charts/k8s/values.yaml
- go.mod
- go.sum
- pkg/controllers/resources/nodes/syncer.go
- pkg/controllers/resources/nodes/translate.go
- pkg/options/flags.go
- pkg/options/options.go
- pkg/util/translate/multi_namespace.go
- vendor/github.com/loft-sh/vcluster-values/helmvalues/common.go
- vendor/modules.txt
/kind bugfix
resolves ENG-3877
> bugfix: fix the incorrect calculation of node resources when sidecar containers are being injected during sync to host with virtual scheduler enabled

- .github/workflows/e2e.yaml
- .github/workflows/lint.yaml
- .github/workflows/unit-tests.yaml
- CONTRIBUTING.md
- Dockerfile
- Dockerfile.cli
- go.mod
Towards #ENG-4734
Update Go to version 1.24 and trigger CI when go version or a dependency version changes.
> Update Go to 1.24

- .github/dependabot.yml
related to #ENG-4734
Change dependabot config to check for Dockerfile and github-actions updates weekly.
> Check docker and github-actions updates weekly

- chart/values.schema.json
- chart/values.yaml
- config/config.go
resolves ENG-6260
Made the comments for External Secrets Operator more clear
> fix: update wording in ESO schema

- pkg/k8s/k8s.go
> fix: restart vCluster if k8s  exits

- chart/templates/_backingstore.tpl
- chart/tests/etcd-statefulset_test.yaml
- chart/tests/statefulset_test.yaml
- chart/values.schema.json
- chart/values.yaml
- cmd/vcluster/cmd/restore.go
- cmd/vcluster/cmd/snapshot.go
- config/config.go
- config/default_extra_values.go
- config/legacyconfig/migrate.go
- config/values.yaml
- pkg/etcd/client.go
- pkg/k0s/k0s.go
- pkg/k3s/k3s.go
- pkg/k8s/k8s.go
/kind feature
resolves https://github.com/loft-sh/vcluster/issues/2558
currently just a draft, looking forward to your opinion and recommendations before adding tests and validations
Support external standalone ETCD
> feat: support external etcd

- .github/workflows/release.yaml
resolves OPS-121
- Improve branch calculation for Slack release notifications
- Fix missing version and incorrect branch information in Slack notifications
- Implement distance-based algorithm to accurately identify source branch for release tags
> fix(ci): improve branch calculation from tags

- Justfile
- test/e2e/syncer/services/services.go
- test/e2e/webhook/webhook.go
wait for labels and annotations to be eventually equal in service bi-directional e2e test
/kind test
resolves #
Fixed an issue with flaky bi-directional e2e test
> fix service sync e2e flaky test

- pkg/syncer/from_host_syncer_test.go
/kind test
These tests were originally added in #2625 while working on #ENG-5567.
Add generic FromHost syncer unit tests.
> Add generic FromHost syncer unit tests

- .github/workflows/e2e.yaml
* Do proper caching instead of uploading e2e binaries (should speed up building quite a bit)
* Merge cli / syncer build stages
* Remove unnecessary steps
> test: improve e2e tests

- pkg/controllers/resources/storageclasses/host_syncer_test.go
/kind test
These tests were originally added in #2625 while working on #ENG-5567.
Add StorageClass FromHost syncer unit tests.
> Add StorageClass FromHost syncer tests

- chart/templates/networkpolicy.yaml
- chart/tests/networkpolicy_test.yaml
- chart/values.schema.json
- chart/values.yaml
- config/config.go
- config/values.yaml
/kind feature
Changes:
* Adds `policies.networkPolicy.extraWorkloadRules`
* Adds `policies.networkPolicy.extraControlPlaneRules`
> feat: add extra rules for network policy

- chart/templates/clusterrole.yaml
- chart/templates/role.yaml
- chart/tests/role_test.yaml
- chart/values.schema.json
- chart/values.yaml
- config/config.go
- config/values.yaml
> add istio config

- pkg/controllers/resources/pods/syncer.go
- pkg/pro/istio.go
/kind feature
part of ENG-6592
Adds istio patches to pod syncer
> apply istio patches

- pkg/cli/create_helm.go
- pkg/config/validation.go
- pkg/config/validation_test.go
/kind bugfix
resolves #ENG-6431
Avoids having 2 patches applying in the same path.
Please note that this rule applies to all the patches on all the base paths.
> fix(patches): Avoid same path patches

- .github/workflows/release.yaml
> fix(ci): correctly reference cli-docs workflow trigger in release

- pkg/cli/find/find.go
/kind bugfix
Fixed an issue where printing test logs failed due to permission error introduced in #2697.
> [fix] Ignore permission error when listing VirtualClusterInstances

- .backportrc.json
- .github/workflows/backport.yaml
Removing the original pr description section as it often repeated the linear issue ID and reopened linear old issues as well as caused problems with changing issues statuses.
References OPS-136
Removing the original pr description section as it often repeated the linear issue ID and reopened linear old issues as well as caused problems with changing issues statuses.
> feat(ci): remove original pr description in backport prs

- test/e2e/syncer/services/services.go
/kind test
This pull request makes e2e services test more deterministic by using constant namespace names for the tests and pulling namespace creation and deletion into the spec subjects (`It` blocks).
This e2e test has been flaky for a while (latest failure from [today](https://github.com/loft-sh/vcluster/actions/runs/14751969126/job/41411726656?pr=2730)), and this change might not fix that issue, but it's a step towards making the test more deterministic and easier to debug.
> Make services e2e test more deterministic

- pkg/config/validation.go
- pkg/config/validation_test.go
Add validations for:
- CertManager
- KubeVirt
- ExternalSecrets
resolves #ENG-6669
Add validation on incompatible CRD syncs and integrations for: CertManager, KubeVirt and ExternalSecrets.
> [ENG-6669] feat(validation): Add validations for collisions of integrations and CRD syncs

- config/default_extra_values.go
- docs/pages/deploying-vclusters/compat-matrix.mdx
- pkg/constants/coredns.go
resolves #ENG-6170
Basically remove versions of k8s under 1.30
> [ENG-6170] refactor(versions): Remove older versions of images

- chart/values.schema.json
- chart/values.yaml
- config/config.go
resolves ENG-6742
Documents that controlplane.distro.k8s.version is deprecated
> docs: documents that controlplane.distro.k8s.version is deprecated

- chart/values.schema.json
- chart/values.yaml
- config/config.go
resolves #
Adds deprecation notice to k0s and k3s distributions in the documentation.
> chore: adds deprecation notice to k0s and k3s distros

- README.md
Updated the vCluster gif. This follows the quickstart guide in the docs.
Created a new vCluster gif for the README
> created a new vCluster gif for the README

- hack/assets/assets.go
/kind bugfix
resolves #ENG-5979
With this PR we get this:
For `images.txt`
```
$ go run -mod vendor ./hack/assets/cmd/main.go --latest 0.25.0-rc.2
ghcr.io/loft-sh/vcluster-pro:0.25.0-rc.2
library/alpine:3.20
ghcr.io/loft-sh/kubernetes:v1.32.1
registry.k8s.io/etcd:3.5.21-0
rancher/k3s:v1.32.1-k3s1
coredns/coredns:1.11.3
```
For `optional.txt`
```
$ go run -mod vendor ./hack/assets/cmd/main.go --optional 0.25.0-rc.2
ghcr.io/loft-sh/vcluster-oss:0.25.0-rc.2
ghcr.io/loft-sh/kubernetes:v1.31.1
ghcr.io/loft-sh/kubernetes:v1.30.2
registry.k8s.io/etcd:3.5.15-0
registry.k8s.io/etcd:3.5.13-0 …
```
> fix(images.txt): Move vcluster-oss to the optional part

- cmd/vclusterctl/cmd/platform/create/space.go
- pkg/cli/create_platform.go
> fix call errors.Wrap with nil value error

- Justfile
Part of ENG-5979
Fixed an issue where vcluster justfile threw an error
> Fixes optional images text generation

- chart/templates/_init-containers.tpl
- chart/tests/statefulset_test.yaml
- config/config_test.go
Resolves ENG-6743
Resolves ENG-6779
> refactor: change k8s image logic

- chart/templates/platform-rbac.yaml
- chart/tests/platform-secret-role_test.yaml
> fix: wrong namespace for platform rbac

- pkg/k8s/k8s.go
/kind bugfix
Resolves #2617
Ref: https://github.com/k3s-io/kine/issues/357
> fix: compaction issue with kine

- test/e2e/syncer/fromhost/configmaps.go
- test/e2e/syncer/fromhost/secrets.go
- test/e2e/syncer/pods/pods.go
- test/framework/util.go
/kind bugfix
I suspect that [this issue](https://github.com/nginx/docker-nginx-unprivileged/issues/302) in the nginx image we use in e2e is gonna break our suite. The image needs to be pinned to previous tag.
Here is failure with a dummy commit before pinning the tag - https://github.com/loft-sh/vcluster/actions/runs/14696414303/job/41238649749?pr=2720
> Pin nginx-unprivileged image in e2e tests

- chart/templates/role.yaml
- chart/tests/role_test.yaml
/kind bugfix
resolves #
Added list & watch permissions for ReferenceGrant
> add list & watch permissions for ReferenceGrant

- pkg/cli/localkubernetes/configure.go
/kind bugfix
resolves ENG-6873
fixed vCluster connect background proxy is not port-forwarding to the localhost when host server address is 0.0.0.0
> fix: vCluster connecting with background proxy

- pkg/controllers/resources/namespaces/syncer.go
/kind bugfix
part of #ENG-6785
> ENG-6785 | Update namespace syncer to import namespaces

- chart/templates/role.yaml
- chart/tests/role_test.yaml
> chore: add lease permissions for privateNodes

- pkg/cli/localkubernetes/configure.go
/kind bugfix
Fixed an issue where vcluster connect wouldn't work correctly anymore
> fix: vcluster connect

- .github/actionlint.yaml
- .github/workflows/actionlint.yml
/kind bugfix
/kind feature
/kind test
References OPS-166
> feat(ci): add actionlint ci for workflow files

- chart/values.schema.json
- chart/values.yaml
- cmd/vcluster/cmd/snapshot.go
- config/config.go
- config/values.yaml
- pkg/k8s/k8s.go
- pkg/pro/embedded_etcd.go
- pkg/setup/initialize.go
- pkg/util/command/command.go
- pkg/util/command/command_test.go
> feat: add more private node options & merge args

- chart/templates/service.yaml
- chart/tests/service_test.yaml
> fix: konnectivity service

- cmd/vcluster/cmd/snapshot.go
- pkg/setup/initialize.go
- pkg/util/servicecidr/servicecidr.go
- pkg/util/servicecidr/servicecidr_test.go
/kind bugfix
resolves ENG-6989
Fixed an issue where vcluster wouldn't detect the service cidr correctly in v1.33 Kubernetes clusters
> fix: service cidr detection

- pkg/util/translate/labels.go
/kind bugfix
Part of #ENG-6682
> ENG-6682 | Always include marker label in synced objects

- Justfile
- chart/values.schema.json
- chart/values.yaml
- cmd/vcluster/cmd/node/node.go
- cmd/vcluster/cmd/node/upgrade.go
- cmd/vcluster/cmd/root.go
- cmd/vclusterctl/cmd/node/load-docker-image.go
- cmd/vclusterctl/cmd/node/node.go
- cmd/vclusterctl/cmd/node/upgrade.go
- cmd/vclusterctl/cmd/root.go
- config/config.go
- config/values.yaml
- pkg/pro/privatenodes.go
- pkg/snapshot/pod/pod.go
- pkg/util/applier/direct.go
> feat: auto-upgrade, load-images

- cmd/vclusterctl/cmd/platform/reset.go
/kind bugfix
resolves ENG-7022
CLI: delete user's access keys on password reset
> delete user's access keys on password reset

- pkg/cli/create_helm.go
/kind bugfix
resolves ENG-6422
Fixed an issue when upgrading vcluster with different distro than the default one
> fix: vcluster upgrade of k3s distro

- chart/templates/statefulset.yaml
- chart/values.schema.json
- chart/values.yaml
- cmd/vcluster/cmd/restore.go
- cmd/vcluster/cmd/snapshot.go
- cmd/vcluster/cmd/start.go
- cmd/vclusterctl/cmd/token/create.go
- config/config.go
- config/values.yaml
- pkg/certs/ensure.go
- pkg/config/config.go
- pkg/config/validation.go
- pkg/constants/constants.go
- pkg/etcd/client.go
- pkg/k8s/k8s.go
- pkg/k8s/migrate.go
- pkg/pro/privatenodes.go
- pkg/server/cert/cert.go
- pkg/server/server.go
- pkg/setup/controller_context.go
- pkg/setup/controllers.go
- pkg/setup/initialize.go
- pkg/setup/managers.go
- pkg/setup/proxy.go
- pkg/syncer/synccontext/context.go
- pkg/telemetry/collect_controlplane.go
- pkg/util/command/command.go
- pkg/util/command/prochandle.go
- pkg/util/command/prochandle_other.go
- pkg/util/command/prochandle_unix.go
Changes:
* Refactor constants to allow changing the values and move all filepath references to 
* Since standalone mode has no host cluster, skip certain parts of the code where host client is required
* Change the way how we currently execute api-server, controller-manager etc to allow restarting the vCluster process without left-over processes
> feat: add standalone

- pkg/cli/cleanup_namespaces.go
/kind bugfix
resolves ENG-7237
resolves ENG-6976
Fixed an issue where vcluster wasn not properly cleaning up namespaces. 
`none` cleanup policy now cleans up metadata added by vCluster to namespace objects. This way namespace looks like ordinary namespace once vCluster is uninstalled and can be later on imported by other vCluster.
`all` cleanup policy now checks for protected namespaces and won't try to delete them, instead it will also just cleanup metadata.
> Add metadata cleanup to no-op namespace cleanup handler, check for protected namespaces in all namespace cleanup handler

- cmd/vcluster/cmd/snapshot.go
- pkg/pro/embedded_etcd.go
- pkg/setup/initialize.go
> feat: embedded etcd auto-heal

- .github/CODEOWNERS
Sorted and (lightweight) grouped entries in CODEOWNERS, so it's easier to maintain it.
> Sort and group CODEOWNERS entries

- pkg/cli/cleanup_namespaces.go
Resolves ENG-7351
```bash
> vcluster delete test-cleanup-2
15:55:53 info Stopping background proxy...
15:55:53 info Delete vcluster test-cleanup-2...
15:55:53 done Successfully deleted virtual cluster test-cleanup-2 in namespace vcluster-test-cleanup-2
15:55:53 info Starting cleanup of vCluster 'test-cleanup-2' namespaces.
15:55:53 info Namespace 'host-namespace-from-host' was imported, cleaning up its resources and metadata...
15:55:58 info Issuing delete for namespace 'host-ns'
15:55:58 info Waiting for namespace 'host-ns' to be fully terminated...
15:56:10 info Successfully deleted virtual cluster namespace 'host-ns'
15:56:10 info Issuing delete for namespace 'host-ns-2' …
```
> Add polling to synced namespaces cleanup when deleting vcluster

- pkg/server/cert/cert.go
Fixes an issue where node ips were not correctly added to the server certificate when using a NodePort service with vCluster
> fix: add control plane pods to certs

- pkg/server/server.go
Fixes an issue where when using KubeVirt or MetricsServer integration, the authorizer wasn't called correctly.
> fix: missing authorizer checks

- pkg/server/filters/panic_recovery.go
- pkg/server/server.go
> fix: panic recovery log message

- cmd/vclusterctl/cmd/token/create.go
- cmd/vclusterctl/cmd/token/list.go
- pkg/constants/cli.go
resolves ENG-7423
add --control-plane flag to vcluster token create
> add --control-plane flag to vcluster token create

- pkg/setup/initialize.go
Fixes an issue where an error while starting embedded etcd or k8s wouldn't fail vCluster
> fix: fail if starting embedded etcd or k8s starting fails

- chart/values.schema.json
- chart/values.yaml
- cmd/vcluster/cmd/start.go
- config/config.go
- config/values.yaml
- pkg/pro/privatenodes.go
- pkg/server/cert/cert.go
- pkg/server/cert/syncer.go
/kind bugfix
/kind feature
/kind test
resolves #
> Update nodepools config struct

- chart/values.schema.json
- chart/values.yaml
- config/config.go
Follow up to 
* ENG-6743
* https://github.com/loft-sh/vcluster/pull/2762
> Clarifies how default k8s version is set

- .github/CODEOWNERS
Removing QA as a codeowner for the test directory
> Update CODEOWNERS to remove QA

- .github/CODEOWNERS
Added eng-qa and developers to tests/e2e folder instead of removing eng-qa from tests/e2e folder.
/kind bugfix
/kind feature
/kind test
resolves #
> Update CODEOWNERS so that QA can approve tests changes without dev

- test/e2e/e2e_suite_test.go
- test/e2e/syncer/tohost/networkpolicy.go
- test/e2e/values.yaml
/kind test
resolves #
ENG-5212
Added test to check the sync of network policy from vCluster to host.
> Added e2e test for network policy sync to host from vcluster

- chart/values.schema.json
- chart/values.yaml
- config/config.go
- config/config_test.go
- config/default_extra_values.go
- config/legacyconfig/migrate.go
- pkg/cli/describe_helm.go
Improve various aspects about image ref handling:
- use same Image type where applicable
- make image parsing more robust & support some more edge cases
- add tests
> Refactor image ref handling

- cmd/vcluster/cmd/certs/check.go
- cmd/vcluster/cmd/certs/rotate.go
- pkg/certs/rotate.go
> fix: add flag to configure pki path for cert rotation

- cmd/vclusterctl/cmd/node/delete.go
/kind bugfix
resolves ENG-7907
> fix: drain emptydir-data

- chart/values.schema.json
- chart/values.yaml
- config/config.go
- config/values.yaml
> feat: add kubelet and kube-proxy config

- config/config.go
- config/config_test.go
/kind bugfix
resolves #ENG-8029
Fixed upgrade of vclusters created with <0.27.0.
> Fix: config change breaks upgrade to 0.27.0

- .github/workflows/e2e.yaml
/kind bugfix
/kind feature
/kind test
resolves #
> fix: aws oidc permissions

- chart/templates/_init-containers.tpl
- chart/tests/statefulset_test.yaml
- chart/values.schema.json
- chart/values.yaml
- config/config.go
- config/values.yaml
> refactor: remove importNodeBinaries, importImages & bundleRepository

- pkg/platform/helper.go
Fixed an issue where trying to run `vcluster platform connect vcluster my-vcluster` with an externally deployed vCluster would result in the error:
```
14:09:32 fatal prepare vCluster kube config: find space instance cluster: couldn't find cluster  in project default
```
> fix: externally connected vclusters

- cmd/vclusterctl/cmd/platform/add/vcluster.go
- pkg/cli/add_vcluster_helm.go
/kind bugfix
This checks in the platform for the existence of the vCluster in
another project. Since moving vClusters from its original project is
not allowed, it now returns an error.
resolves #ENG-8329
Backport of #3042
> Backport of #3042 to v0.27.x - Avoid `vcluster platform add vcluster` to try to set another project

- .github/workflows/sync-config-schema.yaml
> fix: skip vcluster-config sync on next tags

- cmd/vclusterctl/cmd/platform/login.go
/kind bugfix
resolves ENG-8458
> [v0.27] Fix the platform login issue

- chart/values.schema.json
- chart/values.yaml
- config/config.go
- config/values.yaml
- pkg/config/validation.go
> ENG-8528 | Rename nodePools to autoNodes in privateNodes config

- pkg/cli/create_helm.go
- pkg/config/validation.go
/kind bugfix
This is a follow up PR for https://github.com/loft-sh/loft-enterprise/pull/4654 which is the platform checking of the same logic as this one
resolves #ENG-7334
> fix: Check for platform project existence on CLI

- pkg/platform/version.go
resolves ENG-8339
Updating platform version to 4.3.5
> update platform version in vcluster to latest stable

- chart/values.schema.json
- chart/values.yaml
- config/config.go
- config/values.yaml
> refactor: rename tunnel to vpn

- .github/workflows/sync-config-schema.yaml
/kind bugfix
resolves #
Happened during a release where a PR in vcluster-docs for main did already exist. I guess we want this PR to reflect latest main anyway.
> fix: close potentially already existing PRs

- chart/values.schema.json
- config/config.go
- config/values.yaml
- pkg/config/validation.go
Changes:
* Introduces a required provider field for autoNodes
* Fixes an issue where we haven't updated "values.yaml" properly with the ephemeral-storage (#3156)
> refactor: introduce provider field for auto nodes

- pkg/cli/list_helm.go
- pkg/cli/list_platform.go
Humanize vclusters age display, resolves #ENG-8322
> fix: vcluster age display

- chart/values.yaml
- config/values.yaml
- test/conformanceValues.yaml
/kind feature
**What does this pull request do? Which issues does it resolve?** (use `resolves #<issue_number>` if possible)
Upgrade etcd in deployed mode to 3.6.4.
> Upgrade etcd in deployed mode to 3.6.4

- .github/workflows/sync-config-schema.yaml
> fix(ci): generate pr in the correct docs version folder (#3134)

- pkg/cli/snapshot_helm.go
- pkg/snapshot/request.go
towards ENG-9108
Move code that creates snapshot request resources into snapshot pkg so it can be reused for the vcluster binary command.
> Move snapshot request resources creation into snapshot pkg

- chart/values.yaml
- config/legacyconfig/migrate_test.go
- config/values.yaml
> refactor: increase memory limits
